export type HelpTarget='home'|'books'|'accounts'|'entry:manual'|'entry:ai'|'entry:import'|'entry:family'|'insights'|'activities'|'families'|'budget'|'schedules'|'profile'|'profile:memory'|'settings'|'chat';
type Pair=[string,string];
type Link={target:HelpTarget;label:Pair};
type Step={title:Pair;text:Pair;action?:Link};
type Figure={key:string;caption:Pair};
type Section={id:string;title:Pair;paragraphs?:Pair[];steps?:Step[];figures?:Figure[];example?:Pair;note?:Pair;questions?:{q:Pair;a:Pair}[];action?:Link};
type Chapter={id:string;group:Pair;title:Pair;intro:Pair;sections:Section[]};
const begin:Pair=['认识与准备','Introduction & setup'],record:Pair=['记录每一笔','Recording transactions'],review:Pair=['查看与管理','Review & management'],support:Pair=['助手与设置','Assistant & settings'];
const link=(target:HelpTarget,zh:string,en:string):Link=>({target,label:[zh,en]});
const fig=(key:string,zh:string,en:string):Figure=>({key,caption:[zh,en]});
export const guideChapters:Chapter[]=[
 {id:'intro',group:begin,title:['认识 TallyBear','Welcome to TallyBear'],intro:['TallyBear 是可自主部署的个人与家庭记账应用，目前版本为 2.0。从一张订单截图开始，到钱包余额、家庭协作和长期消费习惯，都可以在同一个工作台管理。','TallyBear is a self-hosted personal and family finance app, currently at version 2.0. Record a receipt, understand your wallet balances, coordinate household spending and build reusable purchase memories in one workspace.'],sections:[
  {id:'workspace',title:['你可以用它做什么','What you can do'],paragraphs:[['日常记账可以手动输入、上传截图、导入支付账单，也可以直接和小熊对话。识别结果会先形成草稿，核对后才正式入账。','Enter transactions manually, upload receipts, import payment statements or talk to the assistant. Recognized entries become drafts for review before they are posted.'],['收支分析把图表和明细放在一起。你可以按日期、分类或钱包查看开销，再从图表进入原订单，查看商品、退款和结算细节。','Analysis combines charts and records. Filter by date, category or wallet, then open the underlying order to inspect items, refunds and checkout details.']],figures:[fig('overview','首页：查看所选范围的收支和最近记录。','Overview: totals and recent transactions for the selected scope.'),fig('charts','收支分析：从分类或趋势图进入对应明细。','Analysis: open records from category and trend charts.')],action:link('home','打开我的账本','Open My books')},
  {id:'dimensions',title:['四个概念，分别管理','Four independent concepts'],paragraphs:[['账本决定记录放在哪里、谁可以查看，例如私人账本和家庭共享账本。钱包决定实际从哪里扣款，例如微信余额、储蓄卡或信用账户。','A book determines where a record belongs and who can see it, such as a private journal or shared household book. A wallet identifies the actual funding source, such as cash, a bank account or credit account.'],['活动把一次旅行或聚会的交易归在一起，可以跨不同账本。分类说明消费用途，例如餐饮、交通、买菜和会员订阅。活动不会替代分类。','An activity groups spending for a trip or event across books. A category describes its purpose, such as dining, transport, groceries or subscriptions. Activities do not replace categories.']],example:['一次旅行可以同时包含私人账本的购物和共享账本的餐饮。用活动看整次旅行，用分类看餐饮花费，用钱包看实际扣款；不必把同一笔付款再记一次。','A trip can include shopping in a private book and dining in a shared book. Use the activity for the trip total, categories for dining spend and wallets for actual cash movements—without recording the same payment again.']},
  {id:'collaboration',title:['共同记账与个人记忆','Shared finance and personal memory'],paragraphs:[['家庭成员可以参与共享账本与家庭活动，个人钱包和私人账本仍保留各自的访问边界。家庭往来单独记录成员间转账和结算。','Family members can join shared books and family activities while private books and personal wallets retain their access boundaries. Family movements track transfers and settlements separately.'],['记忆中心保存确认过的商品身份和记账偏好。下次遇到同款商品，系统可以建议分类与字段；本次金额、日期和付款编号仍以新证据为准。','Memory center keeps confirmed product identities and bookkeeping preferences. Future purchases can receive category and field suggestions, while new amounts, dates and payment references come from current evidence.']],figures:[fig('memory','记忆中心：查看商品、偏好与来源，纠正不准确的关联。','Memory center: inspect products, preferences and evidence, and correct mistaken links.')]},
  {id:'reading',title:['如何阅读这本说明书','How to use this manual'],paragraphs:[['第一次使用，请依次阅读“建立账本和钱包”和“手动记账”。之后可以按目录查找单个任务，或输入关键词和问题搜索。','Start with “Set up books and wallets” and “Manual entries”. Then use the contents to find a specific task, or search by keyword or question.'],['每章的功能按钮只打开相应页面，不会替你保存账单。点击“询问助手”会带入本章主题，你可以补充问题后再发送。截图随页面语言切换，手机优先展示手机截图，也可切换到电脑截图。','Feature buttons open the relevant page without saving anything. “Ask the assistant” prefills this chapter’s topic; add your question before sending. Screenshots follow the interface language, with mobile and desktop views available.']]}
 ]},
 {id:'start',group:begin,title:['建立账本和钱包','Set up books and wallets'],intro:['先确定记录归属，再建立实际使用的钱包。完成这一章后，就可以保存第一笔交易并核对余额。','Set up where records belong and which wallets fund them. You can then post your first transaction and check its balance effect.'],sections:[
  {id:'books',title:['第一步：选择或创建账本','Step 1: choose or create a book'],steps:[{title:['确定私人或共享','Choose private or shared'],text:['打开账本管理，填写名称、图标和用途。仅自己使用选私人账本；需要他人一起记账选共享账本，再设置成员权限。','Open Book management and choose a name, icon and purpose. Use a private book for yourself or a shared book for collaboration, then grant member permissions.'],action:link('books','前往账本管理','Open Book management')},{title:['切换到要使用的账本','Select the book'],text:['点击顶部账本选择器确认当前账本。后续录入默认使用这里的选择；保存前也应检查卡片上的记入账本。','Use the book picker at the top. New entries default to this book, but check the destination on the confirmation card before saving.']}],figures:[fig('books','账本管理：私人和共享账本分别显示，选择后进入工作台。','Book management: select a private or shared book for the workspace.')]},
  {id:'wallets',title:['第二步：建立钱包并核对期初余额','Step 2: add wallets and opening balances'],steps:[{title:['按实际资金账户建立','Create actual funding accounts'],text:['在资金资产添加微信余额、银行卡、现金或信用账户。微信支付绑定银行卡时，银行卡与微信余额应是不同钱包。','Add your cash, bank and credit accounts in Assets. A bank card used through a payment app is separate from that app’s stored balance.'],action:link('accounts','前往资金资产','Open Assets')},{title:['以开始记账时的余额为准','Use the balance at your starting point'],text:['期初余额是你开始记录前已有的钱；信用账户已有欠款填负数。不要同时把期初余额再记成一笔收入。','Opening balance is money already held when you start tracking. Existing credit debt is negative. Do not also record the opening balance as income.']}],figures:[fig('assets','资金资产：个人钱包与家庭共同钱包分范围查看。','Assets: personal and shared family wallets use separate scopes.')]},
  {id:'first',title:['第三步：保存并检查第一笔','Step 3: post and verify a transaction'],paragraphs:[['录入一笔已知金额的小额消费，保存后检查：账本是否多了这一笔，实际扣款钱包是否减少相同金额，收入和转账是否被误选。之后再批量录入历史账单。','Post a small known expense. Confirm it appears in the correct book, the funding wallet decreases by the right amount, and the type is not income or transfer. Then continue with historical records.']],action:link('entry:manual','开始手动记账','Start a manual entry'),note:['共享账本中的可见交易，不一定都是你个人钱包的支出。查看本人资金变化时选择个人钱包口径。','Visible transactions in a shared book are not necessarily paid by your wallets. Use the personal-wallet scope for your own cash flow.']}
 ]},
 {id:'record',group:record,title:['手动记账与常用预设','Manual entries and presets'],intro:['适合金额和付款信息已经明确的消费。按照“交易类型 → 金额与日期 → 钱包与分类 → 详情 → 保存”的顺序录入。','Use manual entry when the amount and payment details are known. Work through type, amount and date, wallet and category, details, then save.'],sections:[
  {id:'required',title:['填写核心交易信息','Enter the core transaction'],steps:[{title:['选择收支类型','Choose the transaction type'],text:['支出用于消费，收入用于实际收入；自有钱包之间移动资金用转账，退款使用退款类型并关联原消费。','Use Expense for purchases, Income for earnings, Transfer for movement between your wallets, and Refund for money returned against a purchase.'],action:link('entry:manual','打开手动记账','Open Manual entry')},{title:['填写实际金额与日期','Enter the actual amount and date'],text:['金额填写整笔实际支付，不要再次加上商品明细。交易日期为年月日；缺失时默认记录当天。交易时间单独填写时分秒，未知可以留空。','Enter the full payment amount without adding items a second time. Date uses year-month-day and defaults to the recording day if absent. Time is separate and may be left blank.']},{title:['选择真正扣款的钱包','Select the actual funding wallet'],text:['支付平台、支付渠道和资金钱包不是同一字段。例如京东下单、微信支付、银行卡扣款，应选择银行卡作为钱包。','Order platform, payment channel and funding wallet are separate fields. An order placed on a marketplace and paid through an app may still debit your bank card.']}],figures:[fig('manual','手动记账：收支类型、金额、日期、分类和钱包构成核心表单。','Manual entry: type, amount, date, category and wallet form the core fields.')]},
  {id:'details',title:['补充商品与可追溯信息','Add product and reference details'],paragraphs:[['标题应能帮助你以后辨认这笔消费。外卖可用菜品或商品作为标题，商家另外填写；堂食可以用餐厅和用餐场景。备注保存商品或消费相关补充，例如规格、用途和同行人数。','Choose a title that identifies the purchase later. For delivery, use the food or product and keep the merchant in its own field; dine-in can use the restaurant and occasion. Notes hold purchase details such as specification, purpose or party size.'],['订单号和支付流水号可选填，方便搜索、退款关联和核对。需要保留原始账单时勾选保存凭证；生活附图用于记录商品或场景，不参加默认识别。','Order and payment references are optional and help with search, refunds and reconciliation. Select receipt retention to keep original evidence. Personal photos document the item or occasion and are not used for default recognition.']]},
  {id:'presets',title:['把重复输入保存为预设','Save repeat inputs as a preset'],paragraphs:[['在“常用一笔”中保存早餐、通勤或工资等常用内容。下次选择预设后检查本次金额、日期和钱包，确认保存才会产生交易。保存预设本身不会入账。','Save frequent breakfasts, commutes or salary details in presets. On reuse, check the new amount, date and wallet before confirming. Saving a preset does not create a transaction.']],example:['同一家早餐店，昨天 12 元、今天 15 元：可以复用商家与分类，今天金额仍填 15 元。两次付款分别保存。','For two visits to the same café, reuse merchant and category but enter today’s actual amount. Save each payment separately.'],questions:[{q:['可以不填交易时间吗？','Can I leave the time blank?'],a:['可以。交易日期用于统计，交易时间只是补充信息，不应为了通过表单猜一个时间。','Yes. The date drives reporting; the time is additional information and should not be guessed.']}]}
 ]},
 {id:'receipts',group:record,title:['AI 文字、截图与草稿核对','AI text, screenshots and draft review'],intro:['先让识别生成草稿，再核对事实。长图可以分段读取，但最终应按实际订单组织，不能把图片段数当作付款笔数。','Generate drafts first, then check the facts. Long images may be read in sections, but payments must follow actual orders rather than image segments.'],sections:[
  {id:'input',title:['提供本次消费信息','Provide this purchase’s evidence'],steps:[{title:['输入描述或添加图片','Describe the purchase or add images'],text:['在 AI 文字／截图页输入消费描述；图片按从上到下、从订单到结算的阅读顺序添加。尽量保留订单号、支付时间和最终实付区域。','In AI text / images, enter the purchase description or add images in reading order, from items to checkout. Keep order references, payment time and final amount visible.'],action:link('entry:ai','打开 AI 文字／截图','Open AI text / images')},{title:['开始识别并查看任务','Start recognition and follow progress'],text:['点击识别并生成草稿。切换页面后可在后台任务查看进度；不必重复提交相同图片。','Select Recognize and create drafts. Progress remains in Background tasks after navigating away; avoid submitting the same images repeatedly.']}],figures:[fig('intake','识别入口：文字和图片共同描述本次消费。','Recognition input: text and images describe the current purchase.')]},
  {id:'check',title:['按顺序核对草稿','Review the draft in order'],steps:[{title:['核对订单归属和实付','Verify the order and final payment'],text:['先看订单号、商家和日期，再看实际支付。商品页上的小计不能代替没有显示的实付金额。','Check reference, merchant and date before the final payment. An item-page subtotal cannot stand in for an unseen checkout amount.']},{title:['检查商品与结算项','Check items and adjustments'],text:['区分单价、数量和行小计。满减、配送费等应在优惠／费用区域，不是商品。金额不一致时先看差额提示。','Distinguish unit price, quantity and line total. Discounts and fees belong in adjustments, not products. Inspect any reconciliation warning.']},{title:['选择钱包并确认','Choose the wallet and confirm'],text:['唯一付款线索可能预选钱包；多个可能钱包时要自己选择。检查记入账本和活动后确认保存。','An unambiguous funding clue may preselect a wallet; choose manually when several are possible. Check the book and activity before confirming.']}],figures:[fig('draft','草稿核对：待确认信息、商品和保存操作分开呈现。','Draft review: missing information, items and saving actions are separated.')]},
  {id:'duplicates',title:['一张长订单被拆成两张卡片怎么办？','What if one long order becomes two cards?'],paragraphs:[['向助手说明“这是同一订单，请合并待确认卡片”，提供订单号和原图。核对新卡片是否保留完整商品、使用结算实付，并确认旧卡片已被替代或取消。不要把两张卡片都保存。','Tell the assistant that the cards belong to one order and ask it to merge the pending drafts, providing the reference and image. Verify the replacement contains all items and the checkout payment, and that old cards are replaced or cancelled. Do not save both.']],note:['识别和合并的解释、金额差异及待核对原因应留在提示区。备注用于消费相关信息，不保存处理日志。','Recognition explanations, differences and review reasons belong in hints. Notes are for purchase information, not processing logs.']}
 ]},
 {id:'calculator',group:record,title:['商品小计、优惠与手续费','Item totals, discounts and fees'],intro:['整单只有一次实际付款。商品解释买了什么，优惠和费用解释结算如何加减；计算器提供推荐金额，最后仍以实际支付为准。','An order has one actual payment. Items describe the purchase and adjustments explain checkout additions and deductions. The calculator suggests totals; actual payment remains authoritative.'],sections:[
  {id:'items',title:['用单价和数量计算小计','Calculate a line total'],steps:[{title:['先判断截图金额的含义','Identify what the displayed amount means'],text:['“单价 13.90 × 2”和“这一行合计 13.90”不同。识别不清时保留未知字段，不能把行小计再乘一次数量。','A unit price of 13.90 × 2 is different from a line total of 13.90. Leave unclear fields unknown rather than multiplying a line total again.']},{title:['采用或修改推荐值','Adopt or edit the suggestion'],text:['输入单价和数量后查看推荐小计。仍跟随计算的小计会自动更新；已识别或手动更改的小计保留不变，可以再次比对。','Enter unit price and quantity to see the suggestion. A subtotal following the calculator updates automatically; recognized or manually edited totals are preserved for comparison.'],action:link('entry:manual','打开记账表单','Open the entry form')}],figures:[fig('line-items','商品明细：分别显示数量、单价、小计及整单结算。','Item details: quantity, unit price, line totals and order checkout remain distinct.')]},
  {id:'adjustments',title:['单独填写优惠和费用','Record adjustments separately'],paragraphs:[['优惠券、满减和抹零是减项；配送、包装和手续费是加项。在对应区域填写，避免将它们作为商品参与复购统计。','Coupons, promotional discounts and rounding deductions reduce checkout. Delivery, packaging and service fees increase it. Record them in adjustments so they do not become repeat-purchase products.'],['商品价格已经是优惠后金额时，不再重复减去同一优惠。查看推荐实付，与订单结算区比对，主动采用或手动填写实际金额。','If item prices already include a discount, do not subtract it again. Compare the suggested payment with checkout, then adopt it or enter the actual amount.']],example:['商品合计 50 元，优惠 5 元，配送 3 元：推荐实付 48 元。如果订单实付是 47 元，应检查是否还有 1 元优惠，而不是凭空补一个商品。','Items total 50, discount 5 and delivery 3: suggested payment is 48. If checkout says 47, investigate another deduction rather than inventing an item.']},
  {id:'difference',title:['差额如何处理','Handle unexplained differences'],paragraphs:[['完整截图仍无法解释差额时，保留真实实付和已知商品，按界面要求填写核验原因。之后可从待核验记录继续补充；商品明细不会额外增加钱包支出。','If the full receipt cannot explain a difference, preserve the actual payment and known items and supply the requested verification reason. Continue later from records awaiting verification. Item details do not create extra wallet expenses.']]}
 ]},
 {id:'refund',group:record,title:['关联退款与返现','Link refunds and cashback'],intro:['退款是新的到账记录，与原消费建立关系。原消费保留购买事实，退款按到账日期冲减净支出。','A refund is a new receipt of money linked to the purchase. The purchase remains intact; the refund reduces net spending on its own date.'],sections:[
  {id:'original',title:['第一步：搜索原消费','Step 1: find the original purchase'],steps:[{title:['切换为退款','Choose Refund'],text:['打开记一笔的手动记账，选择退款。进入原消费搜索，不要在收入类型下直接保存。','Open Manual entry and select Refund. Use the original-purchase search rather than saving it as income.'],action:link('entry:manual','打开手动记账，选择退款','Open Manual entry, then Refund')},{title:['核对并关联原单','Verify and link the purchase'],text:['用订单号、商品或商家搜索；结合日期、金额和账本区分同名重复购买。原消费可以来自其他有权限的账本，不需要先移动。','Search by order reference, product or merchant. Use dates, amounts and book names to distinguish repeat purchases. An accessible purchase may belong to another book without being moved.']}],figures:[fig('refund','退款表单：选择原消费后核对本次到账金额和收款钱包。','Refund form: link the purchase and check this refund’s amount and receiving wallet.')]},
  {id:'receive',title:['第二步：填写本次到账','Step 2: record this refund'],paragraphs:[['填写本次实际到账金额、日期和收款钱包，核对关联带入的分类与商品信息。退款去向可以与原付款钱包不同，例如信用账户消费退到银行卡。','Enter this refund’s amount, date and receiving wallet. Review inherited category and product details. A refund may go to a different wallet, such as a bank account rather than the original credit account.'],['如果原消费有分摊，关联退款后按最新净额重算覆盖期；记录退款不会要求删除原消费。','If the purchase has cost allocation, a linked refund recalculates its coverage using the new net amount. The original purchase does not need to be deleted.']]},
  {id:'multiple',title:['多次退款和返现','Multiple refunds and cashback'],example:['购买 100 元，先退 30 元，后退 70 元，再返现 5 元：分别记录三笔并关联同一原单，累计到账 105 元，净支出为 -5 元。','A purchase of 100 receives refunds of 30 and 70, followed by cashback of 5. Record three receipts linked to that purchase. Cumulative refunds are 105 and net spending is -5.'],questions:[{q:['为什么退款没有减少原购买月份的现金支出？','Why did the original month’s cash spending not change?'],a:['现金收支按实际发生日期统计，退款冲减到账期间的净支出。分摊成本按覆盖期重算，是另一种口径。','Cash flow uses actual transaction dates, so the refund reduces spending in the period received. Recalculated allocated costs use a different reporting basis.']},{q:['搜索出来很多一样的商品怎么办？','What if many identical products appear?'],a:['优先使用订单或支付流水编号；没有编号时结合日期、金额和钱包核对，不要仅凭标题选单。','Prefer order or payment references. Otherwise verify date, amount and wallet rather than choosing by title alone.']}]}
 ]},
 {id:'analysis',group:review,title:['收支分析与图表明细','Analysis and chart drilldowns'],intro:['先确定统计对象和日期，再看图表。相同筛选下的图表、汇总和明细应一起理解。','Choose the scope and dates before reading charts. Interpret totals, charts and records using the same filters.'],sections:[
  {id:'scope',title:['选定范围和周期','Choose scope and period'],steps:[{title:['账本还是个人钱包','Book or personal wallets'],text:['当前账本展示该本记录；个人钱包汇总本人钱包跨账本的实际收支，排除其他成员和家庭共同钱包，关联付款只统计一次。','The current book shows its records. Personal-wallet reporting aggregates your own wallets across books, excluding other members and shared wallets, and counts linked payments once.'],action:link('insights','打开收支分析','Open Analysis')},{title:['选择年、月、周、日或自定义','Choose year, month, week, day or custom dates'],text:['区间包含起止日；周一至周日为一周。自定义起止日后点击应用，再确认页面显示的实际范围。','Ranges include both endpoints. Weeks run Monday through Sunday. Apply custom dates and check the displayed range.']}],figures:[fig('analysis','收支分析：范围和周期位于图表之前，先确认统计口径。','Analysis: scope and period precede charts so you can establish the reporting basis.')]},
  {id:'drilldown',title:['从图表找到订单','Open orders from charts'],paragraphs:[['点击分类饼图的分类或趋势图的数据点，打开对应交易列表。列表分页展示；继续点击某笔记录，查看钱包、商家、商品、优惠费用和订单编号等完整信息。','Select a category slice or trend point to open its transaction list. Records are paginated; open one for wallet, merchant, items, adjustments and reference details.'],['下方明细可继续按分类、钱包和关键词筛选。筛选会联动图表和汇总；要恢复完整视图，先清除筛选。','Refine records by category, wallet or keyword. Filters also affect charts and totals; clear them to return to the full view.']],figures:[fig('charts','分类和趋势图：用于选择要继续查看的明细范围。','Category and trend charts select the records to explore.')]},
  {id:'totals',title:['理解收入、净支出和结余','Understand the totals'],paragraphs:[['收入不包含账户之间的转账。净支出是消费减到账退款，收支结余是收入减净支出。不同日期或范围的数字不能直接相互替代。','Income excludes transfers between accounts. Net spending is purchases minus refunds received; cash surplus is income minus net spending. Results from different scopes or dates are not interchangeable.']],note:['钱包余额是当前余额，不是所选历史期间的期末余额。需要看期间变化时使用收入、支出和转入转出统计。','Wallet balances are current, not historical closing balances. Use period income, spending and transfers to understand changes.']}
 ]},
 {id:'wallets',group:review,title:['钱包、还款与余额校正','Wallets, repayments and balance correction'],intro:['资金资产管理实际的钱和负债。先区分消费、账户转移与余额调整，再选择对应操作，避免把同一笔消费计算两次。','Assets tracks money and debt. Distinguish purchases, transfers and balance adjustments to avoid counting spending twice.'],sections:[
  {id:'ownership',title:['个人资产和家庭资产分开查看','Separate personal and family assets'],paragraphs:[['“我的资产”只汇总本人个人钱包，包括归档钱包的余额。家庭范围只汇总所选家庭的共同钱包，不会混入各成员的私人银行卡。','My assets includes only your personal wallets, including archived balances. A family scope includes that family’s shared wallets, not members’ private bank accounts.'],['钱包可以跨账本使用。把交易关联到另一个账本不会再次扣款；归档钱包也不会删除历史流水或余额。','Wallets can fund transactions in multiple books. Linking a transaction to another book does not debit it again, and archiving a wallet preserves its history and balance.']],figures:[fig('assets','资产页面：余额分布、期间收支与钱包列表在同一范围下查看。','Assets: balance distribution, period cash flow and wallets share the selected scope.')],action:link('accounts','打开资金资产','Open Assets')},
  {id:'repayment',title:['还款为什么需要两个账户？','Why does repayment need two accounts?'],paragraphs:[['还本金会同时减少付款钱包的钱和信用账户的欠款，所以记录资金转出账户与转入的负债账户。购买发生时已经计过消费，还本金不再重复计入消费支出。','Repaying principal reduces both cash in the paying wallet and debt in the credit wallet. That requires a source and destination. The purchase already counted as spending; repaying its principal does not count again.'],['自有账户充值、提现和互转也使用转账。利息、手续费属于额外成本，应另记支出。若原购买尚未记录，先确认购买和期初负债如何登记，再补完整链条。','Top-ups, withdrawals and movements between your accounts also use transfers. Interest and fees are additional expenses. If the purchase was never recorded, establish the purchase and opening debt before completing the records.']],example:['信用账户买相机 1,000 元：购买记录消费并增加欠款。之后银行卡还本金 200 元：银行卡减少 200 元，欠款减少 200 元，不再增加 200 元消费。','Buy a camera for 1,000 on credit: the purchase creates spending and debt. Repay 200 from a bank account: bank funds and debt each decrease by 200 without another 200 of spending.'],action:link('entry:manual','打开手动记账，选择转账','Open Manual entry, then Transfer')},
  {id:'balance',title:['余额对不上时，先核对再校正','Reconcile before adjusting a balance'],steps:[{title:['检查常见原因','Check common causes'],text:['查看是否选错钱包、漏了退款或转账、重复录入期初余额，或把一张订单拆成多笔实付。','Check the funding wallet, missing refunds or transfers, duplicated opening balances and orders accidentally posted as multiple payments.']},{title:['有流水时使用智能核对','Compare statements when available'],text:['把支付流水截图交给助手，结合编号和相邻顺序定位漏记或重复。存在同名同价消费时不要仅凭金额删除。','Give the assistant statement images to compare references and neighboring sequence. Do not delete same-price purchases based on amount alone.'],action:link('chat','打开助手核对','Open the assistant')},{title:['只需对齐余额时登记差额','Adjust the difference when appropriate'],text:['在钱包的余额校正中填写真实余额和原因。系统保存差额调整，不制造收入或消费，也不会解释漏的是哪笔交易。','Enter the actual balance and reason in wallet correction. The system records a balance adjustment, not income or spending; this does not identify the missing transaction.']}]},
  {id:'lifecycle',title:['归档、合并和删除钱包','Archive, merge or remove wallets'],paragraphs:[['暂时不用的钱包优先归档，之后可恢复。需要合并时选择保留钱包，核对余额：默认相加不一定等于真实金额，尤其是两个钱包曾重复记了期初余额。','Archive unused wallets so they can be restored later. When merging, choose the retained wallet and verify its real balance; adding two balances may be wrong if both included the same opening funds.'],['有流水、校准或周期计划的钱包不能直接当空钱包删除。先按界面合并到其他钱包，相关记录转入保留钱包，原账本归属保持不变。','Wallets with history, adjustments or schedules are not empty wallets. Merge through the interface to move related records to the retained wallet without changing their books.']]}
 ]},
 {id:'reconcile',group:review,title:['用支付流水智能核对','Reconcile payment statements'],intro:['适合“余额不对，但不知道漏了哪笔”的情况。提供完整流水上下文，让助手比对已记账记录，再由你确认补记或修改。','Use reconciliation when balances differ but the missing transaction is unknown. Supply statement context, compare it with saved records, then confirm any corrections.'],sections:[
  {id:'evidence',title:['准备可比较的流水','Prepare comparable evidence'],steps:[{title:['保留上下文','Keep surrounding context'],text:['截图保留日期、商家、金额、订单／流水编号，以及相邻几笔的先后顺序。多张截图按顺序上传，重叠区域可以保留。','Keep dates, merchants, amounts, payment references and adjacent transaction order visible. Upload multiple images in sequence; overlapping regions can help.']},{title:['说明核对范围','State the reconciliation scope'],text:['告诉助手是哪种支付渠道、哪个日期区间、哪个账本或个人钱包范围。微信支付可能由银行卡扣款，应说明实际资金来源。','Specify the payment channel, date range and book or wallet scope. Explain the funding account if a payment app debited a bank card.'],action:link('chat','前往小熊对话','Open Bear assistant')}]},
  {id:'review',title:['逐项处理核对结果','Review each reconciliation result'],paragraphs:[['助手比较编号、时间、金额和前后关系。你可能看到已匹配、疑似漏记、疑似重复和不确定候选；缺少可靠证据时保留不确定，不强行合并。','The assistant compares references, times, amounts and order. Results can include matches, possible missing or duplicate entries and uncertain candidates. Keep uncertainty when evidence is insufficient.'],['确认目标后，让助手准备补记或修改卡片。核对真实记录、钱包和金额，再点击确认；分析文字本身不会修改账目。','Once you identify the target, ask for an entry or edit card. Verify the record, wallet and amount before confirming; analytical text alone does not change transactions.']],figures:[fig('reconcile','核对入口：描述日期与范围，添加流水截图后发送给助手。','Reconciliation input: describe the dates and scope, attach statements and send them to the assistant.')]},
  {id:'retry',title:['超时后如何继续','Continue after a timeout'],paragraphs:[['在后台任务查看失败阶段并重试；已完成的分段结果可以复用。不要同时重复上传整组图片和反复确认草稿。未长期保存的原图可能到期清理，届时需要重新上传。','Inspect the failed stage in Background tasks and retry. Completed image sections can be reused. Avoid resubmitting the same batch and confirming duplicate drafts. Temporary images may expire and then need uploading again.']]}
 ]},
 {id:'activities',group:review,title:['旅行与活动账','Trips and activities'],intro:['用一个活动归集旅行、聚会或项目开销。活动可以跨账本，交易仍保留自己的分类、钱包和访问权限。','Group a trip, gathering or project in an activity. It can span books while transactions retain their categories, wallets and permissions.'],sections:[
  {id:'create',title:['创建并选择活动归属','Create an activity and its scope'],steps:[{title:['填写名称、类型与计划','Set its name, type and plan'],text:['在活动账创建活动，按需要填写日期和预算。旅行、聚会等类型方便之后筛选。','Create an activity with optional dates and budget. Types such as travel or gatherings help later filtering.'],action:link('activities','打开活动账','Open Activities')},{title:['选择个人或家庭','Choose personal or family'],text:['仅自己整理时使用个人活动；需要家庭成员参与时选择家庭。活动共享不会让成员获得原本无权查看的私人交易。','Use a personal activity for yourself or choose a family for participation. Sharing an activity does not expose private transactions that members cannot otherwise access.']}],figures:[fig('activities','活动账：活跃与归档活动分开管理，可查看预算和关联交易。','Activities: manage active and archived groups, budgets and linked records.')]},
  {id:'record',title:['从日常录入直接归入活动','Assign spending during normal entry'],paragraphs:[['在记一笔选择活跃活动后照常保存，或将已有交易关联到活动。活动只增加归集关系，不新增付款，不必为活动另建一份重复账单。','Select an active activity while recording, or link existing transactions afterward. The link adds grouping, not another payment.'],['同一活动既可含私人购物，也可含共享餐饮。活动汇总按当前用户可见交易统计；不同成员看到的明细可能不同。','One activity can include private shopping and shared meals. Activity totals use transactions visible to the current user, so members may see different details.']],action:link('entry:manual','记一笔活动消费','Record activity spending')},
  {id:'archive',title:['结束、恢复与删除','Finish, restore or delete'],paragraphs:[['结束后归档以移出活跃列表，在归档页面仍可查看；需要继续记账时先恢复。删除活动只解除活动关联，不删除原交易。','Archive completed activities to remove them from active lists while retaining access in the archive. Restore before adding more spending. Deleting the activity removes links, not original transactions.']]}
 ]},
 {id:'family',group:review,title:['家庭、共享账本与成员往来','Families, shared books and movements'],intro:['家庭关系、账本权限和实际资金分别管理。先建立成员关系和可见范围，再记录消费或成员间结算。','Family membership, book access and actual funds are managed separately. Establish access before recording purchases and settlements.'],sections:[
  {id:'access',title:['邀请成员与授予账本权限','Invite members and grant book access'],steps:[{title:['发送家庭邀请','Send a family invitation'],text:['家庭负责人按登录账号邀请，对方接受后成为成员。账号由系统管理员维护，加入家庭不会新建另一个账号。','The family owner invites a login account; the recipient joins on acceptance. Administrators manage accounts, and joining a family does not create a second account.'],action:link('families','打开家庭管理','Open Families')},{title:['单独授予共享账本权限','Grant shared-book access separately'],text:['由账本所有者设置成员和角色。加入家庭不会自动开放所有账本；退出家庭也不会撤销另行授予的账本权限。','The book owner sets members and roles. Joining a family does not automatically open every book, and leaving it does not revoke separately granted book access.'],action:link('books','管理账本成员','Manage book members')}],figures:[fig('family','家庭管理：家庭成员与邀请在这里管理。','Families: manage membership and invitations here.'),fig('books','账本管理：每本共享账本单独设置访问权限。','Book management: access is configured separately for each shared book.')]},
  {id:'movement',title:['记录内部转账、AA 与借还款','Record transfers, settlements and loans'],steps:[{title:['选择往来类型','Choose a movement type'],text:['在记一笔 → 家庭往来选择转账、赠与、共同入金、AA 或借还款，检查双方成员、日期和金额。','In Record → Family movements, choose transfer, gift, contribution, settlement or loan/repayment and check members, date and amount.'],action:link('entry:family','打开家庭往来','Open Family movements')},{title:['由收款人确认到账钱包','Let the recipient confirm their wallet'],text:['待确认的往来暂不改变双方余额。收款方用自己的账号选择真实到账钱包，再完成确认。','Pending movements do not yet affect balances. The recipient signs in and selects their actual receiving wallet before confirming.']}],figures:[fig('family-entry','家庭往来工作区：录入、待确认与历史记录在同一入口。','Family movements: entry, pending confirmations and history share a workspace.')]},
  {id:'count',title:['避免把结算重复算成消费','Avoid counting settlements as purchases'],example:['你先替两人支付餐费 200 元，另一人返还你 100 元：商家消费只记录一次，成员返还在家庭往来记录。不要再增加一笔 100 元餐饮支出。','You pay a restaurant 200 for two people and receive 100 from the other person. Record the merchant purchase once and the repayment as a family movement, not another dining expense.'],paragraphs:[['往来详情中的个人标题、备注、流水号与附图由各自维护。这里记录已发生的资金关系，不会发起真实转账。','Each member maintains private titles, notes, references and photos in movement details. These records document transfers; they do not move real money.']]}
 ]},
 {id:'plans',group:review,title:['预算、订阅、分期与分摊','Budgets, subscriptions and installment costs'],intro:['预算关注还可以花多少，周期计划关注下一次付款，分摊关注成本覆盖哪些月份。它们与实际付款记录配合使用。','Budgets track remaining allowance, recurring plans track upcoming payments, and allocation tracks the months a cost covers. They complement actual payment records.'],sections:[
  {id:'shared-recurring',title:['提前规划费用，各自归入账本','Plan recurring costs for separate ledgers'],steps:[{title:['先建立周期费用计划，不扣钱包','Create a plan without charging a wallet'],text:['在费用归属与分担中新建周期计划，填写首次付款日、每隔几个月付款、每人每月承担及自己的归属账本。成员可用个人账本，也可选自己能编辑的共享账本。','In Cost allocation & sharing, create a recurring plan with its first due date, payment interval in months, each person’s monthly share and your cost ledger. Choose a private ledger or a shared ledger you can edit.'],action:link('schedules','打开计划与分摊','Open Plans & allocation')},{title:['参与人自己确认','Each participant accepts'],text:['其他成员打开“我的归属与确认”，查看周期和金额，选择自己的账本并接受。创建人不能替其他成员确认；成员可撤回同意，阻止后续付款确认。','Other participants open My ledger and acceptance, review the interval and amounts, choose their own ledger and accept. The creator cannot accept for them. Withdrawing acceptance blocks future payment confirmation.']},{title:['实际付款后确认本期','Confirm after the real payment'],text:['到期后由付款人确认。未记过账时选择付款钱包和日期，只新增一次实际支出；已通过识图或手动记过账时选择“关联已记账的付款”。完成后自动建立分摊并推进下一个付款日。','When due, the payer confirms after paying. Select the wallet and date if the payment has not been recorded; otherwise choose Link a recorded payment. Confirmation creates the allocation and advances the next due date.']},{title:['按自己的账本查看成本，再关联结算','View your attributed costs and settle separately'],text:['在收支分析切换“分摊项目成本”，勾选“仅当前账本的归属成本”。实际收支仍显示原始付款，不能与分摊成本相加。成员之间真正转钱后，从账期记录打开费用项目，点击“向成员结算”，选择自己的付款钱包、收款成员和金额。收款人选择到账钱包确认后自动关联，不要另记一次房租消费。已有家庭转账可直接关联；首次付款前的成员垫款先记家庭往来，项目建立后关联。','In Analysis, select Allocated project costs and filter to the current ledger. Cash flow still shows the original payment; do not add it to allocated costs. After a real transfer, open the cycle’s cost project and choose Settle with a member. Select your payment wallet, recipient and amount. The recipient confirms their receiving wallet and the transfer settles automatically, without another rent expense. Existing family transfers can be linked. For advances before the first payment, record a family transfer and link it after the project exists.']}],example:['10 月 15 日起每三个月付 12,900 元，每月两人承担 2,900 元和 1,400 元：付款覆盖 10 月 15 日至次年 1 月 15 日，成本归属 10、11、12 月；下一次付款日为 1 月 15 日。','A payment of 12,900 every three months starting October 15, with monthly shares of 2,900 and 1,400, covers October 15 through January 15. Costs belong to October, November and December; the next payment is due January 15.'],note:['计划不会实际支付或到期自动扣账，也不会自动记录房补。尚未处理的账期保留待确认；金额或成员变化时先暂停，再建立新规则。','Plans do not send money, post a payment solely because it is due, or invent income offsets. Unprocessed cycles remain pending. Pause and create a new rule when amounts or participants change.']},
  {id:'budget',title:['设置每月分类预算','Set monthly category budgets'],paragraphs:[['选择预算月份，为需要控制的分类设置额度。查看实际净支出和剩余金额；预算仍按月管理，不随分析页自定义周期变成任意周期预算。','Choose a month and set limits for categories you want to control. Review net spending and remaining allowance. Budgets remain monthly even when Analysis uses a custom period.']],figures:[fig('budgets','每月预算：按分类比较额度和实际开销。','Monthly budgets: compare category limits and spending.')],action:link('budget','打开每月预算','Open Monthly budgets')},
  {id:'subscription',title:['创建订阅或周期计划','Create a subscription or recurring plan'],steps:[{title:['填写频率和下一次日期','Set frequency and next date'],text:['进入计划与分摊，填写服务名称、金额、扣款钱包和周期。GPT、iCloud 或视频会员通常使用会员订阅分类。','Open Plans & allocation and set the service, amount, wallet and interval. Use a subscription category for services such as GPT, iCloud or streaming.'],action:link('schedules','打开计划与分摊','Open Plans & allocation')},{title:['到期核对后确认付款','Review and confirm each payment'],text:['实际金额可能变化，到期后核对再入账。计划不会自动发起扣款；暂停或删除计划不删除已有付款。','Amounts may change, so review each due payment before posting. Plans do not charge your accounts automatically; pausing or deleting them preserves past payments.']}],figures:[fig('plans','周期计划：查看下一次日期与频率，再确认实际付款。','Recurring plans: review the next date and interval before confirming a payment.')]},
  {id:'installment',title:['分期本金与分摊成本分别处理','Separate installments from cost allocation'],paragraphs:[['分期购买先记录消费和负债，还本金用转账；利息与手续费另记支出。提前还款后可以调整剩余期数与日期，不能再把本金当新消费。','An installment purchase records spending and debt; principal repayments use transfers, while interest and fees are expenses. After early repayment, adjust remaining dates and terms without counting principal again.'],['需要看使用期成本时设置覆盖期。日／周按天分摊，月／年按月分摊，尾差按最小货币单位补齐。分摊不改变原付款日期、钱包余额或欠款。','Set a coverage period for usage costs. Day/week coverage is allocated by day and month/year coverage by month, with minor-unit rounding reconciled. Allocation does not change the original payment date, wallet balance or debt.']],example:['一次付清 120 元年费，现金收支在付款日记 120 元；按 12 个月分摊时，每月成本为 10 元。两种口径不能相加。','An annual fee of 120 is a cash payment of 120 on its payment date. Across 12 months, allocated cost is 10 per month. Do not add both views together.']}
 ]},
 {id:'memory',group:support,title:['个人画像与学习纠正','Personal profile and corrections'],intro:['个人画像从已确认账目中整理习惯，按场景提出建议。打开个人资料 → 个人画像，可以看依据、改规则，也能继续管理原有商品记忆。','Your personal profile learns from confirmed records and suggests fields for the current context. Open Profile → Personal profile to inspect evidence, adjust rules and manage existing product memories.'],sections:[
  {id:'browse',title:['先看画像总览','Start with the overview'],steps:[{title:['打开个人画像','Open your personal profile'],text:['总览显示有效账目数量和日期范围。按场景、商家或钱包搜索，筛选稳定习惯、近期变化和仍在观察的建议。','The overview shows the number and date range of valid records. Search contexts, merchants or wallets and filter established, changing or tentative habits.'],action:link('profile:memory','打开个人画像','Open Personal profile')},{title:['查看支持这条建议的记录','Inspect the evidence'],text:['点击习惯卡片，查看候选取值、加权支持占比，以及近 30 天和此前的记录数量。下方来源列表支持分页。支持占比表示记录中的倾向，不是预测准确率。','Open a habit card to inspect alternatives, weighted support and counts from the last 30 days versus earlier records. Supporting records are paginated. Support describes the evidence; it is not prediction accuracy.']}],note:['账目修改、删除或失去访问权限后，下次读取画像就会重新计算。同一笔钱在多个账本展示只算一次依据。','The next profile read reflects edits, deletions and lost access. A payment displayed in several books counts as one observation.']},
  {id:'weights',title:['理解权重与近期变化','Understand weights and recent changes'],paragraphs:[['分类、钱包和消费场景分别判断。每笔依据按交易日期衰减，60 天后权重减半；编辑旧账不会把它变成最近的消费。明确纠正权重更高，未手动确认的自动填充不会算作独立偏好。','Category, wallet and context are evaluated separately. Evidence decays by purchase date, with a 60-day half-life. Editing an old record does not make its purchase recent. Explicit corrections carry more weight; unconfirmed auto-fills do not count as independent preferences.'],['近期习惯与过去不一致时，页面标为“近期有变化”，保留候选供你核对。缺少消费时间时不套用时段偏好；补录旧订单也不会自动采用现在的位置。','When recent behavior differs from older records, the profile marks it Recently changed and retains alternatives for review. Missing purchase times do not activate time-band rules. Backdated receipts never inherit the current location automatically.']]},
  {id:'rules',title:['设置、纠正或停用场景规则','Set, correct or stop a context rule'],steps:[{title:['选择适用条件','Choose when a rule applies'],text:['在“场景与规则”新增规则，选择收支类型，再加商家、消费场景等条件。也可限定工作日／周末、消费时段或已保存的区域；所有条件同时满足才生效。','In Habits & rules, add a rule, choose expense or income and add conditions such as merchant or context. Optionally restrict day type, purchase time or a saved area. All conditions must match.']},{title:['选择要填写的字段','Choose the suggested field'],text:['选择付款钱包、分类或其他字段并填写取值。明确规则优先于统计习惯，本次明确输入仍然优先。若同场景已有冲突规则，需要勾选替换后保存。','Choose a wallet, category or other field and its value. Explicit rules take priority over learned habits; explicit current input still wins. Replacing a conflicting rule for the same context requires checking the replacement option.']},{title:['调整不准确的建议','Correct an inaccurate suggestion'],text:['从习惯卡片展开依据，可以纠正偏好、不再建议某个取值，或停止此场景自动填充。学习记录提供可撤销操作；已有更新的规则不能被旧操作覆盖。','From an insight, correct the preference, exclude an option or stop automatic filling in that context. History offers eligible undo actions; an older action cannot overwrite a newer rule.']}],example:['例如，只在“餐饮 + 午餐”时建议微信钱包，不必把微信设为所有消费的默认付款方式。','For example, suggest a WeChat wallet only for dining at lunch, without making it the default for every purchase.']},
  {id:'apply',title:['记账时采用或撤回建议','Use or undo suggestions while recording'],paragraphs:[['AI 文字、识图和助手卡片使用同一套个人画像。展开“来自你的个人画像”，查看预填字段及依据；有歧义时选择候选，也可撤回填充或直接改字段。正常确认入账仍由你完成。','AI text entry, receipt recognition and assistant cards use the same personal profile. Expand From your personal profile to inspect fields and evidence, choose an alternative or undo a fill. Posting still requires your confirmation.'],['同款商品可以复用身份和规格。本次金额、数量、日期、订单号和流水号不从旧单补齐。历史钱包是建议；本次付款线索不一致或有多个可能钱包时，需要核对。','Repeat purchases can reuse product identity and specifications, never old amounts, quantities, dates or payment references. Historical wallets are suggestions. Conflicting funding evidence or several plausible wallets require review.']]},
  {id:'location',title:['按需使用位置，不持续追踪','Use location on demand'],steps:[{title:['先开启位置辅助','Enable location assistance'],text:['在“学习与隐私”开启位置辅助。登录或打开页面不会触发定位；只有点击“使用当前位置”或“定位并匹配常用区域”才请求浏览器授权。','Enable location assistance in Learning & privacy. Signing in or opening the page never requests location. Only Use current location or Locate a saved area requests browser permission.']},{title:['保存自己命名的区域','Save an area you name'],text:['填写区域名称，例如“公司附近”。定位坐标会降低精度，区域至少约 1.5 公里；也可以只保存名称，之后手动选择。定位被拒绝或失败不影响正常记账。','Name an area, for example Near the office. Coordinates are coarsened and areas cover at least about 1.5 km. You can save a name without coordinates and select it manually. Denial or failure does not block entry.']},{title:['确认这是本次消费地点','Confirm the purchase location'],text:['在 AI 录入区或助手输入选项中添加消费区域。匹配后还需勾选“确认本次消费发生在此区域”，才用于场景匹配。只有另行开启“保留消费区域关联”，入账后才保存此关联用于学习。','Add a purchase area in AI entry or assistant input options. Confirm This purchase took place in this area before it influences matching. After posting, the association is kept for learning only when Retain purchase-area links is enabled.']}],note:['原始坐标不会进入账单、后台记账任务或外部模型。关闭保留开关会删除账目与区域的关联；“清除地点信息”还会移除常用区域及相关规则。','Raw coordinates never enter transactions, background entry jobs or external models. Turning off retention deletes purchase-area links. Clear location information also removes saved areas and their rules.']},
  {id:'manage',title:['管理商品、长期安排和隐私','Manage products, arrangements and privacy'],paragraphs:[['“商品与服务”保留别名、规格和购买来源，可编辑、合并或拆分。“长期安排”查看订阅、活动等关联线索，不会自动创建计划或付款。“待确认”集中处理变化和未确认的记忆。','Products & services retains aliases, specifications and purchase sources, with editing, merge and split controls. Arrangements shows links to subscriptions and activities without creating plans or payments. Review collects changing habits and unconfirmed memories.'],['画像规则和地点仅本人可见。商品记忆仍可明确共享给家庭，但不连带开放私人账单或钱包。遗忘记忆会删除内容和向量，不删除原账单；允许重新学习后才重新纳入。','Profile rules and areas are private. Product memories may still be explicitly shared with a family without exposing private records or wallets. Forgetting removes memory content and vectors, not transactions; relearning needs explicit permission.'],['“学习与隐私”可以暂停自动建议、导出画像，或运行已有的历史整理与向量重建。画像的场景统计直接读取有效账目，不需要先运行历史整理。全局搜索可查明确规则；助手能解释画像，并通过确认卡准备规则修改。','Learning & privacy can pause suggestions, export the profile or run existing history organization and embedding rebuilds. Context statistics read valid transactions directly and do not require a history job first. Global search finds explicit rules; the assistant can explain the profile and prepare rule changes for confirmation.']],action:link('chat','向助手询问画像','Ask the assistant about your profile')}
 ]},
 {id:'assistant',group:support,title:['与助手对话和确认操作','Ask the assistant and confirm actions'],intro:['助手可以解释功能、查账、分析和准备操作。查询范围会影响答案；修改账目必须经过可核对的确认卡。','The assistant explains features, queries records, analyzes spending and prepares actions. Scope affects answers, and financial changes require reviewable confirmation cards.'],sections:[
  {id:'ask',title:['先说范围，再说问题','State the scope and question'],steps:[{title:['选择分析范围','Choose an analysis scope'],text:['确认当前账本、日期或个人钱包口径。查找之前提到的订单时提供编号、金额和大致日期，帮助跨有权限账本定位。','Check the book, dates or personal-wallet scope. For a prior order, provide its reference, amount and approximate date to locate it across accessible books.'],action:link('chat','打开小熊对话','Open Bear assistant')},{title:['把问题写具体','Ask a specific question'],text:['例如“比较这月和上月餐饮开销”或“先找出订单，再把钱包改成储蓄卡”。问功能用法时，助手会检索这本说明书。','For example, compare dining this month and last month, or find an order before changing its wallet. For how-to questions, the assistant searches this manual.']}],figures:[fig('assistant','对话与确认卡：自然语言提出请求，卡片核对后执行。','Conversation and confirmation cards: request an action in words, then review it before execution.')]},
  {id:'confirm',title:['区分回答、修改卡片与正式执行','Distinguish answers, draft edits and execution'],paragraphs:[['分析回答不会直接改账。助手准备新建、修改或删除卡片后，检查目标记录、账本、金额、钱包以及更改字段，再点击确认。编辑卡片不是确认入账。','An analytical response does not change records. After a create, edit or delete card appears, verify the target, book, amount, wallet and changed fields before confirming. Editing a card is not posting it.'],['要求通过对话修改待确认卡片后，应查看更新卡片和旧卡状态。如果只有文字说已修改、没有更新卡片，不要把文字当作已经保存的依据。','After requesting a draft revision, inspect the updated card and old card status. If only text claims a change without an updated card, do not treat that as proof of saving.']]},
  {id:'history',title:['切页、历史记录与后台任务','Navigation, history and background work'],paragraphs:[['消息发送后保存到历史，离开页面不取消后台处理。通过历史／报告回到对话，后台任务查看处理进度或失败原因。需要长期保留的分析可以保存为报告。','Messages persist on send, and navigating away does not cancel background work. Use History / reports to return, and Background tasks for progress or errors. Save useful analysis as a report.'],['密码、模型密钥和文件上传应在专门页面完成。助手提供页面入口，不需要你在聊天里发送密码或密钥。','Use dedicated pages for passwords, model keys and uploads. The assistant can link those pages without asking for secrets in chat.']]}
 ]},
 {id:'search',group:review,title:['搜索与整理已有账单','Search and organize saved records'],intro:['全局搜索寻找系统记录，说明书搜索寻找操作方法。查到记录后先核对身份，再修改、关联或整理。','Global search finds application records; manual search finds instructions. Verify the record before changing, linking or organizing it.'],sections:[
  {id:'find',title:['跨账本查找交易','Find transactions across books'],paragraphs:[['点击顶部放大镜或 Ctrl／⌘ K。默认搜索全部有权限账本，可按账本、类型、日期和金额缩小结果。商品、商家、备注、订单号及流水号都能用于查找。','Use the top magnifying glass or Ctrl/⌘ K. Search spans accessible books by default and can be narrowed by book, type, date and amount. Use product, merchant, notes or payment references.'],['重复购买同名商品时，优先用订单／流水编号定位。搜索商品明细金额和整单金额是不同条件；展开订单检查后再操作。','For repeat purchases, prefer order/payment references. Item subtotal and full-order amount are different search fields; expand the order and verify it first.']],figures:[fig('search','全局搜索：按结果类型和账本范围查找，再打开详情。','Global search: refine by record type and book scope, then open details.')]},
  {id:'organize',title:['移动、关联与删除的区别','Move, link or delete'],paragraphs:[['移动把记录调整到另一账本。关联复制让同一付款在多个账本展示，实际金额和日期保持关联，不再次扣款；分类和备注可以按各账本维护。','Moving changes the record’s book. Linking displays the same payment in multiple books without another debit; amount and date remain linked while categories and notes can be book-specific.'],['原消费与退款一起整理，商品、图片和分摊随记录保留。目标账本成员可以查看这些内容，整理前确认共享范围。','Organize purchases and refunds together, preserving items, images and allocation. Members of the destination book can see that content, so check access first.']],action:link('insights','打开明细进行整理','Open records for organization'),note:['删除某本账本的关联不一定删除整笔付款。删除最后一份记录会撤销相应资产收支，确认前检查提示。','Removing one book’s link does not necessarily delete the payment. Deleting the final record reverses its wallet effect; check the confirmation.']},
  {id:'limits',title:['理解两类搜索的范围','Understand search scope'],paragraphs:[['交易和全局记录搜索以已保存文字及字段为依据，不直接搜索未识别照片里的内容。说明书搜索结合关键词和语义检索，财务记忆另有自己的权限过滤与向量检索。','Transaction and global searches use saved text and fields, not unread text inside photos. Manual search combines keyword and semantic retrieval; financial memory has separate permission-filtered retrieval.']]}
 ]},
 {id:'import',group:record,title:['导入微信与支付宝账单','Import payment statements'],intro:['适合批量补齐历史交易。导入先生成可核对记录，确认渠道、钱包和重复项后再保存。','Use import to fill historical transactions in batches. Review channels, funding wallets and duplicates before posting.'],sections:[
  {id:'file',title:['准备并上传 CSV 文件','Prepare and upload a CSV'],steps:[{title:['从支付平台导出账单','Export a statement'],text:['使用微信或支付宝提供的 CSV 账单。不要把文件只改扩展名；截图应走 AI 图片识别。','Use a CSV exported by WeChat or Alipay. Renaming another file’s extension does not convert it; screenshots belong in AI image recognition.']},{title:['选择文件导入','Choose the file'],text:['在记一笔切换到微信／支付宝账单，上传文件。支持 UTF-8 和 GBK 中文编码，不能确定的信息会留待核对。','In Record, choose the payment-statement import tab and upload the file. UTF-8 and GBK Chinese encodings are supported; uncertain fields remain for review.'],action:link('entry:import','打开账单导入','Open statement import')}],figures:[fig('import','账单文件导入：选择 CSV，而不是上传订单图片。','Statement import: choose a CSV rather than an order image.')]},
  {id:'review',title:['核对资金归属与重复项','Review funding and duplicates'],paragraphs:[['平台名称不代表实际钱包，逐笔检查扣款或收款账户。未支付记录不会入账；相似或已有记录要核对，不要把重复导入当成新消费。','A platform name does not identify the funding wallet. Check paying or receiving accounts. Unpaid records are not posted; review similar or existing entries to avoid duplicates.'],['保存前检查总笔数、收入支出方向、金额和日期。先完成一小批，确认账户余额变化符合预期，再继续剩余记录。','Check count, direction, amounts and dates before saving. Start with a small batch and verify wallet effects before continuing.']],questions:[{q:['文件乱码或列无法识别怎么办？','What if the file is garbled or columns are not recognized?'],a:['重新使用支付平台的原始导出文件；检查是否为支持的 CSV。不要在无法核对金额和日期时直接确认。','Use the original platform export and confirm it is a supported CSV. Do not post records if you cannot verify amounts and dates.']}]}
 ]},
 {id:'settings',group:support,title:['分类、个人资料与模型设置','Categories, profile and model settings'],intro:['个人资料和分类属于用户，模型与语言配置属于部署。按权限进入对应位置修改，避免把个人偏好误当成共享设置。','Profiles and categories belong to users; model and language configuration belongs to the deployment. Use the appropriate scope and permissions.'],sections:[
  {id:'categories',title:['维护自己的分类','Maintain personal categories'],paragraphs:[['在账本设置添加、搜索、编辑或调整分类顺序，必要时停用。分类跟随个人账户，在不同账本通用，其他成员的分类调整不会覆盖你的设置。','Add, search, edit, reorder or deactivate categories in Book settings. Your categories apply across books; another member’s changes do not overwrite them.'],['按消费目的分类：会员服务使用会员订阅，旅行中吃饭仍可用餐饮，再通过活动归入旅行。','Classify by purpose: memberships use subscriptions, and dining during a trip can remain Dining while the activity groups it into the trip.']],figures:[fig('categories','分类管理：维护个人分类名称、图标和顺序。','Category management: maintain personal names, icons and ordering.')],action:link('settings','打开账本设置','Open Book settings')},
  {id:'profile',title:['资料、主题与退出登录','Profile, theme and sign-out'],paragraphs:[['在个人资料修改头像、显示名称和密码；外观主题可选择小熊或极简风格。手机的“更多”菜单包含个人资料和退出登录，退出前等待草稿同步完成。','Edit avatar, display name and password in Profile, and choose the bear or minimal theme. Mobile More includes Profile and sign-out; allow drafts to sync before signing out.']],figures:[fig('profile','个人资料：账号资料、外观主题和记忆中心分别管理。','Profile: account details, theme and memory management are separate tabs.')],action:link('profile','打开个人资料','Open Profile')},
  {id:'models',title:['识图、助手和记忆模型分别配置','Configure recognition, assistant and memory models'],paragraphs:[['管理员在账本设置配置快速识图的文字／图片模型与 AI 助手模型。记忆中心的学习与设置中配置嵌入、提炼和候选判别模型，并测试连接。','Administrators configure recognition text/vision models and assistant models in Book settings. Memory embedding, extraction and candidate judgment are configured and tested in Memory center’s Learning & settings.'],['说明书检索复用记忆嵌入模型。正文更新后会自动重建变化章节的向量，未完成或服务失败时仍可关键词检索。','Manual search reuses the memory embedding model. Changed chapters are reindexed after updates; keyword search remains available during indexing or service failure.'],['语言和币种由部署配置决定，不是个人切换项。中文界面使用中文说明和截图，英文界面使用英文；改变币种配置不会换算既有账目金额。','Language and currency are deployment settings, not per-user toggles. Chinese and English interfaces use their matching manual and screenshots. Changing currency configuration does not convert existing amounts.']]}
 ]},
 {id:'troubleshooting',group:support,title:['常见问题与排查顺序','Troubleshooting and next steps'],intro:['先检查范围和已保存状态，再处理数据。下面按常见现象给出排查顺序，不需要重建账本或重复录入来试错。','Check scope and saved state before changing data. Use these checks to diagnose common issues without recreating books or posting duplicates.'],sections:[
  {id:'questions',title:['按现象排查','Check the symptom'],questions:[{q:['为什么助手两次给出的统计不同？','Why did the assistant give different totals?'],a:['比较账本／个人钱包范围、日期和筛选，再让助手用原记录 ID 或订单号复核。当前范围未找到不等于账目不存在，也不应直接判定上一条结果是编造。','Compare book/wallet scope, dates and filters, then ask it to verify the original record ID or order reference. A missing result in one scope does not prove the record is absent or the earlier answer was fabricated.']},{q:['金额对了，钱包余额还是不对？','Why is the amount correct but the balance wrong?'],a:['检查实际扣款钱包、期初余额、转账和退款方向，再查看是否同一付款重复入账。需要查漏时使用流水核对，只需对齐时使用余额校正。','Check the funding wallet, opening balance, transfer/refund direction and duplicate postings. Use statements to find omissions or balance correction to align the balance.']},{q:['切换页面后找不到识图结果？','Where is recognition after leaving the page?'],a:['先查看后台任务是否完成，再回到记一笔检查草稿；助手任务回历史对话查看。失败先重试任务，不要先重新上传并重复确认。','Check Background tasks, then return to Record for drafts or conversation history for assistant work. Retry a failed task before resubmitting and confirming duplicates.']},{q:['搜索没有结果怎么办？','What if search returns nothing?'],a:['交易搜索先去掉日期和账本限制，尝试订单号或较短商品名；说明书搜索可换成关键词或问题，也可按目录浏览。只有保存的交易文字参与交易搜索。','For records, remove date/book filters and try a reference or shorter product name. For help, try keywords, a question or the contents. Transaction search uses saved record text.']},{q:['为什么某些按钮看不到或不可用？','Why is a button missing or disabled?'],a:['检查账本是否只读、目标是否归档、卡片是否已确认，以及当前账号是否有管理员权限。不要通过另记一笔绕过已有记录状态。','Check read-only access, archived targets, confirmed card state and administrator permissions. Do not create a duplicate transaction to work around an existing record’s state.']}]},
  {id:'ask',title:['带着上下文询问助手','Ask with enough context'],paragraphs:[['说明你在哪个页面、想完成什么、实际看到什么；涉及账单时提供日期、金额或订单号，不发送密码和密钥。使用下面的答疑按钮可以先带入本章主题，再补充你的问题。','Describe the page, intended task and observed behavior. For transactions, include date, amount or reference, but never passwords or keys. The assistant button below prefills this chapter so you can add details.']]}
 ]}
];
