import type {PoolClient} from 'pg';
import {z} from 'zod';
import {db,transaction,lockBook} from './db';
import {Failure} from './access';
import {periodShare,periodLastDay,advancePeriod as calculatePeriod} from '@/lib/period';
import type {PeriodUnit} from '@/lib/period';
function advancePeriod(start:string,unit:PeriodUnit,count:number,anchor?:number){try{return calculatePeriod(start,unit,count,anchor);}catch(e){throw new Failure(e instanceof Error?e.message:'周期无效');}}
const month=z.string().regex(/^[1-9]\d{3}-(0[1-9]|1[0-2])$/);
export async function allocations(book:string,method:string,body:unknown,params:URLSearchParams, connection?:PoolClient){
 if(method==='GET'){
 const selected=month.parse(params.get('month'));const result=(await db.query(`SELECT COALESCE((SELECT json_agg(x) FROM (SELECT t.id,t.version,t.title,t.payee,t.product,t.category,t.amount::float8 AS amount,to_char(t.date,'YYYY-MM-DD') AS date,to_char(a.start_month,'YYYY-MM') AS start,a.months,a.period_unit,COALESCE(a.period_count,a.months) AS period_count,to_char(COALESCE(a.start_date,a.start_month),'YYYY-MM-DD') AS start_date,COALESCE((SELECT sum(r.amount) FROM transactions r WHERE r.refund_of=t.id AND r.book_id=t.book_id AND r.kind='refund' AND NOT r.deleted),0)::float8 AS refunded FROM expense_allocations a JOIN transactions t ON t.id=a.transaction_id WHERE t.book_id=$1 AND t.kind='expense' AND NOT t.deleted) x),'[]'::json) AS items, COALESCE((SELECT sum(CASE WHEN t.kind='refund' THEN -t.amount ELSE t.amount END) FROM transactions t WHERE t.book_id=$1 AND NOT t.deleted AND t.kind IN ('expense','refund') AND date_trunc('month',t.date)=$2::date AND NOT EXISTS(SELECT 1 FROM expense_allocations a JOIN transactions original ON original.id=a.transaction_id WHERE original.kind='expense' AND NOT original.deleted AND (a.transaction_id=t.id OR a.transaction_id=t.refund_of))),0)::float8 AS ordinary`,[book,selected+'-01'])).rows[0];
 const items=result.items.map((x:any)=>({...x,end:periodLastDay(x.start_date,x.period_unit,x.period_count),monthly:Math.sign(x.amount-x.refunded)*periodShare(Math.abs(x.amount-x.refunded),x.start_date,x.period_unit,x.period_count,selected)}));const allocated=items.reduce((n:number,x:any)=>n+x.monthly,0);return {month:selected,items,allocated,ordinary:result.ordinary,total:result.ordinary+allocated};
 }
 const b=z.object({id:z.string().uuid(),version:z.number().int(),start:month.optional(),months:z.number().int().min(1).optional(),periodUnit:z.enum(['day','week','month','year']).default('month'),periodCount:z.number().int().positive().safe().optional(),startDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),remove:z.boolean().default(false)}).parse(body);
 return transaction(async c=>{await lockBook(c,book);const t=(await c.query('SELECT version,kind FROM transactions WHERE id=$1 AND book_id=$2 AND NOT deleted',[b.id,book])).rows[0];if(!t||t.kind!=='expense')throw new Failure('请选择当前账本中的消费支出');if(t.version!==b.version)throw new Failure('记录已更新，请重新打开后设置',409);if(b.remove)await c.query('DELETE FROM expense_allocations WHERE transaction_id=$1',[b.id]);else{const count=b.periodCount||b.months,start=b.startDate||(b.start?b.start+'-01':'');if(!start||!count)throw new Failure('请填写开始日期和覆盖周期');const normalized=b.periodUnit==='month'||b.periodUnit==='year'?start.slice(0,7)+'-01':start;advancePeriod(normalized,b.periodUnit,count);await c.query('INSERT INTO expense_allocations(transaction_id,start_month,months,start_date,period_unit,period_count) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(transaction_id) DO UPDATE SET start_month=$2,months=$3,start_date=$4,period_unit=$5,period_count=$6',[b.id,normalized.slice(0,7)+'-01',b.periodUnit==='month'?count:b.periodUnit==='year'?count*12:1,normalized,b.periodUnit,count]);}await c.query('UPDATE transactions SET version=version+1 WHERE id=$1',[b.id]);return {ok:true};},connection);
}
