import type {PoolClient} from 'pg';
import {db} from './db';
import {Failure} from './access';
import {z} from 'zod';
export async function movementBookOptions(c:PoolClient,user:string){const books=(await c.query("SELECT b.id,b.name,b.icon FROM books b JOIN members m ON m.book_id=b.id WHERE b.owner_id=$1 AND b.kind='private' AND m.user_id=$1 AND m.role<>'viewer' ORDER BY b.created_at",[user])).rows;const preferred=(await c.query('SELECT book_id FROM family_book_preferences WHERE user_id=$1',[user])).rows[0];return {books,defaultBookId:preferred?books.find(b=>b.id===preferred.book_id)?.id||null:(books.length===1?books[0].id:null)};}
export async function linkMovementBook(c:PoolClient,user:string,movement:string,requested?:string|null){const options=await movementBookOptions(c,user);const book=requested===undefined?options.defaultBookId:requested;if(book){z.string().uuid().parse(book);if(!options.books.some(b=>b.id===book))throw new Failure('只能选择自己的个人账本',403);await c.query('INSERT INTO family_movement_books VALUES($1,$2,$3) ON CONFLICT(movement_id,user_id) DO UPDATE SET book_id=EXCLUDED.book_id',[movement,user,book]);await c.query('INSERT INTO family_book_preferences VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET book_id=EXCLUDED.book_id',[user,book]);}else{await c.query('DELETE FROM family_movement_books WHERE movement_id=$1 AND user_id=$2',[movement,user]);if(requested===null)await c.query('INSERT INTO family_book_preferences VALUES($1,NULL) ON CONFLICT(user_id) DO UPDATE SET book_id=NULL',[user]);}}
export async function bookMovements(user:string,book:string,params:URLSearchParams){z.string().uuid().parse(book);if(!(await db.query("SELECT 1 FROM books b JOIN members m ON m.book_id=b.id WHERE b.id=$1 AND b.owner_id=$2 AND b.kind='private' AND m.user_id=$2",[book,user])).rowCount)throw new Failure('无权查看此个人账本',403);
 const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/);const from=date.parse(params.get('from')),to=date.parse(params.get('to'));const offset=z.coerce.number().int().nonnegative().parse(params.get('offset')||0);
 const rows=(await db.query(`SELECT v.id,v.family_id,v.kind,v.status,v.amount::float8 AS amount,to_char(v.date,'YYYY-MM-DD') AS date,v.note,CASE WHEN v.sender_id=$1 THEN 'out' ELSE 'in' END AS direction,CASE WHEN v.sender_id=$1 THEN r.name ELSE s.name END AS counterparty,CASE WHEN v.sender_id=$1 THEN a.name ELSE t.name END AS wallet, count(*) OVER()::int AS total FROM family_movement_books l JOIN family_movements v ON v.id=l.movement_id JOIN users s ON s.id=v.sender_id LEFT JOIN users r ON r.id=v.recipient_id LEFT JOIN accounts a ON a.id=v.source_id AND a.owner_id=$1 LEFT JOIN accounts t ON t.id=v.target_id AND t.owner_id=$1 WHERE l.user_id=$1 AND l.book_id=$2 AND v.date BETWEEN $3::date AND $4::date AND v.status<>'cancelled' ORDER BY v.date DESC,v.created_at DESC LIMIT 20 OFFSET $5`,[user,book,from,to,offset])).rows;return {rows,total:rows[0]?.total||0};}
