import {deployment} from '@/lib/deployment';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {db,transaction} from './db';
import {Failure,type User,member} from './access';
import {enqueue,watchJob} from './jobs';
const uuid=z.string().uuid();
export async function financeChat(book:string,u:User,method:string,body:any,params:URLSearchParams,signal:AbortSignal){
 if(method==='GET'){const id=params.get('id');if(id){uuid.parse(id);const c=(await db.query('SELECT * FROM finance_conversations WHERE id=$1 AND book_id=$2 AND user_id=$3',[id,book,u.id])).rows[0];if(!c)throw new Failure('对话不存在',404);return {conversation:c,turns:(await db.query('SELECT * FROM finance_turns WHERE conversation_id=$1 ORDER BY created_at,id',[id])).rows};}return {conversations:(await db.query('SELECT id,title,updated_at FROM finance_conversations WHERE book_id=$1 AND user_id=$2 ORDER BY updated_at DESC',[book,u.id])).rows,reports:(await db.query('SELECT * FROM finance_reports WHERE book_id=$1 AND user_id=$2 ORDER BY created_at DESC',[book,u.id])).rows};}
 body.language=deployment().language;
 const op=z.enum(['create','rename','delete','send','save_report','edit_report','delete_report']).parse(body.operation);
 if(op==='create'){const id=randomUUID();await db.query('INSERT INTO finance_conversations(id,book_id,user_id,title) VALUES($1,$2,$3,$4)',[id,book,u.id,body.language==='en'?'New conversation':'新的财务对话']);return {id};}
 if(op==='edit_report'||op==='delete_report'){const b=z.object({id:uuid,version:z.number().int(),title:z.string().trim().min(1).max(100).optional(),content:z.string().max(80000).optional()}).parse(body);const q=op==='delete_report'?await db.query('DELETE FROM finance_reports WHERE id=$1 AND book_id=$2 AND user_id=$3 AND version=$4',[b.id,book,u.id,b.version]):await db.query('UPDATE finance_reports SET title=COALESCE($5,title),content=COALESCE($6,content),version=version+1 WHERE id=$1 AND book_id=$2 AND user_id=$3 AND version=$4',[b.id,book,u.id,b.version,b.title,b.content]);if(!q.rowCount)throw new Failure('报告已变化或不存在，请刷新',409);return {ok:true};}
 if(op==='save_report'){const turn=uuid.parse(body.turnId);const t=(await db.query("SELECT t.* FROM finance_turns t JOIN finance_conversations c ON c.id=t.conversation_id WHERE t.id=$1 AND c.book_id=$2 AND c.user_id=$3 AND t.status='complete'",[turn,book,u.id])).rows[0];if(!t)throw new Failure('请选择一条已完成的回答');const id=randomUUID(),title=z.string().trim().min(1).max(100).parse(body.title||t.question.slice(0,60));await db.query('INSERT INTO finance_reports(id,book_id,user_id,title,content,artifacts,model) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,book,u.id,title,t.answer,t.artifacts,t.model]);return {id};}
 const id=uuid.parse(body.id);const conversation=(await db.query('SELECT * FROM finance_conversations WHERE id=$1 AND book_id=$2 AND user_id=$3',[id,book,u.id])).rows[0];if(!conversation)throw new Failure('对话不存在',404);
 if(op==='delete'){if((await db.query("SELECT 1 FROM ai_jobs WHERE kind='chat' AND payload->>'id'=$1 AND status IN ('queued','running')",[id])).rowCount)throw new Failure('请先取消这段对话的后台任务',409);await db.query('DELETE FROM finance_conversations WHERE id=$1',[id]);return {ok:true};}
 if(op==='rename'){const title=z.string().trim().min(1).max(100).parse(body.title);await db.query('UPDATE finance_conversations SET title=$1,updated_at=now() WHERE id=$2',[title,id]);return {ok:true};}
 const b=z.object({deviceTime:z.string().max(30).optional(),useHistory:z.boolean().default(false),language:z.enum(['en','zh-CN']).default('zh-CN'),requestId:uuid,text:z.string().max(12000),month:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),images:z.array(z.string().regex(/^(data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+|\/api\/receipts\/[0-9a-f-]{36})$/)).default([])}).parse(body);if(!b.text.trim()&&!b.images.length)throw new Failure('请输入问题或添加账单图片');
 await transaction(async c=>{await c.query('SELECT id FROM finance_conversations WHERE id=$1 FOR UPDATE',[id]);if((await c.query("SELECT 1 FROM ai_jobs WHERE kind='chat' AND payload->>'id'=$1 AND status IN ('queued','running')",[id])).rowCount)throw new Failure('这段对话仍在后台处理，可到后台任务查看或取消',409);await c.query('INSERT INTO finance_turns(id,conversation_id,question) VALUES($1,$2,$3)',[b.requestId,id,b.text||(b.language==='en'?'Please read the attached receipts':'请识别附图账单')]);await c.query('UPDATE finance_conversations SET title=CASE WHEN title=$1 THEN $2 ELSE title END,updated_at=now() WHERE id=$3',[b.language==='en'?'New conversation':'新的财务对话',(b.text||(b.language==='en'?'Receipt recognition':'图片账单识别')).slice(0,60),id]);await enqueue(u,book,'chat',{...b,id},b.requestId,c);});
 return body.background===true?{jobId:b.requestId}:watchJob(b.requestId,signal);
}
