import {z} from 'zod';
import {db,transaction,lockBook} from './db';
import {Failure,type User,passwordHash} from './auth';
import stickers from '@/lib/stickers.json';
const name=z.string().trim().min(1).max(80);
export const avatar=z.string().max(350000).refine(v=>v.startsWith('sticker:')?stickers.includes(v.slice(8)):/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v)?true:v.length>0&&v.length<=12&&!/[<>]/.test(v),'头像格式无效，请重新选择图片并等待自动压缩完成');
export async function profile(u:User,body:unknown){const b=z.object({name,avatar}).parse(body);await db.query('UPDATE users SET name=$1,avatar=$2 WHERE id=$3',[b.name,b.avatar,u.id]);return {ok:true};}
export async function manageUser(u:User,body:unknown){if(!u.admin)throw new Failure('需要管理员权限',403);const b=z.object({id:z.string().uuid(),name,avatar,disabled:z.boolean(),password:z.string().min(1).max(200).optional()}).parse(body);if(b.id===u.id&&b.disabled)throw new Failure('不能停用自己的账号');return transaction(async c=>{const target=(await c.query('SELECT admin FROM users WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!target)throw new Failure('用户不存在',404);if(target.admin&&b.id!==u.id)throw new Failure('其他管理员请自行管理其账号');await c.query('UPDATE users SET name=$1,avatar=$2,disabled=$3 WHERE id=$4',[b.name,b.avatar,b.disabled,b.id]);if(b.password)await c.query('UPDATE users SET password=$1 WHERE id=$2',[passwordHash(b.password),b.id]);if(b.disabled||b.password)await c.query('DELETE FROM sessions WHERE user_id=$1',[b.id]);return {ok:true};});}
export async function bookMetadata(book:string,body:unknown){const b=z.object({name,icon:z.string().min(1).max(12),description:z.string().trim().max(500),kind:z.enum(['private','shared'])}).parse(body);if(b.icon.startsWith('sticker:')&&!stickers.includes(b.icon.slice(8)))throw new Failure('表情不存在');return transaction(async c=>{await lockBook(c,book);if(b.kind==='private'&&(await c.query('SELECT 1 FROM books WHERE id=$1 AND family_id IS NOT NULL',[book])).rowCount)throw new Failure('请先在家庭管理中解除账本关联，再改为私人账本');if(b.kind==='private'&&(await c.query("SELECT 1 FROM members WHERE book_id=$1 AND role<>'owner'",[book])).rowCount)throw new Failure('请先移除其他成员，再改为私人账本');await c.query('UPDATE books SET name=$1,icon=$2,description=$3,kind=$4 WHERE id=$5',[b.name,b.icon,b.description,b.kind,book]);return {ok:true};});}
