import {receiptOriginSchema,receiptOriginInstructions,receiptPlatform,matchReceiptWallet} from '@/lib/receipt-origin';
import {listAssets} from './accounts';
import {withDeviceTime} from '@/lib/entry-time';
import {sceneInstructions} from '@/lib/entry-scene';
import {applyPreferences} from './receipt-preferences';
import {cleanReceiptNote} from './receipt-note';
import {deployment} from '@/lib/deployment';
import {receiptId,resolveReceipt} from './receipts';
import {Annotation,StateGraph,START,END} from '@langchain/langgraph';
import {verifyAndRepair} from './receipt-verification';
import {mergeReceipts} from './receipt-merge';
import {receiptImageBatches} from './receipt-images';
import {listCategories} from './categories';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {callModel,type ModelProgress} from './ai';
import {db} from './db';
import {details,matchReason,refundCandidates,missingFields,type Comparable} from './intake';
import {Failure} from './access';
const proposed=z.preprocess(value=>value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value).filter(([,v])=>v!==null)):value,z.object({...details,receiptOrigin:receiptOriginSchema.optional(),walletCandidates:z.array(z.string().uuid()).default([]),walletMatch:z.enum(['funding','channel']).optional(),currency:z.string().max(12).optional(),id:z.string().uuid().optional(),kind:z.enum(['income','expense','transfer','refund']),amount:z.number().int().min(0).max(100000000000).default(0),date:z.string().default(''),payee:z.string().max(120).default(''),category:z.string().max(60).default('其他'),note:z.string().max(2000).default(''),accountId:z.string().default(''),targetId:z.string().nullable().optional(),externalId:z.string().max(200).optional(),status:z.enum(['paid','pending','closed','refund_pending','refunded','unknown']).default('unknown')}));
export async function existingEntries(book:string){return (await db.query(`SELECT id,kind,amount::float8 AS amount,to_char(date,'YYYY-MM-DD') AS date,payee,account_id AS "accountId",external_id AS "externalId",order_id AS "orderId",platform,occurred_at AS "occurredAt",product,category,note,version FROM transactions WHERE book_id=$1 AND NOT deleted ORDER BY date DESC`,[book])).rows as Comparable[];}
export function reconcile(proposals:ReturnType<typeof proposed.parse>[],existing:Comparable[]){
 const accepted:Comparable[]=[];
 return proposals.map(e=>{
  const id=e.id||randomUUID();const item={...e,id,note:cleanReceiptNote(e.note)};
  const matches=[...existing,...accepted].filter(r=>r.id!==id).map(r=>({record:r,reason:matchReason(item,r)})).filter(m=>m.reason).slice(0,8);
  const originals=e.kind==='refund'?refundCandidates(item,[...existing,...accepted]).slice(0,20):[];
  const result={...item,missing:missingFields(item),matches,refundCandidates:originals,action:matches.length?'skip':'create',refundOf:originals.length===1?originals[0].id:null};
  if(!matches.length)accepted.push(item);return result;
 });
}
async function extractReceipt(book:string,body:unknown,progress:ModelProgress={}){
 const b=z.object({language:z.enum(['en','zh-CN']).default('zh-CN'),text:z.string().max(12000).default(''),images:z.array(z.string()).default([]),image:z.string().optional(),useHistory:z.boolean().default(false)}).parse(body);b.language=deployment().language;
 const images=b.images.length?b.images:b.image?[b.image]:[];

 if(images.some(i=>!receiptId(i)&&!/^data:image\/(png|jpeg|webp);base64,/.test(i)))throw new Failure('截图需为PNG、JPEG或WebP');


 const categoryOptions=(await listCategories(book)).filter(c=>!c.archived).map(c=>c.name);
 const all:z.infer<typeof proposed>[]=[];
 let batch=0;
 for await(const prepared of receiptImageBatches(images,progress.signal,s=>resolveReceipt(s,book))){
 progress.signal?.throwIfAborted();progress.onStage?.(b.language==='en'?`Reading batch ${batch+1} of ${images.length} source images`:`识别助手：第 ${batch+1} 批，共 ${images.length} 张原图`);
 const cached=await progress.checkpoint?.get(`batch:${batch}`);
 const output=cached||await callModel(b.language==='en'?`Read all orders, payment records and refunds from the supplied images and text. Deployment currency: ${deployment().currency}. If another currency is explicitly visible, return that currency code without conversion. Otherwise use the deployment currency. Write summaries and explanations in English; preserve original merchant names and existing category names. Image relationships: ${prepared.labels.join("; ")}. Available categories: ${JSON.stringify(categoryOptions)}. Text: ${b.text}. ${sceneInstructions} ${receiptOriginInstructions}
Return JSON {"message":"explanation","entries":[{"currency":"ISO currency code","kind":"expense|income|transfer|refund","amount":0,"date":"YYYY-MM-DD or empty","occurredAt":"visible timestamp","title":"short merchant-led title","payee":"merchant","platform":"platform","orderId":"order number","externalId":"payment or refund reference, omit if absent","product":"concise product summary","lineItems":[{"kind":"item|discount|fee","name":"short item name","quantity":null,"unitPrice":null,"amount":null}],"category":"existing category name","categorySource":"explicit only when the user explicitly named this category; otherwise omit","note":"necessary explanation","accountId":"","targetId":null,"status":"paid|pending|closed|refund_pending|refunded|unknown","source":"source image numbers or text"}]}.
All monetary values are integer minor units (100 per major unit). Extract multiple orders from each image. Merge complementary screenshots or long-image sections of the same order using order IDs, merchant, time and item positions, never amount alone. Keep one final paid total. Deduplicate overlapping rows by context and position, but retain genuinely repeated purchases. Flag conflicting or ambiguous evidence in note. Separate title from item descriptions: prefer the visible store or restaurant name, otherwise use a short spending description without inventing a merchant. Summarize verbose product names to essential type, specification and quantity. Include up to 200 line items per order; never count items as separate transactions. Unknown item amounts, quantities or unit prices must be null, not zero. Do not distribute the total to invent item prices. Explicit checkout discounts are negative discount rows; delivery or packaging fees are positive fee rows. Do not subtract discounts already reflected in item subtotals. Never invent a discount to balance a discrepancy. Example: items 105.00, checkout discount 5.00 => item 10500, discount -500, amount 10000. Exclude total/payment summary rows from line items. Empty lineItems if none visible.
Merge order and payment evidence for the same payment without adding their amounts. Do not invent dates, amounts, account IDs or order IDs. Missing order amount is 0 for review; missing date/account is empty. Refunds are not income: only received refunds are kind refund. Pending refunds have refund_pending status; unpaid and closed orders are pending/closed. If original payment and actual refund are both visible, return separate expense/refund with their own dates and amounts. A refund reference must not reuse the original payment reference. An expense with refunded status still represents original payment. Unknown status requires review.
Recognize platforms from explicit text or distinctive visual evidence following receiptOrigin instructions; wallet selection is a separate step. Always leave accountId empty and targetId null. A missing funding account is not a recognition error. Never put internal field names, account-matching explanations or requests to select an account in note/message. Notes contain only useful extra context such as purpose, reimbursement or gifts. Omit transient fulfillment status, repeated totals and missing-field commentary. Use an empty note when there is no useful extra context. Keep bundles with only a visible bundle price as one line; never infer per-item prices from promotional slogans. Withdrawals, top-ups and credit-card/BNPL principal repayments are transfers, not income/expense. Explicit interest and fees are separate expenses. Credit purchases are expenses at purchase, not again at repayment. Do not infer a principal/fee split when it is missing. Use today only when text explicitly says today: ${new Date().toISOString().slice(0,10)}.`:`请用简体中文生成摘要。账本币种：${deployment().currency}。若原图明确是其他币种，currency必须填原图币种，不得换算或默认为账本币种；未显示币种时用账本币种。自动识别：自主区分独立订单、同一订单跨图及支付流水。图片对应关系：${prepared.labels.join('\n')}。分类优先从这些可用分类选择：${JSON.stringify(categoryOptions)}。识别所有图片中的所有订单、支付流水、退款，图片可重叠。同一个订单跨图或长图分段，只输出一个完整条目；订单号、商家、时间、连续商品位置共同判断归属，不能只按金额或商家归并。相邻图的重复行根据上下文和位置只保留一次，跨图互补字段补齐；同一订单中真实重复购买的行保留，不得仅凭名称价格相同全局去重。整单实付只取最终付款金额，不累加各图重复总额；数量和单价不明留null。订单不连续、价格冲突或模糊处写入note供核对。返回JSON {"message":"说明，使用所选界面语言","entries":[{"currency":"币种代码，例如USD、EUR、GBP、CNY","kind":"expense|income|transfer|refund","amount":整数分,"date":"YYYY-MM-DD或空字符串","occurredAt":"可见交易时间原文","title":"简短账目主标题，优先店名", "payee":"商家","platform":"京东/拼多多/抖音/微信/支付宝等","orderId":"订单号","externalId":"支付或退款流水号，无则省略","product":"商品摘要","lineItems":[{"kind":"item|discount|fee","name":"菜品或商品简称","quantity":数量或null,"unitPrice":单价整数分或null,"amount":该行小计整数分或null}],"category":"现有分类名称","categorySource":"仅当用户在文字中明确指定了这个分类时填explicit，否则省略","note":"必要说明","accountId":"","targetId":null,"status":"paid|pending|closed|refund_pending|refunded|unknown","source":"原图编号，例如原图1/原图2或文字"}]}。
规则：逐笔提取，不把账单汇总金额再算作一笔。一张图可有多笔，多图保留来源。一个已付款订单记一笔实付总额，title与商品内容分开：餐饮使用可见店名（可附午餐/晚餐），盒马、七鲜等使用商家简称加购物/买菜；优先提取门店名，不用菜品或商品明细串作标题。title不超过20个汉字；看不出店名时用简短消费概括，不编造店名。payee保留可见完整商家名。多件商品汇总到product，同时逐行写入lineItems（最多200项），不拆成独立交易。小票菜品、购物商品保留简明名称、数量、单价、行小计；金额全部是整数分。缺失字段填null而不是0，不根据整单金额平均猜价格。明确的整单优惠、优惠券、满减、抹零写为kind=discount的负小计，商品行kind=item，配送费/包装费kind=fee为正小计。商品已用折后小计时不得再次减去已包含的优惠；只有票面明确但未包含在商品行的结算优惠才单列，单纯差额不猜为优惠。例如商品105元、结算优惠5元，分别写10500和-500分，实付amount=10000；总计、实付不再作为明细。行小计优先使用票面实际数字，不擅自强行凑齐整单实付。没有明细则lineItems为空数组。商品摘要最多60个汉字，保留品类、关键规格、数量，去掉促销词和堆砌标题。订单与流水是同一笔时合并信息，不叠加金额；platform优先填订单平台，其次支付渠道；二者分别保留在receiptOrigin中，商家填payee，不在note重复。不得编造金额、时间、账户、订单号；信用卡、白条、花呗等还本金属于transfer，不是再次消费；明确的利息或手续费单独记expense，不明的本金费用拆分不得猜测。赊购在购买时记expense。金额缺失填0，日期/账户缺失填空字符串，供用户补充。只有明确到账的退款才kind=refund，退款申请中/退货中status=refund_pending；未支付pending、关闭closed都不入账。已退款订单若同时清楚显示原支付和实际退款，分开两笔expense和refund，各自实际金额与日期；只有退款信息则只提退款。退款流水号不能填原支付流水号。退款不属于收入。kind=expense且status=refunded仍表示原支付，不转为退款。status=unknown需用户核实。今天${new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})}，只在文字明确说今天时使用。平台可以依据文字或明确的页面视觉特征识别，按receiptOrigin规则分别记录订单平台、支付渠道和扣款证据；不把支付渠道直接当作扣款钱包。accountId固定留空，targetId固定为null。未提供资金来源不属于识别错误，不要求用户补充图片。note和message不得出现accountId、账户匹配失败或请选择账户等内部字段与操作说明；备注只保留用户特意提供的用途、报销、赠送等额外有价值信息。不要重复实付、商家或商品；不要记录配餐中、配送中等临时订单状态；不要记录未显示时间、订单号、支付平台等缺失字段说明。没有额外信息时note为空字符串。套餐只显示总价时保留一条套餐明细及总价，不自行拆算每件价格；例如两个圆筒套餐实付7.5元，不凭第二份半价倒算成5元和2.5元。提现和充值属于转账，不能当作消费或收入。文字：${b.text}。${sceneInstructions} ${receiptOriginInstructions}`,prepared.images.length?prepared.images:undefined,progress);
 if(!Array.isArray(output.entries)||output.entries.length>200)throw new Failure('识别结果超过200笔或格式不正确，请分批识别',502);
 const parsed=output.entries.map((raw:unknown)=>{const item=proposed.parse(raw);return {...item,categorySource:item.categorySource||'model' as const,accountId:'',targetId:null};});if(parsed.some((entry:z.infer<typeof proposed>)=>entry.currency&&entry.currency!==deployment().currency))throw new Failure(b.language==='en'?`Receipt currency does not match ${deployment().currency}. No currency conversion was performed.`:`图片币种与账本${deployment().currency}不同，未进行汇率换算，请核对后单独处理。`);if(!cached)await progress.checkpoint?.set(`batch:${batch}`,{entries:parsed});
 all.push(...parsed);
 batch++;
 if(all.length>1000)throw new Failure('本次识别超过1000条记录，请分批处理');
 }
 for(const e of all){e.accountId='';e.targetId=null;if(e.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||Number.isNaN(Date.parse(e.date))||new Date(e.date).toISOString().slice(0,10)!==e.date))e.date='';}
 const merged=await mergeReceipts(all,raw=>proposed.parse(raw),progress);
 const consolidated=merged.entries;
 const ignored=consolidated.filter(e=>['pending','closed','refund_pending'].includes(e.status));
 return {message:b.language==='en'?`Read ${images.length} images; merged ${merged.merged} groups of duplicate/complementary orders; ${merged.uncertain} need review`:`已自动识别 ${images.length} 张图片，归并 ${merged.merged} 组重复/互补订单，${merged.uncertain} 处保留待核对`,proposals:consolidated.filter(e=>!ignored.includes(e)),ignored};
}
export async function review(book:string,body:unknown){const b=z.object({entries:z.array(proposed).max(1000)}).parse(body);return {entries:reconcile(b.entries,await existingEntries(book))};}

export async function recognize(book:string,body:unknown,progress:ModelProgress={},userId?:string){const english=deployment().language==='en';
 const cachedStep=async<T,>(key:string,fn:()=>Promise<T>):Promise<T>=>{const saved=await progress.checkpoint?.get(key);if(saved)return saved;const value=await fn();await progress.checkpoint?.set(key,value);return value;};
 type Extracted=Awaited<ReturnType<typeof extractReceipt>>;
 type Result={message:string;entries:ReturnType<typeof reconcile>;ignored:Extracted['ignored']};
 const State=Annotation.Root({extracted:Annotation<Extracted>(),result:Annotation<Result>()});
 const graph=new StateGraph(State)
 .addNode('read_receipt',async()=>{progress.signal?.throwIfAborted();progress.onStage?.('识别助手：读取图片、归并订单和商品');return {extracted:await cachedStep('extracted',()=>extractReceipt(book,body,progress))};})
 .addNode('normalize',async state=>{progress.signal?.throwIfAborted();progress.onStage?.(english?'Standardizing fields and matching relevant category preferences':'统一消费格式，匹配相关商家分类习惯');return {extracted:{...state.extracted,proposals:await applyPreferences(book,state.extracted.proposals,!!(body as {useHistory?:boolean}).useHistory,english,progress,userId)}};})
 .addNode('match_wallet',async state=>{progress.onStage?.(english?'Matching payment method to your wallets':'根据付款方式匹配个人钱包');const wallets=userId?await listAssets(userId):[];return {extracted:{...state.extracted,proposals:state.extracted.proposals.map(e=>{const match=userId?matchReceiptWallet(e.receiptOrigin,wallets,userId):null;return {...e,platform:e.receiptOrigin?receiptPlatform(e.receiptOrigin):e.platform,...(match?{accountId:match.accountId,walletCandidates:match.candidates,...(match.accountId&&match.basis?{walletMatch:match.basis}:{})}:{accountId:''})};})}};})
 .addNode('reconcile',async state=>{progress.signal?.throwIfAborted();progress.onStage?.('核对订单与已有流水、退款');const e=state.extracted;return {result:{message:e.message+(english?` Prepared ${e.proposals.length} drafts; skipped ${e.ignored.length} unpaid, closed or pending-refund records.`:`。生成${e.proposals.length}笔草稿，未支付/关闭/退款未到账${e.ignored.length}笔未入账。`),entries:reconcile(e.proposals,await existingEntries(book)),ignored:e.ignored}};})
 .addNode('check_amounts',async state=>{progress.signal?.throwIfAborted();progress.onStage?.('金额核验：逐项加总，与实付比较');const e=state.extracted;const checked=await cachedStep('verified',()=>verifyAndRepair(e.proposals,async(faults,attempt)=>{
 const input=body as {text?:string;images?:string[];image?:string;useHistory?:boolean};
 const instructions=(english?`Amount verification attempt ${attempt}: reread original images and rebuild full line items. Check missing or duplicate items, negative discounts, delivery/packaging fees, quantities and unit prices. Never invent balancing adjustments; unknown amounts remain null. Exclude total rows. Correct only visible evidence. Orders to inspect: `:`金额复核第${attempt}次：请重新逐项阅读原图，核查漏项、重复明细、优惠负数、配送费/包装费以及数量单价，重建完整明细。不得为了凑齐金额编造优惠或调整项，不得把未知小计当0；总计行不能重复作为明细。证据不足保持未知。只纠正图片可见事实。待核查订单：`)+JSON.stringify(faults.map(f=>({orderId:f.orderId,externalId:f.externalId,payee:f.payee,date:f.date,amount:f.amount,known:f.lineItems.reduce((n,i)=>n+(i.amount??0),0),missing:f.lineItems.filter(i=>i.amount===null).length}))).slice(0,3000);
 const retry=await extractReceipt(book,{...input,text:(input.text||'').slice(0,8000)+'\n'+instructions},{...progress,checkpoint:undefined});return retry.proposals;
 },message=>progress.onStage?.(message),progress.signal));
 return {extracted:{...e,proposals:checked.entries,message:e.message+(english?` Amount verification: repaired ${checked.repaired}; ${checked.unresolved} still need review.`:`。金额核验：重新处理修正${checked.repaired}笔，${checked.unresolved}笔结算明细未对齐，可确认实付后保存。`)}};})
 .addEdge(START,'read_receipt').addEdge('read_receipt','check_amounts').addEdge('check_amounts','normalize').addEdge('normalize','match_wallet').addEdge('match_wallet','reconcile').addEdge('reconcile',END).compile();
 const output=await graph.invoke({},{signal:progress.signal});const ids=[...((body as any).images||[]),...((body as any).image?[(body as any).image]:[])].map(receiptId).filter(Boolean);return {...output.result,entries:output.result.entries.map(e=>{const timed=withDeviceTime(e,(body as {deviceTime?:string}).deviceTime);return {...timed,missing:missingFields(timed),attachmentIds:ids,retainReceipts:false,verificationReason:''};})};
}
