import {accountAccess} from './accounts';
import {textMatch} from './search-match';
import {defaultCategories} from './categories';
import {z} from 'zod';
import {db} from './db';
import {Failure} from './access';
import {LIST_PAGE_SIZE} from '@/lib/pagination';
const day=z.string().refine(s=>s===''||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s),'日期无效').default('');
export const searchSchema=z.object({q:z.string().trim().max(200).default(''),mode:z.enum(['contains','exact']).default('contains'),entity:z.enum(['all','transaction','account','book','category','schedule','template','report','conversation','budget']).default('all'),book:z.union([z.literal('all'),z.string().uuid()]).default('all'),field:z.enum(['all','payee','product','note','order','item','platform']).default('all'),category:z.string().max(60).default(''),account:z.union([z.literal('all'),z.string().uuid()]).default('all'),kind:z.enum(['all','expense','income','refund','transfer']).default('all'),from:day,to:day,min:z.coerce.number().int().min(-100000000000).max(100000000000).optional(),max:z.coerce.number().int().min(-100000000000).max(100000000000).optional(),amountScope:z.enum(['order','item','either']).default('order'),state:z.enum(['active','trash','all']).default('active'),offset:z.coerce.number().int().min(0).default(0)});
export function parseSearch(params:URLSearchParams){const p=searchSchema.parse(Object.fromEntries(params));if(p.from&&p.to&&p.to<p.from)throw new Failure('结束日期不能早于开始日期');if(p.min!==undefined&&p.max!==undefined&&p.max<p.min)throw new Failure('最高金额不能低于最低金额');return p;}
export async function search(user:string,params:URLSearchParams){
 const p=parseSearch(params);
 const values:any[]=[user];const arg=(v:any)=>{values.push(v);return '$'+values.length;};
 const field=arg(p.field),defaults=arg(defaultCategories.map(([name])=>name));
 const sources=`WITH visible AS MATERIALIZED (SELECT b.* FROM books b JOIN members m ON m.book_id=b.id WHERE m.user_id=$1), categories AS(SELECT v.id AS book_id,n.name,COALESCE(c.icon,'🧸') AS icon,COALESCE(c.archived,false) AS archived FROM visible v CROSS JOIN LATERAL (SELECT unnest(${defaults}::text[]) AS name UNION SELECT name FROM category_preferences WHERE book_id=v.id UNION SELECT category FROM transactions WHERE book_id=v.id UNION SELECT category FROM budgets WHERE book_id=v.id) n LEFT JOIN category_preferences c ON c.book_id=v.id AND c.name=n.name WHERE NOT COALESCE(c.deleted,false)), sources AS (
 SELECT 'transaction'::text AS entity,t.id::text AS id,t.book_id,COALESCE(NULLIF(t.title,''),NULLIF(t.payee,''),NULLIF(t.product,''),t.category) AS title,
 CASE ${field} WHEN 'payee' THEN ARRAY[t.payee] WHEN 'product' THEN ARRAY[t.product] WHEN 'note' THEN ARRAY[t.note] WHEN 'order' THEN ARRAY[t.order_id,t.external_id] WHEN 'platform' THEN ARRAY[t.platform] WHEN 'item' THEN ARRAY(SELECT x->>'name' FROM jsonb_array_elements(t.line_items) x) ELSE ARRAY[t.title,t.scene->>'origin',t.scene->>'destination',t.scene->>'branch',t.payee,t.product,t.note,t.category,t.platform,t.order_id,t.external_id,a.name,a.holder,a.institution,a.suffix,u.name,COALESCE(dest.name,'')]||ARRAY(SELECT x->>'name' FROM jsonb_array_elements(t.line_items) x)||ARRAY(SELECT f.name FROM transaction_receipts r JOIN receipt_files f ON f.id=r.file_id WHERE r.transaction_id=t.id) END AS fields,
 t.category,t.account_id,t.target_id,t.kind,t.date AS day,t.amount AS money,t.line_items AS items,t.deleted,t.created_at AS stamp,
 to_jsonb(t)||jsonb_build_object('date',to_char(t.date,'YYYY-MM-DD'),'amount',t.amount::float8,'account_name',a.name,'creator_name',u.name,'account_ownership',a.ownership) AS detail
 FROM transactions t JOIN visible v ON v.id=t.book_id JOIN accounts a ON a.id=t.account_id JOIN users u ON u.id=t.created_by LEFT JOIN accounts dest ON dest.id=t.target_id
 UNION ALL SELECT 'book',v.id::text,v.id,v.name,ARRAY[v.name,v.description],NULL,NULL,NULL,NULL,NULL,NULL,'[]',false,v.created_at,jsonb_build_object('description',v.description) FROM visible v
 UNION ALL SELECT 'account',a.id::text,NULL::uuid,a.name,ARRAY[a.name,a.holder,a.institution,a.suffix],NULL,a.id,NULL,NULL,NULL,NULL,'[]',false,now(),jsonb_build_object('holder',a.holder,'institution',a.institution,'suffix',a.suffix,'archived',a.archived) FROM accounts a WHERE ${accountAccess('$1')}
 UNION ALL SELECT 'category',c.book_id::text||':'||c.name,c.book_id,c.name,ARRAY[c.name],c.name,NULL,NULL,NULL,NULL,NULL,'[]',false,now(),jsonb_build_object('archived',c.archived,'icon',c.icon) FROM categories c
 UNION ALL SELECT 'schedule',s.id::text,s.book_id,s.name,ARRAY[s.name,s.value->>'payee',s.value->>'note',s.value->>'product',s.value->>'category'],s.value->>'category',(s.value->>'accountId')::uuid,NULL,s.value->>'kind',s.next_date,(s.value->>'amount')::bigint,'[]',false,now(),to_jsonb(s) FROM bill_schedules s JOIN visible v ON v.id=s.book_id WHERE s.user_id=$1
 UNION ALL SELECT 'template',s.id::text,s.book_id,s.name,ARRAY[s.name,s.value->>'payee',s.value->>'note',s.value->>'product',s.value->>'category']||ARRAY(SELECT x->>'name' FROM jsonb_array_elements(COALESCE(s.value->'lineItems','[]')) x),s.value->>'category',(s.value->>'accountId')::uuid,NULL,s.value->>'kind',NULL,(s.value->>'amount')::bigint,COALESCE(s.value->'lineItems','[]'),false,now(),to_jsonb(s) FROM entry_templates s JOIN visible v ON v.id=s.book_id WHERE s.user_id=$1
 UNION ALL SELECT 'report',r.id::text,r.book_id,r.title,ARRAY[r.title,r.content],NULL,NULL,NULL,NULL,NULL,NULL,'[]',false,r.created_at,jsonb_build_object('content',r.content) FROM finance_reports r JOIN visible v ON v.id=r.book_id WHERE r.user_id=$1
 UNION ALL SELECT 'conversation',c.id::text,c.book_id,c.title,ARRAY[c.title]||ARRAY(SELECT f.text FROM finance_turns t CROSS JOIN LATERAL (VALUES(t.question),(t.answer)) f(text) WHERE t.conversation_id=c.id),NULL,NULL,NULL,NULL,NULL,NULL,'[]',false,c.updated_at,jsonb_build_object('content',(SELECT string_agg(concat_ws(E'\n',t.question,t.answer),E'\n\n' ORDER BY t.created_at) FROM finance_turns t WHERE t.conversation_id=c.id)) FROM finance_conversations c JOIN visible v ON v.id=c.book_id WHERE c.user_id=$1
 UNION ALL SELECT 'budget',b.book_id::text||':'||b.month||':'||b.category,b.book_id,b.category||'预算',ARRAY[b.category],b.category,NULL,NULL,NULL,(b.month||'-01')::date,b.amount,'[]',false,now(),jsonb_build_object('month',b.month) FROM budgets b JOIN visible v ON v.id=b.book_id
 )`;
 const filters:string[]=[];
 if(p.book!=='all')filters.push('s.book_id='+arg(p.book)+'::uuid');
 if(p.entity!=='all')filters.push('s.entity='+arg(p.entity));
 if(p.field!=='all')filters.push("s.entity='transaction'");
 if(p.state==='trash')filters.push('s.deleted');else if(p.state==='active')filters.push('NOT s.deleted');
 if(p.category)filters.push('s.category='+arg(p.category));
 if(p.account!=='all'){const a=arg(p.account);filters.push(`(s.account_id=${a}::uuid OR s.target_id=${a}::uuid)`);}
 if(p.kind!=='all')filters.push('s.kind='+arg(p.kind));
 if(p.from)filters.push('s.day>='+arg(p.from)+'::date');if(p.to)filters.push('s.day<='+arg(p.to)+'::date');
 if(p.min!==undefined||p.max!==undefined){const lo=arg(p.min??-100000000000),hi=arg(p.max??100000000000);const order=`s.money BETWEEN ${lo} AND ${hi}`,item=`EXISTS(SELECT 1 FROM jsonb_array_elements(s.items) x WHERE (x->>'amount')::bigint BETWEEN ${lo} AND ${hi})`;filters.push(p.amountScope==='order'?order:p.amountScope==='item'?item:`(${order} OR ${item})`);}
 if(p.q)filters.push(textMatch('s.fields',arg(p.q),p.mode));
 const result=await db.query(`${sources}, filtered AS MATERIALIZED(SELECT s.*,COALESCE(v.name,'资金资产') AS book_name FROM sources s LEFT JOIN visible v ON v.id=s.book_id ${filters.length?'WHERE '+filters.join(' AND '):''}), page AS(SELECT * FROM filtered ORDER BY stamp DESC,entity,id LIMIT ${LIST_PAGE_SIZE} OFFSET ${arg(p.offset)}) SELECT json_build_object('total',(SELECT count(*) FROM filtered),'groups',(SELECT COALESCE(json_object_agg(entity,n),'{}') FROM (SELECT entity,count(*) AS n FROM filtered GROUP BY entity) g),'rows',(SELECT COALESCE(json_agg(to_jsonb(page)-'fields'),'[]') FROM page)) AS result`,values);
 return result.rows[0].result;
}
export async function searchOptions(user:string,params:URLSearchParams){const p=parseSearch(params);const visible=`SELECT b.id,b.name FROM books b JOIN members m ON m.book_id=b.id WHERE m.user_id=$1 AND ($2::uuid IS NULL OR b.id=$2)`;const args=[user,p.book==='all'?null:p.book];const accounts=(await db.query(`WITH visible AS(${visible}) SELECT a.id,a.name,a.institution,a.type,a.suffix,a.holder,COALESCE(f.name,u.name) AS book_name FROM accounts a LEFT JOIN families f ON f.id=a.family_id LEFT JOIN users u ON u.id=a.owner_id WHERE ${accountAccess('$1')} OR EXISTS(SELECT 1 FROM transactions t JOIN visible v ON v.id=t.book_id WHERE t.account_id=a.id OR t.target_id=a.id) ORDER BY a.name,a.id`,args)).rows;const categories=(await db.query(`WITH visible AS(${visible}) SELECT n.name,array_agg(DISTINCT c.icon) FILTER (WHERE c.icon IS NOT NULL) AS icons FROM visible v CROSS JOIN LATERAL(SELECT unnest($3::text[]) AS name UNION SELECT name FROM category_preferences WHERE book_id=v.id UNION SELECT category FROM transactions WHERE book_id=v.id UNION SELECT category FROM budgets WHERE book_id=v.id) n LEFT JOIN category_preferences c ON c.book_id=v.id AND c.name=n.name WHERE NOT COALESCE(c.deleted,false) GROUP BY n.name ORDER BY n.name`,[...args,defaultCategories.map(c=>c[0])])).rows;const categoryOptions=categories.map(r=>({name:r.name,icon:r.icons?.length===1?r.icons[0]:r.icons?.length>1?'🏷️':defaultCategories.find(c=>c[0]===r.name)?.[1]||'🏷️'}));return {accounts,categories:categoryOptions.map(c=>c.name),categoryOptions};}
