import {db} from './db';
import {summarizeWalletFunds,type FundEvent} from '@/lib/wallet-funds';
export async function walletFunds(accounts:{id:string;name:string;opening:number}[],from:string,to:string){
 const ids=accounts.map(a=>a.id),names=new Map(accounts.map(a=>[a.id,a.name]));
 const entries=(await db.query(`WITH entries AS (SELECT DISTINCT ON(COALESCE(event_id,id)) * FROM transactions WHERE NOT deleted AND (account_id=ANY($1::uuid[]) OR target_id=ANY($1::uuid[])) ORDER BY COALESCE(event_id,id),created_at,id) SELECT id,book_id,account_id,target_id,kind,amount::float8 AS amount,to_char(date,'YYYY-MM-DD') AS date,created_at,occurred_at,title,payee,note,external_id,order_id FROM entries WHERE date<=$2::date`,[ids,to])).rows;
 const movements=(await db.query(`SELECT v.id,v.source_id,v.target_id,v.kind,v.amount::float8 AS amount,to_char(v.date,'YYYY-MM-DD') AS date,v.created_at,v.note,v.external_id,s.name AS sender,r.name AS recipient FROM family_movements v JOIN users s ON s.id=v.sender_id LEFT JOIN users r ON r.id=v.recipient_id WHERE v.status='confirmed' AND (v.source_id=ANY($1::uuid[]) OR v.target_id=ANY($1::uuid[])) AND v.date<=$2::date`,[ids,to])).rows;
 const adjustments=(await db.query(`SELECT id,account_id,amount::float8 AS amount,to_char(created_at AT TIME ZONE 'Asia/Shanghai','YYYY-MM-DD') AS date,created_at,note FROM account_adjustments WHERE account_id=ANY($1::uuid[]) AND (created_at AT TIME ZONE 'Asia/Shanghai')::date<=$2::date`,[ids,to])).rows;
 const events:FundEvent[]=entries.map(t=>({id:t.id,bookId:t.book_id,date:t.date,createdAt:t.created_at,occurredAt:t.occurred_at,kind:t.kind,amount:t.amount,sourceId:t.account_id,targetId:t.target_id,title:t.title||t.payee||t.kind,counterparty:t.payee,sourceName:names.get(t.account_id)||'',targetName:names.get(t.target_id)||'',note:t.note,reference:t.external_id||t.order_id||'',origin:'transaction'}));
 for(const m of movements){const outgoing=ids.includes(m.source_id),both=outgoing&&ids.includes(m.target_id),gift=m.kind==='gift'&&!both;events.push({id:m.id,date:m.date,createdAt:m.created_at,kind:gift?(outgoing?'expense':'income'):'transfer',amount:m.amount,sourceId:gift&&!outgoing?m.target_id:m.source_id,targetId:gift?null:m.target_id,title:outgoing?'转给 '+(m.recipient||'共同钱包'):'收到 '+m.sender+'的转账',counterparty:outgoing?m.recipient||'共同钱包':m.sender,sourceName:names.get(gift&&!outgoing?m.target_id:m.source_id)||'',targetName:gift?'':names.get(m.target_id)||'',note:m.note||'',reference:m.external_id||'',origin:'family'});}
 for(const j of adjustments)events.push({id:j.id,date:j.date,createdAt:j.created_at,kind:'adjustment',amount:j.amount,sourceId:j.account_id,targetId:null,title:'余额校准',counterparty:'',sourceName:names.get(j.account_id)||'',targetName:'',note:j.note,origin:'adjustment'});
 return summarizeWalletFunds(events,accounts,from,to);
}
