import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {db,transaction,lockBook} from './db';
import {Failure} from './access';
export async function wallets(user:string,method:string,body:any):Promise<any>{
 if(method==='POST'){const b=z.object({accountId:z.string().uuid(),walletId:z.string().uuid().optional(),name:z.string().trim().min(1).max(80).optional(),balance:z.number().int().min(-100000000000).max(100000000000).optional(),expectedBalance:z.number().optional(),note:z.string().trim().min(1).max(500).optional()}).parse(body);return transaction(async c=>{const a=(await c.query("SELECT a.*,m.role FROM accounts a JOIN members m ON m.book_id=a.book_id AND m.user_id=$2 WHERE a.id=$1",[b.accountId,user])).rows[0];if(a?.role!=='owner')throw new Failure('需要账本所有者权限',403);await lockBook(c,a.book_id);if((await c.query('SELECT wallet_id FROM accounts WHERE id=$1',[a.id])).rows[0].wallet_id)throw new Failure('账户已关联真实钱包');let id=b.walletId;if(id){const w=(await c.query('SELECT * FROM wallets WHERE id=$1 AND owner_id=$2 FOR UPDATE',[id,user])).rows[0];if(!w)throw new Failure('请选择自己管理的真实钱包',403);if((await c.query('SELECT 1 FROM accounts WHERE wallet_id=$1 AND book_id=$2',[id,a.book_id])).rowCount)throw new Failure('同一本账本只能引用同一钱包一次');}else{id=randomUUID();await c.query('INSERT INTO wallets VALUES($1,$2,$3,$4)',[id,user,b.name||a.name,a.id]);}await c.query('UPDATE accounts SET wallet_id=$1,version=version+1 WHERE id=$2',[id,a.id]);return {id};});}
 if(method==='PATCH'){const b=z.object({walletId:z.string().uuid(),accountId:z.string().uuid().optional(),name:z.string().trim().min(1).max(80).optional(),balance:z.number().int().min(-100000000000).max(100000000000).optional(),expectedBalance:z.number().optional(),note:z.string().trim().min(1).max(500).optional()}).parse(body);return transaction(async c=>{const linked=(await c.query('SELECT DISTINCT book_id FROM accounts WHERE wallet_id=$1 ORDER BY book_id',[b.walletId])).rows;for(const a of linked)await lockBook(c,a.book_id);const w=(await c.query('SELECT * FROM wallets WHERE id=$1 AND owner_id=$2 FOR UPDATE',[b.walletId,user])).rows[0];if(!w)throw new Failure('需要钱包管理权限',403);if(b.balance!==undefined){if(!b.note)throw new Failure('请填写校准原因');const current=(await wallets(user,'GET',{})).find((x:any)=>x.id===w.id);if(!current?.complete)throw new Failure('需要能访问全部关联账本才能核对总余额',403);if(current.balance!==b.expectedBalance)throw new Failure('余额已变化，请刷新后重新核对',409);const diff=b.balance-current.balance;if(diff){await c.query('INSERT INTO account_adjustments(id,book_id,account_id,amount,note,created_by) SELECT $1,book_id,id,$2,$3,$4 FROM accounts WHERE id=$5',[randomUUID(),diff,b.note,user,w.primary_account]);await c.query('UPDATE accounts SET version=version+1 WHERE id=$1',[w.primary_account]);}return {ok:true};}if(b.accountId){if(b.accountId===w.primary_account){if((await c.query('SELECT 1 FROM accounts WHERE wallet_id=$1 AND id<>$2',[w.id,b.accountId])).rowCount)throw new Failure('请先解除其他引用，再解除期初账户');await c.query('DELETE FROM wallets WHERE id=$1',[w.id]);}else await c.query('UPDATE accounts SET wallet_id=NULL,version=version+1 WHERE id=$1 AND wallet_id=$2',[b.accountId,w.id]);}else if(b.name)await c.query('UPDATE wallets SET name=$1 WHERE id=$2',[b.name,w.id]);return {ok:true};});}
 if(method!=='GET')throw new Failure('操作不存在');
 const rows=(await db.query(`SELECT w.id,w.name,w.owner_id=$1 AS managed,w.primary_account,NOT EXISTS(SELECT 1 FROM accounts a WHERE a.wallet_id=w.id AND NOT EXISTS(SELECT 1 FROM members m WHERE m.book_id=a.book_id AND m.user_id=$1)) AS complete FROM wallets w WHERE EXISTS(SELECT 1 FROM accounts a JOIN members m ON m.book_id=a.book_id WHERE a.wallet_id=w.id AND m.user_id=$1)`,[user])).rows;
 for(const w of rows){const accounts=(await db.query(`SELECT a.id,a.name,b.name AS book_name,a.book_id,a.opening::float8 AS opening FROM accounts a JOIN members m ON m.book_id=a.book_id AND m.user_id=$2 JOIN books b ON b.id=a.book_id WHERE a.wallet_id=$1`,[w.id,user])).rows;const ids=accounts.map(a=>a.id);const flows=(await db.query(`WITH flows AS (SELECT COALESCE(event_id,id) AS event,CASE WHEN kind IN ('income','refund') THEN amount ELSE -amount END AS amount,0 AS direction,created_at,id FROM transactions WHERE account_id=ANY($1::uuid[]) AND NOT deleted UNION ALL SELECT COALESCE(event_id,id),amount,1,created_at,id FROM transactions WHERE target_id=ANY($1::uuid[]) AND NOT deleted), distinct_flows AS (SELECT DISTINCT ON(event,direction) amount FROM flows ORDER BY event,direction,created_at,id) SELECT COALESCE(sum(amount),0)::float8 AS value FROM distinct_flows`,[ids])).rows[0].value;const adjustment=(await db.query('SELECT COALESCE(sum(amount),0)::float8 AS value FROM account_adjustments WHERE account_id=ANY($1::uuid[])',[ids])).rows[0].value;w.accounts=accounts.map(({opening,...a})=>a);w.visibleMovement=flows+adjustment;w.balance=w.complete?(accounts.find(a=>a.id===w.primary_account)?.opening||0)+w.visibleMovement:null;delete w.primary_account;}
 return rows;
}
