import test from 'node:test';
import assert from 'node:assert/strict';
import {runFinanceAgent,type AgentArtifact} from '../src/server/finance-agent';
import type {chatCompletion} from '../src/server/ai';
const user={id:'user',name:'测试',username:'test',admin:false,avatar:'🧸',theme:'bear' as const};
test('真实工具循环先取数、执行图表工具、回灌结果再回答，固定账本范围',async()=>{let calls=0;const events:string[]=[];const model:typeof chatCompletion=async(messages,tools,delta)=>{assert.equal(messages[0].role,'system');if(calls++===0)return {model:'test',message:{role:'assistant',content:null,tool_calls:[{id:'draw',type:'function',function:{name:'draw_chart',arguments:JSON.stringify({from:'2026-09-01',to:'2026-09-30',type:'bar',dimension:'category',title:'支出'})}}]}};assert.equal(messages.at(-1)?.role,'tool');delta('支出共100元。');return {model:'test',message:{role:'assistant',content:'支出共100元。'}};};const result=await runFinanceAgent({book:'private-book',user,question:'画分类图',month:'2026-09',history:[],images:[],signal:new AbortController().signal,emit:e=>events.push(e)},model,async(name,args,ctx,artifacts)=>{assert.equal(ctx.book,'private-book');if(name==='draw_chart')artifacts.charts.push({id:'chart',type:'bar',title:'支出',from:'2026-09-01',to:'2026-09-30',unit:'元',data:[{name:'餐饮',value:100}]});return {amount:10000};});assert.equal(result.artifacts.charts.length,1);assert.equal(result.artifacts.tools.length,2);assert.match(result.text,/100元/);assert.ok(events.includes('tool_result'));});
test('模型不能调用未提供的工具或直接写账',async()=>{const model:typeof chatCompletion=async()=>({model:'test',message:{role:'assistant',content:null,tool_calls:[{id:'x',type:'function',function:{name:'execute_sql',arguments:'{}'}}]}});await assert.rejects(runFinanceAgent({book:'b',user,question:'x',month:'2026-09',history:[],images:[],signal:new AbortController().signal,emit:()=>{}},model,async()=>({})),/不可用/);});
test('中断保存部分回答与工具记录，不伪装成完整报告',async()=>{const model:typeof chatCompletion=async(_m,_t,delta)=>{delta('已经查到');throw new Error('中断');};try{await runFinanceAgent({book:'b',user,question:'x',month:'2026-09',history:[],images:[],signal:new AbortController().signal,emit:()=>{}},model,async()=>({}));assert.fail();}catch(e){assert.equal((e as any).partial.text,'已经查到');assert.equal((e as any).partial.artifacts.tools.length,1);}});
import {financeChartData} from '../src/lib/finance-chart-data';
test('图表按整数分换算，补零空白日期与月份，负退款不会丢失',()=>{const data={categories:[{name:'退款',value:-120}],daily:[{date:'2026-09-02',income:0,expense:-120}]};assert.deepEqual(financeChartData(data,'daily_expense','2026-09-01','2026-09-03').map(x=>x.value),[0,-1.2,0]);assert.deepEqual(financeChartData(data,'monthly_expense','2026-08-01','2026-10-31').map(x=>x.value),[0,-1.2,0]);assert.equal(financeChartData(data,'category','2026-09-01','2026-09-30')[0].value,-1.2);});
test('LangGraph 总助手按需委派，专业助手独立取数后交回图表与结论',async()=>{
 const seen:string[]=[],events:string[]=[];let supervisor=0,specialist=0;
 const call=(name:string,args:any)=>({id:name,type:'function',function:{name,arguments:JSON.stringify(args)}});
 const model:typeof chatCompletion=async(messages,tools,delta)=>{
  const isSpecialist=String(messages[0].content).includes('你是财务分析助手');
  if(isSpecialist){assert.ok(!tools.some((t:any)=>t.function.name.startsWith('delegate_')));assert.ok(!tools.some((t:any)=>t.function.name==='prepare_entries'));if(specialist++===0)return {model:'configurable-model',message:{role:'assistant',content:null,tool_calls:[call('draw_chart',{from:'2026-09-01',to:'2026-09-30',type:'bar',dimension:'category',title:'支出'})]}};delta('有工具依据的分析 [[chart:chart-1]]');return {model:'configurable-model',message:{role:'assistant',content:'有工具依据的分析 [[chart:chart-1]]'}};}
  if(supervisor++===0)return {model:'configurable-model',message:{role:'assistant',content:null,tool_calls:[call('delegate_analysis',{task:'分析本月支出并画图'})]}};
  assert.match(String(messages.at(-1)?.content),/有工具依据的分析/);delta('这是完整报告 [[chart:chart-1]]');return {model:'configurable-model',message:{role:'assistant',content:'这是完整报告 [[chart:chart-1]]'}};
 };
 const result=await runFinanceAgent({book:'fixed-book',user,question:'分析本月并画图',month:'2026-09',history:[],images:[],signal:new AbortController().signal,emit:e=>events.push(e)},model,async(name,args,ctx,artifacts)=>{assert.equal(ctx.book,'fixed-book');seen.push(name);if(name==='draw_chart')artifacts.charts.push({id:'chart-1',type:'bar',title:'支出',from:'2026-09-01',to:'2026-09-30',unit:'元',data:[{name:'餐饮',value:100}]});return {amount:10000};});
 assert.equal(result.artifacts.agents?.length,1);assert.equal(result.artifacts.agents?.[0].status,'complete');assert.equal(result.artifacts.charts.length,1);assert.ok(!result.text.includes('有工具依据的分析'));assert.ok(events.includes('agent_start')&&events.includes('agent_done'));assert.deepEqual(seen,['financial_summary','draw_chart']);
});
test('专业助手不能越过自己的工具范围，失败交回总助手',async()=>{
 let count=0,illegalExecuted=false;const model:typeof chatCompletion=async(messages,tools,delta)=>{if(String(messages[0].content).includes('你是账目核对助手'))return {model:'test',message:{role:'assistant',content:null,tool_calls:[{id:'bad',type:'function',function:{name:'prepare_entries',arguments:'{}'}}]}};if(count++===0)return {model:'test',message:{role:'assistant',content:null,tool_calls:[{id:'delegate',type:'function',function:{name:'delegate_reconciliation',arguments:JSON.stringify({task:'核对退款'})}}]}};assert.match(String(messages.at(-1)?.content),/不可用/);delta('核对未完成，请补充信息');return {model:'test',message:{role:'assistant',content:'核对未完成，请补充信息'}};};
 const result=await runFinanceAgent({book:'fixed',user,question:'核对',month:'2026-09',history:[],images:[],signal:new AbortController().signal,emit:()=>{}},model,async name=>{if(name==='prepare_entries')illegalExecuted=true;return {};});assert.equal(illegalExecuted,false);assert.equal(result.artifacts.agents?.[0].status,'error');
});
