import {test} from 'node:test';
import assert from 'node:assert/strict';
import {planMemoryFill,changeMemorySelection,resolveMemoryField} from '../src/lib/memory-fields';
import {memorySuggestion} from '../src/lib/memory';
const suggestion=(fields:Record<string,string>,id='00000000-0000-4000-8000-000000000001')=>memorySuggestion.parse({id,title:'商品',status:'matched',reason:'已确认',fields});
test('only stable fields fill; explicit category and current facts win',()=>{const input={product:'当前商品名',title:'',payee:'',category:'购物',categorySource:'explicit',amount:123,date:'2026-09-26',orderId:'new'};const result=planMemoryFill(input,[suggestion({product:'规范名',payee:'商店',category:'餐饮',title:'规范名',amount:'999',orderId:'old'})]);assert.equal(result.value.payee,'商店');assert.equal(result.value.title,'规范名');assert.equal(result.value.product,input.product);assert.equal(result.value.category,'购物');assert.equal(result.value.amount,123);assert.equal(result.value.orderId,'new');assert.ok(result.suggestions[0].fieldChanges.some(c=>c.field==='category'&&c.state==='conflict'));});
test('removing association reverts auto-fill but preserves later manual edit',()=>{const applied=planMemoryFill({payee:'',category:'其他'},[suggestion({payee:'商店',category:'餐饮'})]);const removed=changeMemorySelection({...applied.value,payee:'手动商店'},applied.suggestions,[]);assert.equal(removed.value.payee,'手动商店');assert.equal(removed.value.category,'其他');});
test('conflicting sources never auto-fill category',()=>{const result=planMemoryFill({category:'其他'},[suggestion({category:'购物'}),suggestion({category:'餐饮'},'00000000-0000-4000-8000-000000000002')]);assert.equal(result.value.category,'其他');assert.ok(result.suggestions.every(s=>s.fieldChanges[0].state==='conflict'));const chosen=resolveMemoryField(result.value,result.suggestions,result.suggestions[0].id,undefined,'category',true);assert.equal(chosen.value.category,'购物');assert.equal(chosen.value.categorySource,'explicit');});
test('line-level identity does not replace order merchant or product summary',()=>{const s=suggestion({product:'单件商品',payee:'旧商家',category:'购物'});s.itemId='line-1';const result=planMemoryFill({product:'本次多商品',payee:''},[s]);assert.equal(result.value.product,'本次多商品');assert.equal(result.value.payee,'');});
