'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Archive,ArchiveRestore,ChevronLeft,ChevronRight,FolderPlus,Pencil,Search,Trash2,NotebookPen} from 'lucide-react';
import {useI18n} from './LanguageProvider';
import {formatMoney} from '@/lib/deployment';
import {amountToCents} from '@/server/model';
import type {ManagedBook} from './ManagementPages';
import {FormSelect} from './FormSelect';
import {DateField} from './DateField';
import type {Activity} from './ActivitySelect';
import {Sheet} from './Sheet';

type ActivityRow={id:string;book_id:string;book_name:string;kind:string;amount:number;date:string;title:string;payee:string;category:string;product:string;account_name:string};
type Breakdown={id?:string;name?:string;category?:string;date?:string;amount:number};
type ActivityReport={activity:Activity;rows:ActivityRow[];totals:{count:number;income:number;expense:number;refund:number};categories:Breakdown[];wallets:Breakdown[];books:Breakdown[];daily:Breakdown[]};
type SearchRow={id:string;family_movement_id?:string|null;title:string;payee:string;category:string;date:string;amount:number};
type Family={id:string;name:string};
const activityCategories=['旅行','聚会','节日','家居装修','教育','医疗','工作','运动','其他'];
async function request(path:string,method='GET',body?:unknown){const response=await fetch('/api/'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}

function BreakdownBars({title,items,label}:{title:string;items:Breakdown[];label:(item:Breakdown)=>string}){
 const {t:tr}=useI18n(),max=Math.max(1,...items.map(item=>Math.max(0,item.amount)));
 return <section className="panel activity-breakdown"><h2>{tr(title)}</h2>{items.length?items.map((item,index)=><div className="activity-bar" key={(item.id||item.category||item.date||item.name||'')+index}><div><span>{label(item)}</span><strong>{formatMoney(item.amount)}</strong></div><span className="activity-bar-track"><span style={{width:`${Math.max(0,item.amount)/max*100}%`}}/></span></div>):<p className="muted">{tr('暂无可统计的支出')}</p>}</section>;
}

export function ActivitiesPage({books,activities,userId,initialId,onRecord,onChanged}:{books:ManagedBook[];activities:Activity[];userId:string;initialId?:string;onRecord:(id:string)=>void;onChanged:()=>Promise<void>}){
 const {t:tr}=useI18n();
 const [view,setView]=useState<'active'|'archived'>('active'),[selected,setSelected]=useState(''),[listQuery,setListQuery]=useState(''),[listCategory,setListCategory]=useState('all'),[listFamily,setListFamily]=useState('all'),[listPage,setListPage]=useState(0);
 const [families,setFamilies]=useState<Family[]>([]),[editor,setEditor]=useState<Activity|null|undefined>(undefined),[name,setName]=useState(''),[activityCategory,setActivityCategory]=useState('旅行'),[familyId,setFamilyId]=useState(''),[description,setDescription]=useState(''),[startsOn,setStartsOn]=useState(''),[endsOn,setEndsOn]=useState(''),[budget,setBudget]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirmDelete,setConfirmDelete]=useState(false);
 const [report,setReport]=useState<ActivityReport|null>(null),[summary,setSummary]=useState<ActivityReport|null>(null),[loading,setLoading]=useState(false),[book,setBook]=useState('all'),[kind,setKind]=useState('all'),[category,setCategory]=useState(''),[account,setAccount]=useState('all'),[q,setQ]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0);
 const [adding,setAdding]=useState(false),[sourceBook,setSourceBook]=useState(books.find(b=>b.role!=='viewer')?.id||''),[sourceQuery,setSourceQuery]=useState(''),[sourceRows,setSourceRows]=useState<SearchRow[]>([]),[sourceTotal,setSourceTotal]=useState(0),[sourceOffset,setSourceOffset]=useState(0),[sourceLoading,setSourceLoading]=useState(false);
 const openedFromSearch=useRef('');
 const selectedActivity=activities.find(a=>a.id===selected);
 const visible=useMemo(()=>activities.filter(a=>a.archived===(view==='archived')).filter(a=>listCategory==='all'||a.category===listCategory).filter(a=>listFamily==='all'||(listFamily==='personal'?!a.familyId:a.familyId===listFamily)).filter(a=>[a.name,a.category,a.description,a.familyName||''].join(' ').toLocaleLowerCase().includes(listQuery.trim().toLocaleLowerCase())),[activities,view,listCategory,listFamily,listQuery]);
 const listPageCount=Math.max(1,Math.ceil(visible.length/12));
 const shown=visible.slice(listPage*12,listPage*12+12);
 const activity=visible.find(a=>a.id===selected);
 const categories=[...new Set(activities.map(a=>a.category))].sort();
 const activeCount=activities.filter(a=>!a.archived).length,archivedCount=activities.length-activeCount;

 useEffect(()=>{request('families').then(data=>setFamilies(data.items||[])).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!initialId||openedFromSearch.current===initialId)return;const target=activities.find(a=>a.id===initialId);if(target){openedFromSearch.current=initialId;setView(target.archived?'archived':'active');setSelected(target.id);}},[initialId,activities]);
 useEffect(()=>{if(selectedActivity&&selectedActivity.archived===(view==='archived'))return;setSelected(activities.find(a=>a.archived===(view==='archived'))?.id||'');},[activities,view,selected]);
 useEffect(()=>{setListPage(0);},[view,listCategory,listFamily,listQuery]);
 useEffect(()=>{if(listPage>=listPageCount)setListPage(listPageCount-1);},[listPage,listPageCount]);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(q);setOffset(0);},250);return()=>clearTimeout(timer);},[q]);
 useEffect(()=>{setBook('all');setKind('all');setCategory('');setAccount('all');setQ('');setOffset(0);setReport(null);setSummary(null);},[selected]);
 useEffect(()=>{if(!selected)return;const controller=new AbortController(),params=new URLSearchParams({book,kind,category,account,q:search,offset:String(offset),limit:'20'});setLoading(true);fetch('/api/activities/'+selected+'?'+params,{signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!controller.signal.aborted)setReport(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[selected,book,kind,category,account,search,offset,revision]);
 useEffect(()=>{if(!selected)return;const controller=new AbortController();fetch('/api/activities/'+selected,{signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!controller.signal.aborted)setSummary(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[selected,revision]);
 useEffect(()=>{if(!adding||!sourceBook)return;const controller=new AbortController(),timer=setTimeout(()=>{setSourceLoading(true);const params=new URLSearchParams({from:'2000-01-01',to:'2100-12-31',q:sourceQuery,limit:'20',offset:String(sourceOffset)});fetch(`/api/books/${sourceBook}/report?${params}`,{signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!controller.signal.aborted){setSourceRows(value.rows.filter((row:SearchRow)=>!row.family_movement_id));setSourceTotal(value.totals?.count||0);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setSourceLoading(false);});},250);return()=>{controller.abort();clearTimeout(timer);};},[adding,sourceBook,sourceQuery,sourceOffset,revision]);

 function openEditor(item?:Activity){setEditor(item||null);setName(item?.name||'');setActivityCategory(item?.category||'旅行');setFamilyId(item?.familyId||'');setDescription(item?.description||'');setStartsOn(item?.startsOn||'');setEndsOn(item?.endsOn||'');setBudget(item?.budget==null?'':String(item.budget/100));setError('');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const payload={name,category:activityCategory,familyId:familyId||null,description,startsOn:startsOn||null,endsOn:endsOn||null,budget:budget?amountToCents(budget):null};let id=editor?.id;if(editor)await request('activities','PUT',{id,...payload});else id=(await request('activities','POST',payload)).id;await onChanged();setView(editor?.archived?'archived':'active');setSelected(id||'');setEditor(undefined);setRevision(n=>n+1);setNotice(tr('活动已保存'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function archive(item:Activity){setBusy(true);setError('');try{await request('activities','PATCH',{id:item.id,archived:!item.archived});await onChanged();setView(item.archived?'active':'archived');setSelected(item.id);setRevision(n=>n+1);setNotice(tr(item.archived?'活动已恢复':'活动已归档'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!activity)return;setBusy(true);setError('');try{await request('activities','DELETE',{id:activity.id});setConfirmDelete(false);setSelected('');await onChanged();setReport(null);setSummary(null);setNotice(tr('活动已删除，原账目未删除'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function assign(row:SearchRow){setBusy(true);setError('');try{await request('activities/assign','PUT',{bookId:sourceBook,transactionId:row.id,activityId:selected});await onChanged();setRevision(n=>n+1);setNotice(tr('已加入活动'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function unassign(row:ActivityRow){setBusy(true);setError('');try{await request('activities/assign','PUT',{bookId:row.book_id,transactionId:row.id,activityId:null});await onChanged();setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const net=(summary?.totals.expense||0)-(summary?.totals.refund||0),remaining=activity?.budget==null?null:activity.budget-net;

 return <div className="activities-page">
  <section className="panel activity-index">
   <div className="panel-title activity-main-header"><div><h2>{tr('活动账')}</h2><p className="muted">{tr('一次活动可归集多个账本，原账目和钱包余额保持不变。')}</p></div><button onClick={()=>openEditor()}><FolderPlus size={18}/>{tr('创建活动')}</button></div>
   <div className="activity-tabs" role="group" aria-label={tr('活动状态')}><button type="button" aria-pressed={view==='active'} className={view==='active'?'active':''} onClick={()=>setView('active')}>{tr('进行中')} <small>{activeCount}</small></button><button type="button" aria-pressed={view==='archived'} className={view==='archived'?'active':''} onClick={()=>setView('archived')}>{tr('归档活动')} <small>{archivedCount}</small></button></div>
   <div className="activity-index-filters"><label className="activity-search"><Search size={18}/><input value={listQuery} onChange={e=>setListQuery(e.target.value)} placeholder={tr('搜索活动名称、类型、家庭或说明')} aria-label={tr('搜索活动')}/></label><FormSelect value={listCategory} onChange={setListCategory} aria-label={tr('活动类型')}><option value="all">{tr('全部活动类型')}</option>{categories.map(value=><option key={value} value={value}>{value}</option>)}</FormSelect><FormSelect value={listFamily} onChange={setListFamily} aria-label={tr('活动归属')}><option value="all">{tr('全部归属')}</option><option value="personal">{tr('仅个人活动')}</option>{families.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</FormSelect></div>
   {shown.length?<div className="activity-list">{shown.map(item=><button key={item.id} type="button" className={selected===item.id?'activity-tile is-active':'activity-tile'} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><strong>{item.name}</strong><span>{item.category} · {item.familyName||tr('个人活动')}</span><small>{item.entryCount} {tr('笔可见记录')}</small></button>)}</div>:<div className="empty">{tr(view==='archived'?'暂无归档活动':'没有符合条件的活动')}</div>}
   {visible.length>12&&<div className="pagination"><button className="secondary" disabled={listPage===0} onClick={()=>setListPage(n=>n-1)}><ChevronLeft size={16}/>{tr('上一页')}</button><span>{listPage+1} / {listPageCount}</span><button className="secondary" disabled={listPage+1>=listPageCount} onClick={()=>setListPage(n=>n+1)}>{tr('下一页')}<ChevronRight size={16}/></button></div>}
  </section>
  {error&&<p role="alert" className="error">{tr(error)}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
  {activity&&<>
   <section className="panel activity-overview"><div className="panel-title"><div><h2>{activity.name}</h2><p className="muted">{activity.category} · {activity.familyName||tr('个人活动')}{activity.archived?' · '+tr('已归档'):''}</p>{activity.description&&<p>{activity.description}</p>}<small>{[activity.startsOn,activity.endsOn].filter(Boolean).join(' — ')}</small></div><div className="activity-actions">
    {!activity.archived&&<button onClick={()=>onRecord(activity.id)}><NotebookPen size={17}/>{tr('记一笔到活动')}</button>}
    {activity.editable&&<>
     {activity.archived&&<button className="secondary" disabled={busy} onClick={()=>archive(activity)}><ArchiveRestore size={16}/>{tr('重新启用')}</button>}
     <button className="secondary" onClick={()=>openEditor(activity)}><Pencil size={16}/>{tr('编辑')}</button>
     {!activity.archived&&<button className="secondary" disabled={busy} onClick={()=>archive(activity)}><Archive size={16}/>{tr('归档此活动')}</button>}
     <button className="secondary activity-delete" disabled={busy} onClick={()=>setConfirmDelete(true)}><Trash2 size={16}/>{tr('删除活动')}</button>
    </>}
   </div></div>
    <div className="activity-metrics"><div><small>{tr('可见净支出')}</small><strong>{formatMoney(net)}</strong></div><div><small>{tr('收入')}</small><strong>{formatMoney(summary?.totals.income||0)}</strong></div><div><small>{tr('活动预算')}</small><strong>{activity.budget==null?'—':formatMoney(activity.budget)}</strong></div><div><small>{tr('可见预算剩余')}</small><strong className={remaining!=null&&remaining<0?'expense':''}>{remaining==null?'—':formatMoney(remaining)}</strong></div></div><small>{tr('只统计你有权访问的账本记录。家庭成员可共同记账，但私人账本不会自动共享；退款冲减支出，转账不计收支。')}</small>
   </section>
   <div className="activity-chart-grid"><BreakdownBars title="按分类" items={report?.categories||[]} label={item=>item.category||tr('其他')}/><BreakdownBars title="按付款钱包" items={report?.wallets||[]} label={item=>item.name||tr('未知钱包')}/><BreakdownBars title="按账本" items={report?.books||[]} label={item=>item.name||tr('未知账本')}/><BreakdownBars title="每日净支出" items={report?.daily||[]} label={item=>item.date||''}/></div>
   <section className="panel activity-records"><div className="panel-title"><h2>{tr('活动明细')}</h2><button className="secondary" disabled={activity.archived||busy||!books.some(b=>b.role!=='viewer')} onClick={()=>{setSourceBook(books.find(b=>b.role!=='viewer')?.id||'');setSourceQuery('');setSourceOffset(0);setAdding(true);}}>{tr('加入已有交易')}</button></div>
    <div className="activity-filters"><label>{tr('账本')}<FormSelect value={book} onChange={v=>{setBook(v);setOffset(0);}}><option value="all">{tr('全部账本')}</option>{books.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</FormSelect></label><label>{tr('类型')}<FormSelect value={kind} onChange={v=>{setKind(v);setOffset(0);}}><option value="all">{tr('全部类型')}</option><option value="expense">{tr('支出')}</option><option value="refund">{tr('退款')}</option><option value="income">{tr('收入')}</option><option value="transfer">{tr('转账')}</option></FormSelect></label><label>{tr('分类')}<FormSelect value={category} onChange={v=>{setCategory(v);setOffset(0);}}><option value="">{tr('全部分类')}</option>{[...new Set((summary?.categories||[]).map(item=>item.category).filter(Boolean))].map(item=><option key={item} value={item}>{item}</option>)}</FormSelect></label><label>{tr('钱包')}<FormSelect value={account} onChange={v=>{setAccount(v);setOffset(0);}}><option value="all">{tr('全部钱包')}</option>{(summary?.wallets||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</FormSelect></label></div>
    <label className="activity-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tr('搜索商家、商品、备注、订单号')} aria-label={tr('搜索活动明细')}/></label><p className="muted">{tr('匹配 {0} 笔',[report?.totals.count||0])}</p>
    {loading?<p role="status">{tr('正在读取活动…')}</p>:report?.rows.length?report.rows.map(row=><div className="activity-record" key={row.id}><div><strong>{row.title||row.payee||row.product||row.category}</strong><small>{row.date} · {row.book_name} · {row.account_name} · {row.category}</small></div><strong className={row.kind==='expense'?'expense':'income'}>{row.kind==='expense'?'-':''}{formatMoney(row.amount)}</strong>{!activity.archived&&books.find(b=>b.id===row.book_id)?.role!=='viewer'&&<button className="text-button" disabled={busy} onClick={()=>unassign(row)}>{tr('移出活动')}</button>}</div>):<div className="empty">{tr('当前筛选下没有交易')}</div>}
    {!!report&&report.totals.count>20&&<div className="pagination"><button className="secondary" disabled={offset===0||loading} onClick={()=>setOffset(n=>Math.max(0,n-20))}><ChevronLeft size={16}/>{tr('上一页')}</button><span>{offset+1}–{Math.min(offset+20,report.totals.count)} / {report.totals.count}</span><button className="secondary" disabled={loading||offset+20>=report.totals.count} onClick={()=>setOffset(n=>n+20)}>{tr('下一页')}<ChevronRight size={16}/></button></div>}
   </section>
  </>}
  {editor!==undefined&&<Sheet title={tr(editor?'编辑活动':'创建活动')} onClose={()=>!busy&&setEditor(undefined)}><form className="activity-form" onSubmit={save}><label>{tr('活动名称')}<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required placeholder={tr('例如：国庆旅行')}/></label><label>{tr('活动类型')}<input list="activity-category-options" value={activityCategory} onChange={e=>setActivityCategory(e.target.value)} maxLength={40} required placeholder={tr('旅行、聚会等')}/><datalist id="activity-category-options">{activityCategories.map(c=><option key={c} value={c}/>)}</datalist></label><label>{tr('活动归属')}<FormSelect value={familyId} onChange={setFamilyId} disabled={!!editor&&editor.ownerId!==userId}><option value="">{tr('个人活动，仅自己可见')}</option>{families.map(f=><option key={f.id} value={f.id}>{f.name} · {tr('家庭成员可参与')}</option>)}</FormSelect></label><p className="muted">{tr('家庭活动会显示给家庭成员；各人的私人账本仍按原权限保护。')}</p><label>{tr('活动说明（选填）')}<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} rows={3}/></label><div className="form-grid"><label>{tr('开始日期（选填）')}<DateField type="date" value={startsOn} onChange={setStartsOn}/></label><label>{tr('结束日期（选填）')}<DateField type="date" value={endsOn} onChange={setEndsOn}/></label></div><label>{tr('总预算（选填）')}<input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="0.00"/></label>{error&&<p role="alert" className="error">{tr(error)}</p>}<button disabled={busy}>{tr('保存活动')}</button></form></Sheet>}
  {confirmDelete&&activity&&<Sheet title={tr('删除活动')} onClose={()=>!busy&&setConfirmDelete(false)}><p>{tr('确定删除“{0}”？只删除活动和归集关系，原账本里的交易不会删除。',[activity.name])}</p>{error&&<p role="alert" className="error">{tr(error)}</p>}<div className="activity-confirm-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirmDelete(false)}>{tr('取消')}</button><button className="activity-delete" disabled={busy} onClick={remove}>{tr('确认删除活动')}</button></div></Sheet>}
  {adding&&<Sheet title={tr('加入已有交易')} onClose={()=>setAdding(false)}><div className="activity-add"><label>{tr('从哪个账本选择')}<FormSelect value={sourceBook} onChange={v=>{setSourceBook(v);setSourceOffset(0);}}>{books.filter(b=>b.role!=='viewer').map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</FormSelect></label><label>{tr('搜索交易')}<input value={sourceQuery} onChange={e=>{setSourceQuery(e.target.value);setSourceOffset(0);}} placeholder={tr('商家、商品或订单号')}/></label>{sourceLoading?<p role="status">{tr('正在查找记录…')}</p>:sourceRows.length?sourceRows.map(row=><div className="activity-add-row" key={row.id}><div><strong>{row.title||row.payee||row.category}</strong><small>{row.date} · {row.category} · {formatMoney(row.amount)}</small></div><button className="secondary" disabled={busy} onClick={()=>assign(row)}>{tr('加入')}</button></div>):<p className="muted">{tr('没有找到交易，请换个关键词。')}</p>}{sourceTotal>20&&<div className="pagination"><button className="secondary" disabled={sourceOffset===0||sourceLoading} onClick={()=>setSourceOffset(n=>Math.max(0,n-20))}><ChevronLeft size={16}/>{tr('上一页')}</button><span>{sourceOffset+1}–{Math.min(sourceOffset+20,sourceTotal)} / {sourceTotal}</span><button className="secondary" disabled={sourceLoading||sourceOffset+20>=sourceTotal} onClick={()=>setSourceOffset(n=>n+20)}>{tr('下一页')}<ChevronRight size={16}/></button></div>}</div></Sheet>}
 </div>;
}
