'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,FolderPlus,Pencil,Search,Archive,ArchiveRestore} from 'lucide-react';
import {useI18n} from './LanguageProvider';
import {formatMoney} from '@/lib/deployment';
import {amountToCents} from '@/server/model';
import type {ManagedBook} from './ManagementPages';
import {FormSelect} from './FormSelect';
import {DateField} from './DateField';
import type {Activity} from './ActivitySelect';
import {Sheet} from './Sheet';

type ActivityRow={id:string;book_id:string;book_name:string;kind:string;amount:number;date:string;title:string;payee:string;category:string;product:string;account_name:string};
type Breakdown={id?:string;name?:string;category?:string;date?:string;amount:number};
type ActivityReport={activity:Activity;rows:ActivityRow[];totals:{count:number;income:number;expense:number;refund:number};categories:Breakdown[];wallets:Breakdown[];books:Breakdown[];daily:Breakdown[]};
type SearchRow={id:string;book_id:string;family_movement_id?:string|null;title:string;payee:string;category:string;date:string;amount:number;kind:string};
async function request(path:string,method='GET',body?:unknown){const response=await fetch('/api/'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
function BreakdownBars({title,items,label}:{title:string;items:Breakdown[];label:(item:Breakdown)=>string}){const {t:tr}=useI18n(),max=Math.max(1,...items.map(item=>Math.max(0,item.amount)));return <section className="panel activity-breakdown"><h2>{tr(title)}</h2>{items.length?items.map((item,index)=><div className="activity-bar" key={(item.id||item.category||item.date||item.name||'')+index}><div><span>{label(item)}</span><strong>{formatMoney(item.amount)}</strong></div><span className="activity-bar-track"><span style={{width:`${Math.max(0,item.amount)/max*100}%`}}/></span></div>):<p className="muted">{tr('暂无可统计的支出')}</p>}</section>;}

export function ActivitiesPage({books,activities,onChanged}:{books:ManagedBook[];activities:Activity[];onChanged:()=>Promise<void>}){const {t:tr}=useI18n();
 const [selected,setSelected]=useState(''),[editor,setEditor]=useState<Activity|null|undefined>(undefined),[name,setName]=useState(''),[description,setDescription]=useState(''),[startsOn,setStartsOn]=useState(''),[endsOn,setEndsOn]=useState(''),[budget,setBudget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [report,setReport]=useState<ActivityReport|null>(null),[summary,setSummary]=useState<ActivityReport|null>(null),[loading,setLoading]=useState(false),[book,setBook]=useState('all'),[kind,setKind]=useState('all'),[category,setCategory]=useState(''),[account,setAccount]=useState('all'),[q,setQ]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0);
 const [adding,setAdding]=useState(false),[sourceBook,setSourceBook]=useState(books.find(b=>b.role!=='viewer')?.id||''),[sourceQuery,setSourceQuery]=useState(''),[sourceRows,setSourceRows]=useState<SearchRow[]>([]),[sourceTotal,setSourceTotal]=useState(0),[sourceOffset,setSourceOffset]=useState(0),[sourceLoading,setSourceLoading]=useState(false);
 useEffect(()=>{if(!selected&&activities.length)setSelected(activities[0].id);},[activities,selected]);
 useEffect(()=>{const timer=setTimeout(()=>{setSearch(q);setOffset(0);},250);return()=>clearTimeout(timer);},[q]);
 useEffect(()=>{setBook('all');setKind('all');setCategory('');setAccount('all');setQ('');setOffset(0);},[selected]);
 useEffect(()=>{if(!selected){setReport(null);return;}const controller=new AbortController(),params=new URLSearchParams({book,kind,category,account,q:search,offset:String(offset),limit:'20'});setLoading(true);fetch('/api/activities/'+selected+'?'+params,{signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!controller.signal.aborted)setReport(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[selected,book,kind,category,account,search,offset,revision]);
 useEffect(()=>{if(!selected){setSummary(null);return;}const controller=new AbortController();fetch('/api/activities/'+selected,{signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!controller.signal.aborted)setSummary(value);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[selected,revision]);
 useEffect(()=>{if(!adding||!sourceBook)return;const controller=new AbortController(),timer=setTimeout(()=>{setSourceLoading(true);const params=new URLSearchParams({from:'2000-01-01',to:'2100-12-31',q:sourceQuery,limit:'20',offset:String(sourceOffset)});fetch(`/api/books/${sourceBook}/report?${params}`,{signal:controller.signal}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error);if(!controller.signal.aborted){setSourceRows(value.rows.filter((row:SearchRow)=>!row.family_movement_id));setSourceTotal(value.totals?.count||0);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setSourceLoading(false);});},250);return()=>{controller.abort();clearTimeout(timer);};},[adding,sourceBook,sourceQuery,sourceOffset,revision]);
 function openEditor(activity?:Activity){setEditor(activity||null);setName(activity?.name||'');setDescription(activity?.description||'');setStartsOn(activity?.startsOn||'');setEndsOn(activity?.endsOn||'');setBudget(activity?.budget==null?'':String(activity.budget/100));setError('');}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const payload={name,description,startsOn:startsOn||null,endsOn:endsOn||null,budget:budget?amountToCents(budget):null};let nextId=editor?.id;if(editor)await request('activities','PUT',{id:editor.id,...payload});else nextId=(await request('activities','POST',payload)).id;await onChanged();setSelected(nextId||'');setEditor(undefined);setRevision(n=>n+1);setNotice(tr('活动已保存'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function archive(activity:Activity){setBusy(true);setError('');try{await request('activities','PATCH',{id:activity.id,archived:!activity.archived});await onChanged();setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function assign(row:SearchRow){setBusy(true);setError('');try{await request('activities/assign','PUT',{bookId:sourceBook,transactionId:row.id,activityId:selected});await onChanged();setRevision(n=>n+1);setNotice(tr('已加入活动'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const activity=activities.find(a=>a.id===selected),net=(summary?.totals.expense||0)-(summary?.totals.refund||0),remaining=activity?.budget==null?null:activity.budget-net;
 return <div className="activities-page"><section className="panel"><div className="panel-title"><div><h2>{tr('我的活动')}</h2><p className="muted">{tr('活动可归集不同账本的交易；每笔交易仍只在原账本和实际钱包中记账。')}</p></div><button onClick={()=>openEditor()}><FolderPlus size={18}/>{tr('创建活动')}</button></div>{activities.length?<div className="activity-list">{activities.map(item=><button key={item.id} type="button" className={selected===item.id?'activity-tile is-active':'activity-tile'} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)}><strong>{item.name}</strong><small>{item.entryCount} {tr('笔记录')}{item.archived?' · '+tr('已归档'):''}</small></button>)}</div>:<div className="empty">{tr('还没有活动。创建一次旅行、聚会或装修计划，开始归集相关支出。')}</div>}</section>
 {error&&<p role="alert" className="error">{tr(error)}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {activity&&<><section className="panel activity-overview"><div className="panel-title"><div><h2>{activity.name}</h2><p className="muted">{activity.description||tr('按活动查看跨账本的真实收支')}</p><small>{[activity.startsOn,activity.endsOn].filter(Boolean).join(' — ')}</small></div><div className="inline"><button className="secondary" onClick={()=>openEditor(activity)}><Pencil size={16}/>{tr('编辑')}</button><button className="secondary" disabled={busy} onClick={()=>archive(activity)}>{activity.archived?<ArchiveRestore size={16}/>:<Archive size={16}/>} {tr(activity.archived?'恢复活动':'归档活动')}</button></div></div><div className="activity-metrics"><div><small>{tr('净支出')}</small><strong>{formatMoney(net)}</strong></div><div><small>{tr('收入')}</small><strong>{formatMoney(summary?.totals.income||0)}</strong></div><div><small>{tr('活动预算')}</small><strong>{activity.budget==null?'—':formatMoney(activity.budget)}</strong></div><div><small>{tr('预算剩余')}</small><strong className={remaining!=null&&remaining<0?'expense':''}>{remaining==null?'—':formatMoney(remaining)}</strong></div></div><small>{tr('退款冲减支出；转账只展示，不计入收支。上方总览为整个活动，下方图表和明细按筛选更新。')}</small></section>
 <div className="activity-chart-grid"><BreakdownBars title="按分类" items={report?.categories||[]} label={item=>item.category||tr('其他')}/><BreakdownBars title="按付款钱包" items={report?.wallets||[]} label={item=>item.name||tr('未知钱包')}/><BreakdownBars title="按账本" items={report?.books||[]} label={item=>item.name||tr('未知账本')}/><BreakdownBars title="每日净支出" items={report?.daily||[]} label={item=>item.date||''}/></div>
 <section className="panel activity-records">
  <div className="panel-title"><h2>{tr('活动明细')}</h2><button className="secondary" disabled={activity.archived||busy} onClick={()=>{setSourceBook(books.find(b=>b.role!=='viewer')?.id||'');setSourceQuery('');setAdding(true);}}>{tr('加入已有交易')}</button></div>
  <div className="activity-filters">
   <label>{tr('账本')}<FormSelect value={book} onChange={v=>{setBook(v);setOffset(0);}}><option value="all">{tr('全部账本')}</option>{books.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</FormSelect></label>
   <label>{tr('类型')}<FormSelect value={kind} onChange={v=>{setKind(v);setOffset(0);}}><option value="all">{tr('全部类型')}</option><option value="expense">{tr('支出')}</option><option value="refund">{tr('退款')}</option><option value="income">{tr('收入')}</option><option value="transfer">{tr('转账')}</option></FormSelect></label>
   <label>{tr('分类')}<FormSelect value={category} onChange={v=>{setCategory(v);setOffset(0);}}><option value="">{tr('全部分类')}</option>{[...new Set((summary?.categories||[]).map(item=>item.category).filter(Boolean))].map(item=><option key={item} value={item}>{item}</option>)}</FormSelect></label>
   <label>{tr('钱包')}<FormSelect value={account} onChange={v=>{setAccount(v);setOffset(0);}}><option value="all">{tr('全部钱包')}</option>{(summary?.wallets||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</FormSelect></label>
  </div>
  <label className="activity-search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tr('搜索商家、商品、备注、订单号')} aria-label={tr('搜索活动明细')}/></label>
  <p className="muted">{tr('匹配 {0} 笔',[report?.totals.count||0])}</p>
  {loading?<p role="status">{tr('正在读取活动…')}</p>:report?.rows.length?report.rows.map(row=><div className="activity-record" key={row.id}><div><strong>{row.title||row.payee||row.product||row.category}</strong><small>{row.date} · {row.book_name} · {row.account_name} · {row.category}</small></div><strong className={row.kind==='expense'?'expense':'income'}>{row.kind==='expense'?'-':''}{formatMoney(row.amount)}</strong>{books.find(b=>b.id===row.book_id)?.role!=='viewer'&&<button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await request('activities/assign','PUT',{bookId:row.book_id,transactionId:row.id,activityId:null});await onChanged();setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{tr('移出活动')}</button>}</div>):<div className="empty">{tr('当前筛选下没有交易')}</div>}
  {!!report&&report.totals.count>20&&<div className="pagination"><button className="secondary" disabled={offset===0||loading} onClick={()=>setOffset(n=>Math.max(0,n-20))}><ChevronLeft size={16}/>{tr('上一页')}</button><span>{offset+1}–{Math.min(offset+20,report.totals.count)} / {report.totals.count}</span><button className="secondary" disabled={loading||offset+20>=report.totals.count} onClick={()=>setOffset(n=>n+20)}>{tr('下一页')}<ChevronRight size={16}/></button></div>}
 </section></>}
 {editor!==undefined&&<Sheet title={tr(editor?'编辑活动':'创建活动')} onClose={()=>setEditor(undefined)}><form className="activity-form" onSubmit={save}><label>{tr('活动名称')}<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} required placeholder={tr('例如：国庆旅行')}/></label><label>{tr('活动说明（选填）')}<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} rows={3}/></label><div className="form-grid"><label>{tr('开始日期（选填）')}<DateField type="date" value={startsOn} onChange={setStartsOn}/></label><label>{tr('结束日期（选填）')}<DateField type="date" value={endsOn} onChange={setEndsOn}/></label></div><label>{tr('总预算（选填）')}<input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="0.00"/></label><p className="muted">{tr('活动可以关联多个账本；预算只用于提醒，不影响账本余额。')}</p>{error&&<p role="alert" className="error">{tr(error)}</p>}<button disabled={busy}>{tr('保存活动')}</button></form></Sheet>}
 {adding&&<Sheet title={tr('加入已有交易')} onClose={()=>setAdding(false)}><div className="activity-add"><label>{tr('从哪个账本选择')}<FormSelect value={sourceBook} onChange={v=>{setSourceBook(v);setSourceOffset(0);}}>{books.filter(b=>b.role!=='viewer').map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</FormSelect></label><label>{tr('搜索交易')}<input value={sourceQuery} onChange={e=>{setSourceQuery(e.target.value);setSourceOffset(0);}} placeholder={tr('商家、商品或订单号')}/></label>{sourceLoading?<p role="status">{tr('正在查找记录…')}</p>:sourceRows.length?sourceRows.map(row=><div className="activity-add-row" key={row.id}><div><strong>{row.title||row.payee||row.category}</strong><small>{row.date} · {row.category} · {formatMoney(row.amount)}</small></div><button className="secondary" disabled={busy} onClick={()=>assign(row)}>{tr('加入')}</button></div>):<p className="muted">{tr('没有找到交易，请换个关键词。')}</p>}{sourceTotal>20&&<div className="pagination"><button className="secondary" disabled={sourceOffset===0||sourceLoading} onClick={()=>setSourceOffset(n=>Math.max(0,n-20))}><ChevronLeft size={16}/>{tr('上一页')}</button><span>{sourceOffset+1}–{Math.min(sourceOffset+20,sourceTotal)} / {sourceTotal}</span><button className="secondary" disabled={sourceLoading||sourceOffset+20>=sourceTotal} onClick={()=>setSourceOffset(n=>n+20)}>{tr('下一页')}<ChevronRight size={16}/></button></div>}</div></Sheet>}</div>;
}
