'use client';
import {DateField} from './DateField';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import {CalendarRange} from 'lucide-react';
import {CategoryIcon} from './VisualSelect';
import {periodLastDay,periodLabels,type PeriodUnit} from '@/lib/period';
import {FormSelect} from './FormSelect';
const yuan=(n:number)=>formatMoney(n);
type Allocation={title?:string;start_date:string;period_unit:PeriodUnit;period_count:number;id:string;version:number;payee:string;product:string;category:string;amount:number;refunded:number;start:string;months:number;end:string;monthly:number};
export function AllocationEditor({book,id,version,amount,date,initial,onSaved}:{book:string;id:string;version:number;amount:number;date:string;initial?:Allocation;onSaved:()=>void}){const {t:tr,locale}=useI18n();
 const [start,setStart]=useState(initial?.start_date||date.slice(0,7)+'-01'),[unit,setUnit]=useState<PeriodUnit>(initial?.period_unit||'month'),[count,setCount]=useState(initial?.period_count||initial?.months||12),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(!!initial),[net,setNet]=useState(amount);
 useEffect(()=>{if(initial)return;const c=new AbortController();fetch(`/api/books/${book}/allocations?month=${date.slice(0,7)}`,{signal:c.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);const x=data.items.find((x:Allocation)=>x.id===id);if(x){setStart(x.start_date||x.start+'-01');setUnit(x.period_unit||'month');setCount(x.period_count||x.months);setNet(x.amount-x.refunded);}setReady(true);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[book,id,date,initial]);
 let end='',preview='';try{end=periodLastDay(start,unit,count);const periods=unit==='month'?count:unit==='year'?count*12:unit==='week'?count*7:count;preview=tr('每{0} {1}{2}',[tr(unit==='month'||unit==='year'?'月':'天'),yuan(Math.floor(net/periods)),net%periods?tr('，前 {0} 期各多 0.01 元',[net%periods]):'']);}catch{}

 async function save(remove=false){setBusy(true);setError('');try{const r=await fetch(`/api/books/${book}/allocations`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version,startDate:start,periodUnit:unit,periodCount:count,remove})});const d=await r.json();if(!r.ok)throw new Error(d.error);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="allocation-editor" open={!!initial}><summary><CalendarRange size={18}/>{tr("费用周期分摊")}</summary>{!ready&&<p>{tr("正在读取设置…")}</p>}<div className="form-grid"><label>{tr("周期数量")}<input disabled={(!ready || busy)} type="number" min={1} step={1} value={(count || '')} onChange={e=>setCount(Number(e.target.value))}/></label><label>{tr("周期单位")}<FormSelect disabled={(!ready || busy)} value={unit} onChange={v=>{setUnit(v as PeriodUnit);if(v==='month'||v==='year')setStart(start.slice(0,7)+'-01');}}>{Object.entries(periodLabels).map(([v,label])=><option key={v} value={v}>{tr(label)}</option>)}</FormSelect></label><label>{tr("开始")}{unit==='month'||unit==='year'?<DateField disabled={(!ready || busy)} type="month" value={start.slice(0,7)} onChange={value=>setStart(value?value+'-01':'')}/>:<DateField disabled={(!ready || busy)} type="date" value={start} onChange={value=>setStart(value)}/>}</label></div>{end&&<p className="notice">{start} {tr("至")}{end} · {count} {tr(periodLabels[unit])}<br/>{preview}{tr("，总额")}{yuan(net)}。</p>}{!end&&ready&&<p className="muted">{tr("请填写有效的正整数周期和开始日期。")}</p>}<details className="usage-help"><summary>{tr("分摊口径")}</summary><p>{tr("日 / 周按覆盖天数平均分摊，再汇总到各月；月 / 年按整月平均分摊。余下的分分配给前面的期数，总额不变，付款只记录一次。")}</p></details>{error&&<p className="error">{tr(error)}</p>}<div className="sheet-actions"><button type="button" disabled={((busy || !ready) || !end)} onClick={()=>save()}>{tr("保存分摊")}</button><button type="button" className="secondary" disabled={(busy || !ready)} onClick={()=>save(true)}>{tr("取消分摊")}</button></div></details>;
}
export function AllocationPanel({book,month,revision,canWrite,onSaved}:{book:string;month:string;revision:number;canWrite:boolean;onSaved:()=>void}){const {t:tr,locale}=useI18n();
 const [data,setData]=useState<{items:Allocation[];allocated:number;ordinary:number;total:number}|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState('');
 useEffect(()=>{const c=new AbortController();setData(null);setError('');fetch(`/api/books/${book}/allocations?month=${month}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[book,month,revision]);
 return <section className="panel allocation-panel"><h2><CalendarRange size={22}/>{tr("把订阅费用，摊进每个月")}</h2><p className="muted">{month} {tr("· 普通净支出 + 本月订阅分摊，已排除订阅付款原额，避免重复。账户余额及上方实际收支不变。")}</p>{error&&<p className="error">{tr(error)}</p>}{data&&<><div className="allocation-totals"><div><small>{tr("本月订阅分摊")}</small><strong>{yuan(data.allocated)}</strong></div><div><small>{tr("普通净支出")}</small><strong>{yuan(data.ordinary)}</strong></div><div><small>{tr("按月费用合计")}</small><strong>{yuan(data.total)}</strong></div></div>{!data.items.length?<details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("在周期账单中开启分摊，或打开一笔已有消费，设置覆盖周期。")}</p></details>:<details><summary>{tr("查看已设置的分摊（")}{data.items.length} {tr("项）")}</summary>{data.items.map(a=><div className="allocation-row" key={a.id}><div className="rank"><span><CategoryIcon name={a.category}/><strong>{(((a.title || a.payee) || a.product) || a.category)}</strong></span><strong>{yuan(a.monthly)} {tr("/ 本月")}</strong></div><small>{a.start_date} {tr("至")}{a.end} · {a.period_count} {tr(periodLabels[a.period_unit])} {tr("· 原额")}{yuan(a.amount)}{(a.refunded>0 && tr(" · 已退 {0}",[yuan(a.refunded)]))}</small>{canWrite&&<button className="text-button" onClick={()=>setEditing(editing===a.id?'':a.id)}>{tr("调整分摊")}</button>}{editing===a.id&&<AllocationEditor key={((a.id + ':') + a.version)} book={book} id={a.id} version={a.version} amount={a.amount-a.refunded} date={(a.start + '-01')} initial={a} onSaved={()=>{setEditing('');onSaved();}}/>}</div>)}</details>}<details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("关联退款后按最新净额重算整个覆盖期；修改或删除原消费会同步更新分摊。暂停或删除续费计划不影响已经付款的分摊。")}</p></details></>}</section>;
}
