'use client';
import {useEffect,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,ArrowLeftRight} from 'lucide-react';
import {VisualSelect,AccountIcon} from './VisualSelect';
import {Sheet} from './Sheet';
import {formatMoney} from '@/lib/deployment';
export function BookMovements({book,from,to,revision,onChanged}:{book:string;from:string;to:string;revision:number;onChanged:()=>void}){
 const [data,setData]=useState<any>({rows:[],total:0}),[offset,setOffset]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[editing,setEditing]=useState<any>(null),[books,setBooks]=useState<any[]>([]),[target,setTarget]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>setOffset(0),[book,from,to]);
 useEffect(()=>{if(!from||!to||to<from)return;const c=new AbortController();setLoading(true);fetch(`/api/book-movements/${book}?${new URLSearchParams({from,to,offset:String(offset)})}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!d.rows.length&&offset){setOffset(0);return;}setData(d);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[book,from,to,offset,revision,version]);
 async function edit(row:any){setEditing(row);setTarget(book);setBooks([]);setError('');try{const r=await fetch('/api/family-finance/'+row.family_id);const d=await r.json();if(!r.ok)throw Error(d.error);setBooks(d.books);}catch(e){setError((e as Error).message);}}
 return <section className="book-movements"><div className="panel-title"><h3><ArrowLeftRight size={18}/>资金往来</h3><small>转入／转出 · 不计收支</small></div>{error&&<p className="error">{error}</p>}{loading?<p role="status">正在读取…</p>:data.rows.length?data.rows.map((r:any)=><article className="schedule-card" key={r.id}><div><strong>{r.direction==='in'?<ArrowDownLeft size={18}/>:<ArrowUpRight size={18}/>} {r.direction==='in'?'转入':'转出'} · {r.counterparty||'自己／共同钱包'}</strong><small>{r.date} · {r.status==='pending'?'待收款确认':'已到账'}{r.note?' · '+r.note:''}</small>{r.wallet&&<small><AccountIcon name={r.wallet} size={18}/>{r.wallet}</small>}</div><strong>{formatMoney(r.amount)}</strong><button className="text-button" onClick={()=>edit(r)}>展示账本</button></article>):<p className="muted">本期间暂无家庭资金往来</p>}{data.total>20&&<div className="pagination"><button disabled={loading||!offset} onClick={()=>setOffset(n=>Math.max(0,n-20))}>上一页</button><span>{offset+1}–{Math.min(offset+20,data.total)} / {data.total}</span><button disabled={loading||offset+20>=data.total} onClick={()=>setOffset(n=>n+20)}>下一页</button></div>}
 {editing&&<Sheet title="调整我的展示账本" onClose={()=>{if(!busy)setEditing(null);}}><VisualSelect label="展示账本" value={target} onChange={setTarget} options={[{value:'',label:'仅保留在家庭往来'},...books.map(b=>({value:b.id,label:b.name,icon:b.icon}))]}/><button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/family-finance/'+editing.family_id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'display',id:editing.id,displayBookId:target||null})});const d=await r.json();if(!r.ok)throw Error(d.error);setEditing(null);setVersion(n=>n+1);onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>保存</button>{error&&<p className="error">{error}</p>}</Sheet>}
 </section>;
}
