'use client';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {VisualSelect,CategoryIcon} from './VisualSelect';
import {useState} from 'react';
import {Plus,ChevronRight} from 'lucide-react';
import {Sheet} from './Sheet';
import {amountToCents} from '@/server/model';
type Budget={category:string;amount:number};
const yuan=(n:number)=>formatMoney(n);
export function BudgetPanel({month,budgets,spending,categories,canWrite,onSave,onDelete}:{month:string;budgets:Budget[];spending:{name:string;value:number}[];categories:string[];canWrite:boolean;onSave:(b:Budget)=>Promise<void>;onDelete:(category:string)=>Promise<void>}){const {t:tr,locale}=useI18n();
 const [editing,setEditing]=useState<Budget|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><div className="panel-title"><h2>{month.replace('-','年')}{tr("月预算")}</h2>{canWrite&&<button className="text-button" onClick={()=>{setEditing(null);setOpen(true);setError('');}}><Plus size={18}/>{tr("添加")}</button>}</div>{budgets.map(b=>{const spent=spending.find(s=>s.name===b.category)?.value||0;return <button className="budget-card" key={b.category} onClick={()=>{if(canWrite){setEditing(b);setOpen(true);setError('');}}} disabled={!canWrite}><div className="rank"><strong><CategoryIcon name={b.category}/>{b.category}</strong><span>{yuan(spent)} / {yuan(b.amount)} {canWrite&&<ChevronRight size={15}/>}</span></div><progress max={(b.amount || 1)} value={Math.max(0,Math.min(spent,b.amount||1))}/><small className={spent>b.amount?'expense':''}>{spent>b.amount?(tr("已超支 ") + yuan(spent-b.amount)):(tr("还可用 ") + yuan(b.amount-spent))}</small></button>;})}{!budgets.length&&<div className="empty"><details className="usage-help"><summary>{tr("使用说明")}</summary><p>{tr("为最关心的开销设个额度，随时看看还剩多少。")}</p></details></div>}{open&&<Sheet title={editing?tr("调整分类预算"):tr("添加分类预算")} onClose={()=>{if(!busy)setOpen(false);}}>{error&&<p className="error" role="alert">{tr(error)}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const amount=amountToCents(String(f.get('amount')));run(()=>onSave({category:String(f.get('category')),amount}));}catch(e){setError((e as Error).message);}}}><label>{tr("分类")}<VisualSelect name="category" defaultValue={editing?.category} disabled={!!editing} options={Array.from(new Set([...(editing?[editing.category]:[]),...categories])).map(c=>({value:c,label:c}))}/></label><label>{tr("预算金额（元）")}<input name="amount" inputMode="decimal" defaultValue={editing?editing.amount/100:''} required/></label><div className="sheet-actions">{editing&&<button type="button" className="secondary" disabled={busy} onClick={()=>run(()=>onDelete(editing.category))}>{tr("删除预算")}</button>}<button disabled={busy}>{tr("保存预算")}</button></div></form></Sheet>}</section>;
}
