 'use client';
import {useI18n} from './LanguageProvider';
import {useState} from 'react';
import {Sheet} from './Sheet';
import {SymbolIcon,StickerPicker} from './VisualSelect';
export type Category={name:string;icon:string;archived:boolean};
export function CategoryPanel({items,canWrite,onSave}:{items:Category[];canWrite:boolean;onSave:(value:unknown)=>Promise<void>}){const {t:tr,locale}=useI18n();
 const [editing,setEditing]=useState<Category|null>(null),[open,setOpen]=useState(false),[all,setAll]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[icon,setIcon]=useState('🧸'),[deleting,setDeleting]=useState(false);
 function edit(c:Category|null){setEditing(c);setIcon(c?.icon||'sticker:001');setError('');setDeleting(false);setOpen(true);}
 async function save(value:unknown){setBusy(true);setError('');try{await onSave(value);setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><div className="panel-title"><h2>{tr("我的分类小伙伴")}</h2>{canWrite&&<button className="text-button" onClick={()=>edit(null)}>{tr("＋ 添加分类")}</button>}</div><details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("给每种开销挑一个表情，记账时一眼就能找到。")}</p></details><input aria-label={tr("搜索分类")} placeholder={tr("搜索分类名称…")} value={query} onChange={e=>setQuery(e.target.value)}/><div className="category-manager">{items.filter(c=>(all||!c.archived)&&c.name.includes(query)).map(c=><button className="secondary" disabled={!canWrite} key={c.name} onClick={()=>edit(c)}><SymbolIcon icon={c.icon} size={52}/><strong>{c.name}</strong><small>{c.archived?tr("已停用"):tr("点击编辑")}</small></button>)}</div><button className="text-button" onClick={()=>setAll(v=>!v)}>{all?tr("隐藏停用分类"):tr("显示停用分类")}</button>{open&&<Sheet title={editing?tr("修改分类"):tr("添加分类")} onClose={()=>{if(!busy)setOpen(false);}}>{error&&<p className="error" role="alert">{tr(error)}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({name:editing?.name||String(f.get('name')),newName:editing?String(f.get('name')):undefined,icon,archived:editing?.archived||false});}}><fieldset disabled={busy}><label>{tr("分类名称")}<input name="name" defaultValue={editing?.name} maxLength={60} required placeholder={tr("例如：宠物、宝宝、数码")}/></label><StickerPicker value={icon} onChange={setIcon}/>{editing&&<details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("改名同步更新历史记录和预算；删除分类仅移出分类列表，已有账目保留原名称。")}</p></details>}<div className="sheet-actions">{editing&&<button type="button" className="secondary" onClick={()=>save({...editing,archived:!editing.archived})}>{editing.archived?tr("恢复分类"):tr("停用分类")}</button>}<button>{tr("保存分类")}</button></div>{editing&&(deleting?<div className="notice">{tr("确定删除「")}{editing.name}{tr("」？已有记录保留，相关模板和计划请改选分类。")}<button type="button" className="secondary" onClick={()=>setDeleting(false)}>{tr("取消")}</button><button type="button" onClick={()=>save({...editing,operation:'delete'})}>{tr("确认删除")}</button></div>:<button type="button" className="text-button" onClick={()=>setDeleting(true)}>{tr("删除这个分类")}</button>)}</fieldset></form></Sheet>}</section>;
}
