'use client';
import {useEffect,useState} from 'react';
import {useI18n} from './LanguageProvider';
import {FinanceChart} from './InteractiveFinanceChart';
import {deployment,formatMoney} from '@/lib/deployment';
export function CostReport({from,to,bookId,onOpen}:{from:string;to:string;bookId?:string;onOpen:(id:string)=>void}){
 const {locale}=useI18n(),l=(zh:string,en:string)=>locale==='en'?en:zh;
 const [currentBook,setCurrentBook]=useState(false);
 const [scope,setScope]=useState('personal'),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{setOffset(0);},[from,to]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setData(null);const timer=setTimeout(()=>fetch('/api/cost-projects/report?'+new URLSearchParams({from,to,scope,q,offset:String(offset),...(currentBook&&scope==='personal'&&bookId?{bookId}:{})}),{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);}),250);return()=>{clearTimeout(timer);c.abort();};},[from,to,scope,q,offset,currentBook,bookId]);
 return <section className="panel cost-projects"><h2>{l('分摊项目成本与净承担','Allocated project costs')}</h2><p className="muted">{l('仅统计已确认的费用项目，不包含未设置分摊的普通消费。真实钱包流水保持不变。','Includes approved cost projects only, not ordinary unallocated spending. Wallet cash flows are unchanged.')}</p>{bookId&&scope==='personal'&&<label className="check"><input type="checkbox" checked={currentBook} onChange={e=>{setCurrentBook(e.target.checked);setOffset(0);}}/>{l('仅当前账本的归属成本','Attributed costs in the current ledger only')}</label>}<div className="cost-toolbar"><label>{l('统计范围','Scope')}<select value={scope} onChange={e=>{setScope(e.target.value);setOffset(0);}}><option value="personal">{l('我的承担（跨账本）','My share across ledgers')}</option><option value="shared">{l('参与项目总额（仅共享抵减）','Participating project totals (shared offsets only)')}</option></select></label><label>{l('搜索项目','Search projects')}<input value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label></div>{error&&<p className="error" role="alert">{error}</p>}{loading&&<p role="status">{l('正在汇总…','Loading…')}</p>}{data&&<><dl className="cost-report-totals">{[[l('期间成本','Period cost'),data.totals.cost],[l('到账抵减','Received offsets'),data.totals.offset],[l('净承担','Net cost'),data.totals.net],[l('预计抵减','Expected offsets'),data.totals.expected]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{formatMoney(value)}</dd></div>)}</dl><FinanceChart chart={{id:'cost-net',title:l('每月净承担','Monthly net cost'),type:'bar',from,to,unit:deployment().currency,data:data.monthly}}/>{data.excluded.length>0&&<p className="error">{l('部分项目来源发生变化，已暂时排除：','Some projects have changed sources and are excluded: ')}{data.excluded.map((p:any)=>p.title).join(' / ')}</p>}{data.rows.map((r:any)=><button key={r.id+r.month} className="cost-project-row secondary" onClick={()=>onOpen(r.id)}><span><strong>{r.title}</strong><small>{r.month} · {r.category}</small></span><strong>{formatMoney(r.net)}</strong></button>)}{!data.rows.length&&<p>{l('此期间没有已生效的分摊项目。','No active cost projects in this period.')}</p>}<div className="cost-toolbar"><button className="secondary" disabled={!offset} onClick={()=>setOffset(v=>v-20)}>{l('上一页','Previous')}</button><span>{data.total?offset+1:0}–{Math.min(offset+20,data.total)} / {data.total}</span><button className="secondary" disabled={offset+20>=data.total} onClick={()=>setOffset(v=>v+20)}>{l('下一页','Next')}</button></div></>}</section>;
}
