'use client';
import {useEffect,useState} from 'react';
import {useI18n} from './LanguageProvider';
import {formatMoney} from '@/lib/deployment';
import {costScheduleProgress,type CostSchedule} from '@/lib/cost-schedule';
import {PagedList} from './PagedList';

// Operate: extend the existing cost surface, separating promises from money paid.
// Inherit its type, colors and responsive form grid. No extra modal or new theme.
// First viewport: next due date and status; actions reveal one inline task at a time.
// Finish: inspect desktop/mobile and hand off review and surface documentation.
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}
export function CostSchedules({onProject}:{onProject:(id:string)=>void}){
 const {locale}=useI18n(),l=(zh:string,en:string)=>locale==='en'?en:zh;
 const [rows,setRows]=useState<any[]>([]),[options,setOptions]=useState<any>(null),[books,setBooks]=useState<any[]>([]),[assets,setAssets]=useState<any[]>([]);
 const [rule,setRule]=useState<CostSchedule|null>(null),[creationId,setCreationId]=useState(''),[book,setBook]=useState(''),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[selected,setSelected]=useState<any>(null),[action,setAction]=useState(''),[history,setHistory]=useState<any[]>([]),[historyOffset,setHistoryOffset]=useState(0),[historyLoading,setHistoryLoading]=useState(false),[sourceLoading,setSourceLoading]=useState(false);
 const [account,setAccount]=useState(''),[paidDate,setPaidDate]=useState(''),[paymentMode,setPaymentMode]=useState('new'),[sources,setSources]=useState<any[]>([]),[source,setSource]=useState(''),[query,setQuery]=useState(''),[sourceOffset,setSourceOffset]=useState(0);
 useEffect(()=>{Promise.all([api('cost-projects/options'),api('books'),api('assets')]).then(([o,b,a])=>{setOptions(o);setBooks(b.filter((v:any)=>v.role!=='viewer'));setAssets(a.filter((v:any)=>v.owner_id===o.userId&&!v.archived));}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{let live=true;setLoading(true);api('cost-schedules?offset='+offset).then(v=>{if(live)setRows(v);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[offset,revision]);
 useEffect(()=>{if(action!=='history'||!selected)return;let live=true;setHistoryLoading(true);api(`cost-schedules/${selected.id}/history?offset=${historyOffset}`).then(v=>{if(live)setHistory(v);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setHistoryLoading(false);});return()=>{live=false;};},[action,selected,historyOffset]);
 useEffect(()=>{if(action!=='pay'||paymentMode!=='existing')return;let live=true;setSourceLoading(true);const timer=setTimeout(()=>api('cost-projects/sources?'+new URLSearchParams({q:query,offset:String(sourceOffset)})).then(v=>{if(live)setSources(v);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setSourceLoading(false);}),250);return()=>{live=false;clearTimeout(timer);};},[action,paymentMode,query,sourceOffset]);
 const people=options?.people.filter((p:any)=>p.family_id===rule?.familyId)||[];
 const name=(id:string)=>options?.people.find((p:any)=>p.id===id)?.name||l('我','Me');
 const update=(patch:Partial<CostSchedule>)=>setRule(v=>v?{...v,...patch}:v);
 const close=()=>{setSelected(null);setAction('');setRule(null);};
 async function run(path:string,body:any){setBusy(true);setError('');try{const result=await api('cost-schedules'+path,body);close();setRevision(v=>v+1);if(result.project_id){window.dispatchEvent(new Event('cost-payment-recorded'));onProject(result.project_id);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function open(s:any,kind:string){setSelected(s);setAction(kind);setRule(null);setBook(s.members.find((m:any)=>m.user_id===options?.userId)?.book_id||'');setAccount('');setSource('');setSources([]);setQuery('');setSourceOffset(0);setHistoryOffset(0);setHistory([]);setPaymentMode('new');setPaidDate(new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}));setError('');}
 const bookField=<label>{action==='pay'?l('付款记入账本','Record payment in ledger'):l('我的归属账本','My cost ledger')}<select required value={book} onChange={e=>setBook(e.target.value)}><option value="">{l('选择账本','Choose a ledger')}</option>{books.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>;
 return <div className="cost-section cost-schedules"><div className="cost-toolbar"><div><h3>{l('周期费用计划','Recurring cost plans')}</h3><p className="muted">{l('先定规则，到期确认实付。分摊不再次扣款；家庭转账另行结算。','Plan first, confirm the real payment when due. Allocation never charges again; family transfers settle separately.')}</p></div><button className="secondary" disabled={!options||busy} onClick={()=>{close();setCreationId(crypto.randomUUID());setBook('');setRule({title:'',category:l('房租','Rent'),familyId:null,firstDate:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),months:3,shares:[{userId:options.userId,amount:0}]});}}>{l('新建周期计划','New recurring plan')}</button></div>
 {error&&<p className="error" role="alert">{error}</p>}
 {rule?<form onSubmit={e=>{e.preventDefault();void run(action==='edit'?'/'+selected.id+'/edit':'',{id:creationId,rule,bookId:book,...(action==='edit'?{version:selected.version}:{})});}}><fieldset disabled={busy}><h4>{action==='edit'?l('编辑周期计划','Edit recurring plan'):l('周期和金额','Schedule and amounts')}</h4>{action==='edit'&&<p className="notice">{l('仅修改后续计划，历史付款与分摊保持不变。修改成员、承担金额或延长计划后，其他成员需要重新确认。','Updates future cycles only. Past payments and allocations stay unchanged. Changes to members, shares or an extension require renewed acceptance.')}</p>}<div className="form-grid"><label>{l('名称','Name')}<input required maxLength={120} value={rule.title} onChange={e=>update({title:e.target.value})}/></label><label>{l('分类','Category')}<input required value={rule.category} onChange={e=>update({category:e.target.value})}/></label><label>{l('首次付款日','First due date')}<input disabled={action==='edit'&&selected?.processed>0} required type="date" value={rule.firstDate} onChange={e=>update({firstDate:e.target.value})}/></label><label>{l('每隔几个月付款','Pay every N months')}<input disabled={action==='edit'&&selected?.processed>0} required type="number" min={1} max={120} value={rule.months} onChange={e=>update({months:Number(e.target.value)})}/></label><label>{l('结束规则','End condition')}<select value={rule.totalCycles==null?'unlimited':'limited'} onChange={e=>update({totalCycles:e.target.value==='unlimited'?null:Math.max(1,selected?.processed||0)})}><option value="unlimited">{l('持续重复','Repeat indefinitely')}</option><option value="limited">{l('指定总期数','Fixed number of cycles')}</option></select></label>{rule.totalCycles!=null&&<label>{l('总期数（含已处理）','Total cycles (including processed)')}<input required type="number" min={Math.max(1,selected?.processed||0)} max={120} value={rule.totalCycles} onChange={e=>update({totalCycles:Number(e.target.value)})}/></label>}{bookField}<label>{l('参与家庭','Family')}<select value={rule.familyId||''} onChange={e=>update({familyId:e.target.value||null,shares:[rule.shares.find(s=>s.userId===options.userId)!]})}><option value="">{l('仅自己','Just me')}</option>{[...new Map<string,string>(options.people.map((p:any)=>[p.family_id,p.family_name])).entries()].map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label></div>
 <h4>{l('每人每月承担','Each person’s monthly share')}</h4>{people.filter((p:any)=>p.id!==options.userId).map((p:any)=><label className="check" key={p.id}><input type="checkbox" checked={rule.shares.some(s=>s.userId===p.id)} onChange={e=>update({shares:e.target.checked?[...rule.shares,{userId:p.id,amount:0}]:rule.shares.filter(s=>s.userId!==p.id)})}/>{p.name}</label>)}<div className="form-grid">{rule.shares.map((s,i)=><label key={s.userId}>{name(s.userId)}<input required type="number" min="0.01" step="0.01" value={s.amount/100} onChange={e=>update({shares:rule.shares.map((v,j)=>j===i?{...v,amount:Math.round(Number(e.target.value)*100)}:v)})}/></label>)}</div>{rule.totalCycles!=null&&rule.firstDate&&rule.months>0&&<p className="notice">{l('覆盖结束日（不含当天）：','Coverage ends (exclusive): ')}{costScheduleProgress(rule,0).coverageEnd} · {l('跳过的账期也计入总期数。','Skipped cycles also count toward the limit.')}</p>}<p>{l('每期付款','Payment per cycle')} <strong>{formatMoney(rule.shares.reduce((n,s)=>n+s.amount,0)*rule.months)}</strong></p><p className="muted">{l('成本从付款日所在自然月起等额归属。其他成员需接受规则并选择自己的账本。现在不需要选择钱包，不会入账。','Costs are allocated equally from the due month. Other members must accept and choose their own ledger. No wallet is needed and no payment is recorded now.')}</p><div className="cost-toolbar"><button type="submit">{busy?l('保存中…','Saving…'):action==='edit'?l('保存计划修改','Save changes'):l('保存计划，不扣款','Save plan without payment')}</button><button type="button" className="text-button" onClick={close}>{l('取消','Cancel')}</button></div></fieldset></form>:selected?<div><div className="cost-toolbar"><h4>{selected.rule.title} · {selected.next_date}</h4><button className="text-button" disabled={busy} onClick={close}>{l('返回计划','Back to plans')}</button></div>
 {action==='respond'&&<form onSubmit={e=>{e.preventDefault();void run('/'+selected.id+'/respond',{version:selected.version,accept:true,bookId:book});}}><p>{l('接受以下规则，后续付款确认后自动归属到你选择的账本，不产生额外扣款。','Accept these rules to attribute future confirmed payments to your selected ledger, without another wallet charge.')}</p><p><strong>{l('每','Every ')} {selected.rule.months} {l('个月付款，每期',' months, per cycle ')} {formatMoney(selected.rule.shares.reduce((n:number,s:any)=>n+s.amount,0)*selected.rule.months)}</strong></p><p className="muted">{l('分类：','Category: ')}{selected.rule.category} · {l('成本从到期日所在自然月起，按上述周期的月数等额分摊。','Costs are allocated equally over these calendar months, starting with the due month.')}</p><p className="notice">{selected.totalCycles?`${l('总期数','Total cycles')}: ${selected.totalCycles} · ${l('覆盖至','Coverage ends')}: ${selected.coverageEnd}`:l('持续重复，未设结束期数','Repeats indefinitely; no cycle limit')}</p><div className="cost-accept-shares"><PagedList items={selected.rule.shares}>{(s:any)=><div><span>{name(s.userId)}</span><strong>{formatMoney(s.amount)}<small> / {l('月','month')}</small></strong></div>}</PagedList></div>{bookField}<div className="cost-toolbar"><button disabled={busy}>{l('接受规则并保存账本','Accept and save ledger')}</button><button type="button" className="text-button" disabled={busy} onClick={()=>run('/'+selected.id+'/respond',{version:selected.version,accept:false})}>{l('撤回我的同意','Withdraw my acceptance')}</button></div></form>}
 {action==='pay'&&<form onSubmit={e=>{e.preventDefault();void run('/'+selected.id+'/confirm',{version:selected.version,dueDate:selected.next_date,bookId:paymentMode==='existing'?sources.find(s=>s.id===source)?.book_id:book,...(paymentMode==='existing'?{transactionId:source}:{accountId:account,paidDate})});}}><p className="notice">{l('仅在实际付款后确认。若已通过识图或手动记账，请关联原付款，避免重复记账。','Confirm only after payment. If already recorded, link the existing payment to avoid duplicates.')}</p><p>{l('本期金额','Cycle amount')} <strong>{formatMoney(selected.rule.shares.reduce((n:number,s:any)=>n+s.amount,0)*selected.rule.months)}</strong></p><label>{l('付款记录','Payment record')}<select value={paymentMode} onChange={e=>setPaymentMode(e.target.value)}><option value="new">{l('已付款，尚未记账','Paid, not yet recorded')}</option><option value="existing">{l('关联已记账的付款','Link a recorded payment')}</option></select></label>{paymentMode==='new'?<div className="form-grid">{bookField}<label>{l('实际付款钱包','Actual payment wallet')}<select required value={account} onChange={e=>setAccount(e.target.value)}><option value="">{l('请选择','Choose')}</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{l('实际付款日期','Actual payment date')}<input required type="date" value={paidDate} onChange={e=>setPaidDate(e.target.value)}/></label></div>:<><label>{l('搜索原付款','Search recorded payments')}<input value={query} onChange={e=>{setQuery(e.target.value);setSourceOffset(0);setSource('');}}/></label>{sourceLoading?<p role="status">{l('正在查找…','Searching…')}</p>:sources.slice(0,20).map(s=><label className="check" key={s.id}><input required type="radio" name="cost-payment" checked={source===s.id} onChange={()=>setSource(s.id)}/>{s.title||s.payee} · {s.date} · {formatMoney(s.amount)}</label>)}<div className="cost-toolbar"><button type="button" className="secondary" disabled={sourceLoading||!sourceOffset} onClick={()=>{setSource('');setSourceOffset(v=>v-20);}}>{l('上一页','Previous')}</button><span>{sources[0]?.total?sourceOffset+1:0}–{Math.min(sourceOffset+20,sources[0]?.total||0)} / {sources[0]?.total||0}</span><button type="button" className="secondary" disabled={sourceLoading||sources.length<=20} onClick={()=>{setSource('');setSourceOffset(v=>v+20);}}>{l('下一页','Next')}</button></div></>}<div className="cost-toolbar"><button disabled={busy||paymentMode==='existing'&&!source}>{busy?l('保存中…','Saving…'):l('确认实际付款并分摊','Confirm payment and allocate')}</button></div></form>}
 {action==='history'&&<>{historyLoading&&<p role="status">{l('正在加载账期…','Loading cycles…')}</p>}<PagedList items={historyLoading?[]:history} pageSize={20}>{(h:any)=><div className="cost-edit-row"><span>{h.due_date}</span>{h.project_id?<button className="secondary" onClick={()=>onProject(h.project_id)}>{l('查看分摊与结算','View allocation and settlement')}</button>:<span>{l('已跳过','Skipped')}</span>}</div>}</PagedList>{!historyLoading&&!error&&!history.length&&<p>{l('尚无已处理账期','No processed cycles yet')}</p>}<div className="cost-toolbar"><button className="secondary" disabled={historyLoading||!historyOffset} onClick={()=>setHistoryOffset(v=>v-20)}>{l('上一页','Previous')}</button><span>{history[0]?.total?historyOffset+1:0}–{Math.min(historyOffset+20,history[0]?.total||0)} / {history[0]?.total||0}</span><button className="secondary" disabled={historyLoading||historyOffset+20>=(history[0]?.total||0)} onClick={()=>setHistoryOffset(v=>v+20)}>{l('下一页','Next')}</button></div></>}
 </div>:<>{loading?<p role="status">{l('加载中…','Loading…')}</p>:rows.map(s=><div className="cost-edit-row cost-schedule-card" key={s.id}><div className="cost-schedule-summary"><strong>{s.rule.title}</strong><small>{s.completed?l('全部账期已处理','All cycles processed'):s.next_date} · {s.completed?l('已结束','Completed'):s.paused?l('已暂停','Paused'):s.members.some((m:any)=>!m.accepted)?l('待成员同意','Awaiting acceptance'):s.due?l('到期待确认付款','Due: confirm payment'):l('未到期，不扣款','Upcoming, no payment recorded')}</small><div className="cost-schedule-amount"><small>{l('每期付款','Payment per cycle')}</small><b> {formatMoney(s.rule.shares.reduce((n:number,p:any)=>n+p.amount,0)*s.rule.months)}</b><small>{l('每','Every ')}{s.rule.months}{l('个月一次',' months')}</small></div><small className="cost-schedule-progress">{s.totalCycles?`${l('已处理','Processed')} ${s.processed} / ${s.totalCycles} · ${l('覆盖至','Coverage ends')} ${s.coverageEnd}`:l('持续重复','Repeats indefinitely')}</small><div className="cost-schedule-shares">{s.rule.shares.map((p:any)=><span key={p.userId}>{s.members.find((m:any)=>m.user_id===p.userId)?.name||name(p.userId)}<strong>{formatMoney(p.amount)}<small> / {l('月','month')}</small></strong><small>{s.members.find((m:any)=>m.user_id===p.userId)?.accepted?l('已确认','Accepted'):l('待确认','Awaiting acceptance')}</small></span>)}</div></div><div className="cost-toolbar cost-schedule-actions"><button className="secondary" disabled={busy} onClick={()=>open(s,'respond')}>{l('我的归属与确认','My ledger and acceptance')}</button>{s.owner_id===options?.userId&&<><button className="secondary" disabled={busy} onClick={()=>{open(s,'edit');setRule({...s.rule});}}>{l('编辑计划','Edit plan')}</button><button disabled={busy||!s.due||s.members.some((m:any)=>!m.accepted)} onClick={()=>open(s,'pay')}>{l('确认本期付款','Confirm this payment')}</button><button className="text-button" disabled={busy} onClick={()=>run('/'+s.id+'/pause',{version:s.version,paused:!s.paused})}>{s.paused?l('恢复','Resume'):l('暂停','Pause')}</button></>}<button className="text-button" onClick={()=>open(s,'history')}>{l('账期记录','Cycle history')}</button></div></div>)}{!loading&&!rows.length&&<p className="muted">{l('尚无周期计划。可提前规划房租、保险或服务费用，到期再确认实付。','No recurring plans. Plan rent, insurance or services now and confirm payment when due.')}</p>}<div className="cost-toolbar"><button className="secondary" disabled={!offset||loading} onClick={()=>setOffset(v=>v-20)}>{l('上一页','Previous')}</button><span>{offset/20+1} / {Math.max(1,Math.ceil((rows[0]?.total||0)/20))}</span><button className="secondary" disabled={loading||offset+20>=(rows[0]?.total||0)} onClick={()=>setOffset(v=>v+20)}>{l('下一页','Next')}</button></div></>}
 </div>;
}
