'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Plus,Search,Trash2} from 'lucide-react';
import {useI18n} from './LanguageProvider';
import {formatMoney} from '@/lib/deployment';
import {calculateCostPlan,type CostPlan} from '@/lib/cost-attribution';
import {PagedList} from './PagedList';
import './cost-projects.css';

async function request(path:string,method='GET',body?:unknown){const r=await fetch('/api/cost-projects'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}
type Source={id:string;title:string;payee:string;date:string;amount:number;book_name:string};
type Options={userId:string;people:{id:string;name:string;family_id:string;family_name:string}[]};
function SourcePicker({kind,onChoose,onClose}:{kind:'expense'|'income';onChoose:(v:Source)=>void;onClose:()=>void}){
 const {locale}=useI18n(),l=(zh:string,en:string)=>locale==='en'?en:zh;
 const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[rows,setRows]=useState<Source[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;setLoading(true);const timer=setTimeout(()=>request('/sources?'+new URLSearchParams({q,kind,offset:String(offset)})).then(d=>{if(live){setRows(d);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);}),250);return()=>{live=false;clearTimeout(timer);};},[q,kind,offset]);
 return <section className="cost-source-picker" aria-label={l('选择原始账单','Choose an existing transaction')}><div className="cost-toolbar"><h4>{kind==='income'?l('关联工资或其他收入','Link salary or other income'):l('关联已支付账单','Link an existing payment')}</h4><button type="button" className="text-button" onClick={onClose}>{l('关闭','Close')}</button></div><label><Search size={16}/>{l('跨可编辑账本搜索本人流水','Search your transactions across editable ledgers')}<input autoFocus value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label>{error&&<p role="alert" className="error">{error}</p>}{loading?<p role="status">{l('正在查找…','Searching…')}</p>:rows.slice(0,20).map(r=><button type="button" className="cost-source-row secondary" key={r.id} onClick={()=>onChoose(r)}><span><strong>{r.title||r.payee}</strong><small>{r.date} · {r.book_name}</small></span><b>{formatMoney(r.amount)}</b></button>)}{!loading&&!rows.length&&<p>{l('没有符合条件的账单。请先完成真实收付款记账。','No matching transactions. Record the actual payment or income first.')}</p>}<div className="cost-toolbar"><button className="secondary" type="button" disabled={!offset||loading} onClick={()=>setOffset(v=>Math.max(0,v-20))}>{l('上一页','Previous')}</button><span>{offset/20+1}</span><button className="secondary" type="button" disabled={rows.length<=20||loading} onClick={()=>setOffset(v=>v+20)}>{l('下一页','Next')}</button></div></section>;
}
function PersonalOffsets({entries,userId,month,busy,onSave}:{entries:CostPlan['offsets'];userId:string;month:string;busy:boolean;onSave:(entries:CostPlan['offsets'])=>void}){
 const {locale}=useI18n(),l=(zh:string,en:string)=>locale==='en'?en:zh;
 const [items,setItems]=useState(entries),[picker,setPicker]=useState<number|null>(null),[editing,setEditing]=useState(false);
 const update=(i:number,patch:Partial<CostPlan['offsets'][number]>)=>setItems(old=>old.map((o,j)=>i===j?{...o,...patch}:o));
 return <div className="cost-section"><h3>{l('我的收入抵减','My income offsets')}</h3><p className="muted">{l('只改变我的净承担，不改变其他人的分担。可关联工资中的部分金额；默认不共享收入金额和来源。原收入变化后，抵减暂按预计处理，请重新核对保存。','Changes only your net cost, not anyone else’s share. Link part of your salary or other income; amounts and sources are private by default. Changed income becomes an estimate until reviewed.')}</p>{!editing?<button className="secondary" disabled={busy} onClick={()=>setEditing(true)}>{l('管理我的抵减','Manage my offsets')} ({entries.length})</button>:<><PagedList items={items}>{(o,i)=><div className="cost-offset"><div className="form-grid"><label>{l('归属月份','Cost month')}<input type="month" value={o.month} onChange={e=>update(i,{month:e.target.value})}/></label><label>{l('抵减金额','Offset amount')}<input type="number" min="0.01" step="0.01" value={o.amount/100} onChange={e=>update(i,{amount:Math.round(Number(e.target.value)*100)})}/></label></div><div className="cost-toolbar"><button className="secondary" onClick={()=>setPicker(i)}>{o.transactionId?l('已关联收入 · 更换','Income linked · change'):l('关联到账收入','Link received income')}</button>{o.transactionId&&<button className="text-button" onClick={()=>update(i,{transactionId:null})}>{l('改为预计','Mark expected')}</button>}<label className="check"><input type="checkbox" checked={o.shared} onChange={e=>update(i,{shared:e.target.checked})}/>{l('共享抵减金额（不共享收入来源）','Share offset amount, not income source')}</label><button className="text-button" onClick={()=>setItems(old=>old.filter((_,j)=>i!==j))}>{l('移除','Remove')}</button></div></div>}</PagedList>{picker!==null&&<SourcePicker kind="income" onClose={()=>setPicker(null)} onChoose={s=>{update(picker,{transactionId:s.id});setPicker(null);}}/>}<div className="cost-toolbar"><button className="secondary" onClick={()=>setItems(old=>[...old,{id:crypto.randomUUID(),userId,month,transactionId:null,amount:0,shared:false}])}>{l('添加抵减','Add offset')}</button><button disabled={busy||items.some(o=>!o.amount||!o.month)} onClick={()=>onSave(items)}>{l('保存我的抵减','Save my offsets')}</button><button className="text-button" onClick={()=>{setEditing(false);setItems(entries);}}>{l('取消','Cancel')}</button></div></>}</div>;
}
export function CostProjects({month,seed,onClearSeed,initialId,onClearTarget}:{initialId?:string;onClearTarget?:()=>void;month:string;seed?:{id:string;amount:number;date:string};onClearSeed?:()=>void}){
 const {locale}=useI18n(),l=(zh:string,en:string)=>locale==='en'?en:zh;
 const creationId=useRef('');
 const [movements,setMovements]=useState<any[]>([]);
 const [options,setOptions]=useState<Options|null>(null),[list,setList]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[plan,setPlan]=useState<CostPlan|null>(null),[picker,setPicker]=useState<'expense'|number|null>(null),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[archived,setArchived]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[previewing,setPreviewing]=useState(false),[sourceNames,setSourceNames]=useState<Record<string,string>>({}),[movement,setMovement]=useState(''),[settlementAmount,setSettlementAmount]=useState('');
 useEffect(()=>{request('/options').then(setOptions).catch(e=>setError(e.message));},[]);
 useEffect(()=>{let live=true;setLoading(true);const timer=setTimeout(()=>request('?'+new URLSearchParams({q,offset:String(offset),archived:String(archived)})).then(d=>{if(live)setList(d);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);}),200);return()=>{live=false;clearTimeout(timer);};},[q,offset,archived,revision]);
 const blank=(initial?:typeof seed):CostPlan=>{creationId.current=crypto.randomUUID();return ({title:'',category:l('其他','Other'),familyId:null,sources:initial?[{transactionId:initial.id,amount:initial.amount}]:[],coverageStart:initial?.date||month+'-01',coverageEnd:new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),1)).toISOString().slice(0,10),mode:'monthly',startMonth:month,months:1,periods:[],shares:[{userId:options!.userId,amount:initial?.amount||0}],offsets:[]});};
 useEffect(()=>{if(seed&&options){setSelected(null);setPlan(blank(seed));setPreviewing(false);onClearSeed?.();}},[seed,options]);
 useEffect(()=>{if(initialId){void open(initialId);onClearTarget?.();}},[initialId]);
 useEffect(()=>{setMovement('');setSettlementAmount('');setMovements([]);if(selected?.id)request('/'+selected.id+'/movements').then(setMovements).catch(e=>setError(e.message));},[selected?.id]);
 const people=options?.people.filter(p=>p.family_id===plan?.familyId)||[];
 const person=(id:string)=>options?.people.find(p=>p.id===id)?.name||selected?.members?.find((m:any)=>m.user_id===id)?.name||(id===options?.userId?l('我','Me'):id.slice(0,8));
 const set=(patch:Partial<CostPlan>)=>{setPlan(p=>p?{...p,...patch}:p);setPreviewing(false);setError('');};
 let preview:ReturnType<typeof calculateCostPlan>|null=null,problem='';if(plan)try{preview=calculateCostPlan(plan);}catch(e){problem=(e as Error).message;}
 const total=plan?.sources.reduce((n,s)=>n+s.amount,0)||0;
 const cents=(value:string)=>Math.round(Number(value)*100);
 async function open(id:string){setBusy(true);setError('');try{const d=await request('/'+id);setSelected(d);setSourceNames(d.sourceNames||{});setPlan(null);setNotice('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function operation(path:string,body:any){if(!selected)return;setBusy(true);setError('');try{await request('/'+selected.id+path,'POST',{version:selected.version,...body});await open(selected.id);setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){if(!plan||!preview)return;setBusy(true);setError('');try{const result=await request(selected?'/'+selected.id:'',selected?'PUT':'POST',{id:creationId.current,plan,version:selected?.version});await open(result.id||selected.id);setRevision(v=>v+1);setNotice(l('费用规则已保存，未新增钱包扣款。','Cost rules saved. No additional wallet payment was created.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel cost-projects"><div className="cost-toolbar"><div><h2>{l('费用归属与分担','Cost allocation & sharing')}</h2><p className="muted">{l('付款只记一次，费用按期、按人查看。个账与公账均可关联。','Record the payment once; attribute costs by period and person, from private or shared ledgers.')}</p></div>{(selected||plan)?<button type="button" className="secondary" disabled={busy} onClick={()=>{setSelected(null);setPlan(null);setPicker(null);setError('');setNotice('');}}><ArrowLeft size={16}/>{l('返回项目','Back to projects')}</button>:<button disabled={!options||busy} type="button" onClick={()=>{setPlan(blank());setPreviewing(false);setError('');}}><Plus size={18}/>{l('新建费用项目','New cost project')}</button>}</div>
 {error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 {!selected&&!plan&&<><div className="cost-toolbar"><label>{l('搜索费用项目','Search cost projects')}<input value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></label><label className="check"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setOffset(0);}}/>{l('查看已归档','Show archived')}</label></div>{loading?<p role="status">{l('正在加载…','Loading…')}</p>:list.length?list.map(p=><button className="cost-project-row secondary" key={p.id} disabled={busy} onClick={()=>open(p.id)}><strong>{p.title}</strong><span>{p.pending?l('待成员确认','Awaiting approval'):l('已生效','Active')}</span></button>):<p className="empty">{l('关联一笔已支付账单，设置它属于哪些月份、由谁承担。不会再次扣款。','Link an existing payment and choose its periods and participants. This does not charge a wallet again.')}</p>}<div className="cost-toolbar"><button className="secondary" disabled={!offset||loading} onClick={()=>setOffset(v=>v-20)}>{l('上一页','Previous')}</button><span>{offset/20+1} / {Math.max(1,Math.ceil((list[0]?.total||0)/20))}</span><button className="secondary" disabled={loading||offset+20>=(list[0]?.total||0)} onClick={()=>setOffset(v=>v+20)}>{l('下一页','Next')}</button></div></>}
 {plan&&<form onSubmit={e=>{e.preventDefault();if(previewing)void save();else setPreviewing(true);}}><fieldset disabled={busy}>
 <div className="cost-section"><h3>{l('原始付款','Original payments')}</h3><div className="form-grid"><label>{l('费用名称','Project name')}<input required maxLength={120} value={plan.title} onChange={e=>set({title:e.target.value})}/></label><label>{l('费用分类','Category')}<input required maxLength={60} value={plan.category} onChange={e=>set({category:e.target.value})}/></label></div><PagedList items={plan.sources}>{(s,i)=><div className="cost-edit-row"><span>{sourceNames[s.transactionId]||l('已关联付款','Linked payment')}<small>{s.transactionId.slice(0,8)}</small></span><label>{l('参与分摊金额','Amount to allocate')}<input type="number" min="0.01" step="0.01" required value={s.amount/100} onChange={e=>set({sources:plan.sources.map((v,j)=>j===i?{...v,amount:cents(e.target.value)}:v)})}/></label><button type="button" className="text-button" aria-label={l('移除付款关联','Remove payment link')} onClick={()=>set({sources:plan.sources.filter((_,j)=>j!==i)})}><Trash2 size={18}/></button></div>}</PagedList><button type="button" className="secondary" onClick={()=>setPicker('expense')}><Plus size={16}/>{l('查找已支付账单','Find a payment')}</button><p>{l('本项目原始费用','Original project cost')} <strong>{formatMoney(total)}</strong></p></div>
 <div className="cost-section"><h3>{l('期间归属','Cost periods')}</h3><div className="form-grid"><label>{l('实际覆盖开始日','Coverage starts')}<input type="date" required value={plan.coverageStart} onChange={e=>set({coverageStart:e.target.value})}/></label><label>{l('覆盖结束日（不含当天）','Coverage ends (exclusive)')}<input type="date" required value={plan.coverageEnd} onChange={e=>set({coverageEnd:e.target.value})}/></label><label>{l('分摊方式','Allocation method')}<select value={plan.mode} onChange={e=>set({mode:e.target.value as CostPlan['mode']})}><option value="monthly">{l('指定自然月等额','Equal calendar months')}</option><option value="daily">{l('真实覆盖期按天','Daily over coverage')}</option><option value="custom">{l('自定义期间金额','Custom periods')}</option></select></label>{plan.mode==='monthly'&&<><label>{l('归属起始月份','First cost month')}<input type="month" required value={plan.startMonth} onChange={e=>set({startMonth:e.target.value})}/></label><label>{l('分摊月数','Number of months')}<input type="number" min={1} max={1200} required value={plan.months} onChange={e=>set({months:Number(e.target.value)})}/></label></>}</div>{plan.mode==='custom'&&<><PagedList items={plan.periods}>{(p,i)=><div className="cost-edit-row"><label>{l('开始','Start')}<input type="date" required value={p.start} onChange={e=>set({periods:plan.periods.map((v,j)=>j===i?{...v,start:e.target.value}:v)})}/></label><label>{l('结束（不含当天）','End (exclusive)')}<input type="date" required value={p.end} onChange={e=>set({periods:plan.periods.map((v,j)=>j===i?{...v,end:e.target.value}:v)})}/></label><label>{l('金额','Amount')}<input type="number" step="0.01" min={0} value={p.amount/100} onChange={e=>set({periods:plan.periods.map((v,j)=>j===i?{...v,amount:cents(e.target.value)}:v)})}/></label><button type="button" className="text-button" onClick={()=>set({periods:plan.periods.filter((_,j)=>j!==i)})}>{l('移除','Remove')}</button></div>}</PagedList><button type="button" className="secondary" onClick={()=>set({periods:[...plan.periods,{start:plan.coverageStart,end:plan.coverageEnd,amount:total}]})}>{l('添加期间','Add period')}</button></>}</div>
 <div className="cost-section"><h3>{l('成员承担','Participants')}</h3><label>{l('选人范围（不改变记入账本）','Choose participants (does not move the transaction)')}<select disabled={!!selected} value={plan.familyId||''} onChange={e=>set({familyId:e.target.value||null,shares:[{userId:options!.userId,amount:total}]})}><option value="">{l('仅自己','Just me')}</option>{[...new Map(options?.people.map(p=>[p.family_id,p.family_name])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>{!selected&&people.filter(p=>p.id!==options?.userId).map(p=><label className="check" key={p.id}><input type="checkbox" checked={plan.shares.some(s=>s.userId===p.id)} onChange={e=>set({shares:e.target.checked?[...plan.shares,{userId:p.id,amount:0}]:plan.shares.filter(s=>s.userId!==p.id)})}/>{p.name}</label>)}<button type="button" className="text-button" onClick={()=>set({shares:plan.shares.map((s,i)=>({...s,amount:Math.floor(total/plan.shares.length)+(i<total%plan.shares.length?1:0)}))})}>{l('按当前成员均分','Split equally')}</button><div className="form-grid">{plan.shares.map((s,i)=><label key={s.userId}>{person(s.userId)} · {l('全期承担','Total share')}<input type="number" step="0.01" min={0} required value={s.amount/100} onChange={e=>set({shares:plan.shares.map((v,j)=>j===i?{...v,amount:cents(e.target.value)}:v)})}/></label>)}</div><p className="muted">{l('其他成员须确认分担。私人账单详情和钱包余额不随邀请共享。','Other participants must approve their shares. Private transaction details and wallet balances are not shared.')}</p></div>
 <div className="cost-section"><h3>{l('收入抵减（可选）','Income offsets (optional)')}</h3><p className="muted">{l('工资等任意收入可关联部分金额。预计收入不计入已实现净承担。','Use part of any income, including salary. Expected income does not reduce realized costs.')}</p><PagedList items={plan.offsets}>{(o,i)=><div className="cost-offset"><div className="form-grid"><label>{l('归属月份','Cost month')}<input type="month" required value={o.month} onChange={e=>set({offsets:plan.offsets.map((v,j)=>j===i?{...v,month:e.target.value}:v)})}/></label><label>{l('抵减金额','Offset amount')}<input type="number" min="0.01" step="0.01" required value={o.amount/100} onChange={e=>set({offsets:plan.offsets.map((v,j)=>j===i?{...v,amount:cents(e.target.value)}:v)})}/></label><label>{l('受益人','Beneficiary')}<select value={o.userId} onChange={e=>set({offsets:plan.offsets.map((v,j)=>j===i?{...v,userId:e.target.value,shared:e.target.value!==options?.userId||v.shared}:v)})}>{plan.shares.map(s=><option key={s.userId} value={s.userId}>{person(s.userId)}</option>)}</select></label></div><div className="cost-toolbar"><button type="button" className="secondary" onClick={()=>setPicker(i)}>{o.transactionId?l('已关联到账收入 · 更换','Income linked · change'):l('关联实际到账收入','Link received income')}</button>{o.transactionId&&<button type="button" className="text-button" onClick={()=>set({offsets:plan.offsets.map((v,j)=>j===i?{...v,transactionId:null}:v)})}>{l('改为预计','Mark expected')}</button>}<label className="check"><input type="checkbox" checked={o.shared} onChange={e=>set({offsets:plan.offsets.map((v,j)=>j===i?{...v,shared:e.target.checked}:v)})}/>{l('向参与者共享抵减金额','Share offset amount')}</label><button type="button" className="text-button" onClick={()=>set({offsets:plan.offsets.filter((_,j)=>j!==i)})}>{l('移除','Remove')}</button></div><small>{o.transactionId?(sourceNames[o.transactionId]||l('实际收入关联','Received income linked')):l('预计，尚未计入实际抵减','Expected, not included in realized offsets')}</small></div>}</PagedList><button type="button" className="secondary" onClick={()=>set({offsets:[...plan.offsets,{id:crypto.randomUUID(),transactionId:null,userId:options!.userId,month:plan.startMonth,amount:0,shared:false}]})}><Plus size={16}/>{l('添加抵减','Add offset')}</button></div>
 {picker!==null&&<SourcePicker kind={picker==='expense'?'expense':'income'} onClose={()=>setPicker(null)} onChoose={s=>{setSourceNames(n=>({...n,[s.id]:s.title||s.payee}));if(picker==='expense'){set({title:plan.title||s.title||s.payee,sources:[...plan.sources,{transactionId:s.id,amount:s.amount}],...(plan.shares.length===1?{shares:[{...plan.shares[0],amount:total+s.amount}]}:{})});}else{set({offsets:plan.offsets.map((o,i)=>i===picker?{...o,transactionId:s.id}:o)});}setPicker(null);}}/>}
 {previewing&&<div className="cost-section"><h3>{l('确认预览','Review before saving')}</h3>{problem?<p role="alert" className="error">{problem}</p>:preview&&<><p className="notice">{l('本次仅更新费用分析，不新增收入或扣款。','This updates cost attribution only. No income or payment is created.')}</p><PagedList items={preview.periods}>{p=><div className="cost-period"><strong>{p.start} → {p.end}</strong><b>{formatMoney(p.amount)}</b><div>{p.shares.map(s=><span key={s.userId}>{person(s.userId)} {formatMoney(s.amount)}</span>)}</div></div>}</PagedList></>}</div>}
 <div className="cost-toolbar"><button type="submit" disabled={busy||previewing&&!preview}>{busy?l('正在保存…','Saving…'):previewing?l('确认保存规则','Confirm cost rules'):l('预览分摊结果','Preview allocation')}</button><button type="button" className="secondary" onClick={()=>{setPlan(null);setPicker(null);}}>{l('取消编辑','Cancel editing')}</button></div></fieldset></form>}
 {selected&&!plan&&<><div className="cost-toolbar"><div><h3>{selected.title}</h3><p>{selected.coverageStart} → {selected.coverageEnd} · {l('原始费用','Original cost')} {formatMoney(selected.total)}</p></div>{selected.ownerId===options?.userId&&<><button className="secondary" disabled={busy||selected.archived} onClick={()=>{setPlan(selected.proposedPlan||selected.plan);setPreviewing(false);}}>{l('编辑规则','Edit rules')}</button><button className="text-button" disabled={busy} onClick={()=>operation('/archive',{archived:!selected.archived})}>{selected.archived?l('恢复项目','Restore project'):l('归档项目','Archive project')}</button></>}</div>{!selected.valid&&<p role="alert" className="error">{l('来源已变化，请所有者核对后重新保存。以下是原规则，不作为当前有效统计。','A source changed. The owner must review it. These are previous rules, not current valid totals.')}</p>}{selected.pending&&!selected.archived&&<div className="notice"><p>{l('存在待确认的分担规则；已生效版本在确认完成前保持不变。','A proposal awaits approval. The current agreed version remains effective until approval.')}</p><PagedList items={selected.proposedPeriods||[]}>{(p:any)=><p>{p.start} · {p.shares.map((s:any)=>`${person(s.userId)} ${formatMoney(s.amount)}`).join(' / ')}</p>}</PagedList><PagedList items={selected.proposedOffsets||[]}>{(o:any)=><p>{o.month} · {person(o.userId)} · {o.realized?l('到账抵减','Received offset'):l('预计抵减','Expected offset')} {formatMoney(o.amount)}</p>}</PagedList><button disabled={busy} onClick={()=>operation('/respond',{accept:true})}>{l('接受本版分担','Accept this version')}</button><button className="secondary" disabled={busy} onClick={()=>operation('/respond',{accept:false})}>{l('拒绝本版分担','Reject this version')}</button></div>}
 <div className="cost-section"><h3>{l('我的月度承担','My monthly costs')}</h3><p className="muted">{l('分摊记录不扣钱包；未到账抵减单独显示。','Allocation does not charge your wallet. Expected offsets are shown separately.')}</p><PagedList items={selected.personal}>{(r:any)=><div className="cost-period"><strong>{r.month}</strong><dl><div><dt>{l('承担','Share')}</dt><dd>{formatMoney(r.cost)}</dd></div><div><dt>{l('到账抵减','Received offsets')}</dt><dd>{formatMoney(r.offset)}</dd></div><div><dt>{l('净承担','Net cost')}</dt><dd><strong>{formatMoney(r.net)}</strong></dd></div>{r.expected>0&&<div><dt>{l('预计净承担','Projected net cost')}</dt><dd>{formatMoney(r.projected)}</dd></div>}</dl></div>}</PagedList></div>
 {options&&!selected.archived&&<PersonalOffsets key={selected.id+':'+selected.version} entries={selected.personalOffsets||[]} userId={options.userId} month={selected.coverageStart.slice(0,7)} busy={busy} onSave={entries=>operation('/personal-offsets',{entries})}/>}
 <div className="cost-section"><h3>{l('全项目结算','Whole-project settlement')}</h3>{selected.settlement.map((s:any)=><p key={s.userId}>{person(s.userId)} · {s.balance>=0?l('待收回','To receive'):l('待补付','To pay')} <strong>{formatMoney(Math.abs(s.balance))}</strong></p>)}<p className="muted">{l('只关联参与人之间已经确认的真实转账，不再次扣款。','Link an already confirmed transfer between participants. This does not create another payment.')}</p><div className="form-grid"><label>{l('已确认的家庭转账','Confirmed family transfer')}<select value={movement} onChange={e=>{setMovement(e.target.value);const m=movements.find(m=>m.id===e.target.value);setSettlementAmount(m?String(m.amount/100):'');}}><option value="">{l('选择已有转账','Choose an existing transfer')}</option>{movements.map(m=><option key={m.id} value={m.id}>{String(m.date).slice(0,10)} · {m.sender} → {m.recipient} · {formatMoney(m.amount)}</option>)}</select></label><label>{l('用于本项目的金额','Amount for this project')}<input type="number" min="0.01" step="0.01" value={settlementAmount} onChange={e=>setSettlementAmount(e.target.value)}/></label></div><button className="secondary" disabled={busy||!selected.active||!selected.valid||!movement||!Number(settlementAmount)} onClick={()=>operation('/settlements',{movementId:movement,amount:cents(settlementAmount)})}>{l('关联已有结算','Link settlement')}</button></div>
 <div className="cost-section"><h3>{l('变更记录','Change history')}</h3><PagedList items={selected.changes}>{(c:any)=><p>{({personal_offsets:l('个人抵减更新','Personal offsets updated'),created:l('创建','Created'),accepted:l('接受','Accepted'),rejected:l('拒绝','Rejected'),revised:l('修订','Revised'),settlement:l('关联结算','Settlement linked'),archive:l('归档状态变更','Archive status changed')} as Record<string,string>)[c.operation]||c.operation} · v{c.version} · {new Date(c.created_at).toLocaleString(locale)}</p>}</PagedList></div></>}
 </section>;
}
