'use client';
import {changeMemorySelection,resolveMemoryField} from '@/lib/memory-fields';
import {MemorySuggestions} from './MemorySuggestions';
import {ReceiptOriginHint} from './ReceiptOriginHint';
import {SceneFields} from './SceneFields';
import type {EntryScene} from '@/lib/entry-scene';
import type {ManagedBook} from './ManagementPages';
import {ActivitySelect} from './ActivitySelect';
import {DateField} from './DateField';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {FormSelect} from './FormSelect';

import {TransactionPhotos} from './TransactionPhotos';
import {VerificationConfirm} from './VerificationConfirm';
import {accountLabel,type AccountIdentity} from '@/lib/accounts';
import {LineItemsEditor} from './LineItems';
import type {LineItem} from '@/lib/line-items';
import {useContext,useState} from 'react';
import {VisualSelect,CategoryIcons} from './VisualSelect';
import {purchaseDefaults,purchaseFromRow} from '@/lib/purchase-memory';
import {RefundPicker} from './RefundPicker';
import {amountToCents} from '@/server/model';
import type {CategorySuggestion} from '@/lib/category-learning';
export type Draft={memorySuggestions?:import("@/lib/memory").MemorySuggestion[];activityId?:string|null;categorySource?:'explicit'|'model';categorySuggestion?:CategorySuggestion;walletCandidates?:string[];walletMatch?:'funding'|'channel';receiptOrigin?:import('@/lib/receipt-origin').ReceiptOrigin;scene?:EntryScene;targetBook?:string;title?:string;photoIds?:string[];retainReceipts?:boolean;verificationReason?:string;attachmentIds?:string[];lineItems?:LineItem[];id:string;accountId:string;targetId?:string|null;kind:'income'|'expense'|'transfer'|'refund';amount:number;date:string;payee:string;category:string;note:string;externalId?:string;platform?:string;orderId?:string;product?:string;occurredAt?:string;source?:string;refundOf?:string|null;status?:string;action?:'create'|'skip'|'merge';mergeId?:string;mergeVersion?:number;matches?:{record:Original;reason:string}[];refundCandidates?:Original[];missing?:string[]};
export type Original={id:string;kind:string;amount:number;date:string;payee:string;product?:string;version?:number};
export function DraftReview({book,books,drafts,setDrafts,accounts,originals,busy,onReview,onSave}:{book:string;books:ManagedBook[];drafts:Draft[];setDrafts:(d:Draft[])=>void;accounts:(AccountIdentity&{id:string})[];originals:Original[];busy:boolean;onReview:()=>void;onSave:()=>void}){const {t:tr,locale}=useI18n();
 const [uploading,setUploading]=useState(0);
 const categories=useContext(CategoryIcons);
 const change=(id:string,patch:Partial<Draft>)=>setDrafts(drafts.map(d=>{if(d.id!==id)return d;const next={...d,...patch};if(['kind','payee','scene','title','product','lineItems'].some(key=>Object.prototype.hasOwnProperty.call(patch,key)))delete next.categorySuggestion;return next;}));
 const incomplete=drafts.filter(d=>d.action!=='skip'&&(d.action==='merge'?!d.mergeId:!d.amount||!d.date||!d.accountId||!d.category.trim()||(d.kind==='transfer'&&(!d.targetId||d.targetId===d.accountId))));
 const money=(n:number)=>formatMoney(n);
 return <section className="panel intake-review"><div className="panel-title"><div><h2>{tr("核对小票 ·")}{drafts.length}{tr("笔")}</h2><details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("相似记录默认跳过；补充详情不会再次扣款。确认后才保存。图片保留原分辨率压缩；勾选保存凭证才长期留存，否则上传7天后清理。")}</p></details></div><button className="secondary" disabled={(busy || uploading>0)} onClick={onReview}>{tr("重新检查重复")}</button></div>{drafts.map((d,i)=><article className={`receipt ${d.action==='skip'?'receipt-skipped':''}`} key={d.id} id={('draft-' + d.id)}><fieldset disabled={(busy || uploading>0)}><div className="panel-title"><strong>{(i + 1)}. {(((d.title || d.payee) || d.product) || tr("待补充的小记录"))}</strong><span className="muted">{(d.source || tr("手动 / 账单"))}{d.platform?(' · ' + d.platform):''}</span></div>
 {d.status==='unknown'&&<p className="notice">{tr("付款状态不明确，请确认这笔钱已实际支付或到账。")}</p>}
 {!!d.matches?.length&&<div className="match-box"><strong>{tr("发现可能重复的记录")}</strong>{d.matches.map(m=><p key={m.record.id}>{m.reason} · {m.record.date} {m.record.payee} {money(m.record.amount)}{m.record.version?tr(" · 已入账"):tr(" · 本批草稿")}</p>)}</div>}
 <label>{tr('记入账本')}<VisualSelect value={d.targetBook||book} label={tr('记入账本')} disabled={d.action==='merge'} onChange={v=>change(d.id,{targetBook:v,refundOf:null})} options={books.filter(b=>b.role!=='viewer').map(b=>({value:b.id,label:b.name,icon:b.icon}))}/></label><ActivitySelect value={d.activityId||''} onChange={v=>change(d.id,{activityId:v||null})} disabled={d.action==='skip'}/>{d.targetBook&&d.targetBook!==book&&d.refundOf&&<p className="muted">{tr('退款记入原单所在账本，原消费不移动。')}</p>}<SceneFields value={d.scene} onChange={(scene,title)=>change(d.id,{scene,...(title?{title}:{})})}/><label>{tr("交易时间（选填）")}<input value={d.occurredAt||''} maxLength={30} placeholder="14:30" onChange={e=>change(d.id,{occurredAt:e.target.value})}/></label><label>{tr("账目标题")}<input value={(d.title || '')} maxLength={80} placeholder={(d.payee || tr("例如：盒马购物、七鲜买菜、店名 · 晚餐"))} onChange={e=>change(d.id,{title:e.target.value})}/></label>
 <div className="form-grid"><label>{tr("这笔如何处理")}<FormSelect value={(d.action || 'create')} onChange={selectedValue=>change(d.id,{action:selectedValue as Draft['action'],...(selectedValue==='merge'?{targetBook:book}:{})})}><option value="create">{tr("新增一笔（确认是独立交易）")}</option><option value="skip">{tr("跳过，不入账")}</option>{d.matches?.some(m=>m.record.version)&&<option value="merge">{tr("只补充已有记录的信息")}</option>}</FormSelect></label>{d.action==='merge'&&<label>{tr("补充到哪笔")}<FormSelect value={(d.mergeId || '')} onChange={selectedValue=>{const r=d.matches?.find(m=>m.record.id===selectedValue)?.record;change(d.id,{mergeId:r?.id,mergeVersion:r?.version});}}><option value="">{tr("请选择已有记录")}</option>{d.matches?.filter(m=>m.record.version).map(m=><option key={m.record.id} value={m.record.id}>{m.record.date} {m.record.payee} {money(m.record.amount)}</option>)}</FormSelect></label>}
 <ReceiptOriginHint origin={d.receiptOrigin}/><label>{tr("类型")}<FormSelect value={d.kind} onChange={selectedValue=>change(d.id,{kind:selectedValue as Draft['kind'],refundOf:null})}><option value="expense">{tr("消费支出")}</option><option value="income">{tr("收入")}</option><option value="refund">{tr("退款到账")}</option><option value="transfer">{tr("账户转账")}</option></FormSelect></label><label>{tr("金额（元）")}<input type="number" min="0.01" step="0.01" value={d.amount?d.amount/100:''} placeholder={tr("请补充金额")} onChange={e=>{try{change(d.id,{amount:e.target.value?amountToCents(e.target.value):0});}catch{}}}/></label><label>{d.kind==='refund'?tr("退款到账日"):tr("支付 / 交易日期")}<DateField type="date" value={d.date} onChange={value=>change(d.id,{date:value})}/></label><label>{tr("资金账户")}<VisualSelect label={tr("请选择实际收付款账户")} value={d.accountId} onChange={v=>change(d.id,{accountId:v,walletMatch:undefined})} options={accounts.map(a=>({value:a.id,label:accountLabel(a)+(d.walletCandidates?.includes(a.id)?(locale==='en'?' · matches receipt':' · 符合付款信息'):''),account:true,accountName:[a.institution,a.name,a.type].filter(Boolean).join(' ')}))}/></label><label>{tr("分类")}<VisualSelect value={d.category} onChange={v=>change(d.id,{category:v,categorySource:'explicit'})} options={Array.from(new Set([d.category,...categories.map(c=>c.name)])).map(name=>({value:name,label:name}))}/></label>{d.categorySuggestion&&<p aria-live="polite" className={`category-suggestion ${d.category!==d.categorySuggestion.category?'is-corrected':''}`}><strong>{tr(d.category!==d.categorySuggestion.category?'已采用你的修正':'个人分类习惯')}</strong><span>{tr(({template:'常用一笔',route:'相同路线',merchant_context:'相同商家与商品',merchant:'相同商家',context:'相似商品'} as Record<string,string>)[d.categorySuggestion.basis])} · {tr("匹配度")} {Math.round(d.categorySuggestion.confidence*100)}% · {d.categorySuggestion.evidenceCount}{tr("条个人记录")}</span><small>{tr(d.category!==d.categorySuggestion.category?'保存后会优先学习这次修正。':'这是预选建议，保存前仍可修改。')}</small></p>}<details className="receipt-details"><summary>{tr("商家、商品与订单详情")}</summary><div className="form-grid"><label>{tr("交易对方")}<input value={d.payee} maxLength={120} onChange={e=>change(d.id,{payee:e.target.value})}/></label><label>{tr("商品摘要")}<input value={(d.product || '')} maxLength={160} placeholder={tr("例如：洗衣液 2kg × 2瓶")} onChange={e=>change(d.id,{product:e.target.value})}/></label><label>{tr("商城 / 平台")}<input value={(d.platform || '')} maxLength={40} onChange={e=>change(d.id,{platform:e.target.value})}/></label><label>{tr("订单号")}<input value={(d.orderId || '')} maxLength={200} onChange={e=>change(d.id,{orderId:e.target.value})}/></label><label>{tr("交易 / 退款流水号")}<input value={(d.externalId || '')} maxLength={200} onChange={e=>change(d.id,{externalId:e.target.value})}/></label><label>{tr("备注")}<input value={d.note} maxLength={2000} onChange={e=>change(d.id,{note:e.target.value})}/></label></div></details>
 {d.kind==='refund'&&<RefundPicker book={d.targetBook||book} books={books} value={d.refundOf||''} onChange={id=>change(d.id,{refundOf:id||null})} onSelect={row=>change(d.id,{...purchaseDefaults(purchaseFromRow(row.detail),true),refundOf:row.id,targetBook:row.book_id,orderId:row.detail.order_id||'',accountId:accounts.some(a=>a.id===row.detail.account_id)?row.detail.account_id:d.accountId})} amount={d.amount} onAmountChange={amount=>change(d.id,{amount})} exclude={d.id} local={drafts.filter(r=>r.kind==='expense'&&r.action!=='skip'&&(r.targetBook||book)===(d.targetBook||book))}/>}
 <MemorySuggestions suggestions={d.memorySuggestions} name={d.product||d.title||''} onChange={(next,resolution)=>{const filled=resolution?resolveMemoryField(d,next,resolution.id,resolution.itemId,resolution.field,resolution.useMemory):changeMemorySelection(d,d.memorySuggestions||[],next);change(d.id,{...filled.value,memorySuggestions:filled.suggestions});}}/>
 {d.scene?.purchaseGroup&&<p className="muted">{tr('已关联历史同款，可在全局搜索中查看同款购买。')}<button type="button" className="text-button" onClick={()=>change(d.id,{scene:{...d.scene!,purchaseGroup:undefined}})}>{tr('取消同款关联')}</button></p>}
 {d.kind==='transfer'&&<label>{tr("转入账户")}<VisualSelect value={(d.targetId || '')} onChange={v=>change(d.id,{targetId:v})} options={accounts.filter(a=>a.id!==d.accountId).map(a=>({value:a.id,label:accountLabel(a),account:true,accountName:[a.institution,a.name,a.type].filter(Boolean).join(' ')}))}/></label>}</div>
 {d.accountId&&d.walletMatch==='channel'&&<small className="wallet-match-note" role="status">{tr("已按支付渠道自动选择，请核对是否为实际扣款账户。")}</small>}
 {d.accountId&&d.walletMatch==='funding'&&<small className="wallet-match-note" role="status">{tr("已根据明确扣款信息自动选择。")}</small>}
 {!d.accountId&&(d.walletCandidates?.length||0)>1&&<small className="wallet-match-note" role="status">{tr("找到多个符合付款信息的钱包，请选择实际扣款账户。")}</small>}
 {d.kind==='refund'&&<details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("退款增加到账账户余额，冲减到账月份的支出；关联后沿用原消费分类。支持多次退款和返现，累计可超过原消费，净支出可为负数。")}</p></details>}
 {d.kind!=='transfer'&&<LineItemsEditor items={(d.lineItems || [])} onChange={items=>change(d.id,{lineItems:items})} total={d.amount} onTotal={amount=>change(d.id,{amount})}/>}
 {!!d.attachmentIds?.length&&<label className="receipt-retention"><input type="checkbox" checked={!!d.retainReceipts} onChange={e=>change(d.id,{retainReceipts:e.target.checked})}/>{tr("保存图片凭证（")}{d.attachmentIds.length}{tr("张）")}</label>}
 <TransactionPhotos book={book} ids={(d.photoIds || [])} onChange={ids=>change(d.id,{photoIds:ids})} disabled={(busy || uploading>0)} onBusy={value=>setUploading(n=>n+(value?1:-1))}/>
 <VerificationConfirm items={(d.lineItems || [])} total={d.amount} value={(d.verificationReason || '')} onChange={v=>change(d.id,{verificationReason:v})}/><button className="text-button" disabled={(busy || uploading>0)} onClick={()=>setDrafts(drafts.filter(r=>r.id!==d.id))}>{tr("移除草稿")}</button></fieldset></article>)}{incomplete.length>0&&<p className="notice">{tr("有")}{incomplete.length} {tr("笔需要补全金额、日期、账户或处理方式。")}<button className="text-button" onClick={()=>document.getElementById('draft-'+incomplete[0].id)?.scrollIntoView({block:'start'})}>{tr("定位第一笔")}</button></p>}<button disabled={((busy || uploading>0) || incomplete.length>0)} onClick={onSave}>{tr("确认保存 · 新增")}{drafts.filter(d=>!d.action||d.action==='create').length} {tr("笔 / 补充")}{drafts.filter(d=>d.action==='merge').length} {tr("笔")}</button></section>;
}
