'use client';
import {TransactionBalance} from './TransactionBalance';
import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import {ImagePlus,X} from 'lucide-react';
import {Sheet} from './Sheet';
import {VisualSelect} from './VisualSelect';
import {formatMoney} from '@/lib/deployment';
import type {LedgerRow} from '@/lib/ledger-types';
export function FamilyMovementDetails({row,onClose,onChanged,embedded=false}:{row:Pick<LedgerRow,'id'|'movement_family_id'|'amount'|'title'|'account_name'|'account_institution'|'wallet_balances'>;embedded?:boolean;onClose:()=>void;onChanged:()=>Promise<void>}){
 const {t:tr,locale}=useI18n();
 const [options,setOptions]=useState<any>(null),[movement,setMovement]=useState<any>(null),[book,setBook]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false);
 const [form,setForm]=useState({title:'',note:'',transactionTime:'',platform:'',externalId:''}),[files,setFiles]=useState<any[]>([]),[removed,setRemoved]=useState<string[]>([]);
 useEffect(()=>{const c=new AbortController();fetch('/api/family-finance/'+row.movement_family_id,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{const m=d.movements.find((m:any)=>m.id===row.id);if(!m)throw Error(tr('往来记录不存在'));setOptions(d);setMovement(m);setBook(m.displayBookId||'');setFiles(m.attachments||[]);setForm({title:m.details?.title||row.title,note:m.details?.note??m.note??'',transactionTime:m.details?.transaction_time||'',platform:m.details?.platform??m.platform??'',externalId:m.details?.external_id??m.external_id??''});}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[row.id,row.movement_family_id]);
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/family-finance/'+row.movement_family_id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'edit',id:row.id,displayBookId:book||null,...form,removeAttachments:removed})});const d=await r.json();if(!r.ok)throw Error(d.error);await onChanged();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(images:File[],purpose:string){setBusy(true);setError('');try{for(const image of images){const r=await fetch(`/api/receipts?movement=${row.id}&purpose=${purpose}`,{method:'POST',headers:{'x-file-name':encodeURIComponent(image.name),'Content-Type':image.type},body:image});const d=await r.json();if(!r.ok)throw Error(d.error);setFiles(f=>[...f,{id:d.data.split('/').at(-1),name:image.name,purpose}]);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const labels={gift:tr('红包 / 赠与'),aa:tr('AA 结算'),loan:tr('借款'),repayment:tr('还款'),contribution:tr('共同入金'),transfer:tr('内部转账')};
 const canEdit=movement&&[movement.sender_id,movement.recipient_id].includes(options?.userId);
 const content=<>
 {!movement&&!error&&<p role="status">{tr("正在读取往来详情…")}</p>}{movement&&<div className="family-detail-heading"><p className="muted">{labels[movement?.kind as keyof typeof labels]||tr('家庭往来')} · {movement?.status==='confirmed'?tr('已到账'):movement?.status==='cancelled'?tr('已取消'):tr('待收款')}</p><strong className="family-detail-amount">{formatMoney(row.amount)}</strong><h3>{form.title||row.title}</h3></div>}
 {options&&<><dl className="movement-detail-fields">{[[tr('交易日期'),movement.date],[tr('交易时间'),form.transactionTime],[tr('转出人'),movement.sender_name],[tr('接收人'),movement.recipient_name||movement.target_name||tr('钱包转入')],[tr('转出钱包'),movement.source_name||tr('对方个人钱包（不可见）')],[tr('到账钱包'),movement.target_name||(movement.status==='pending'?tr('等待收款人选择'):movement.status==='cancelled'?tr('未到账'):tr('对方个人钱包（不可见）'))],[tr('创建时间'),new Date(movement.created_at).toLocaleString(locale)],[tr('最后修改'),new Date(movement.details?.updated_at||movement.confirmed_at||movement.created_at).toLocaleString(locale)]].filter(([,value])=>value).map(([label,value])=><div key={label} ><dt className="muted">{label}</dt><dd >{value}</dd></div>)}</dl>
 <TransactionBalance id={row.id} balances={row.wallet_balances}/><h3>{tr("我的记录")}</h3><p className="muted">{tr("以下补充信息仅自己可见。")}</p>
 {editing?<div style={{display:'grid',gap:16}}>{(['title','transactionTime','platform','externalId','note'] as const).map(key=><label key={key}>{{title:tr('记录标题'),transactionTime:tr('交易时间'),platform:tr('支付平台'),externalId:tr('交易流水号'),note:tr('备注')}[key]}{key==='note'?<textarea value={form[key]} maxLength={2000} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input type={key==='transactionTime'?'time':'text'} maxLength={key==='platform'?60:200} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<label>{tr("记入我的账本")}<VisualSelect label={tr("记入我的账本")} value={book} onChange={setBook} options={[{value:'',label:tr('暂不展示在个人账本')},...options.books.map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))]}/></label></div>:<>{form.platform&&<p>{tr("支付平台：")}{form.platform}</p>}{form.externalId&&<p style={{overflowWrap:'anywhere'}}>{tr("流水号：")}{form.externalId}</p>}{form.note&&<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{form.note}</p>}<p>{tr("记入账本：")}{options.books.find((b:any)=>b.id===book)?.name||tr('暂不展示')}</p></>}
 {(['receipt','photo'] as const).map(purpose=><section className="transaction-photos" key={purpose}><div className="panel-title"><strong>{purpose==='receipt'?tr('交易凭证'):tr('生活附图')}</strong>{canEdit&&<label className="upload"><ImagePlus size={18}/>{busy?tr('上传中…'):tr('添加图片')}<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={e=>{void upload(Array.from(e.target.files||[]),purpose);e.target.value='';}}/></label>}</div><div className="life-photo-grid">{files.filter(f=>f.purpose===purpose&&!removed.includes(f.id)).map(f=><figure key={f.id}><a href={'/api/receipts/'+f.id} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/receipts/'+f.id} alt={f.name}/></a>{editing&&<button className="photo-remove" aria-label={tr("移除图片")} disabled={busy} onClick={()=>setRemoved([...removed,f.id])}><X size={16}/></button>}</figure>)}</div>{!files.some(f=>f.purpose===purpose&&!removed.includes(f.id))&&<p className="muted">{tr("尚未添加")}{purpose==='receipt'?tr('交易凭证'):tr('生活附图')}</p>}</section>)}
 <></>
 {canEdit&&<button disabled={busy} onClick={()=>editing?void save():setEditing(true)}>{busy?tr('处理中…'):editing?tr('保存修改'):tr('修改记录')}</button>}</>}{error&&<p className="error" role="alert">{error}</p>}</>;
 return embedded?<div className="family-detail-page"><button className="text-button" disabled={busy} onClick={onClose}>{tr("← 返回往来记录")}</button>{content}</div>:<Sheet title={tr("这笔家庭往来")} onClose={()=>{if(!busy)onClose();}}>{content}</Sheet>;
}
