'use client';
import {useEffect,useState} from 'react';
import type {ChatAction} from '@/lib/chat-actions';
import {DateField} from './DateField';
import {VisualSelect} from './VisualSelect';
import {amountToCents} from '@/server/model';
const kinds={transfer:'成员转账',gift:'红包／赠与',aa:'AA结算',loan:'借款',repayment:'归还借款',contribution:'共同钱包入金'};
export function FamilyActionEditor({action,onSave,onCancel}:{action:ChatAction;onSave:(d:Record<string,any>)=>Promise<void>;onCancel:()=>void}){
 const [data,setData]=useState({...action.data}),[families,setFamilies]=useState<any[]>([]),[options,setOptions]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const update=(key:string,value:any)=>setData(d=>({...d,[key]:value}));
 useEffect(()=>{fetch('/api/families').then(r=>r.json()).then(d=>setFamilies(d.items||[])).catch(e=>setError(e.message));},[]);
 useEffect(()=>{setOptions(null);if(!data.familyId)return;const c=new AbortController();fetch(`/api/family-finance/${data.familyId}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(setOptions).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[data.familyId]);
 const select=(key:string,label:string,items:any[])=> <label>{label}<VisualSelect label={label} value={data[key]||''} onChange={v=>setData(d=>({...d,[key]:v||null,...(key==='kind'?{targetId:null,recipientId:null,expenseId:null,loanId:null}:{}),...(key==='targetId'&&data.operation==='create'?{recipientId:null}:key==='recipientId'?{targetId:null}:{})}))} options={[{value:'',label:'请选择'},...items]}/></label>;
 const wallets=(options?.wallets||[]).map((w:any)=>({value:w.id,label:[w.name,w.suffix].filter(Boolean).join(' · '),account:true,accountName:[w.institution,w.name].join(' ')}));
 return <form className="chat-inline-editor family-action-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const d={...data};if(d.amountInput!==undefined)d.amount=amountToCents(d.amountInput);delete d.amountInput;await onSave(d);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 <div className="form-grid"><label>家庭<VisualSelect label="家庭" value={data.familyId||''} onChange={familyId=>setData(d=>({...d,familyId,sourceId:null,targetId:null,recipientId:null,movementId:null,expenseId:null,loanId:null,transactionId:null,shares:[]}))} options={families.map(f=>({value:f.id,label:f.name,icon:'🏡'}))}/></label>
 {data.operation!=='shares'&&select('displayBookId','展示在我的账本',[{value:'',label:'仅家庭往来'},...(options?.books||[]).map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))])}
 {data.operation==='create'&&<>{select('kind','用途',Object.entries(kinds).map(([value,label])=>({value,label})))}{select('sourceId','转出钱包',wallets.filter((w:any)=>data.kind==='transfer'||options.wallets.find((a:any)=>a.id===w.value)?.owner_id===options.userId))}{data.kind!=='contribution'&&select('recipientId','收款成员 · 对方选择到账钱包',(options?.people||[]).filter((p:any)=>p.id!==options.userId).map((p:any)=>({value:p.id,label:p.name,icon:p.avatar})))}{['transfer','contribution'].includes(data.kind)&&select('targetId','转入自己／共同钱包',wallets.filter((w:any)=>w.value!==data.sourceId&&(data.kind!=='contribution'||options.wallets.find((a:any)=>a.id===w.value)?.family_id)))}<label>金额<input inputMode="decimal" value={data.amountInput??(data.amount==null?'':data.amount/100)} onChange={e=>update('amountInput',e.target.value)}/></label><label>交易日期<DateField type="date" value={data.date||''} onChange={v=>update('date',v)}/></label>
 {data.kind==='aa'&&select('expenseId','原消费',(options?.expenses||[]).map((x:any)=>({value:x.id,label:`${x.title||x.payee} · ${(x.amount/100).toFixed(2)}`})))}
 {data.kind==='repayment'&&select('loanId','原借款',(options?.movements||[]).filter((x:any)=>x.kind==='loan'&&x.status==='confirmed'&&x.recipient_id===options.userId).map((x:any)=>({value:x.id,label:`${x.sender_name} → ${x.recipient_name} · ${(x.amount/100).toFixed(2)} · ${x.date}`})))}
 <label>备注<input value={data.note||''} onChange={e=>update('note',e.target.value)}/></label></>}
 {data.operation==='confirm'&&<>{select('movementId','待收款记录',(options?.movements||[]).filter((x:any)=>x.status==='pending'&&x.recipient_id===options.userId).map((x:any)=>({value:x.id,label:`${x.sender_name} → ${x.recipient_name} · ${(x.amount/100).toFixed(2)} · ${x.date}`})))}{select('targetId','到账钱包',wallets.filter((w:any)=>options.wallets.find((a:any)=>a.id===w.value)?.owner_id===options.userId))}</>}
 {data.operation==='shares'&&<>{select('transactionId','原消费',(options?.expenses||[]).map((x:any)=>({value:x.id,label:`${x.title||x.payee} · ${(x.amount/100).toFixed(2)}`})))}{(options?.people||[]).map((p:any)=><label key={p.id}>{p.name}<input inputMode="decimal" defaultValue={(data.shares||[]).find((s:any)=>s.userId===p.id)?.amount/100||''} onChange={e=>{try{update('shares',[...(data.shares||[]).filter((s:any)=>s.userId!==p.id),{userId:p.id,amount:e.target.value?amountToCents(e.target.value):0}]);}catch{}}}/></label>)}</>}
 </div>{data.operation==='create'&&action.warnings.some(w=>w.includes('同日')||w.includes('已有'))&&<label className="check"><input type="checkbox" checked={!!data.allowSimilar} onChange={e=>update('allowSimilar',e.target.checked)}/>已核对相似记录，确定这是另一笔转账</label>}
 {error&&<p className="error" role="alert">{error}</p>}<div className="inline"><button disabled={busy||!options}>更新卡片</button><button type="button" className="secondary" onClick={onCancel} disabled={busy}>取消修改</button></div></form>;
}
