'use client';
import {useEffect,useState} from 'react';
import {ArrowLeftRight,Plus,Check,Gift} from 'lucide-react';
import {VisualSelect} from './VisualSelect';
import {Sheet} from './Sheet';
import {PagedList} from './PagedList';
import {DateField} from './DateField';
import {formatMoney} from '@/lib/deployment';
import {amountToCents} from '@/server/model';
const kinds:Record<string,string>={transfer:'普通转账',gift:'红包赠送',aa:'AA 结算',loan:'借出款',repayment:'归还借款',contribution:'共同钱包入金'};
export function FamilyFinance({family,userId,onChanged}:{family:string;userId:string;onChanged:()=>Promise<void>}){
 const [displayBook,setDisplayBook]=useState<string|null>(null),[organize,setOrganize]=useState<any>(null),[requestId,setRequestId]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[confirm,setConfirm]=useState<any>(null),[kind,setKind]=useState('transfer'),[source,setSource]=useState(''),[recipient,setRecipient]=useState(''),[target,setTarget]=useState(''),[link,setLink]=useState(''),[split,setSplit]=useState<any>(null),[shares,setShares]=useState<Record<string,string>>({});
 async function api(body?:unknown){const r=await fetch('/api/family-finance/'+family,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 async function load(){setData(await api());}
 useEffect(()=>{load().catch(e=>setError(e.message));},[family]);
 async function save(body:unknown){if(busy)return;setBusy(true);setError('');try{await api(body);await load();await onChanged();setOpen(false);setConfirm(null);setSplit(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data)return <section className="panel">{error||'正在读取家庭资金往来…'}</section>;
 const wallets=data.wallets.map((a:any)=>({value:a.id,label:a.name+(a.family_id?' · 家庭共有':''),account:true,accountName:a.institution||a.name}));
 const people=data.people.filter((p:any)=>p.id!==userId).map((p:any)=>({value:p.id,label:p.name,icon:p.avatar}));
 const contributions=data.movements.filter((m:any)=>m.kind==='contribution'&&m.status==='confirmed');
 const aa=data.expenses.filter((e:any)=>e.shares);
 return <section className="panel family-finance"><div className="panel-title"><h2><ArrowLeftRight size={22}/>家庭资金往来</h2><button onClick={()=>{setDisplayBook(data.defaultBookId);setRequestId(crypto.randomUUID());setKind('transfer');setSource('');setRecipient('');setTarget('');setLink('');setError('');setOpen(true);}}><Plus size={18}/>记一笔往来</button></div>
 <details className="usage-help"><summary>使用说明</summary><p>内部转账、红包及共同入金不计家庭消费。成员间转账由收款人确认后同步双方余额；待确认记录暂不影响余额。实际支付给商家的费用仍在账本记一次。这里记录已发生的资金往来，不会真实转账。</p></details>
 {error&&!open&&!confirm&&!split&&<p className="error">{error}</p>}
 <div className="wallet-groups">{data.people.map((p:any)=><article key={p.id}><small>{p.name} · 共同入金</small><strong>{formatMoney(contributions.filter((m:any)=>m.sender_id===p.id).reduce((n:number,m:any)=>n+m.amount,0))}</strong></article>)}</div>
 <details><summary>费用分担 / AA</summary>{data.expenses.filter((e:any)=>e.owner_id===userId).length>0&&<VisualSelect label="设置费用分担" value="" onChange={id=>{const e=data.expenses.find((e:any)=>e.id===id);setSplit(e);setError('');setShares(Object.fromEntries(data.people.map((p:any)=>[p.id,String((e.shares?.find((s:any)=>s.userId===p.id)?.amount||0)/100)])));}} options={[{value:'',label:'选择我已支付的家庭消费，设置分担'},...data.expenses.filter((e:any)=>e.owner_id===userId).map((e:any)=>({value:e.id,label:(e.title||e.payee)+' · '+formatMoney(e.amount)}))]}/>}<PagedList items={aa}>{(e:any)=><article className="schedule-card" key={e.id}><strong>{e.title||e.payee} · {formatMoney(e.amount)}</strong><div>{e.shares.map((s:any)=>{const paid=s.paid||0;return <p key={s.userId}>{data.people.find((p:any)=>p.id===s.userId)?.name||'原成员'}：承担 {formatMoney(s.amount)}{s.userId!==e.owner_id&&` · 已结算 ${formatMoney(paid)} · 待结算 ${formatMoney(Math.max(0,s.amount-paid))}`}</p>;})}</div></article>}</PagedList></details>
 <PagedList items={data.movements}>{(m:any)=><article className="schedule-card" key={m.id}><div><strong>{m.kind==='gift'?<Gift size={16}/>:<ArrowLeftRight size={16}/>} {m.sender_name} → {m.recipient_name||m.target_name} · {kinds[m.kind]}</strong><small>{m.date} · {m.status==='pending'?'待收款人确认':m.status==='confirmed'?'已确认':'已取消'}{m.note?' · '+m.note:''}</small>{m.kind==='loan'&&m.status==='confirmed'&&<small>未归还 {formatMoney(Math.max(0,m.amount-data.movements.filter((v:any)=>v.loan_id===m.id&&v.status==='confirmed').reduce((n:number,v:any)=>n+v.amount,0)))}</small>}</div><strong>{formatMoney(m.amount)}</strong>{[m.sender_id,m.recipient_id].includes(userId)&&<button className="text-button" onClick={()=>{setOrganize(m);setDisplayBook(m.displayBookId);}}>展示账本</button>}{m.status==='pending'&&<div className="inline">{m.recipient_id===userId&&<button disabled={busy} onClick={()=>{setDisplayBook(data.defaultBookId);setConfirm(m);setTarget('');setError('');}}><Check size={16}/>确认到账</button>}<button className="text-button" disabled={busy} onClick={()=>save({operation:'cancel',id:m.id})}>取消</button></div>}</article>}</PagedList>
 {organize&&<Sheet title="调整我的展示账本" onClose={()=>setOrganize(null)}><VisualSelect label="展示账本" value={displayBook||''} onChange={v=>setDisplayBook(v||null)} options={[{value:'',label:'仅家庭往来'},...(data.books||[]).map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))]}/><button disabled={busy} onClick={async()=>{try{setBusy(true);await api({operation:'display',id:organize.id,displayBookId:displayBook});await load();await onChanged();setOrganize(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>保存展示位置</button>{error&&<p className="error">{error}</p>}</Sheet>}
 {!data.movements.length&&<p className="muted">暂无家庭资金往来</p>}
 {open&&<Sheet title="记一笔家庭往来" onClose={()=>{if(!busy)setOpen(false);}}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{save({operation:'create',displayBookId:displayBook,id:requestId,kind,sourceId:source,...(target?{targetId:target}:{recipientId:recipient}),amount:amountToCents(String(f.get('amount'))),date:f.get('date'),note:f.get('note'),allowSimilar:f.get('allowSimilar')==='on',...(kind==='aa'?{expenseId:link}:kind==='repayment'?{loanId:link}:{})});}catch(e){setError((e as Error).message);}}}><fieldset disabled={busy}><label>用途<VisualSelect label="用途" value={kind} onChange={v=>{setKind(v);setTarget('');setRecipient('');setLink('');}} options={Object.entries(kinds).map(([value,label])=>({value,label}))}/></label><label>展示在我的账本<VisualSelect label="展示账本" value={displayBook||''} onChange={v=>setDisplayBook(v||null)} options={[{value:'',label:'仅家庭往来'},...(data.books||[]).map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))]}/></label><label>转出钱包<VisualSelect label="转出钱包" value={source} onChange={setSource} options={[{value:'',label:'请选择'},...wallets.filter((w:any)=>kind==='transfer'||data.wallets.find((a:any)=>a.id===w.value)?.owner_id===userId)]}/></label>{kind!=='contribution'&&<label>收款成员（由对方选择到账钱包）<VisualSelect label="收款成员" value={recipient} onChange={v=>{setRecipient(v);setTarget('');setLink('');}} options={[{value:'',label:'请选择'},...people]}/></label>}{['transfer','contribution'].includes(kind)&&<label>或转入自己的／家庭钱包<VisualSelect label="转入钱包" value={target} onChange={v=>{setTarget(v);setRecipient('');}} options={[{value:'',label:'请选择'},...wallets.filter((w:any)=>(kind==='transfer'||data.wallets.find((a:any)=>a.id===w.value)?.family_id)&&w.value!==source)]}/></label>}{['aa','repayment'].includes(kind)&&<label>{kind==='aa'?'关联消费':'关联借款'}<VisualSelect label="关联记录" value={link} onChange={setLink} options={[{value:'',label:'请选择'},...(kind==='aa'?aa.filter((e:any)=>e.owner_id===recipient).map((e:any)=>({value:e.id,label:(e.title||e.payee)+' · '+formatMoney(e.amount)})):data.movements.filter((m:any)=>m.kind==='loan'&&m.status==='confirmed'&&m.sender_id===recipient&&m.recipient_id===userId).map((m:any)=>({value:m.id,label:m.date+' · '+formatMoney(m.amount)})))]}/></label>}<div className="form-grid"><label>金额<input name="amount" inputMode="decimal" required/></label><label>日期<DateField name="date" type="date" defaultValue={new Date().toLocaleDateString('sv-SE')} required/></label></div><label>备注（选填）<input name="note" maxLength={500}/></label>{error&&<p className="error">{error}</p>}{error.includes('同日')&&<label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" name="allowSimilar" style={{width:18,flex:'0 0 18px'}}/>已核对，确实是另一笔转账</label>}<button disabled={!source||(!target&&!recipient)}>保存往来</button></fieldset></form></Sheet>}
 {confirm&&<Sheet title="确认到账" onClose={()=>{if(!busy)setConfirm(null);}}><p>{confirm.sender_name} · {formatMoney(confirm.amount)}</p><VisualSelect label="展示在我的账本" value={displayBook||''} onChange={v=>setDisplayBook(v||null)} options={[{value:'',label:'仅家庭往来'},...(data.books||[]).map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))]}/><VisualSelect label="实际到账钱包" value={target} onChange={setTarget} options={[{value:'',label:'请选择实际到账钱包'},...wallets.filter((w:any)=>data.wallets.find((a:any)=>a.id===w.value)?.owner_id===userId)]}/>{error&&<p className="error">{error}</p>}<button disabled={busy||!target} onClick={()=>save({operation:'confirm',displayBookId:displayBook,id:confirm.id,targetId:target})}>确认到账</button></Sheet>}
 {split&&<Sheet title="设置费用承担" onClose={()=>{if(!busy)setSplit(null);}}><p>{split.title||split.payee} · {formatMoney(split.amount)}</p><button className="secondary" onClick={()=>{const base=Math.floor(split.amount/data.people.length);setShares(Object.fromEntries(data.people.map((p:any,i:number)=>[p.id,String((base+(i<split.amount%data.people.length?1:0))/100)])));}}>所有成员平均分担</button>{data.people.map((p:any)=><label key={p.id}>{p.name}<input inputMode="decimal" value={shares[p.id]||''} onChange={e=>setShares(v=>({...v,[p.id]:e.target.value}))}/></label>)}{error&&<p className="error">{error}</p>}<button disabled={busy} onClick={()=>{try{save({operation:'shares',transactionId:split.id,shares:data.people.map((p:any)=>({userId:p.id,amount:amountToCents(shares[p.id]||'0')}))});}catch(e){setError((e as Error).message);}}}>保存分担</button></Sheet>}
 </section>;
}
