'use client';
import {useEffect,useState} from 'react';
import {ImagePlus,X} from 'lucide-react';
import {Sheet} from './Sheet';
import {VisualSelect,AccountIcon} from './VisualSelect';
import {formatMoney} from '@/lib/deployment';
import type {LedgerRow} from '@/lib/ledger-types';
export function FamilyMovementDetails({row,onClose,onChanged}:{row:LedgerRow;onClose:()=>void;onChanged:()=>Promise<void>}){
 const [options,setOptions]=useState<any>(null),[movement,setMovement]=useState<any>(null),[book,setBook]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false);
 const [form,setForm]=useState({title:'',note:'',transactionTime:'',platform:'',externalId:''}),[files,setFiles]=useState<any[]>([]),[removed,setRemoved]=useState<string[]>([]);
 useEffect(()=>{const c=new AbortController();fetch('/api/family-finance/'+row.movement_family_id,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{const m=d.movements.find((m:any)=>m.id===row.id);if(!m)throw Error('往来记录不存在');setOptions(d);setMovement(m);setBook(m.displayBookId||'');setFiles(m.attachments||[]);setForm({title:m.details?.title||row.title,note:m.details?.note??m.note??'',transactionTime:m.details?.transaction_time||'',platform:m.details?.platform??m.platform??'',externalId:m.details?.external_id??m.external_id??''});}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[row.id,row.movement_family_id]);
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/family-finance/'+row.movement_family_id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'edit',id:row.id,displayBookId:book||null,...form,removeAttachments:removed})});const d=await r.json();if(!r.ok)throw Error(d.error);await onChanged();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(images:File[],purpose:string){setBusy(true);setError('');try{for(const image of images){const r=await fetch(`/api/receipts?movement=${row.id}&purpose=${purpose}`,{method:'POST',headers:{'x-file-name':encodeURIComponent(image.name),'Content-Type':image.type},body:image});const d=await r.json();if(!r.ok)throw Error(d.error);setFiles(f=>[...f,{id:d.data.split('/').at(-1),name:image.name,purpose}]);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const labels={gift:'红包 / 赠与',aa:'AA 结算',loan:'借款',repayment:'还款',contribution:'共同入金',transfer:'内部转账'};
 return <Sheet title="这笔家庭往来" onClose={()=>{if(!busy)onClose();}}>
 <div style={{textAlign:'center',padding:'20px 0'}}><p className="muted">{labels[movement?.kind as keyof typeof labels]||'家庭往来'} · {movement?.status==='confirmed'?'已到账':movement?.status==='cancelled'?'已取消':'待收款'}</p><h2>{formatMoney(row.amount)}</h2><h3>{form.title||row.title}</h3></div>
 {options&&<><dl className="movement-detail-fields">{[['交易日期',movement.date],['交易时间',form.transactionTime],['转出人',movement.sender_name],['接收人',movement.recipient_name||'共同钱包'],['创建时间',new Date(movement.created_at).toLocaleString()],['最后修改',new Date(movement.details?.updated_at||movement.confirmed_at||movement.created_at).toLocaleString()]].filter(([,value])=>value).map(([label,value])=><div key={label} style={{display:'flex',justifyContent:'space-between',gap:16,margin:'16px 0'}}><dt className="muted">{label}</dt><dd style={{margin:0,textAlign:'right',overflowWrap:'anywhere'}}>{value}</dd></div>)}</dl>
 <p><AccountIcon name={row.account_institution||row.account_name} size={20}/> {row.account_name}</p>
 {editing?<div style={{display:'grid',gap:16}}>{(['title','transactionTime','platform','externalId','note'] as const).map(key=><label key={key}>{{title:'记录标题',transactionTime:'交易时间',platform:'支付平台',externalId:'交易流水号',note:'备注'}[key]}{key==='note'?<textarea value={form[key]} maxLength={2000} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input type={key==='transactionTime'?'time':'text'} maxLength={key==='platform'?60:200} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<label>记入我的账本<VisualSelect label="记入我的账本" value={book} onChange={setBook} options={[{value:'',label:'暂不展示在个人账本'},...options.books.map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))]}/></label></div>:<>{form.platform&&<p>支付平台：{form.platform}</p>}{form.externalId&&<p style={{overflowWrap:'anywhere'}}>流水号：{form.externalId}</p>}{form.note&&<p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{form.note}</p>}<p>记入账本：{options.books.find((b:any)=>b.id===book)?.name||'暂不展示'}</p></>}
 {(['receipt','photo'] as const).map(purpose=><section className="transaction-photos" key={purpose}><div className="panel-title"><strong>{purpose==='receipt'?'交易凭证':'生活附图'}</strong><label className="upload"><ImagePlus size={18}/>{busy?'上传中…':'添加图片'}<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={e=>{void upload(Array.from(e.target.files||[]),purpose);e.target.value='';}}/></label></div><div className="life-photo-grid">{files.filter(f=>f.purpose===purpose&&!removed.includes(f.id)).map(f=><figure key={f.id}><a href={'/api/receipts/'+f.id} target="_blank" rel="noreferrer"><img loading="lazy" src={'/api/receipts/'+f.id} alt={f.name}/></a>{editing&&<button className="photo-remove" aria-label="移除图片" disabled={busy} onClick={()=>setRemoved([...removed,f.id])}><X size={16}/></button>}</figure>)}</div></section>)}
 <details className="usage-help"><summary>记录与图片说明</summary><p>标题、备注、流水号和附图由你单独维护，仅你可见。图片上传后自动保存并压缩；编辑中的移除操作在保存后生效。双方已确认的金额、日期与收付款关系在此保留。</p></details>
 <button disabled={busy} onClick={()=>editing?void save():setEditing(true)}>{busy?'处理中…':editing?'保存修改':'修改记录'}</button></>}{error&&<p className="error" role="alert">{error}</p>}</Sheet>;
}
