'use client';
import {FamilyFinance} from './FamilyFinance';
import {PagedList} from './PagedList';

import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import {Home,Plus,Users,BookOpen,ArrowLeft,Link2,Settings2,Mail} from 'lucide-react';
import {Avatar,AvatarField} from './ManagementPages';
import {SymbolIcon} from './VisualSelect';
import {FormSelect} from './FormSelect';
import {Sheet} from './Sheet';
import './families.css';
type Person={id:string;name:string;username:string;avatar?:string;disabled?:boolean};
type Family={avatar:string;id:string;name:string;description:string;owner_id:string;owner_name?:string;member_count:number};
type Book={id:string;name:string;icon:string;role?:string};
type Detail=Family&{members:Person[];books:Book[];availableBooks:Book[];invitations:Person[]};
type Invite={avatar:string;id:string;name:string;owner_name:string};
async function api(path:string,method='GET',body?:unknown){const r=await fetch('/api/families'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error||'操作未完成');return data;}
export function FamiliesPage({userId,onChanged,onOpenBook,onManageBooks}:{userId:string;onChanged:()=>Promise<void>;onOpenBook:(id:string)=>void;onManageBooks:()=>void}){const {t:tr,locale}=useI18n();
 const [items,setItems]=useState<Family[]>([]),[invitations,setInvitations]=useState<Invite[]>([]),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState<'new'|'edit'|null>(null);
 const [confirm,setConfirm]=useState<{title:string;text:string;action:()=>Promise<void>}|null>(null);
 const [avatar,setAvatar]=useState('🏡'),[uploading,setUploading]=useState(false);
 const owner=detail?.owner_id===userId;
 async function load(id?:string){const d=await api('');setItems(d.items);setInvitations(d.invitations);if(id&&d.items.some((f:Family)=>f.id===id))setDetail(await api('/'+id));else setDetail(null);}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function mutate(path:string,method:string,body?:unknown,message='已保存'){await api('/'+detail!.id+path,method,body);await load(detail!.id);await onChanged();setNotice(message);}
 function ask(title:string,text:string,action:()=>Promise<void>){setConfirm({title,text,action});}
 return <div className="families-page"><div className="panel-title"><div>{detail&&<button className="text-button" onClick={()=>{setDetail(null);setError('');setNotice('');}}><ArrowLeft size={16}/>{tr("所有家庭")}</button>}<h1>{detail&&<Avatar value={detail.avatar} size={44}/>} {(detail?.name || tr("家庭管理"))}</h1></div>{!detail?<button onClick={()=>{setAvatar('🏡');setEdit('new');}}><Plus size={18}/>{tr("创建家庭")}</button>:owner&&<button className="secondary" onClick={()=>{setAvatar(detail!.avatar||'🏡');setEdit('edit');}}><Settings2 size={17}/>{tr("家庭资料")}</button>}</div>
 {error&&<p className="error" role="alert">{tr(error)}</p>}{notice&&<p className="notice" role="status">{tr(notice)}</p>}
 {loading?<p role="status">{tr("正在读取家庭…")}</p>:!detail?<>
 {invitations.length>0&&<section className="panel"><h2><Mail size={21}/>{tr("待处理邀请")}</h2>{<PagedList items={invitations}>{i=><div className="family-row" key={i.id}><Avatar value={i.avatar} size={44}/><span><strong>{i.name}</strong><small>{i.owner_name} {tr("邀请你加入")}</small></span><div className="family-actions"><button disabled={busy} onClick={()=>run(async()=>{await api('/'+i.id+'/invitation','POST',{accept:true});await load(i.id);setNotice('已加入家庭；账本由所有者单独授权。');})}>{tr("加入家庭")}</button><button className="secondary" disabled={busy} onClick={()=>run(async()=>{await api('/'+i.id+'/invitation','POST',{accept:false});await load();})}>{tr("婉拒")}</button></div></div>}</PagedList>}</section>}
 <div className="family-grid">{<PagedList items={items}>{f=><button className="panel family-card" key={f.id} disabled={busy} onClick={()=>run(async()=>{await load(f.id);})}><Avatar value={f.avatar} size={64}/><strong>{f.name}</strong><small>{f.member_count}{tr("位成员 ·")}{f.owner_id===userId?tr("我是负责人"):tr("家庭成员")}</small>{f.description&&<p>{f.description}</p>}<span className="text-button">{tr("查看家庭 →")}</span></button>}</PagedList>}</div>
 {!items.length&&<section className="panel family-empty"><Home size={38}/><h2>{tr("为共同生活建一个家庭")}</h2><p>{tr("你可以独立使用账号，也可以创建家庭或接受邀请。")}</p><button onClick={()=>{setAvatar('🏡');setEdit('new');}}>{tr("创建我的家庭")}</button></section>}
 </>:<>
 {detail.description&&<p className="muted">{detail.description}</p>}
 <div className="family-columns"><section className="panel"><div className="panel-title"><h2><Users size={21}/>{tr("家庭成员")}</h2><small>{detail.members.length}{tr("人")}</small></div>
 {<PagedList items={detail.members}>{m=><div className="family-row" key={m.id}><Avatar value={m.avatar}/><span><strong>{m.name}{m.id===userId?tr("（我）"):''}</strong><small>@{m.username} · {m.id===detail.owner_id?tr("家庭负责人"):tr("家庭成员")}{m.disabled?tr(" · 账号已停用"):''}</small></span>{owner&&m.id!==userId&&<button className="text-button" disabled={busy} onClick={()=>ask('移出家庭',tr("将{0}移出家庭。其独立账号保留，名下账本将解除家庭关联。已单独授予的账本权限仍保留，可在账本管理中撤销。",[m.name]),async()=>mutate('/members','DELETE',{userId:m.id},'已移出家庭'))}>{tr("移出")}</button>}</div>}</PagedList>}
 {owner&&<><form className="family-invite-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const username=String(new FormData(form).get('username'));run(async()=>{await mutate('/invitations','POST',{username},'邀请已发送，等待对方登录后接受');form.reset();});}}><label>{tr("邀请已有账号")}<input name="username" placeholder={tr("输入登录账号")} required maxLength={80}/></label><button disabled={busy}>{tr("发送邀请")}</button></form>{detail.invitations.length>0&&<div className="family-pending"><h3>{tr("等待接受")}</h3>{<PagedList items={detail.invitations}>{i=><div className="family-row" key={i.id}><span>{i.name}<small>@{i.username}</small></span><button className="text-button" disabled={busy} onClick={()=>run(()=>mutate('/invitations','DELETE',{userId:i.id},'已撤回邀请'))}>{tr("撤回")}</button></div>}</PagedList>}</div>}</>}
 </section><section className="panel"><div className="panel-title"><h2><BookOpen size={21}/>{tr("家庭账本")}</h2><button className="text-button" onClick={onManageBooks}>{tr("管理账本")}</button></div>
 {detail.books.length?<PagedList items={detail.books}>{b=><div className="family-row" key={b.id}><SymbolIcon icon={(b.icon || '📒')} size={38}/><span><strong>{b.name}</strong><small>{b.role==='owner'?tr("我是账本所有者"):b.role==='editor'?tr("可记账"):tr("只读")}</small></span><div className="family-actions"><button className="secondary" onClick={()=>onOpenBook(b.id)}>{tr("打开")}</button>{(owner||b.role==='owner')&&<button className="text-button" disabled={busy} onClick={()=>ask('解除账本关联',tr("“{0}”将移出此家庭，账目和已有账本权限保持不变。",[b.name]),async()=>mutate('/books','DELETE',{bookId:b.id},'已解除关联'))}>{tr("解除关联")}</button>}</div></div>}</PagedList>:<p className="muted">{tr("暂无已授权给你的家庭账本。")}</p>}
 {detail.availableBooks.length>0?<form className="family-invite-form" onSubmit={e=>{e.preventDefault();const bookId=String(new FormData(e.currentTarget).get('bookId'));run(()=>mutate('/books','POST',{bookId},'已关联账本，成员权限仍需单独设置'));}}><label>{tr("关联我的共享账本")}<FormSelect name="bookId">{detail.availableBooks.map(b=><option value={b.id} key={b.id} data-icon={b.icon||'📒'}>{b.name}</option>)}</FormSelect></label><button disabled={busy}><Link2 size={17}/>{tr("关联")}</button></form>:<button className="secondary" onClick={onManageBooks}><Plus size={17}/>{tr("前往创建共享账本")}</button>}
 {detail.books.some(b=>b.role==='owner')&&detail.members.some(m=>m.id!==userId)&&<details className="context-details"><summary>{tr("为家庭成员设置账本权限")}</summary><form onSubmit={e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));run(()=>mutate('/access','PUT',values,'账本权限已更新'));}}><label>{tr("账本")}<FormSelect name="bookId">{detail.books.filter(b=>b.role==='owner').map(b=><option value={b.id} key={b.id} data-icon={b.icon||'📒'}>{b.name}</option>)}</FormSelect></label><label>{tr("成员")}<FormSelect name="userId">{detail.members.filter(m=>m.id!==userId).map(m=><option key={m.id} value={m.id} data-icon={m.avatar||'👤'}>{m.name}（{m.username}）</option>)}</FormSelect></label><label>{tr("权限")}<FormSelect name="role"><option value="viewer">{tr("只读")}</option><option value="editor">{tr("可记账")}</option><option value="none">{tr("撤销访问")}</option></FormSelect></label><button disabled={busy}>{tr("保存账本权限")}</button></form></details>}
 </section></div>
 <></>
 <details className="context-details"><summary>{owner?tr("转交或解散家庭"):tr("退出家庭")}</summary>{owner?<><form className="family-invite-form" onSubmit={e=>{e.preventDefault();const userId=String(new FormData(e.currentTarget).get('userId'));ask('转交家庭负责人','转交后你将成为普通家庭成员。账本所有权不会随之变更。',async()=>mutate('/owner','PUT',{userId},'家庭负责人已转交'));}}><label>{tr("新负责人")}<FormSelect name="userId" disabled={!detail.members.some(m=>m.id!==userId&&!m.disabled)}>{detail.members.filter(m=>m.id!==userId&&!m.disabled).map(m=><option key={m.id} value={m.id} data-icon={m.avatar||'👤'}>{m.name}</option>)}</FormSelect></label><button className="secondary" disabled={(busy || !detail.members.some(m=>m.id!==userId&&!m.disabled))}>{tr("转交家庭")}</button></form><button className="text-button" disabled={busy} onClick={()=>ask('解散家庭','解散后家庭成员关系与邀请将移除。所有账号、账本、账目和账本授权保留。',async()=>mutate('','DELETE',undefined,'家庭已解散，账本和账号保留'))}>{tr("解散家庭")}</button></>:<button className="secondary" disabled={busy} onClick={()=>ask('退出家庭','你的账号和账本保留，名下账本会解除家庭关联；已有账本访问权限需单独管理。',async()=>mutate('/members','DELETE',{userId},'已退出家庭'))}>{tr("退出家庭")}</button>}</details>
 </>}
 <></>
 {detail&&<FamilyFinance key={detail.id} family={detail.id} userId={userId} onChanged={onChanged}/>}
 {edit&&<Sheet title={edit==='new'?tr("创建家庭"):tr("家庭资料")} onClose={()=>{if(!busy&&!uploading)setEdit(null);}}><form onSubmit={e=>{e.preventDefault();if(uploading)return;const values={...Object.fromEntries(new FormData(e.currentTarget)),avatar};run(async()=>{if(edit==='new'){const d=await api('','POST',values);await load(d.id);}else{await api('/'+detail!.id,'PUT',values);await load(detail!.id);}setEdit(null);});}}><AvatarField value={avatar} onChange={setAvatar} onProcessing={setUploading}/><label>{tr("家庭名称")}<input name="name" defaultValue={edit==='edit'?detail?.name:''} maxLength={80} required placeholder={tr("例如：我们的小家")}/></label><label>{tr("家庭简介（选填）")}<textarea name="description" defaultValue={edit==='edit'?detail?.description:''} maxLength={500}/></label>{error&&<p className="error">{tr(error)}</p>}<button disabled={(busy || uploading)}>{tr("保存家庭")}</button></form></Sheet>}
 {confirm&&<Sheet title={confirm.title} onClose={()=>{if(!busy)setConfirm(null);}}><p>{confirm.text}</p>{error&&<p className="error">{tr(error)}</p>}<div className="family-actions"><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>{tr("取消")}</button><button disabled={busy} onClick={()=>run(async()=>{await confirm.action();setConfirm(null);})}>{tr("确认")}{confirm.title}</button></div></Sheet>}
 </div>;
}
