'use client';
import {useI18n} from './LanguageProvider';
import {shortChartLabel,chartAmount} from '@/lib/chart-labels';
import {useEffect,useRef} from 'react';
import type {ThinkingBlock} from '@/lib/thinking';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {FinanceChart} from './InteractiveFinanceChart';
export {FinanceChart} from './InteractiveFinanceChart';
import type {ChartArtifact,AgentArtifact} from '@/server/finance-agent';
function ThinkingSection({block:t}:{block:ThinkingBlock}){const {t:tr,locale}=useI18n();const box=useRef<HTMLDivElement>(null),following=useRef(true);useEffect(()=>{if(following.current&&box.current)box.current.scrollTop=box.current.scrollHeight;},[t.text]);return <section><strong>{tr(t.label)}<small>{t.status==='running'?tr("思考中"):t.status==='stopped'?tr("已中断"):tr("已完成")}</small></strong><div className="thinking-text" ref={box} onScroll={e=>{const el=e.currentTarget;following.current=el.scrollHeight-el.scrollTop-el.clientHeight<40;}}>{t.text}{t.status==='running'&&<span className="thinking-cursor" aria-label={tr("正在输出")}>▍</span>}</div></section>;}
export function FinanceNarrative({text,artifacts,book}:{book?:string;text:string;artifacts?:Partial<AgentArtifact>}){const {t:tr,locale}=useI18n();const charts=(artifacts?.charts||[]).map(c=>{const tool=artifacts?.tools?.find(t=>(t.result as any)?.id===c.id);return {...c,dimension:c.dimension||(tool?.args as any)?.dimension,books:c.books||artifacts?.analysisBooks?.map(b=>b.id)||(book?[book]:undefined)};}),used=new Set<string>(),pieces=text.split(/(\[\[chart:[a-zA-Z0-9-]+\]\])/g);return <div className="finance-narrative">{artifacts?.thinking?.length?<details className="thinking-stream"><summary>{tr("思考过程 ·")}{artifacts.thinking.some(t=>t.status==='running')?tr("正在思考…"):tr("查看")}</summary>{artifacts.thinking.map(t=><ThinkingSection key={t.id} block={t}/>)}</details>:null}{artifacts?.agents?.length? <details className="agent-collaboration"><summary>{tr("专业助手协作 ·")}{artifacts.agents.length} {tr("项任务")}</summary>{artifacts.agents.map(a=><article key={a.id}><strong>{tr(a.role)} · {a.status==='running'?tr("处理中"):a.status==='complete'?tr("已完成"):tr("未完成")}</strong><p>{a.task}</p><details><summary>{tr("查看工作结论")}</summary><p style={{whiteSpace:'pre-wrap'}}>{(a.summary || tr("正在处理…"))}</p></details></article>)}</details>:null}{pieces.map((part,i)=>{const id=part.match(/^\[\[chart:([^\]]+)\]\]$/)?.[1],chart=charts.find(c=>c.id===id);if(chart){used.add(chart.id);return <FinanceChart key={i} chart={chart}/>;}return <ReactMarkdown key={i} remarkPlugins={[remarkGfm]} skipHtml components={{img:({alt})=><span>{(alt || tr("图片"))}</span>,a:({children})=><span>{children}</span>}}>{id?tr("（此图未保存在当前回答中）"):part}</ReactMarkdown>;})}{charts.filter(c=>!used.has(c.id)).map(c=><FinanceChart key={c.id} chart={c}/>)}</div>;}
