'use client';
import {useI18n} from './LanguageProvider';
import {shortChartLabel,chartAmount} from '@/lib/chart-labels';
import {useEffect,useRef} from 'react';
import type {ThinkingBlock} from '@/lib/thinking';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,PieChart,Pie,Cell,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import type {ChartArtifact,AgentArtifact} from '@/server/finance-agent';
export function FinanceChart({chart}:{chart:ChartArtifact}){const {t:tr,locale}=useI18n();const colors=['#426e61','#a78eb1','#d2a363','#89afb5','#ba858e'];return <figure className="finance-chart"><figcaption><strong>{chart.title}</strong><small>{chart.from} {tr("至")}{chart.to} {tr("· 单位：")}{tr(chart.unit)} {tr("· 账目查询快照")}</small></figcaption>{!chart.data.length?<p className="muted">{tr("此范围暂无记录")}</p>:<div style={{height:280,width:'100%'}}><ResponsiveContainer>{chart.type==='pie'?<PieChart><Pie data={chart.data} dataKey="value" nameKey="name" innerRadius="45%" outerRadius="78%">{chart.data.map((d,i)=><Cell key={d.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip wrapperStyle={{maxWidth:'min(260px, 75vw)'}} contentStyle={{whiteSpace:'normal',overflowWrap:'anywhere',borderRadius:12,fontSize:12}} formatter={v=>Number(v).toFixed(2)+' '+tr('元')}/></PieChart>:chart.type==='line'?<LineChart data={chart.data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:11}} tickFormatter={shortChartLabel} minTickGap={22}/><YAxis width={48} tick={{fontSize:11}} tickFormatter={chartAmount}/><Tooltip wrapperStyle={{maxWidth:'min(260px, 75vw)'}} contentStyle={{whiteSpace:'normal',overflowWrap:'anywhere',borderRadius:12,fontSize:12}} formatter={v=>Number(v).toFixed(2)+' '+tr('元')}/><Line type="monotone" dataKey="value" name={tr("金额")} stroke="#426e61" dot={chart.data.length<25}/></LineChart>:<BarChart data={chart.data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:11}} tickFormatter={shortChartLabel} minTickGap={22}/><YAxis width={48} tick={{fontSize:11}} tickFormatter={chartAmount}/><Tooltip wrapperStyle={{maxWidth:'min(260px, 75vw)'}} contentStyle={{whiteSpace:'normal',overflowWrap:'anywhere',borderRadius:12,fontSize:12}} formatter={v=>Number(v).toFixed(2)+' '+tr('元')}/><Bar dataKey="value" name={tr("金额")} fill="#426e61" radius={[5,5,0,0]}/></BarChart>}</ResponsiveContainer></div>}<details><summary>{tr("查看图表数据")}</summary><div className="finance-table"><table><thead><tr><th>{tr("项目")}</th><th>{tr("金额（元）")}</th></tr></thead><tbody>{chart.data.map((d,i)=><tr key={i}><td>{d.name}</td><td>{d.value.toFixed(2)}</td></tr>)}</tbody></table></div></details></figure>;}
function ThinkingSection({block:t}:{block:ThinkingBlock}){const {t:tr,locale}=useI18n();const box=useRef<HTMLDivElement>(null),following=useRef(true);useEffect(()=>{if(following.current&&box.current)box.current.scrollTop=box.current.scrollHeight;},[t.text]);return <section><strong>{tr(t.label)}<small>{t.status==='running'?tr("思考中"):t.status==='stopped'?tr("已中断"):tr("已完成")}</small></strong><div className="thinking-text" ref={box} onScroll={e=>{const el=e.currentTarget;following.current=el.scrollHeight-el.scrollTop-el.clientHeight<40;}}>{t.text}{t.status==='running'&&<span className="thinking-cursor" aria-label={tr("正在输出")}>▍</span>}</div></section>;}
export function FinanceNarrative({text,artifacts}:{text:string;artifacts?:Partial<AgentArtifact>}){const {t:tr,locale}=useI18n();const charts=artifacts?.charts||[],used=new Set<string>(),pieces=text.split(/(\[\[chart:[a-zA-Z0-9-]+\]\])/g);return <div className="finance-narrative">{artifacts?.thinking?.length?<details className="thinking-stream"><summary>{tr("思考过程 ·")}{artifacts.thinking.some(t=>t.status==='running')?tr("正在思考…"):tr("查看")}</summary>{artifacts.thinking.map(t=><ThinkingSection key={t.id} block={t}/>)}</details>:null}{artifacts?.agents?.length? <details className="agent-collaboration"><summary>{tr("专业助手协作 ·")}{artifacts.agents.length} {tr("项任务")}</summary>{artifacts.agents.map(a=><article key={a.id}><strong>{tr(a.role)} · {a.status==='running'?tr("处理中"):a.status==='complete'?tr("已完成"):tr("未完成")}</strong><p>{a.task}</p><details><summary>{tr("查看工作结论")}</summary><p style={{whiteSpace:'pre-wrap'}}>{(a.summary || tr("正在处理…"))}</p></details></article>)}</details>:null}{pieces.map((part,i)=>{const id=part.match(/^\[\[chart:([^\]]+)\]\]$/)?.[1],chart=charts.find(c=>c.id===id);if(chart){used.add(chart.id);return <FinanceChart key={i} chart={chart}/>;}return <ReactMarkdown key={i} remarkPlugins={[remarkGfm]} skipHtml components={{img:({alt})=><span>{(alt || tr("图片"))}</span>,a:({children})=><span>{children}</span>}}>{id?tr("（此图未保存在当前回答中）"):part}</ReactMarkdown>;})}{charts.filter(c=>!used.has(c.id)).map(c=><FinanceChart key={c.id} chart={c}/>)}</div>;}
