'use client';
import {MemoryCenter} from './MemoryCenter';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowUp,Paperclip,SlidersHorizontal,Maximize2,Minimize2,X,LoaderCircle,ArrowRight} from 'lucide-react';
import {useI18n} from './LanguageProvider';
import {uploadReceipt} from '@/lib/upload-receipt';
type Attachment={name:string;data:string};
export function FinanceComposer({scopeControl,book,text,onText,images,onImages,busy,uploading,onUploading,useHistory,onHistory,onSend,onBackground,onError,reply,onCancelReply}:{scopeControl?:import("react").ReactNode;book:string;text:string;onText:(s:string)=>void;images:Attachment[];onImages:(fn:(v:Attachment[])=>Attachment[])=>void;busy:boolean;uploading:boolean;onUploading:(v:boolean)=>void;useHistory:boolean;onHistory:(v:boolean)=>void;onSend:()=>void;onBackground:()=>void;onError:(s:string)=>void;reply?:string;onCancelReply:()=>void}){
 const {t:tr}=useI18n();const textarea=useRef<HTMLTextAreaElement>(null),file=useRef<HTMLInputElement>(null),box=useRef<HTMLDivElement>(null);const [expanded,setExpanded]=useState(false),[drag,setDrag]=useState(false),[long,setLong]=useState(false);
 useLayoutEffect(()=>{const el=textarea.current;if(!el)return;const resize=()=>{el.style.height='0px';const natural=el.scrollHeight;const viewport=window.visualViewport?.height||window.innerHeight;const cap=expanded?Math.max(96,Math.min(360,viewport*.42)):Math.max(64,Math.min(160,viewport*.24));el.style.height=Math.min(cap,Math.max(40,natural))+'px';el.style.overflowY=natural>cap?'auto':'hidden';setLong(natural>96);box.current?.closest<HTMLElement>('.finance-main')?.style.setProperty('--composer-height',`${box.current.parentElement?.offsetHeight||120}px`);};resize();const observer=new ResizeObserver(resize);if(box.current)observer.observe(box.current);window.visualViewport?.addEventListener('resize',resize);return()=>{observer.disconnect();window.visualViewport?.removeEventListener('resize',resize);};},[text,expanded]);
 useEffect(()=>{if(!text)setExpanded(false);},[text]);
 async function add(files:File[]){if(busy||uploading||!files.length)return;onUploading(true);onError('');try{for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw new Error('请选择PNG、JPEG或WebP图片');const added=await uploadReceipt(book,f);onImages(v=>[...v,added]);}}catch(e){onError((e as Error).message);}finally{onUploading(false);}}
 return <div className={'finance-composer'+(expanded?' is-expanded':'')}>
  {reply&&<div className="chat-reply-target"><span>{tr('正在修改')} · {reply}</span><button type="button" className="icon-button" aria-label={tr('取消指定修改')} onClick={onCancelReply}><X size={15}/></button></div>}
  <div ref={box} className={'composer-box'+(drag?' is-dragging':'')} onDragOver={e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();setDrag(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(false);}} onDrop={e=>{e.preventDefault();setDrag(false);add(Array.from(e.dataTransfer.files));}}>
   {images.length>0&&<><div className="composer-previews">{images.map((f,i)=><div className="composer-preview" key={f.data}><img src={f.data} alt={f.name}/><button type="button" disabled={busy} title={tr('移除图片')} aria-label={tr('移除图片')+' '+f.name} onClick={()=>onImages(v=>v.filter((_,n)=>n!==i))}><X size={13}/></button><span title={f.name}>{f.name}</span></div>)}</div><small className="composer-attachment-status" role="status">{tr('已添加 {0} 张图片，发送时会一并提交').replace('{0}',String(images.length))}</small></>}
   <textarea ref={textarea} rows={1} aria-label={tr('给财务助手发送消息')} placeholder={tr('描述一笔消费，或问问你的账本…')} value={text} disabled={busy} onChange={e=>onText(e.target.value)} onPaste={e=>{const files=Array.from(e.clipboardData.files);if(files.length){e.preventDefault();add(files);}}} onKeyDown={e=>{if(e.nativeEvent.isComposing||e.nativeEvent.keyCode===229)return;if(e.key==='Enter'&&!e.shiftKey&&(e.ctrlKey||e.metaKey||window.innerWidth>730)){e.preventDefault();if(!uploading)onSend();}}}/>
   <div className="composer-tools"><div className="composer-tools-left"><MemoryCenter/>
    <input hidden ref={file} type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';add(files);}}/>
    <button className="composer-icon" type="button" disabled={busy||uploading} aria-label={tr('添加账单图片')} title={tr('添加账单图片')} onClick={()=>file.current?.click()}>{uploading?<LoaderCircle className="composer-spinner" size={19}/>:<Paperclip size={19}/>}</button>
    <details className="composer-options"><summary title={tr('对话偏好')} aria-label={tr('对话偏好')}><SlidersHorizontal size={18}/>{useHistory&&<i/>}</summary><div><label className="check"><input type="checkbox" checked={useHistory} onChange={e=>onHistory(e.target.checked)}/>{tr('使用我的分类与复购习惯')}</label><small>{tr('只参考你确认过的个人记录；修改分类后会自动学习。')}</small></div></details>{scopeControl}
    {(long||expanded)&&<button className="composer-icon" type="button" aria-label={tr(expanded?'收起输入框':'展开输入框')} title={tr(expanded?'收起输入框':'展开输入框')} onClick={()=>{setExpanded(v=>!v);textarea.current?.focus();}}>{expanded?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button>}
    {uploading&&<small role="status">{tr('正在上传图片…')}</small>}
   </div>{busy?<button type="button" className="composer-background" onClick={onBackground} title={tr('后台继续')}><ArrowRight size={17}/><span>{tr('后台继续')}</span></button>:<button type="button" className="composer-send" aria-label={tr('发送')} title={tr('发送')} disabled={uploading||!text.trim()&&!images.length} onClick={onSend}><ArrowUp size={21}/></button>}</div>
  </div><small className="composer-shortcut">{tr('Enter 发送 · Shift + Enter 换行')}</small>
 </div>;
}
