'use client';
import {useI18n} from './LanguageProvider';
import {Children,isValidElement,useEffect,useRef,useState,type ReactNode} from 'react';
import {ChevronDown} from 'lucide-react';
import {ChoicePicker,type Choice} from './ChoicePicker';
type Props={children:ReactNode;value?:string;defaultValue?:string;name?:string;required?:boolean;disabled?:boolean;'aria-label'?:string;onChange?:(value:string)=>void};
function choices(children:ReactNode):Choice[]{return Children.toArray(children).flatMap(child=>{if(!isValidElement<{value?:string;children?:ReactNode;disabled?:boolean}>(child))return [];if(child.type==='option'){const label=Children.toArray(child.props.children).join('');return [{value:child.props.value??label,label,disabled:child.props.disabled}];}return choices(child.props.children);});}
export function FormSelect({children,value,defaultValue,name,required,disabled,'aria-label':ariaLabel,onChange}:Props){const {t:tr,locale}=useI18n();
 const options=choices(children),[local,setLocal]=useState(defaultValue??options[0]?.value??''),[open,setOpen]=useState(false),[title,setTitle]=useState(ariaLabel||'请选择');const select=useRef<HTMLSelectElement>(null),trigger=useRef<HTMLButtonElement>(null);const selected=value??local;
 useEffect(()=>{const el=select.current!;const label=el.closest('label');if(!ariaLabel&&label){const text=Array.from(label.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join('').trim();if(text)setTitle(text);}const reset=()=>{setLocal(defaultValue??options[0]?.value??'');setOpen(false);};el.form?.addEventListener('reset',reset);return()=>el.form?.removeEventListener('reset',reset);},[ariaLabel,defaultValue,children]);
 function choose(next:string){setLocal(next);onChange?.(next);setOpen(false);}
 return <div className="form-select"><select hidden ref={select} className="select-form-value" name={name} value={selected} required={required} disabled={disabled} tabIndex={-1} aria-hidden="true" onChange={e=>choose(e.target.value)} onInvalid={e=>{e.preventDefault();trigger.current?.focus();setOpen(true);}}>{children}</select><button ref={trigger} type="button" className="visual-trigger" disabled={disabled} aria-label={((tr(title) + ': ') + (options.find(o=>o.value===selected)?.label||tr('请选择')))} aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><span title={options.find(o=>o.value===selected)?.label}>{(options.find(o=>o.value===selected)?.label || tr("请选择"))}</span><ChevronDown size={18}/></button>{open&&<ChoicePicker title={tr(title)} options={options} value={selected} onSelect={choose} onClose={()=>setOpen(false)}/>}</div>;
}
