'use client';
import {useEffect,useState,useCallback} from 'react';
import {Inbox,Check} from 'lucide-react';
import {VisualSelect} from './VisualSelect';
import {Sheet} from './Sheet';
import {formatMoney} from '@/lib/deployment';
async function request(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
export function HomeFamilyInbox({revision,onChanged}:{revision:number;onChanged:()=>Promise<void>}){
 const [data,setData]=useState<any>({rows:[],total:0}),[offset,setOffset]=useState(0),[selected,setSelected]=useState<any>(null),[options,setOptions]=useState<any>(null),[target,setTarget]=useState(''),[book,setBook]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{const d=await request('family-inbox?offset='+offset);if(!d.rows.length&&offset){setOffset(0);return;}setData(d);},[offset]);
 useEffect(()=>{let active=true;const update=()=>{if(active&&document.visibilityState==='visible')load().catch(e=>{if(active)setError(e.message);});};update();const timer=setInterval(update,30000);window.addEventListener('focus',update);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',update);};},[load,revision]);
 async function open(row:any){setSelected(row);setOptions(null);setTarget('');setError('');try{const d=await request('family-finance/'+row.family_id);setOptions(d);setBook(d.defaultBookId||'');}catch(e){setError((e as Error).message);}}
 async function confirm(){setBusy(true);setError('');try{await request('family-finance/'+selected.family_id,{operation:'confirm',id:selected.id,targetId:target,displayBookId:book||null});setSelected(null);await load();await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!data.total&&!error)return null;
 return <section className="panel home-inbox"><div className="panel-title"><h2><Inbox size={22}/>待收款 <small>{data.total||''}</small></h2><button className="text-button" onClick={()=>load().catch(e=>setError(e.message))}>刷新</button></div>{error&&!selected&&<p role="alert" className="error">{error}</p>}{data.rows.map((r:any)=><article key={r.id} className="home-inbox-row"><div><strong>{r.sender_name} <span className="income">+{formatMoney(r.amount)}</span></strong><small>{r.family_name} · {r.date}</small>{r.note&&<p>{r.note}</p>}</div><button onClick={()=>open(r)}><Check size={16}/>收款</button></article>)}{data.total>5&&<div className="pagination"><button className="secondary" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-5))}>上一页</button><span>{offset+1}–{Math.min(offset+5,data.total)} / {data.total}</span><button className="secondary" disabled={offset+5>=data.total} onClick={()=>setOffset(v=>v+5)}>下一页</button></div>}{selected&&<Sheet title="确认到账" onClose={()=>{if(!busy)setSelected(null);}}><p>{selected.sender_name} · {formatMoney(selected.amount)}</p>{options?<><label>实际到账钱包<VisualSelect label="实际到账钱包" value={target} onChange={setTarget} options={[{value:'',label:'请选择到账钱包'},...options.wallets.filter((w:any)=>w.owner_id===options.userId).map((w:any)=>({value:w.id,label:w.name+(w.suffix?' · '+w.suffix:''),account:true,accountName:w.institution||w.name}))]}/></label><label>记入我的账本<VisualSelect label="记入我的账本" value={book} onChange={setBook} options={[{value:'',label:'暂不展示在个人账本'},...options.books.map((b:any)=>({value:b.id,label:b.name,icon:b.icon}))]}/></label><button disabled={busy||!target} onClick={confirm}>{busy?'正在确认…':'确认到账'}</button></>:<p>正在读取我的钱包…</p>}{error&&<p role="alert" className="error">{error}</p>}</Sheet>}</section>;
}
