'use client';
import {DetailSortSelect} from './DetailSortSelect';
import type {DetailSort} from '@/lib/detail-sort';
import {useEffect,useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,PieChart,Pie,Cell,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {ChartNoAxesColumn,ChartPie,ChartLine,ChevronRight,ArrowLeft} from 'lucide-react';
import {ChartTransactionDetail} from './ChartTransactionDetail';
import {Sheet} from './Sheet';
import {CategoryIcon} from './VisualSelect';
import {useI18n} from './LanguageProvider';
import {shortChartLabel,chartAmount} from '@/lib/chart-labels';
import type {ChartArtifact} from '@/server/finance-agent';
import {LIST_PAGE_SIZE} from '@/lib/pagination';
import {chartDetailParams} from '@/lib/finance-query';
const palette=['#8873c7','#ed9975','#639bc6','#d9b44c','#c679a4','#60a899','#939bd1','#bc9378'];
export function FinanceChart({chart,valueLabel}:{chart:ChartArtifact;valueLabel?:string}){
 const [sort,setSort]=useState<DetailSort>('date_desc');
 const {t,locale}=useI18n();const [type,setType]=useState(chart.type),[point,setPoint]=useState<{name:string;value:number}|null>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[offset,setOffset]=useState(0),[detail,setDetail]=useState<any>(null);
 const money=(n:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:chart.unit||'CNY'}).format(n);const canDrill=!!chart.dimension&&!!chart.books?.length;
 const en=locale.startsWith('en'),quantity=chart.metric==='quantity',itemMetric=['item_amount','unit_price','quantity'].includes(chart.metric||'');
 const format=(n:number)=>quantity?new Intl.NumberFormat(locale,{maximumFractionDigits:3}).format(n):money(n);
 const metricLabel=valueLabel||chart.valueLabel||(quantity?(en?'Item quantity':'商品数量'):chart.metric==='unit_price'?(en?'Quantity-weighted unit price':'按数量加权的商品单价'):chart.metric==='item_amount'?(en?'Recorded item subtotal':'已记录商品小计'):chart.metric==='income'?(en?'Income':'收入'):(en?'Net expense':'净支出'));
 const conditions=[chart.filters?.category,chart.filters?.query,chart.filters?.payee,chart.filters?.product,chart.filters?.platform].filter(Boolean).join(' · ');
 useEffect(()=>{if(!point||!canDrill)return;const abort=new AbortController();setResult(null);setError('');const p=chartDetailParams(chart,point.name,offset,LIST_PAGE_SIZE);p.set('sort',sort);fetch(`/api/books/${chart.books![0]}/chart-details?${p}`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(setResult).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[point,offset,sort,chart.from,chart.to,chart.dimension,chart.scope,chart.metric,JSON.stringify(chart.filters),chart.books?.join(','),canDrill]);
 const select=(d:any)=>{if(!canDrill)return;const value=d?.payload||d;if(typeof value?.name==='string'){setPoint({name:value.name,value:value.value});setOffset(0);setDetail(null);}};
 const total=chart.data.reduce((n,d)=>n+d.value,0),negative=chart.data.some(d=>d.value<0),noPie=negative||quantity||chart.metric==='unit_price';const actualType=type==='pie'&&noPie?'bar':type;
 const tip=<Tooltip contentStyle={{borderRadius:12,border:'1px solid #ddd',fontSize:12}} formatter={v=>[format(Number(v)),metricLabel]}/>;
 return <figure className="finance-chart interactive-chart"><figcaption><div><strong>{chart.title}</strong><small>{chart.from} — {chart.to} · {quantity?metricLabel:chart.unit} · {metricLabel}</small>{conditions&&<small>{conditions}</small>}{itemMetric&&<small>{en?'Item evidence only; order discounts and fees are not allocated. Missing values are excluded.':'仅按商品明细计算；整单优惠与手续费不摊入商品，缺失值不视为零。'}</small>}{chart.warnings?.filter(w=>w.startsWith('unknown')).map(w=><small key={w}>{({unknownAmounts:en?'Missing subtotal':'缺少小计',unknownQuantities:en?'Missing quantity':'缺少数量',unknownPrices:en?'Missing unit price':'缺少单价'} as Record<string,string>)[w.split(':')[0]]}: {w.split(':')[1]}</small>)}</div><div className="chart-view-toggle">{([['pie',ChartPie,'环形图'],['bar',ChartNoAxesColumn,'条形图'],['line',ChartLine,'折线图']] as const).map(([v,Icon,label])=><button type="button" key={v} aria-label={t(label)} title={t(label)} aria-pressed={actualType===v} disabled={v==='pie'&&noPie} onClick={()=>setType(v)}><Icon size={17}/></button>)}</div></figcaption>
 {!chart.data.length?<p>{t('此范围暂无记录')}</p>:<><div className="interactive-chart-plot"><ResponsiveContainer>{actualType==='pie'?<PieChart><Pie data={chart.data} dataKey="value" nameKey="name" innerRadius="56%" outerRadius="85%" paddingAngle={chart.data.length>1?2:0} onClick={select} isAnimationActive={false} style={{cursor:canDrill?'pointer':'default'}}>{chart.data.map((d,i)=><Cell key={d.name} fill={palette[i%palette.length]}/>)}</Pie>{tip}</PieChart>:actualType==='line'?<LineChart data={chart.data} onClick={(s:any)=>{if(s?.activePayload?.[0])select(s.activePayload[0]);}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#ddd"/><XAxis dataKey="name" tickFormatter={shortChartLabel} minTickGap={25} tick={{fontSize:11}}/><YAxis width={55} tickFormatter={chartAmount} tick={{fontSize:11}}/>{tip}<Line dataKey="value" stroke={palette[0]} strokeWidth={3} dot={{r:3}} activeDot={{r:7,onClick:(_e:any,p:any)=>select(p)}} isAnimationActive={false}/></LineChart>:<BarChart data={chart.data}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#ddd"/><XAxis dataKey="name" tickFormatter={shortChartLabel} minTickGap={25} tick={{fontSize:11}}/><YAxis width={55} tickFormatter={chartAmount} tick={{fontSize:11}}/>{tip}<Bar dataKey="value" radius={[6,6,0,0]} onClick={select} isAnimationActive={false} cursor={canDrill?'pointer':'default'}>{chart.data.map((d,i)=><Cell key={d.name} fill={palette[i%palette.length]}/>)}</Bar></BarChart>}</ResponsiveContainer></div>
 <div className="chart-data-legend">{chart.data.map((d,i)=><button type="button" key={d.name} disabled={!canDrill} onClick={()=>select(d)}><i style={{background:palette[i%palette.length]}}/>{chart.dimension==='category'&&<CategoryIcon name={d.name} size={24}/>}<span>{d.name||(en?'Not recorded':'未填写')}</span><strong>{format(d.value)}</strong>{actualType==='pie'&&total>0&&<small>{(d.value/total*100).toFixed(1)}%</small>}{canDrill&&<ChevronRight size={14}/>}</button>)}</div></>}
 {point&&<Sheet title={detail?(detail.title||detail.payee||t('账单明细')):point.name} onClose={()=>setPoint(null)}>{detail?<><button className="text-button" onClick={()=>setDetail(null)}><ArrowLeft size={16}/>{t('返回列表')}</button><ChartTransactionDetail row={detail} money={money}/></>:<><p className="muted">{metricLabel} {format(point.value)} · {t('以下为当前账目')}</p><DetailSortSelect value={sort} valueLabel={quantity?(en?'Quantity':'数量'):chart.metric==='unit_price'?(en?'Unit price':'单价'):undefined} onChange={v=>{setSort(v);setOffset(0);}}/>{error?<p role="alert">{error}</p>:!result?<p role="status">{t('正在加载…')}</p>:<><p>{t('当前合计')} {itemMetric?(result.totals.value==null?(en?'Unknown':'未知'):format(Number(result.totals.value)/(quantity?1:100))):money((chart.metric==='income'||chart.dimension?.endsWith('income')?Number(result.totals.income):Number(result.totals.expense)-Number(result.totals.refund))/100)} · {result.totals.count} {t('笔')}</p><div className="chart-drill-list">{result.rows.map((r:any)=><button type="button" key={r.item_key||r.cost_row_key||r.id} onClick={()=>setDetail(r)}><CategoryIcon name={r.category} size={28}/><span><strong>{r.item_name||r.title||r.payee||r.category}</strong><small>{r.date?.slice(0,10)} · {r.account_name}</small></span><b>{itemMetric?(r[quantity?'item_quantity':chart.metric==='unit_price'?'item_unit_price':'item_amount']==null?(en?'Unknown':'未知'):format(Number(r[quantity?'item_quantity':chart.metric==='unit_price'?'item_unit_price':'item_amount'])/(quantity?1:100))):`${r.kind==='refund'?'-':''}${money(r.amount/100)}`}</b><ChevronRight size={15}/></button>)}</div><div className="chart-drill-pages"><button disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-LIST_PAGE_SIZE))}>{t('上一页')}</button><button disabled={offset+LIST_PAGE_SIZE>=result.totals.count} onClick={()=>setOffset(v=>v+LIST_PAGE_SIZE)}>{t('下一页')}</button></div></>}</>}</Sheet>}
 </figure>;
}
