'use client';
import {useEffect,useState} from 'react';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,PieChart,Pie,Cell,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import {ChartNoAxesColumn,ChartPie,ChartLine,ChevronRight,ArrowLeft} from 'lucide-react';
import {Sheet} from './Sheet';
import {CategoryIcon} from './VisualSelect';
import {useI18n} from './LanguageProvider';
import {shortChartLabel,chartAmount} from '@/lib/chart-labels';
import type {ChartArtifact} from '@/server/finance-agent';
import {LIST_PAGE_SIZE} from '@/lib/pagination';
const palette=['#8873c7','#ed9975','#639bc6','#d9b44c','#c679a4','#60a899','#939bd1','#bc9378'];
export function FinanceChart({chart}:{chart:ChartArtifact}){
 const {t,locale}=useI18n();const [type,setType]=useState(chart.type),[point,setPoint]=useState<{name:string;value:number}|null>(null),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[offset,setOffset]=useState(0),[detail,setDetail]=useState<any>(null);
 const money=(n:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:chart.unit||'CNY'}).format(n);const canDrill=!!chart.dimension&&!!chart.books?.length;
 useEffect(()=>{if(!point||!canDrill)return;const abort=new AbortController();setResult(null);setError('');const p=new URLSearchParams({from:chart.from,to:chart.to,limit:String(LIST_PAGE_SIZE),offset:String(offset),kind:chart.dimension?.endsWith('income')?'income':'net_expense'});chart.books!.forEach(b=>p.append('book',b));if(chart.dimension==='category')p.set('category',point.name);else {const from=point.name.length===7?point.name+'-01':point.name;const to=point.name.length===7?new Date(Date.UTC(Number(point.name.slice(0,4)),Number(point.name.slice(5,7)),0)).toISOString().slice(0,10):point.name;p.set('from',from>chart.from?from:chart.from);p.set('to',to<chart.to?to:chart.to);}fetch(`/api/books/${chart.books![0]}/chart-details?${p}`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(setResult).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[point,offset,chart.from,chart.to,chart.dimension,chart.books?.join(','),canDrill]);
 const select=(d:any)=>{if(!canDrill)return;const value=d?.payload||d;if(typeof value?.name==='string'){setPoint({name:value.name,value:value.value});setOffset(0);setDetail(null);}};
 const total=chart.data.reduce((n,d)=>n+d.value,0),negative=chart.data.some(d=>d.value<0);const actualType=type==='pie'&&negative?'bar':type;
 const tip=<Tooltip contentStyle={{borderRadius:12,border:'1px solid #ddd',fontSize:12}} formatter={v=>money(Number(v))}/>;
 return <figure className="finance-chart interactive-chart"><figcaption><div><strong>{chart.title}</strong><small>{chart.from} — {chart.to} · {chart.unit}</small></div><div className="chart-view-toggle">{([['pie',ChartPie,'环形图'],['bar',ChartNoAxesColumn,'条形图'],['line',ChartLine,'折线图']] as const).map(([v,Icon,label])=><button type="button" key={v} aria-label={t(label)} title={t(label)} aria-pressed={actualType===v} disabled={v==='pie'&&negative} onClick={()=>setType(v)}><Icon size={17}/></button>)}</div></figcaption>
 {!chart.data.length?<p>{t('此范围暂无记录')}</p>:<><div className="interactive-chart-plot"><ResponsiveContainer>{actualType==='pie'?<PieChart><Pie data={chart.data} dataKey="value" nameKey="name" innerRadius="56%" outerRadius="85%" paddingAngle={chart.data.length>1?2:0} onClick={select} isAnimationActive={false} style={{cursor:canDrill?'pointer':'default'}}>{chart.data.map((d,i)=><Cell key={d.name} fill={palette[i%palette.length]}/>)}</Pie>{tip}</PieChart>:actualType==='line'?<LineChart data={chart.data} onClick={(s:any)=>{if(s?.activePayload?.[0])select(s.activePayload[0]);}}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#ddd"/><XAxis dataKey="name" tickFormatter={shortChartLabel} minTickGap={25} tick={{fontSize:11}}/><YAxis width={55} tickFormatter={chartAmount} tick={{fontSize:11}}/>{tip}<Line dataKey="value" stroke={palette[0]} strokeWidth={3} dot={{r:3}} activeDot={{r:7,onClick:(_e:any,p:any)=>select(p)}} isAnimationActive={false}/></LineChart>:<BarChart data={chart.data}><CartesianGrid vertical={false} strokeDasharray="3 5" stroke="#ddd"/><XAxis dataKey="name" tickFormatter={shortChartLabel} minTickGap={25} tick={{fontSize:11}}/><YAxis width={55} tickFormatter={chartAmount} tick={{fontSize:11}}/>{tip}<Bar dataKey="value" radius={[6,6,0,0]} onClick={select} isAnimationActive={false} cursor={canDrill?'pointer':'default'}>{chart.data.map((d,i)=><Cell key={d.name} fill={palette[i%palette.length]}/>)}</Bar></BarChart>}</ResponsiveContainer></div>
 <div className="chart-data-legend">{chart.data.map((d,i)=><button type="button" key={d.name} disabled={!canDrill} onClick={()=>select(d)}><i style={{background:palette[i%palette.length]}}/>{chart.dimension==='category'&&<CategoryIcon name={d.name} size={24}/>}<span>{d.name}</span><strong>{money(d.value)}</strong>{actualType==='pie'&&total>0&&<small>{(d.value/total*100).toFixed(1)}%</small>}{canDrill&&<ChevronRight size={14}/>}</button>)}</div></>}
 {point&&<Sheet title={detail?(detail.title||detail.payee||t('账单明细')):point.name} onClose={()=>setPoint(null)}>{detail?<><button className="text-button" onClick={()=>setDetail(null)}><ArrowLeft size={16}/>{t('返回列表')}</button><h2>{money(detail.amount/100)}</h2><p>{detail.date?.slice(0,10)} · {detail.category} · {detail.account_name}</p>{detail.note&&<p>{detail.note}</p>}<div className="chart-drill-items">{(detail.line_items||[]).map((item:any,i:number)=><div key={i}><span>{item.name}{item.quantity!=null?` × ${item.quantity}`:''}</span><strong>{item.amount==null?'—':money(item.amount/100)}</strong></div>)}</div></>:<><p className="muted">{t('图表金额')} {money(point.value)} · {t('以下为当前账目')}</p>{error?<p role="alert">{error}</p>:!result?<p role="status">{t('正在加载…')}</p>:<><p>{t('当前合计')} {money((Number(result.totals.income)||Number(result.totals.expense)-Number(result.totals.refund))/100)} · {result.totals.count} {t('笔')}</p><div className="chart-drill-list">{result.rows.map((r:any)=><button type="button" key={r.id} onClick={()=>setDetail(r)}><CategoryIcon name={r.category} size={28}/><span><strong>{r.title||r.payee||r.category}</strong><small>{r.date?.slice(0,10)} · {r.account_name}</small></span><b>{r.kind==='refund'?'-':''}{money(r.amount/100)}</b><ChevronRight size={15}/></button>)}</div><div className="chart-drill-pages"><button disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-LIST_PAGE_SIZE))}>{t('上一页')}</button><button disabled={offset+LIST_PAGE_SIZE>=result.totals.count} onClick={()=>setOffset(v=>v+LIST_PAGE_SIZE)}>{t('下一页')}</button></div></>}</>}</Sheet>}
 </figure>;
}
