'use client';
import {PagedList} from './PagedList';

import {getLocale} from '@/lib/i18n';
import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import {ListTodo,LoaderCircle,CheckCircle2,XCircle} from 'lucide-react';
import {Sheet} from './Sheet';
import {FinanceNarrative} from './FinanceNarrative';
import type {Draft} from './DraftReview';
type Job={id:string;kind:string;status:string;stage:string;error:string;book_id:string;book_name:string;created_at:string;result?:any};
async function request(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export function JobPanel({book,onDrafts}:{book:string;onDrafts:(drafts:Draft[])=>void}){const {t:tr,locale}=useI18n();
 const [jobs,setJobs]=useState<Job[]>([]),[open,setOpen]=useState(false),[selected,setSelected]=useState<Job|null>(null),[error,setError]=useState('');
 async function refresh(){setJobs(await request('jobs'));}
 useEffect(()=>{let alive=true;const load=()=>request('jobs').then(j=>{if(alive)setJobs(j);}).catch(()=>{});load();const t=setInterval(load,2500);return()=>{alive=false;clearInterval(t);};},[]);
 const count=jobs.filter(j=>['queued','running'].includes(j.status)).length;
 return <><button className="secondary task-trigger" aria-label={tr("后台任务{0}",[count?(locale==='en'?`, ${count} processing`:tr("，{0}个处理中",[count])):tr('暂无进行中的任务')])}  onClick={()=>{setOpen(true);refresh().catch(e=>setError(e.message));}}><ListTodo size={18}/><span className="task-label">{tr("后台任务")}</span>{count>0&&<span className="task-count">{count}</span>}</button>{open&&<Sheet title={tr("后台任务")} onClose={()=>setOpen(false)}><p className="muted">{tr("关闭网页后继续处理，结果保存在这里。")}</p>{error&&<p className="error">{tr(error)}</p>}<div className="job-list">{!jobs.length&&<p>{tr("暂无任务")}</p>}{<PagedList items={jobs}>{j=><article className="job-card" key={j.id}><div className="panel-title"><strong>{j.status==='running'?<LoaderCircle className="spinning" size={17}/>:j.status==='complete'?<CheckCircle2 size={17}/>:j.status==='error'?<XCircle size={17}/>:<ListTodo size={17}/>} {tr(({assistant:'账单识别',chat:'财务对话',connection:'连接测试',memory:'记忆整理'} as any)[j.kind])}</strong><small>{tr(({queued:'排队中',running:'处理中',complete:'已完成',error:'未完成',cancelled:'已取消'} as any)[j.status])}</small></div><p>{tr(j.stage)}</p><small>{(j.book_name || tr("系统设置"))} · {new Date(j.created_at).toLocaleString(getLocale())}</small><div className="inline">{['error','cancelled'].includes(j.status)&&<button className="secondary" onClick={()=>request('jobs/'+j.id,{operation:'retry'}).then(refresh).catch(e=>setError(e.message))}>{j.kind==='chat'?tr("重新生成回答"):tr("从已完成进度重试")}</button>}{['queued','running'].includes(j.status)?<button className="text-button" onClick={()=>request('jobs/'+j.id,{operation:'cancel'}).then(refresh).catch(e=>setError(e.message))}>{tr("取消任务")}</button>:<button className="text-button" onClick={()=>request('jobs/'+j.id).then(setSelected).catch(e=>setError(e.message))}>{tr("查看结果")}</button>}</div></article>}</PagedList>}</div></Sheet>}{selected&&<Sheet title={tr("任务结果")} onClose={()=>setSelected(null)}>{selected.error&&<p className="error">{tr(selected.error)}</p>}{selected.kind==='chat'&&selected.result&&<FinanceNarrative text={selected.result.text} artifacts={selected.result.artifacts}/>}<p>{(selected.result?.message || (!selected.error&&selected.kind==='connection'?'模型连接成功':''))}</p>{(selected.result?.entries||selected.result?.artifacts?.drafts)?.length>0&&<><p>{tr("共")}{(selected.result.entries||selected.result.artifacts.drafts).length} {tr("笔待确认草稿")}</p>{selected.book_id===book?<button onClick={()=>{onDrafts(selected.result.entries||selected.result.artifacts.drafts);setSelected(null);setOpen(false);}}>{tr("打开草稿核对")}</button>:<p>{tr("请切换到任务所属账本后打开草稿。")}</p>}</>}</Sheet>}</>;
}
export function QueueSettings(){const {t:tr,locale}=useI18n();const [n,setN]=useState(2),[message,setMessage]=useState('');useEffect(()=>{request('queue-settings').then(d=>setN(d.concurrency)).catch(e=>setMessage(e.message));},[]);return <section className="panel"><h2>{tr("后台任务")}</h2><form onSubmit={async e=>{e.preventDefault();const r=await fetch('/api/queue-settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({concurrency:n})});const d=await r.json();setMessage(r.ok?'并发数量已更新':d.error);}}><label>{tr("同时处理的任务数")}<input type="number" min={1} max={8} step={1} value={n} onChange={e=>setN(Number(e.target.value))}/></label><></><button>{tr("保存并发设置")}</button>{message&&<p role="status">{tr(message)}</p>}</form></section>;}
