'use client';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {uploadReceipt} from '@/lib/upload-receipt';
import {useEffect,useRef,useState} from 'react';
import {Plus,Trash2,Camera} from 'lucide-react';
import {itemTotals,settlementTotals,verifyItemTotal,type LineItem} from '@/lib/line-items';
import {amountToCents} from '@/server/model';
import {askAssistant} from '@/lib/assistant-client';
import type {Draft} from './DraftReview';
const money=(n:number)=>formatMoney(n);
function cents(s:string){return s===''?null:(s.startsWith('-')?-amountToCents(s.slice(1)):amountToCents(s));}
function Verification({items,total}:{items:LineItem[];total:number}){const {t:tr,locale}=useI18n();const check=verifyItemTotal(items,total);if(check.status==='none')return null;return <span className={check.status==='verified'?'income':'expense'} role="status">{check.status==='verified'?tr("✓ 明细合计与实付一致"):check.status==='incomplete'?tr("待核验：{0}项缺少小计",[check.missing]):tr("核验不一致：差额 {0}，请补充或重新识别小票",[money(check.difference)])}</span>;}
function Settlement({items,total}:{items:LineItem[];total:number}){const {t:tr,locale}=useI18n();const s=settlementTotals(items);return <dl className="settlement-summary"><div><dt>{tr("商品合计")}{s.missing?tr("（待补全）"):''}</dt><dd>{money(s.goods)}</dd></div>{s.discount!==0&&<div><dt>{tr("优惠 / 抹零")}</dt><dd className="income">−{money(s.discount)}</dd></div>}{s.fees!==0&&<div><dt>{tr("包装 / 配送等费用")}</dt><dd>{money(s.fees)}</dd></div>}<div><dt>{tr("结算合计")}</dt><dd>{money(s.net)}</dd></div><div><dt>{tr("实际支付")}</dt><dd>{money(total)}</dd></div></dl>;}
export function LineItemsView({items,total}:{items:LineItem[];total:number}){const {t:tr,locale}=useI18n();const sum=itemTotals(items);if(!items.length)return null;return <section className="item-summary"><h3>{tr("商品与结算明细 ·")}{items.length}{tr("项")}</h3>{items.map((i,n)=><div className="item-summary-row" key={n}><span><strong>{i.name}</strong><small>{i.quantity!==null?tr("数量 {0}",[i.quantity]):''}{i.unitPrice!==null?tr(" · 单价 {0}",[money(i.unitPrice)]):''}</small></span><strong>{i.amount===null?tr("待补充"):money(i.amount)}</strong></div>)}<Settlement items={items} total={total}/><div className="item-reconciliation"><Verification items={items} total={total}/></div></section>;}
export function LineItemsEditor({items,onChange,total,onTotal,book,onBusyChange,onAttachments,onRecognized}:{items:LineItem[];onChange:(items:LineItem[])=>void;total:number;onTotal?:(amount:number)=>void;book?:string;onRecognized?:(draft:Draft)=>void;onAttachments?:(ids:string[])=>void;onBusyChange?:(busy:boolean)=>void}){const {t:tr,locale}=useI18n();
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[found,setFound]=useState<Draft[]>([]),[photos,setPhotos]=useState<{name:string;data:string}[]>([]);const abort=useRef<AbortController|null>(null);useEffect(()=>()=>abort.current?.abort(),[]);const sum=itemTotals(items);
 const change=(index:number,patch:Partial<LineItem>)=>onChange(items.map((i,n)=>n===index?{...i,...patch}:i));
 async function addPhotos(files:File[]){setError('');setFound([]);try{for(const file of files){const added=await uploadReceipt(book!,file);setPhotos(current=>[...current,added]);onAttachments?.([added.data.split('/').at(-1)!]);}}catch{setError('图片读取失败');}}
 async function photo(){if(!photos.length)return;setError('');setFound([]);setBusy(true);onBusyChange?.(true);const controller=new AbortController();abort.current=controller;try{const result=await askAssistant(`books/${book}/assistant`,{text:'这些图片属于同一笔订单，可能有重叠或是长截图。完整归并所有菜品/商品明细、数量、单价及小计，不要把商品拆成多笔交易。',images:photos.map(p=>p.data)},controller.signal,()=>{});const choices=result.entries.filter(e=>e.lineItems?.length);if(!choices.length)throw new Error('没有识别到商品明细，请换一张清晰图片或手动填写。');setFound(choices);}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}finally{setBusy(false);onBusyChange?.(false);}}

 return <details className="line-items-editor" open={((((items.length>0 || photos.length>0) || busy) || found.length>0) || undefined)}><summary>{tr("商品明细")}{items.length?tr(" · {0}项",[items.length]):tr(" · 选填")}</summary><fieldset disabled={busy}>
 {items.map((i,n)=><div className={i.kind==='discount'||i.kind==='fee'||(i.amount??0)<0?'line-item-edit settlement-edit':'line-item-edit'} key={n}><label className="item-name">{i.kind==='discount'||(i.amount??0)<0?tr("优惠 / 抹零名称"):i.kind==='fee'?tr("附加费用名称"):tr("菜品 / 商品")}<input aria-label={tr("第{0}项名称",[n+1])} maxLength={160} placeholder={tr("例如：牛肉面")} value={i.name} onChange={e=>change(n,{name:e.target.value})}/></label>{!i.kind||i.kind==='item'?<><label>{tr("数量")}<input aria-label={tr("第{0}项数量",[n+1])} type="number" min="0.001" step="any" placeholder={tr("选填")} value={(i.quantity ?? '')} onChange={e=>change(n,{quantity:e.target.value===''?null:Number(e.target.value)})}/></label><label>{tr("单价（元）")}<input aria-label={tr("第{0}项单价",[n+1])} type="number" step="0.01" placeholder={tr("选填")} value={i.unitPrice===null?'':i.unitPrice/100} onChange={e=>{try{change(n,{unitPrice:cents(e.target.value)});}catch{}}}/></label></>:null}<label>{i.kind==='discount'||(i.amount??0)<0?tr("减免金额（元）"):tr("小计（元）")}<input aria-label={tr("第{0}项小计",[n+1])} type="number" step="0.01" placeholder={tr("待补充")} min={i.kind==='discount'?'0':undefined} value={i.amount===null?'':i.kind==='discount'||i.amount<0?Math.abs(i.amount)/100:i.amount/100} onChange={e=>{try{const v=cents(e.target.value);change(n,{amount:v===null?null:i.kind==='discount'||(i.amount??0)<0?-Math.abs(v):v});}catch{}}}/></label><div className="item-edit-actions">{(!i.kind||i.kind==='item')&&i.quantity!==null&&i.unitPrice!==null&&<button type="button" className="text-button" onClick={()=>change(n,{amount:Math.round(i.quantity!*i.unitPrice!)})}>{tr("按数量计算")}</button>}<button type="button" className="text-button" aria-label={tr("删除第{0}项",[n+1])} onClick={()=>onChange(items.filter((_,j)=>j!==n))}><Trash2 size={16}/></button></div></div>)}
 <div className="inline"><button type="button" className="secondary" disabled={items.length>=200} onClick={()=>onChange([...items,{name:'',quantity:null,unitPrice:null,amount:null}])}><Plus size={16}/>{tr("添加商品")}</button><button type="button" className="secondary" disabled={items.length>=200} onClick={()=>onChange([...items,{kind:'discount',name:'结算优惠',quantity:null,unitPrice:null,amount:null}])}>{tr("添加优惠 / 抹零")}</button><button type="button" className="text-button" disabled={items.length>=200} onClick={()=>onChange([...items,{kind:'fee',name:'包装 / 配送费',quantity:null,unitPrice:null,amount:null}])}>{tr("添加附加费用")}</button>{book&&<label className="upload"><Camera size={16}/>{tr("添加小票图片")}<input aria-label={tr("上传同一订单的小票图片")} type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';addPhotos(files);}}/></label>}</div>{photos.length>0&&<div className="receipt-photo-queue">{photos.map((p,n)=><div key={n}><span>{(n + 1)}. {p.name}</span><button type="button" className="text-button" disabled={n===0} onClick={()=>{setFound([]);setPhotos(v=>{const a=[...v];[a[n-1],a[n]]=[a[n],a[n-1]];return a;});}}>{tr("上移")}</button><button type="button" className="text-button" onClick={()=>{setFound([]);setPhotos(v=>v.filter((_,i)=>i!==n));}}>{tr("移除")}</button></div>)}<button type="button" onClick={photo}>{tr("合并识别 ·")}{photos.length}{tr("张")}</button></div>}</fieldset>
 {busy&&<p role="status">{tr("正在识别小票…")}<button type="button" className="text-button" onClick={()=>abort.current?.abort()}>{tr("取消")}</button></p>}{error&&<p className="error">{tr(error)}</p>}{found.map(d=><div className="item-photo-result" key={d.id}><LineItemsView items={(d.lineItems || [])} total={d.amount}/><button type="button" className="secondary" onClick={()=>{onChange(d.lineItems||[]);onRecognized?.(d);setFound([]);setPhotos([]);}}>{tr("使用这份明细")}{items.length?tr("（替换当前明细）"):''}</button></div>)}
 {items.length>0&&<Settlement items={items} total={total}/>}
 {items.length>0&&<div className="item-reconciliation"><Verification items={items} total={total}/>{onTotal&&!sum.missing&&sum.known>0&&<button type="button" disabled={busy} className="text-button" onClick={()=>onTotal(sum.known)}>{tr("按结算合计填写实付")}</button>}</div>}
 <details className="usage-help"><summary>{tr("使用说明")}</summary><p>{tr("同一订单可添加多张截图，按顺序合并识别；长图自动分段。明细不重复计入支出。点击“添加优惠 / 抹零”，输入减免金额即可自动扣除。包装或配送费可单列；商品小计若已含优惠，不要再次添加同一优惠。价格不清楚可留空。整单金额以实际支付为准。")}</p></details></details>;
}
