'use client';
import {useI18n} from './LanguageProvider';
import {useState} from 'react';
import type {MemorySuggestion} from '@/lib/memory';
import {memoryFieldLabels} from '@/lib/memory-fields';
export type MemoryFieldResolution={id:string;itemId?:string;field:keyof typeof memoryFieldLabels;useMemory:boolean};
export function MemorySuggestions({suggestions,onChange,name,disabled=false}:{suggestions?:MemorySuggestion[];onChange:(next:MemorySuggestion[],resolution?:MemoryFieldResolution)=>void|Promise<void>;name:string;disabled?:boolean}){
 const {t:tr,locale}=useI18n();
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[sources,setSources]=useState<Record<string,string[]>>({});
 if(!suggestions?.length)return null;
 async function reject(s:MemorySuggestion){setBusy(true);setError('');try{const r=await fetch('/api/memories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'reject',targetId:s.id,name:s.fields.originalName||name})});const v=await r.json();if(!r.ok)throw new Error(v.error);await onChange(suggestions!.filter(v=>v.id!==s.id||v.itemId!==s.itemId));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function change(next:MemorySuggestion[],resolution?:MemoryFieldResolution){setBusy(true);setError('');try{await onChange(next,resolution);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function evidence(id:string){setBusy(true);setError('');try{const r=await fetch('/api/memories?id='+encodeURIComponent(id));const v=await r.json();if(!r.ok)throw new Error(v.error);setSources(p=>({...p,[id]:v.sources.map((s:any)=>[s.date?.slice(0,10),s.title,s.category].filter(Boolean).join(' · '))}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const pages=Math.ceil(suggestions.length/6),current=Math.min(page,pages);
 return <details className="context-details"><summary>{tr("商品记忆 · ")}{suggestions.some(s=>s.status==='matched')?tr('已匹配历史商品'):tr('有相似候选待核对')}</summary><p className="muted">{tr("只关联商品，不复用旧价格、日期、数量或订单号。关联依据不代表本次付款信息。")}</p>{suggestions.slice((current-1)*6,current*6).map(s=><div className="memory-row" key={s.id+(s.itemId||'')}><div><strong>{s.title}</strong><p>{tr(s.reason)}</p>{s.conflicts?.map(c=><p key={c} className="notice">{tr(c)}</p>)}{s.fieldChanges?.map(c=><div key={c.field} className="memory-field-change"><span>{tr(memoryFieldLabels[c.field])}：{c.before||tr('未填写')} → {c.after} · {({applied:tr('已填入'),suggested:tr('建议'),conflict:tr('需选择'),kept:tr('保留本次输入')})[c.state]}</span><div className="memory-actions">{c.state!=='applied'&&<button type="button" disabled={disabled||busy} onClick={()=>change(suggestions,{id:s.id,itemId:s.itemId,field:c.field,useMemory:true})}>{tr("采用此字段")}</button>}<button type="button" disabled={disabled||busy} onClick={()=>change(suggestions,{id:s.id,itemId:s.itemId,field:c.field,useMemory:false})}>{c.state==='applied'?tr('撤回填充'):tr('保留本次')}</button></div></div>)}<small>{s.fields.category||''} · {s.sources.length} {tr(" 条参考来源")}</small>{sources[s.id]&&<p>{sources[s.id].slice(0,5).join('；')||tr('共享记忆不展示私人账单来源')}</p>}</div><div className="memory-actions"><button type="button" className="text-button" disabled={disabled||busy} onClick={()=>evidence(s.id)}>{tr("查看依据")}</button><button type="button" className="secondary" disabled={disabled||busy} onClick={()=>change(suggestions.map(v=>v.itemId===s.itemId&&!!v.fields.product===!!s.fields.product?{...v,conflicts:[],status:v.id===s.id?'matched':'candidate'}:v))}>{s.fields.product?(s.status==='matched'?tr('已选同款'):tr('选择同款')):(s.status==='matched'?tr('已选规则'):tr('采用此规则'))}</button><button type="button" className="text-button" disabled={disabled||busy} onClick={()=>reject(s)}>{tr("不是同款")}</button><button type="button" className="text-button" disabled={disabled||busy} onClick={()=>change(suggestions.filter(v=>v.id!==s.id||v.itemId!==s.itemId))}>{tr("仅本次不使用")}</button></div></div>)}{pages>1&&<div className="memory-actions"><button type="button" disabled={current===1} onClick={()=>setPage(current-1)}>{tr("上一页")}</button><span>{current} / {pages}</span><button type="button" disabled={current===pages} onClick={()=>setPage(current+1)}>{tr("下一页")}</button></div>}{error&&<p role="alert" className="error">{error}</p>}</details>;
}
