'use client';
import {useEffect,useState} from 'react';
import {FolderInput} from 'lucide-react';
import {useI18n} from './LanguageProvider';
import {Sheet} from './Sheet';
import {VisualSelect} from './VisualSelect';
import type {ManagedBook} from './ManagementPages';
type Preview={records:{id:string;version:number;kind:string;title:string;deleted:boolean}[]};
export function OrganizeEntries({book,ids,books,disabled,onSaved}:{book:string;ids:string[];books:ManagedBook[];disabled?:boolean;onSaved:()=>void}){
 const {t:tr}=useI18n();const [open,setOpen]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[target,setTarget]=useState(''),[operation,setOperation]=useState('move'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const key=ids.join(',');
 useEffect(()=>{if(!open)return;const c=new AbortController();setPreview(null);setError('');const q=new URLSearchParams();for(const id of key.split(','))q.append('id',id);fetch(`/api/books/${book}/organize?${q}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setPreview(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[open,book,key]);
 async function save(){if(!preview)return;setBusy(true);setError('');try{const r=await fetch(`/api/books/${book}/organize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids,operation,targetBook:operation==='delete'?undefined:target,versions:Object.fromEntries(preview.records.map(r=>[r.id,r.version]))})});const d=await r.json();if(!r.ok)throw new Error(d.error);setOpen(false);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button type="button" className="secondary" disabled={disabled||!ids.length} onClick={()=>{setOperation('move');setTarget('');setOpen(true);}}><FolderInput size={18}/>{tr('整理账单')}{ids.length>1?` · ${ids.length}`:''}</button>{open&&<Sheet title={tr('整理账单')} onClose={()=>{if(!busy)setOpen(false);}}><div className="organize-options" role="group" aria-label={tr('整理方式')}>{[['move','移动归属'],['copy','关联复制'],['delete','移入回收站']].map(([value,label])=><button className={operation===value?'':'secondary'} type="button" disabled={busy||(value==='copy'&&preview?.records.some(r=>r.kind==='transfer'))} aria-pressed={operation===value} key={value} onClick={()=>setOperation(value)}>{tr(label)}</button>)}</div><p className="muted">{tr(operation==='move'?'从当前账本移出，实际收付款账户不变。':operation==='copy'?'保留原账本，同一笔收支同时展示，总开销与资产不重复计算。':'移除当前账本内的记录，可在回收站恢复。')}</p>{operation!=='delete'&&<label>{tr('目标账本')}<VisualSelect label={tr('目标账本')} disabled={busy} value={target} onChange={setTarget} options={books.filter(b=>b.id!==book&&b.role!=='viewer').map(b=>({value:b.id,label:b.name+' · '+tr(b.kind==='shared'?'共享账本':'个人账本'),icon:b.icon}))}/></label>}{preview?<><p>{tr('将处理 {0} 笔记录',[preview.records.filter(r=>!r.deleted).length])}</p><div className="move-records">{preview.records.filter(r=>!r.deleted).map(r=><div key={r.id}>{r.title}</div>)}</div>{preview.records.filter(r=>!r.deleted).length>ids.length&&<p className="notice">{tr('已包含关联的原消费与退款。')}</p>}<details className="usage-help"><summary>{tr('处理说明')}</summary><p>{tr('原消费与退款一起处理；移动和关联复制保留商品明细、图片与分摊。目标账本成员可以查看这些内容。关联复制遇到已有记录时跳过。')}</p>{operation==='delete'&&<p>{tr('如果这是最后一份记录，删除也会撤销对应的资产收支。')}</p>}</details></>:<p role="status">{tr('正在读取记录…')}</p>}{error&&<p className="error" role="alert">{tr(error)}</p>}<div className="sheet-actions"><button className="secondary" disabled={busy} onClick={()=>setOpen(false)}>{tr('取消')}</button><button disabled={busy||!preview||(operation!=='delete'&&!target)} onClick={save}>{busy?tr('正在处理…'):tr('确认处理')}</button></div></Sheet>}</>;
}
