'use client';
import {SceneFields} from './SceneFields';
import {emptyScene} from '@/lib/entry-scene';
import type {ManagedBook} from './ManagementPages';
import {DateField} from './DateField';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {TransactionPhotos} from './TransactionPhotos';
import {VerificationConfirm} from './VerificationConfirm';
import {accountLabel} from '@/lib/accounts';
import {VisualSelect,SymbolIcon,AccountIcon,CategoryIcon,CategoryIcons} from './VisualSelect';
import {useEffect,useRef,useState} from 'react';
import {LineItemsEditor} from './LineItems';
import type {LineItem} from '@/lib/line-items';
import {RefundPicker} from './RefundPicker';
import {amountToCents} from '@/server/model';
import type {Draft,Original} from './DraftReview';

function id(){const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=bytes[6]&15|64;bytes[8]=bytes[8]&63|128;const h=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
export function QuickEntry({book,books,initial,savedDraft,onDraftChange,categories,accounts,originals,onSave,onCancel}:{book:string;books:ManagedBook[];categories:{name:string;icon:string;archived:boolean}[];initial?:Draft;savedDraft?:Partial<Draft>;onDraftChange?:(draft:Partial<Draft>)=>void;accounts:{id:string;name:string}[];originals:Original[];onSave:(entry:Draft)=>Promise<void>;onCancel:()=>void}){const {t:tr,locale}=useI18n();
 const choices=categories.filter(c=>!c.archived).map(c=>[c.name,c.icon]);
 const pendingId=useRef<string|null>(initial?.id||savedDraft?.id||null),change=useRef(onDraftChange);change.current=onDraftChange;const seed=initial||savedDraft;
 const [destination,setDestination]=useState(seed?.targetBook||book);
 const [occurredAt,setOccurredAt]=useState(seed?.occurredAt||'');
 const [scene,setScene]=useState(seed?.scene||emptyScene());
 const [title,setTitle]=useState(seed?.title||'');
 const [photoIds,setPhotoIds]=useState(seed?.photoIds||[]),[photoBusy,setPhotoBusy]=useState(false);
 const [retainReceipts,setRetainReceipts]=useState(seed?.retainReceipts??false);
 const [verificationReason,setVerificationReason]=useState(seed?.verificationReason||''),[attachmentIds,setAttachmentIds]=useState(seed?.attachmentIds||[]);
 const [lineItems,setLineItems]=useState<LineItem[]>(seed?.lineItems||[]),[recognizing,setRecognizing]=useState(false);
 const [kind,setKind]=useState<Draft['kind']>(seed?.kind||'expense'),[amount,setAmount]=useState(seed?.amount?String(seed.amount/100):''),[date,setDate]=useState(seed?.date||new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'})),[account,setAccount]=useState(seed?.accountId||accounts[0]?.id||''),[target,setTarget]=useState(seed?.targetId||''),[category,setCategory]=useState(seed?.category||choices[0]?.[0]||tr('其他')),[payee,setPayee]=useState(seed?.payee||''),[note,setNote]=useState(seed?.note||''),[product,setProduct]=useState(seed?.product||''),[refund,setRefund]=useState(seed?.refundOf||''),[more,setMore]=useState(!!initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{if(initial)return;let cents=0;try{cents=amount?amountToCents(amount):0;}catch{return;}pendingId.current??=id();change.current?.({targetBook:destination,id:pendingId.current,kind,amount:cents,date,accountId:account,targetId:target,category,payee,note,product,lineItems,verificationReason,attachmentIds,retainReceipts,photoIds,title,scene,occurredAt,refundOf:refund||null});},[kind,amount,date,account,target,category,payee,note,product,refund,lineItems,verificationReason,attachmentIds,retainReceipts,photoIds,title,scene,occurredAt,initial,destination]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy||recognizing||photoBusy)return;setError('');setSaved(false);setBusy(true);try{const cents=amountToCents(amount);if(!cents)throw new Error('请输入大于0的金额');pendingId.current??=initial?.id||id();await onSave({...seed,targetBook:destination,id:pendingId.current,kind,amount:cents,date,accountId:account,targetId:kind==='transfer'?target:null,refundOf:kind==='refund'?refund||null:null,category,payee,note,product,verificationReason,attachmentIds,retainReceipts,photoIds,title,scene,occurredAt,lineItems:kind==='transfer'?[]:lineItems});pendingId.current=null;if(!initial){setAmount('');setTitle('');setScene(emptyScene());setOccurredAt('');setPayee('');setNote('');setProduct('');setLineItems([]);setVerificationReason('');setAttachmentIds([]);setPhotoIds([]);setSaved(true);}}catch(e){setError(e instanceof Error?e.message:'保存未完成，请重试');}finally{setBusy(false);}}
 return <form className="quick-entry" onSubmit={save}><div className="entry-destination"><label>{tr('记入账本')}<VisualSelect label={tr('记入账本')} value={destination} disabled={busy} onChange={setDestination} options={books.filter(b=>b.role!=='viewer').map(b=>({value:b.id,label:b.name+' · '+tr(b.kind==='shared'?'共享账本':'个人账本'),icon:b.icon}))}/></label>{destination!==book&&<p className="muted">{tr(initial?'保存修改时同时移动到账本，实际收付款账户不变。':'保存到所选账本，使用下方的实际收付款账户。')}{(kind==='refund'||initial?.kind==='expense')&&<span>{tr('关联的原消费与退款一起移动。')}</span>}</p>}</div><div className="tabs" role="group" aria-label={tr("记账类型")}>{([['expense','支出'],['income','收入'],['refund','退款'],['transfer','转账']] as const).map(([value,label])=><button type="button" key={value} disabled={busy} className={kind===value?'active':''} onClick={()=>{setKind(value);if(value==='income'&&category==='餐饮')setCategory('工资');if(value==='expense'&&category==='工资')setCategory('餐饮');}}>{tr(label)}</button>)}</div><label className="amount-entry">{kind==='refund'?tr("实际退回多少钱？"):kind==='income'?tr("收到多少钱？"):tr("这一笔多少钱？")}<div><span>{currencySymbol()}</span><input aria-label={tr("金额（元）")} inputMode="decimal" placeholder="0.00" value={amount} required disabled={busy} onChange={e=>setAmount(e.target.value)} autoComplete="off"/></div></label>
 {saved&&<p className="notice" role="status">{tr("这一笔已记好，可以继续记下一笔。")}</p>}
 {kind!=='transfer'&&<><label>{tr("记在哪一类？")}</label><div className="category-picker">{choices.slice(0,more?choices.length:8).map(([value,icon])=><button key={value} type="button" aria-pressed={category===value} className={category===value?'chosen':''} onClick={()=>setCategory(value)}><SymbolIcon icon={icon} size={46}/>{value}</button>)}</div>{!choices.slice(0,more?choices.length:8).some(([value])=>value===category)&&<p className="muted">{tr("已选分类：")}{category}</p>}<button className="text-button" type="button" onClick={()=>setMore(m=>!m)}>{more?tr("收起更多分类"):tr("展开全部分类")}</button></>}
 <div className="form-grid"><label>{kind==='refund'?tr("退款到账日"):tr("交易日期")}<DateField type="date" required value={date} onChange={value=>setDate(value)}/></label><label>{kind==='transfer'?tr("转出账户"):kind==='income'||kind==='refund'?tr("实际到账账户"):tr("实际扣款账户")}<VisualSelect label={tr("资金账户")} value={account} onChange={setAccount} options={accounts.map(a=>({value:a.id,label:accountLabel(a),account:true}))}/></label>{kind==='transfer'&&<label>{tr("转入账户")}<VisualSelect label={tr("请选择转入账户")} value={target} onChange={setTarget} options={accounts.filter(a=>a.id!==account).map(a=>({value:a.id,label:accountLabel(a),account:true}))}/></label>}{kind==='refund'&&<RefundPicker book={book} value={refund} onChange={setRefund} exclude={initial?.id}/>}</div>
<SceneFields value={scene} onChange={(value,title)=>{setScene(value);if(title)setTitle(title);}}/><label>{tr("交易时间（选填）")}<input value={occurredAt} maxLength={30} placeholder="14:30" onChange={e=>setOccurredAt(e.target.value)}/></label><label>{tr("账目标题")}<input value={title} maxLength={80} placeholder={(payee || tr("例如：盒马购物、七鲜买菜、店名 · 晚餐"))} onChange={e=>setTitle(e.target.value)}/></label>
 <label>{kind==='income'?tr("收入来源 / 付款方"):tr("商家 / 交易对方")}<input value={payee} maxLength={120} placeholder={tr("选填，例如：楼下便利店")} onChange={e=>setPayee(e.target.value)}/></label><details open={initial?true:undefined}><summary>{tr("商品与备注")}<span>{tr("选填")}</span></summary><label>{tr("商品摘要")}<input value={product} maxLength={160} onChange={e=>setProduct(e.target.value)}/></label><label>{tr("备注")}<textarea rows={2} value={note} maxLength={2000} placeholder={tr("记一点这笔钱的小故事")} onChange={e=>setNote(e.target.value)}/></label></details>{kind!=='transfer'&&<LineItemsEditor items={lineItems} onChange={setLineItems} total={Number(amount)?Math.round(Number(amount)*100):0} onTotal={n=>setAmount(String(n/100))} book={book} onRecognized={d=>{if(!title)setTitle(d.title||d.payee||'');if(!payee)setPayee(d.payee);}} onBusyChange={setRecognizing} onAttachments={ids=>setAttachmentIds(v=>Array.from(new Set([...v,...ids])))}/>}{kind!=='transfer'&&<VerificationConfirm items={lineItems} total={Math.round(Number(amount)*100)} value={verificationReason} onChange={setVerificationReason}/>}{!!attachmentIds.length&&<label className="receipt-retention"><input type="checkbox" checked={retainReceipts} onChange={e=>setRetainReceipts(e.target.checked)}/>{tr("保存本次上传的图片凭证（")}{attachmentIds.length}{tr("张）")}</label>}{!!attachmentIds.length&&<details className="usage-help"><summary>{tr("图片留存说明")}</summary><p>{tr("保留原分辨率压缩；未勾选的图片上传7天后清理。已保存的历史凭证不受影响。")}</p></details>}<TransactionPhotos book={book} ids={photoIds} onChange={setPhotoIds} disabled={busy} onBusy={setPhotoBusy}/>{error&&<p className="error" role="alert">{tr(error)}</p>}<div className="quick-submit"><button disabled={((busy || recognizing) || photoBusy)}>{busy?tr("正在保存…"):initial?tr("保存修改"):tr("记好了，保存这一笔")}</button>{initial&&<button type="button" className="secondary" disabled={busy} onClick={onCancel}>{tr("取消修改")}</button>}</div></form>;
}
