import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import {TransactionPhotos} from './TransactionPhotos';
export function ReceiptAttachments({book,transaction,canWrite=false,allowRecognize=true,showEmpty=false}:{book:string;transaction:string;canWrite?:boolean;allowRecognize?:boolean;showEmpty?:boolean}){const {t:tr,locale}=useI18n();
 const [message,setMessage]=useState(''),[ready,setReady]=useState(false);
 const [files,setFiles]=useState<{id:string;name:string;purpose:string}[]>([]);
 async function load(){const r=await fetch(`/api/books/${book}/receipts?transaction=${transaction}`);const v=await r.json();if(!r.ok)throw new Error(v.error||'附图加载失败');setFiles(v);setReady(true);}
 useEffect(()=>{setReady(false);setFiles([]);setMessage('');load().catch(e=>setMessage(e.message));},[book,transaction]);
 const receipts=files.filter(f=>f.purpose!=='photo'),photos=files.filter(f=>f.purpose==='photo').map(f=>f.id);
 async function savePhotos(ids:string[]){const added=ids.filter(id=>!photos.includes(id)),removed=photos.filter(id=>!ids.includes(id));for(const [method,list] of [['POST',added],['DELETE',removed]] as const){if(!list.length)continue;const r=await fetch(`/api/books/${book}/photos`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({transaction,ids:list})});const v=await r.json();if(!r.ok)throw new Error(v.error||'附图保存失败');}await load();}
 return <>{receipts.length>0&&<details><summary>{tr("账单凭证 ·")}{receipts.length}{tr("张")}</summary><div className="image-queue">{receipts.map(f=><a key={f.id} href={('/api/receipts/' + f.id)} target="_blank" rel="noreferrer"><img loading="lazy" src={('/api/receipts/' + f.id)} alt={f.name}/><span>{f.name}</span></a>)}</div>{allowRecognize&&<button className="secondary" onClick={async()=>{const r=await fetch(`/api/books/${book}/assistant`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({background:true,text:'重新核对这些凭证的商品明细、实付与重复记录',images:receipts.map(f=>'/api/receipts/'+f.id)})});const d=await r.json();setMessage(r.ok?'已加入后台任务，完成后可打开草稿核对':d.error);}}>{tr("重新识别核验")}</button>}</details>}{showEmpty&&ready&&!files.length&&<p className="muted">{tr("未保存凭证或附图")}</p>}{showEmpty&&!ready&&!message&&<p role="status">{tr("正在加载…")}</p>}{ready&&(!showEmpty||photos.length>0)&&<TransactionPhotos key={transaction} book={book} ids={photos} onChange={canWrite?savePhotos:undefined}/ >}{message&&<p role="status">{tr(message)}</p>}</>;
}
