'use client';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import type {Original} from './DraftReview';
type Choice=Original&{remaining?:number};
export function RefundPicker({book,value,onChange,exclude,local=[]}:{book:string;value:string;onChange:(id:string)=>void;exclude?:string;local?:Original[]}){const {t:tr,locale}=useI18n();
 const [query,setQuery]=useState(''),[results,setResults]=useState<Choice[]>([]),[selected,setSelected]=useState<Choice|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!value){setSelected(null);return;}const draft=local.find(r=>r.id===value);if(draft){setSelected(draft);return;}const abort=new AbortController();fetch('/api/books/'+book+'/refund-options?'+new URLSearchParams({id:value,exclude:exclude||''}),{signal:abort.signal}).then(r=>r.json()).then(rows=>{if(!abort.signal.aborted)setSelected(Array.isArray(rows)?rows[0]||null:null);}).catch(()=>{});return()=>abort.abort();},[book,value,exclude]);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setLoading(true);const timer=setTimeout(()=>{fetch('/api/books/'+book+'/refund-options?'+new URLSearchParams({q:query,exclude:exclude||''}),{signal:abort.signal}).then(async r=>{const rows=await r.json();if(!r.ok)throw new Error(rows.error);if(!abort.signal.aborted)setResults(rows);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);abort.abort();};},[book,query,open,exclude]);
 const choices=Array.from(new Map<string,Choice>([...local.filter(r=>(r.payee+' '+r.product).toLowerCase().includes(query.toLowerCase())),...results].map(r=>[r.id,r])).values());
 return <div className="refund-picker"><span className="muted">{tr("关联原消费")}</span><button type="button" className="secondary" onClick={()=>{setOpen(v=>!v);setError('');}}>{selected?`${selected.date} · ${selected.product||selected.payee} · ${formatMoney(selected.amount)}`:value?tr("原消费不可用，请重新选择"):tr("搜索原消费，或暂不关联")}</button>{open&&<div className="refund-options"><input aria-label={tr("搜索原消费")} placeholder={tr("商家、商品、订单号或日期")} value={query} onChange={e=>{setQuery(e.target.value);setError('');}}/><button type="button" className="text-button" onClick={()=>{onChange('');setOpen(false);}}>{tr("暂不关联原消费")}</button>{error&&<p className="error">{tr(error)}</p>}{loading?<p className="muted">{tr("正在查找…")}</p>:choices.length?choices.map(r=><button type="button" className="refund-option" key={r.id} onClick={()=>{setSelected(r);onChange(r.id);setOpen(false);}}><strong>{((r.product || r.payee) || tr("消费记录"))}</strong><small>{r.date} · {formatMoney(r.amount)}{r.remaining!==undefined?tr(" · 可退 ¥{0}",[(r.remaining/100).toFixed(2)]):tr(" · 本批草稿")}</small></button>):<p className="muted">{tr("没有找到，试试订单号或其他关键词。")}</p>}<small>{tr("显示最多30笔匹配结果，输入关键词可查找更早的记录。")}</small></div>}</div>;
}
