'use client';
import {formatMoney} from '@/lib/deployment';
import {amountToCents} from '@/server/model';
import {refundFromNet} from '@/lib/refund-calculation';
import {useI18n} from './LanguageProvider';
import {useEffect,useState} from 'react';
import type {Original} from './DraftReview';
type Choice=Original&{title?:string;remaining?:number};
export function RefundPicker({book,value,onChange,exclude,local=[],amount,onAmountChange}:{book:string;value:string;onChange:(id:string)=>void;exclude?:string;local?:Original[];amount?:number;onAmountChange?:(amount:number)=>void}){const {t:tr}=useI18n();
 const [query,setQuery]=useState(''),[results,setResults]=useState<Choice[]>([]),[selected,setSelected]=useState<Choice|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [desiredNet,setDesiredNet]=useState(''),[netError,setNetError]=useState('');
 useEffect(()=>{setDesiredNet('');setNetError('');if(!value){setSelected(null);return;}const draft=local.find(r=>r.id===value);if(draft){setSelected(draft);return;}setSelected(current=>current?.id===value?current:null);const abort=new AbortController();fetch('/api/books/'+book+'/refund-options?'+new URLSearchParams({id:value,exclude:exclude||''}),{signal:abort.signal}).then(r=>r.json()).then(rows=>{if(!abort.signal.aborted)setSelected(Array.isArray(rows)?rows[0]||null:null);}).catch(()=>{});return()=>abort.abort();},[book,value,exclude]);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setLoading(true);const timer=setTimeout(()=>{fetch('/api/books/'+book+'/refund-options?'+new URLSearchParams({q:query,exclude:exclude||''}),{signal:abort.signal}).then(async r=>{const rows=await r.json();if(!r.ok)throw new Error(rows.error);if(!abort.signal.aborted)setResults(rows);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);abort.abort();};},[book,query,open,exclude]);
 const choices=Array.from(new Map<string,Choice>([...local.filter(r=>(r.payee+' '+r.product).toLowerCase().includes(query.toLowerCase())),...results].map(r=>[r.id,r])).values());
 const remaining=selected?.remaining;
 const projected=remaining!==undefined&&amount!==undefined?remaining-amount:null;
 function useNet(){if(remaining===undefined||!onAmountChange)return;try{const desired=amountToCents(desiredNet);const refund=refundFromNet(remaining,desired);if(refund===null){setNetError('净支出需低于当前未退金额，且不能小于 0。');return;}onAmountChange(refund);setNetError('');}catch{setNetError('请输入有效金额。');}}
 return <div className="refund-picker"><label className="refund-search-label">{tr('关联原消费 · 搜索已入账订单')}<input type="search" aria-label={tr('搜索已入账订单')} placeholder={tr('商家、商品、订单号、流水号或日期')} value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);setError('');}}/></label>{open&&<div className="refund-options"><button type="button" className="text-button" onClick={()=>setOpen(false)}>{tr('收起结果')}</button>{error&&<p className="error" role="alert">{tr(error)}</p>}{loading?<p className="muted" role="status">{tr('正在查找…')}</p>:choices.length?choices.slice(0,8).map(r=><button type="button" className="refund-option" key={r.id} disabled={r.remaining!==undefined&&r.remaining<=0} onClick={()=>{setSelected(r);onChange(r.id);setOpen(false);setQuery('');}}><strong>{((r.title || r.product || r.payee) || tr('消费记录'))}</strong><small>{r.date} · {formatMoney(r.amount)}{r.remaining!==undefined?(r.remaining>0?tr(' · 尚可退 {0}',[formatMoney(r.remaining)]):tr(' · 已全额退款')):tr(' · 本批草稿')}</small></button>):<p className="muted">{tr('没有找到，试试订单号或其他关键词。')}</p>}<small>{tr('最多显示 8 笔；输入更具体的关键词可查找更早的记录。')}</small></div>}{selected&&<div className="refund-selected" aria-live="polite"><strong>{tr('已关联：')}{selected.title||selected.product||selected.payee||tr('消费记录')}</strong><span>{selected.date} · {tr('原支付')} {formatMoney(selected.amount)}</span>{remaining!==undefined&&<span>{tr('此前已退')} {formatMoney(selected.amount-remaining)} · {tr('当前净支出')} {formatMoney(remaining)}</span>}{amount!==undefined&&amount>0&&<span>{tr('本次退款到账')} {formatMoney(amount)}</span>}{projected!==null&&<span className={projected<0?'error':''}>{tr('本次到账后净支出')} {projected<0?tr('超过可退金额'):formatMoney(projected)}</span>}<button type="button" className="text-button" onClick={()=>{onChange('');setSelected(null);}}>{tr('取消关联')}</button></div>}{!selected&&value&&<p className="error">{tr('原消费不可用，请重新搜索选择。')}</p>}{selected&&remaining!==undefined&&onAmountChange&&<div className="refund-net-input"><label>{tr('也可以按退款后净支出计算')}<input inputMode="decimal" value={desiredNet} placeholder={tr('例如希望最终支出 25.00 元')} onChange={e=>{setDesiredNet(e.target.value);setNetError('');}}/></label><button type="button" className="secondary" onClick={useNet}>{tr('换算为本次退款金额')}</button>{netError&&<small className="error" role="alert">{tr(netError)}</small>}</div>}{!value&&<small className="muted">{tr('找不到原单时可暂不关联；退款仍按实际到账金额单独记录。')}</small>}</div>;
}
