'use client';
import {DateField} from './DateField';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {accountLabel} from '@/lib/accounts';
import {useEffect,useState} from 'react';
import {CopyPlus} from 'lucide-react';
import {VisualSelect} from './VisualSelect';
import type {ManagedBook} from './ManagementPages';
export function ReusePanel({book,id,version,books,onSaved}:{book:string;id:string;version:number;books:ManagedBook[];onSaved:()=>void}){const {t:tr,locale}=useI18n();const [target,setTarget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');return <details className="allocation-editor"><summary><CopyPlus size={18}/>{tr("同时记入另一本账本")}</summary><p className="muted">{tr("将这笔记录的商家、商品、分类、备注及订单信息放入目标账本，目标成员即可查看。各账本独立分类；金额和日期关联，总览只算一次。")}</p><label>{tr("目标账本")}<VisualSelect value={target} onChange={setTarget} options={books.filter(b=>b.id!==book&&b.role!=='viewer').map(b=>({value:b.id,label:b.name,icon:b.icon}))}/></label><p className="entry-book-label">{tr('保留实际付款账户，同一笔交易只扣款一次。')}</p>{error&&<p className="error">{tr(error)}</p>}<button type="button" disabled={(busy || !target)} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch(`/api/books/${book}/reuse`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version,targetBook:target})});const d=await r.json();if(!r.ok)throw new Error(d.error);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{tr("确认复用到所选账本")}</button></details>;}
export function OverviewPage({month,onMonth}:{month:string;onMonth:(m:string)=>void}){const {t:tr,locale}=useI18n();const [data,setData]=useState<{appearances:number;count:number;expense:number;income:number;refund:number}|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();setData(null);fetch('/api/overview?month='+month,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[month]);const yuan=(n:number)=>formatMoney(n);return <><div className="panel-title"><h1>{tr("跨账本总览")}</h1><DateField required aria-label={tr("汇总月份")} type="month" value={month} onChange={value=>onMonth(value)}/></div><details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("汇总你有权限查看的所有账本。同一笔通过“复用”关联的记录只统计一次，账户转账不计收支。这里按实际收付日期统计。")}</p></details>{error&&<p className="error">{tr(error)}</p>}{data&&<><div className="metrics">{[['总收入',data.income],['总净支出',data.expense-data.refund],['收支结余',data.income-data.expense+data.refund]].map(([label,value])=><section className="panel metric" key={tr(label)}><p>{tr(label)}</p><strong>{yuan(Number(value))}</strong></section>)}</div><section className="panel"><h2>{tr("这次统计了什么")}</h2><p>{tr("各账本共展示")}{data.appearances} {tr("条记录，合并为")}{data.count} {tr("笔实际记录，排除")}{data.appearances-data.count} {tr("条重复展示。")}</p><details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("未关联的独立录入不会仅凭金额、日期被合并。分摊费用仍在各账本的月度费用区查看。")}</p></details></section></>}</>;}
