'use client';
import {emptyScene,sceneTitle,type EntryScene} from '@/lib/entry-scene';
import {TrainFront,Utensils,ShoppingBag,Carrot,LayoutGrid,ArrowLeftRight} from 'lucide-react';
import {useI18n} from './LanguageProvider';
export function SceneFields({value,onChange}:{value?:EntryScene;onChange:(value:EntryScene,title:string)=>void}){
 const {t:tr,locale}=useI18n();const s={...emptyScene(),...value};
 const update=(patch:Partial<EntryScene>)=>{const next={...s,...patch};onChange(next,sceneTitle(next,locale==='en'));};
 const options=[['general','通用',LayoutGrid],['transport','交通出行',TrainFront],['dining','餐饮',Utensils],['shopping','购物',ShoppingBag],['groceries','买菜',Carrot]] as const;
 return <section className="scene-fields"><div className="scene-label">{tr('消费场景')}</div><div className="scene-options" role="group" aria-label={tr('消费场景')}>{options.map(([type,label,Icon])=><button type="button" key={type} aria-pressed={s.type===type} onClick={()=>update({...emptyScene(),type})}><Icon size={19}/><span>{tr(label)}</span></button>)}</div>{s.type==='transport'?<div className="scene-details"><div className="scene-transport-modes" role="group" aria-label={tr('交通方式')}>{['地铁','公交','打车','火车'].map(mode=><button type="button" key={mode} aria-pressed={s.transport===tr(mode)||s.transport===mode} onClick={()=>update({transport:tr(mode)})}>{tr(mode)}</button>)}</div><div className="scene-route"><label>{tr('始发站')}<input maxLength={80} value={s.origin} placeholder={tr('从哪里出发')} onChange={e=>update({origin:e.target.value})}/></label><button type="button" className="route-swap" aria-label={tr('交换始发和终点')} onClick={()=>update({origin:s.destination,destination:s.origin})}><ArrowLeftRight size={18}/></button><label>{tr('终点站')}<input maxLength={80} value={s.destination} placeholder={tr('到哪里去')} onChange={e=>update({destination:e.target.value})}/></label></div><details className="scene-custom"><summary>{tr('其他交通方式')}</summary><input aria-label={tr('交通方式')} maxLength={80} value={s.transport} onChange={e=>update({transport:e.target.value})}/></details></div>:s.type!=='general'?<div className="scene-details"><div className="form-grid">{([['merchant','商家简称'],['branch','门店']] as const).map(([key,label])=><label key={key}>{tr(label)}<input maxLength={80} value={s[key]} placeholder={tr('选填')} onChange={e=>update({[key]:e.target.value})}/></label>)}</div>{s.type==='dining'?<><div className="scene-transport-modes" role="group" aria-label={tr('用餐类型')}>{['早餐','午餐','晚餐','夜宵'].map(meal=><button type="button" key={meal} aria-pressed={s.meal===tr(meal)||s.meal===meal} onClick={()=>update({meal:s.meal===tr(meal)?'':tr(meal)})}>{tr(meal)}</button>)}</div><details className="scene-custom"><summary>{tr('自定义用餐类型')}</summary><input aria-label={tr('用餐类型')} value={s.meal} maxLength={80} onChange={e=>update({meal:e.target.value})}/></details></>:<label>{tr('商品概括')}<input value={s.summary} maxLength={80} placeholder={tr('选填')} onChange={e=>update({summary:e.target.value})}/></label>}</div>:null}</section>;
}
