'use client';
import {deployment,formatMoney,currencySymbol} from '@/lib/deployment';
import {useI18n} from './LanguageProvider';
import {accountLabel} from '@/lib/accounts';
import {VisualSelect} from './VisualSelect';
import {useState} from 'react';
import {Sheet} from './Sheet';
import {amountToCents} from '@/server/model';
import type {Draft} from './DraftReview';
export type Template={id:string;name:string;value:Draft;version:number};
export function TemplatesPanel({items,current,accounts,onSave,onDelete,onUse}:{items:Template[];current:Partial<Draft>;accounts:{id:string;name:string}[];onSave:(body:unknown,method:string)=>Promise<void>;onDelete:(id:string)=>Promise<void>;onUse:(value:Draft)=>Promise<void>}){const {t:tr,locale}=useI18n();
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<Template|null>(null),[manage,setManage]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="template-panel"><div className="panel-title"><h3>{tr("常用一笔")}</h3><button className="text-button" onClick={()=>setManage(m=>!m)}>{manage?tr("完成管理"):tr("管理")}</button></div>{error&&!open&&<p className="error">{tr(error)}</p>}<div className="template-chips">{items.map(t=><button type="button" className="secondary" disabled={busy} key={t.id} onClick={()=>{if(manage){setSelected(t);setOpen(true);setError('');}else run(()=>onUse(t.value));}}>{t.name}<small>{formatMoney(t.value.amount)}</small></button>)}<button className="text-button" disabled={(!current.amount || current.kind==='refund')} onClick={()=>{setSelected(null);setOpen(true);setError('');}}>{tr("把当前内容存为常用")}</button></div>{!items.length&&<details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("填好下方金额和账户后，可保存为常用记录。每次使用都会重新核对，不自动扣款。")}</p></details>}{open&&<Sheet title={selected?tr("修改常用记录"):tr("保存常用记录")} onClose={()=>{if(!busy)setOpen(false);}}>{error&&<p className="error" role="alert">{tr(error)}</p>}<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const value=selected?{...selected.value,id:cryptoId(),date:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),amount:amountToCents(String(f.get('amount'))),accountId:String(f.get('accountId')),payee:String(f.get('payee'))}:current;run(()=>onSave({id:selected?.id,version:selected?.version,name:String(f.get('name')),value},selected?'PUT':'POST'));}catch(e){setError((e as Error).message);}}}><label>{tr("叫它什么？")}<input name="name" defaultValue={((selected?.name || current.payee) || '')} maxLength={80} required placeholder={tr("例如：工作日午饭")}/></label>{selected&&<><label>{tr("金额（元）")}<input name="amount" inputMode="decimal" defaultValue={selected.value.amount/100} required/></label><label>{tr("资金账户")}<VisualSelect name="accountId" defaultValue={selected.value.accountId} options={accounts.map(a=>({value:a.id,label:accountLabel(a),account:true}))}/></label><label>{tr("商家")}<input name="payee" defaultValue={selected.value.payee} maxLength={120}/></label></>}<details className="usage-help"><summary>{tr("使用说明")}</summary><p className="muted">{tr("保存金额、分类、账户和备注。使用时自动填写今天的日期，不保留订单号和退款关联。")}</p></details><div className="sheet-actions">{selected&&<button type="button" className="secondary" disabled={busy} onClick={()=>run(()=>onDelete(selected.id))}>{tr("删除常用")}</button>}<button disabled={busy}>{tr("保存")}</button></div></form></Sheet>}</section>;
}
function cryptoId(){const b=crypto.getRandomValues(new Uint8Array(16));b[6]=b[6]&15|64;b[8]=b[8]&63|128;const h=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
