import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID,randomBytes,scryptSync} from 'node:crypto';
const db=new pg.Client({connectionString:process.env.DATABASE_URL});await db.connect();const base=process.env.TEST_ORIGIN||process.env.APP_ORIGIN,uid=randomUUID(),other=randomUUID(),name='accounts_'+uid.slice(0,8),password=randomBytes(16).toString('hex'),salt=randomBytes(16).toString('hex');let book;
async function req(path,method='GET',body,cookie='',status=200){const r=await fetch(base+'/api/'+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});assert.equal(r.status,status,r.status!==status?await r.text():'');return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||''};}
try{for(const [id,n] of [[uid,name],[other,name+'x']])await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$2,$2,$3)',[id,n,salt+':'+scryptSync(password,salt,64).toString('hex')]);const a=(await req('login','POST',{username:name,password})).cookie,b=(await req('login','POST',{username:name+'x',password})).cookie;book=(await req('books','POST',{name:'多账户测试',kind:'private'},a)).data.id;const path='books/'+book;
 const specs=[['工资卡','bank',100000,'1111'],['储蓄卡','bank',200000,'2222'],['日常微信','wechat',1000,'3333'],['日常微信','wechat',2000,'4444'],['个人支付宝','alipay',3000,'5555'],['备用支付宝','alipay',4000,'6666'],['信用卡','credit',-5000,'7777']];for(const [name,type,opening,suffix] of specs)await req(path+'/accounts','POST',{name,type,opening,suffix,holder:'测试持有人',institution:type==='bank'?'测试银行':''},a);
 const accounts=(await req(path+'/accounts','GET',undefined,a)).data;const ids=specs.map(s=>accounts.find(a=>a.suffix===s[3]).id);const post=async(kind,amount,accountId,extra={})=>{const id=randomUUID();await req(path+'/transactions','POST',{entries:[{id,kind,amount,accountId,date:'2026-09-05',payee:kind==='income'?'测试公司':'测试商家',category:kind==='income'?'工资':'餐饮',note:'',...extra}]},a);return id;};
 await post('income',50000,ids[0]);const expense=await post('expense',10000,ids[1]);await post('refund',2000,ids[1],{refundOf:expense});await post('transfer',3000,ids[0],{targetId:ids[3]});await post('transfer',500,ids[2],{targetId:ids[5]});await post('expense',1000,ids[3]);await post('expense',2000,ids[6]);
 const report=(await req(path+'/account-report?from=2026-09-01&to=2026-09-30','GET',undefined,a)).data;assert.deepEqual(report.summary,{bankDeposits:339000,walletAndCash:12000,assets:351000,liabilities:7000,netAssets:344000,income:50000,expense:13000,refund:2000});assert.equal(report.accounts.reduce((n,a)=>n+a.transferIn,0),3500);assert.equal(report.accounts.reduce((n,a)=>n+a.transferOut,0),3500);assert.equal(report.accounts.find(a=>a.id===ids[3]).balance,4000);assert.ok(report.sources.some(s=>s.kind==='income'&&s.counterparty==='测试公司'&&s.amount===50000));
 const past=(await req(path+'/account-report?from=2026-08-01&to=2026-08-31','GET',undefined,a)).data;assert.equal(past.summary.income,0);assert.equal(past.summary.netAssets,344000);await req(path+'/account-report?from=2026-09-01&to=2026-09-30','GET',undefined,b,403);
 await req(path+'/accounts','POST',{name:'无效尾号',suffix:'123456'},a,400);const bank=report.accounts.find(a=>a.id===ids[1]);await req(path+'/accounts','PATCH',{operation:'archive',id:bank.id,version:bank.version,archived:true},a);const archived=(await req(path+'/account-report?from=2026-09-01&to=2026-09-30','GET',undefined,a)).data;assert.equal(archived.summary.bankDeposits,339000);
 const wallet=report.accounts.find(a=>a.id===ids[2]);await req(path+'/accounts','PATCH',{operation:'reconcile',id:wallet.id,version:wallet.version,expectedBalance:wallet.balance,balance:wallet.balance+1000,note:'测试校准'},a);const corrected=(await req(path+'/account-report?from=2026-09-01&to=2026-09-30','GET',undefined,a)).data;assert.equal(corrected.summary.netAssets,345000);assert.equal(corrected.summary.income,50000);
 const records=(await req(path+'/report?from=2026-09-01&to=2026-09-30','GET',undefined,a)).data;assert.equal(records.rows.find(r=>r.target_id===ids[3]).target_account.suffix,'4444');const csv=await fetch(base+'/api/'+path+'/export?from=2026-09-01&to=2026-09-30',{headers:{Cookie:a}});assert.equal(csv.status,200);assert.ok((await csv.text()).includes('尾号4444'));
 console.log('PASS: multiple WeChat/Alipay/bank accounts, deposits/debt, income sources, refunds, internal transfers, archive, reconciliation, dates and access');
}finally{if(book){await db.query('DELETE FROM transactions WHERE book_id=$1 AND kind=\'refund\'',[book]);await db.query('DELETE FROM transactions WHERE book_id=$1',[book]);await db.query('DELETE FROM account_adjustments WHERE book_id=$1',[book]);await db.query('DELETE FROM books WHERE id=$1',[book]);}await db.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[[uid,other]]);await db.query('DELETE FROM login_attempts WHERE username=ANY($1::text[])',[[name,name+'x']]);await db.end();}
