#!/bin/bash
set -euo pipefail
umask 077
cd "$(dirname "$0")/.."
DB_CONTAINER=${DB_CONTAINER:-tallybear-db}
DB_USER=${DB_USER:-tallybear}
DB_NAME=${DB_NAME:-tallybear}
mkdir -p backups/daily data/receipts
exec 9>backups/.backup-lock
flock -n 9 || exit 0
stamp=$(date +%Y%m%d-%H%M%S)
target="backups/daily/.pending-$stamp"
mkdir "$target"
trap 'rm -rf -- "$target"' ERR
docker exec "$DB_CONTAINER" pg_dump -U "$DB_USER" -Fc "$DB_NAME" > "$target/database.dump"
# Temporary recognition inputs are not part of durable vouchers.
docker exec "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT 'receipts/'||id FROM receipt_files WHERE NOT temporary" > "$target/receipt-list"
tar -czf "$target/receipts.tar.gz" -C data -T "$target/receipt-list"
rm "$target/receipt-list"
cp .env "$target/config.env"
readlink current > "$target/release.txt"
mv "$target" "backups/daily/$stamp"
# Only completed backup directories generated by this script are eligible.
find backups/daily -mindepth 1 -maxdepth 1 -type d -name '20??????-??????' -mtime +30 -exec rm -rf -- {} +
printf 'Backup complete: %s\n' "$stamp"
