import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {db} from '../src/server/db';
import {costProjects} from '../src/server/cost-projects';
import {familyFinance} from '../src/server/family-finance';
import {createAccount,listAssets} from '../src/server/accounts';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_cost_test'));
const a=randomUUID(),b=randomUUID(),other=randomUUID(),family=randomUUID(),book=randomUUID(),payment=randomUUID(),project=randomUUID();
const call=(user:string,path:string[]=[],body?:any):Promise<any>=>costProjects(user,body?'POST':'GET',['cost-projects',project,...path],body,new URLSearchParams());
try{
 await db.query(readFileSync('scripts/schema.sql','utf8'));await db.query(readFileSync('scripts/memory-schema.sql','utf8'));
 for(const [id,name] of [[a,'付款测试成员'],[b,'结算测试成员'],[other,'其他成员']])await db.query("INSERT INTO users(id,username,name,password) VALUES($1::uuid,$1::text,$2,'not-a-login')",[id,name]);
 await db.query("INSERT INTO families(id,name,owner_id) VALUES($1,'结算测试家庭',$2)",[family,a]);for(const id of [a,b,other])await db.query('INSERT INTO family_members(family_id,user_id) VALUES($1,$2)',[family,id]);
 await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'结算测试账本','private',$2)",[book,a]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[book,a]);
 const memberBook=randomUUID();await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'成员个人账本','private',$2)",[memberBook,b]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[memberBook,b]);
 const aw=(await createAccount(a,{name:'收款银行卡',opening:1000000})).id,bw=(await createAccount(b,{name:'付款微信',opening:1000000})).id;
 await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,category,created_by) VALUES($1,$2,$3,'expense',430000,'2026-01-15','房租',$4)",[payment,book,aw,a]);
 const plan={title:'结算集成测试房租',category:'房租',familyId:family,sources:[{transactionId:payment,amount:430000}],coverageStart:'2026-01-15',coverageEnd:'2026-02-15',mode:'monthly',startMonth:'2026-01',months:1,periods:[],offsets:[],shares:[{userId:a,amount:290000},{userId:b,amount:140000}]};
 await costProjects(a,'POST',['cost-projects'],{id:project,plan},new URLSearchParams());await call(b,['respond'],{version:1,accept:true});
 const balance=async(user:string)=>(await listAssets(user))[0].balance;
 const id=randomUUID(),transfer={version:1,operation:'create',id,sourceId:bw,recipientId:a,amount:140000,date:'2026-01-15',note:'一月份房租分担'};
 await Promise.all([call(b,['settlement-transfer'],transfer),call(b,['settlement-transfer'],transfer)]);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM family_movements WHERE id=$1',[id])).rows[0].n,1);
 assert.equal(await balance(a),570000);assert.equal(await balance(b),1000000,'Pending transfer does not yet affect balances');
 assert.equal((await call(b)).movements[0].status,'pending');
 await assert.rejects(call(b,['settlement-transfer'],{operation:'confirm',id,targetId:bw}),/收款人/);
 await assert.rejects(call(a,['settlement-transfer'],{operation:'confirm',id,targetId:bw}),/钱包/);
 await assert.rejects(call(other,['settlement-transfer'],{operation:'confirm',id,targetId:aw}),/访问/);
 await call(a,['settlement-transfer'],{operation:'confirm',id,targetId:aw});
 await call(a,['settlement-transfer'],{operation:'confirm',id,targetId:aw});
 await call(b,['settlement-transfer'],transfer);
 assert.equal(await balance(a),710000);assert.equal(await balance(b),860000);
 assert.equal((await call(a)).settlement.every((s:any)=>s.balance===0),true);
 const totals=async(user:string)=>(await costProjects(user,'GET',['cost-projects','report'],{},new URLSearchParams({from:'2026-01-01',to:'2026-01-31'})) as any).totals.cost;
 assert.equal(await totals(a),290000);assert.equal(await totals(b),140000);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE created_by=$1',[a])).rows[0].n,1,'Settlement never creates another expense');
 await assert.rejects(call(b,['settlement-transfer'],{...transfer,amount:130000}),/核对/);
 await assert.rejects(call(b,['settlement-transfer'],{...transfer,id:randomUUID()}),/同日同金额/);
 await assert.rejects(call(b,['settlement-transfer'],{...transfer,id:randomUUID(),recipientId:other}),/承担成员/);
 await assert.rejects(call(b,['settlement-transfer'],{...transfer,id:randomUUID(),sourceId:aw}),/钱包/);
 await assert.rejects(call(b,['settlement-transfer'],{...transfer,id:randomUUID(),date:'2099-01-15'}),/已经发生/);
 const cancelled=randomUUID();await call(b,['settlement-transfer'],{...transfer,id:cancelled,amount:100,date:'2026-01-16'});await call(b,['settlement-transfer'],{operation:'cancel',id:cancelled});assert.equal(await balance(b),860000);
 await assert.rejects(call(a,['settlement-transfer'],{operation:'confirm',id:cancelled,targetId:aw}),/已取消/);
 await assert.rejects(call(b,['settlement-transfer'],{operation:'cancel',id}),/已到账/);
 const general=randomUUID();await call(b,['settlement-transfer'],{...transfer,id:general,amount:100,date:'2026-01-17'});
 await familyFinance(a,family,'POST',{operation:'confirm',id:general,targetId:aw});
 assert.equal((await call(a)).movements.find((m:any)=>m.movement_id===general).status,'confirmed','Existing inbox confirmation automatically settles the linked project');
 assert.equal(await balance(a),710100);assert.equal(await balance(b),859900);
 // Keep one pending synthetic transfer for browser confirmation tests.
 await call(b,['settlement-transfer'],{...transfer,id:randomUUID(),amount:140000,date:'2026-01-18'});
 console.log('Cost settlement passed: one transfer, recipient-only receipt, cancellation, private wallets, automatic linking, unchanged expense and 2900/1400 cost shares.');
}finally{await db.end();}
