import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {db} from '../src/server/db';
import {costSchedules} from '../src/server/cost-schedules';
import {costProjects} from '../src/server/cost-projects';
import {createAccount,listAssets} from '../src/server/accounts';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_cost_test'));
const a=randomUUID(),b=randomUUID(),stranger=randomUUID(),family=randomUUID(),aBook=randomUUID(),bBook=randomUUID(),id=randomUUID();
const call=(u:string,path:string[],body?:any,params=new URLSearchParams()):Promise<any>=>costSchedules(u,body?'POST':'GET',['cost-schedules',...path],body,params);
try{
 await db.query(readFileSync('scripts/schema.sql','utf8'));await db.query(readFileSync('scripts/memory-schema.sql','utf8'));
 for(const [u,name] of [[a,'付款人'],[b,'参与人'],[stranger,'旁观者']])await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$2,$3,\'not-a-login\')',[u,u,name]);
 for(const [book,u] of [[aBook,a],[bBook,b]]){await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'个人测试账本','private',$2)",[book,u]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[book,u]);}
 await db.query("INSERT INTO families(id,name,owner_id) VALUES($1,'周期测试家庭',$2)",[family,a]);for(const u of [a,b])await db.query('INSERT INTO family_members(family_id,user_id) VALUES($1,$2)',[family,u]);
 const account=(await createAccount(a,{name:'测试银行卡',opening:3000000,type:'bank'})).id;
 const rule={title:'季度房租',category:'房租',familyId:family,firstDate:'2026-01-15',months:3,shares:[{userId:a,amount:290000},{userId:b,amount:140000}]};
 const baseline=JSON.stringify(await listAssets(a));await call(a,[],{id,rule,bookId:aBook});
 await call(a,[],{id,rule,bookId:aBook});assert.equal((await call(a,[])).length,1,'Creation retry does not duplicate');
 assert.equal(JSON.stringify(await listAssets(a)),baseline,'Planning does not charge wallet');
 await assert.rejects(call(a,[id,'confirm'],{version:1,dueDate:rule.firstDate,bookId:aBook,accountId:account,paidDate:'2026-01-15'}),/参与人/);
 await assert.rejects(call(b,[id,'respond'],{version:1,accept:true,bookId:aBook}),/账本/);
 await call(b,[id,'respond'],{version:1,accept:true,bookId:bBook});
 assert.equal((await call(stranger,[])).length,0);
 const body={version:2,dueDate:rule.firstDate,bookId:aBook,accountId:account,paidDate:'2026-01-15'};
 const [one,two]=await Promise.all([call(a,[id,'confirm'],body),call(a,[id,'confirm'],body)]);
 assert.equal(one.project_id,two.project_id,'Concurrent confirmation posts once');
 assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE created_by=$1',[a])).rows[0].n,1);
 const balance=(await listAssets(a))[0].balance;assert.equal(balance,1710000);
 const report=await costProjects(b,'GET',['cost-projects','report'],{},new URLSearchParams({from:'2026-01-01',to:'2026-03-31',bookId:bBook}));
 assert.equal((report as any).totals.cost,420000);
 await assert.rejects(costProjects(b,'GET',['cost-projects','report'],{},new URLSearchParams({from:'2026-01-01',to:'2026-03-31',bookId:aBook})),/访问/);
 assert.equal((await call(a,[]))[0].next_date,'2026-04-15');
 const existing=randomUUID();await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,category,created_by) VALUES($1,$2,$3,'expense',1290000,'2026-04-15','房租',$4)",[existing,aBook,account,a]);
 const before=JSON.stringify(await listAssets(a));await call(a,[id,'confirm'],{version:3,dueDate:'2026-04-15',bookId:aBook,transactionId:existing});assert.equal(JSON.stringify(await listAssets(a)),before,'Existing payment is not posted twice');
 await call(a,[id,'pause'],{version:4,paused:true});await assert.rejects(call(a,[id,'confirm'],{version:5,dueDate:'2026-07-15',bookId:aBook,accountId:account,paidDate:'2026-07-15'}),/暂停/);
 await call(a,[id,'pause'],{version:5,paused:false});
 await db.query('DELETE FROM family_members WHERE family_id=$1 AND user_id=$2',[family,b]);await assert.rejects(call(a,[id,'confirm'],{version:6,dueDate:'2026-07-15',bookId:aBook,accountId:account,paidDate:'2026-07-15'}),/家庭/);
 await db.query('INSERT INTO family_members(family_id,user_id) VALUES($1,$2)',[family,b]);
 const prepayId=randomUUID(),today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),tomorrow=new Date(Date.parse(today+'T00:00:00+08:00')+86400000).toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),prepayRule={...rule,title:'预收分摊测试',firstDate:tomorrow,shares:[{userId:a,amount:290000},{userId:b,amount:140000}]};
 const sharedBook=randomUUID();await db.query("INSERT INTO books(id,name,kind,owner_id,family_id) VALUES($1,'家庭测试账本','shared',$2,$3)",[sharedBook,a,family]);for(const u of [a,b])await db.query("INSERT INTO members VALUES($1,$2,'editor')",[sharedBook,u]);
 await call(a,[],{id:prepayId,rule:prepayRule,bookId:sharedBook});await call(b,[prepayId,'respond'],{version:1,accept:true,bookId:sharedBook});
 const transferId=randomUUID();await db.query("INSERT INTO family_movements(id,family_id,sender_id,recipient_id,source_id,kind,amount,date,note,status) VALUES($1,$2,$3,$4,$5,'transfer',420000,$6,'提前转本期分摊','pending')",[transferId,family,b,a,(await createAccount(b,{name:'参与人付款钱包',opening:500000,type:'bank'})).id,today]);
 const aBefore=Number((await listAssets(a)).find((x:any)=>x.id===account).balance);
 const receipt=await call(a,[prepayId,'receive'],{version:2,dueDate:tomorrow,movementId:transferId,targetId:account});assert.equal(receipt.received,420000);assert.equal(Number((await listAssets(a)).find((x:any)=>x.id===account).balance),aBefore+420000,'Early share receipt credits the selected wallet');
 const repeated=await call(a,[prepayId,'receive'],{version:2,dueDate:tomorrow,movementId:transferId,targetId:account});assert.equal(repeated.alreadyReceived,true,'Retry does not credit a receipt twice');
 assert.equal((await db.query('SELECT next_date::text FROM cost_schedules WHERE id=$1',[prepayId])).rows[0].next_date,tomorrow,'Receiving a share does not advance the rent payment schedule');
 const otherProject=await costProjects(a,'GET',['cost-projects',one.project_id],{},new URLSearchParams()) as any;
 await assert.rejects(costProjects(a,'POST',['cost-projects',one.project_id,'settlements'],{version:otherProject.version,movementId:transferId,amount:420000},new URLSearchParams()),/周期计划/);
 await assert.rejects(call(a,[prepayId,'edit'],{version:3,rule:prepayRule,bookId:sharedBook}),/已有成员分摊到账/);
 // Move the fixture clock to its due date without waiting a day.
 await db.query('UPDATE cost_schedule_settlements SET due_date=$2 WHERE schedule_id=$1',[prepayId,today]);await db.query('UPDATE cost_schedules SET next_date=$2,version=version+1 WHERE id=$1',[prepayId,today]);
 const paid=await call(a,[prepayId,'confirm'],{version:4,dueDate:today,bookId:aBook,accountId:account,paidDate:today});
 assert.equal(Number((await db.query('SELECT amount FROM cost_settlements WHERE project_id=$1 AND movement_id=$2',[paid.project_id,transferId])).rows[0].amount),420000,'Early received share is carried into this cycle settlement');
 const settled=await costProjects(b,'GET',['cost-projects',paid.project_id],{},new URLSearchParams()) as any;
 assert.equal(settled.settlement.find((s:any)=>s.userId===b).balance,0,'Paid member has nothing left to settle when the expense is posted');
 const confirmedId=randomUUID(),confirmedPlan=randomUUID();await call(a,[],{id:confirmedPlan,rule:prepayRule,bookId:sharedBook});await call(b,[confirmedPlan,'respond'],{version:1,accept:true,bookId:sharedBook});
 await db.query("INSERT INTO family_movements(id,family_id,sender_id,recipient_id,source_id,target_id,kind,amount,date,status) SELECT $1,family_id,sender_id,recipient_id,source_id,target_id,kind,100000,date,'confirmed' FROM family_movements WHERE id=$2",[confirmedId,transferId]);
 const confirmedBefore=JSON.stringify(await listAssets(a));await call(a,[confirmedPlan,'receive'],{version:2,dueDate:tomorrow,movementId:confirmedId});assert.equal(JSON.stringify(await listAssets(a)),confirmedBefore,'Linking an already received partial share never credits it again');
 const partial=(await call(a,[])).find((s:any)=>s.id===confirmedPlan);assert.equal(partial.received.find((r:any)=>r.user_id===b).amount,100000);
 await call(a,[],{id:randomUUID(),rule:{...rule,title:'未来房租',firstDate:'2099-10-15'},bookId:aBook});
 const future=(await call(a,[])).find((s:any)=>s.rule.title==='未来房租');assert.equal(future.due,false);
 await assert.rejects(call(a,[future.id,'confirm'],{version:1,dueDate:'2099-10-15',bookId:aBook,accountId:account,paidDate:'2099-10-15'}),/未到/);
 const editedRule={...rule,totalCycles:2};
 const editBaseline=JSON.stringify(await listAssets(a));
 await assert.rejects(call(b,[id,'edit'],{version:6,rule:editedRule,bookId:bBook}),/创建人/);
 await assert.rejects(call(a,[id,'edit'],{version:6,rule:{...editedRule,months:1},bookId:aBook}),/已有账期/);
 await assert.rejects(call(a,[id,'edit'],{version:6,rule:{...editedRule,totalCycles:1},bookId:aBook}),/总期数/);
 await call(a,[id,'edit'],{version:6,rule:editedRule,bookId:aBook});
 const completed=(await call(a,[])).find((s:any)=>s.id===id);
 assert.equal(completed.completed,true);assert.equal(completed.due,false);
 assert.ok(completed.members.every((m:any)=>m.accepted),'Shortening retains acceptance');
 await assert.rejects(call(a,[id,'skip'],{version:7,dueDate:'2026-07-15'}),/全部账期/);
 await assert.rejects(call(a,[id,'edit'],{version:6,rule:editedRule,bookId:aBook}),/计划已变化/);
 await call(a,[id,'edit'],{version:7,rule:{...editedRule,totalCycles:3},bookId:aBook});
 assert.equal((await call(a,[])).find((s:any)=>s.id===id).members.find((m:any)=>m.user_id===b).accepted,false,'Extension requires renewed consent');
 await call(b,[id,'respond'],{version:8,accept:true,bookId:bBook});
 await call(a,[id,'skip'],{version:9,dueDate:'2026-07-15'});
 assert.equal((await call(a,[])).find((s:any)=>s.id===id).completed,true,'Skipped cycle counts');
 assert.equal(JSON.stringify(await listAssets(a)),editBaseline,'Editing and skipping never charge wallets');
 assert.equal((await call(a,[id,'history'])).length,3);
 console.log('Cost schedules passed: payments, consent, editing, history preservation, finite cycles, completion, early receipts with shared ledgers, idempotent wallet credits, already received partial shares, reserved transfers and zero remaining settlement.');
}finally{await db.end();}
