import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {db} from '../src/server/db';
import {costProjects} from '../src/server/cost-projects';
import {createAccount,listAssets} from '../src/server/accounts';
import {search} from '../src/server/search';
import type {CostPlan} from '../src/lib/cost-attribution';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_cost_test'),'Use an isolated cost_test database');
const a=randomUUID(),b=randomUUID(),outsider=randomUUID(),family=randomUUID(),book=randomUUID(),expense=randomUUID(),salary=randomUUID();
const route=(user:string,path:string[],method='GET',body:any={},params=new URLSearchParams()):Promise<any>=>costProjects(user,method,['cost-projects',...path],body,params);
try{
 await db.query(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));await db.query(readFileSync(new URL('./cost-projects.sql',import.meta.url),'utf8'));
 await db.query(readFileSync(new URL('./memory-schema.sql',import.meta.url),'utf8'));
 for(const id of [a,b,outsider])await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$2,$3,$4)',[id,id,'Test','not-a-login']);
 await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'Private costs','private',$2)",[book,a]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[book,a]);
 await db.query("INSERT INTO families(id,name,owner_id) VALUES($1,'Cost test family',$2)",[family,a]);for(const id of [a,b])await db.query('INSERT INTO family_members(family_id,user_id) VALUES($1,$2)',[family,id]);
 const account=(await createAccount(a,{name:'Cash',opening:2000000,type:'cash'})).id;
 for(const [id,kind,amount] of [[expense,'expense',1290000],[salary,'income',1000000]])await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,title,created_by,event_id) VALUES($1,$2,$3,$4,$5,'2026-10-15','Cost test',$6,$1)",[id,book,account,kind,amount,a]);
 const balance=JSON.stringify(await listAssets(a));
 const plan:CostPlan={title:'Quarterly rent',category:'Rent',familyId:family,sources:[{transactionId:expense,amount:1290000}],coverageStart:'2026-10-15',coverageEnd:'2027-01-15',mode:'monthly',startMonth:'2026-10',months:3,periods:[],shares:[{userId:a,amount:870000},{userId:b,amount:420000}],offsets:[{id:randomUUID(),transactionId:salary,userId:a,month:'2026-10',amount:150000,shared:false}]};
 const project=await route(a,[],'POST',{plan});let detail=await route(a,[project.id]);assert.equal(detail.pending,true);assert.equal(detail.active,false);
 assert.equal((await route(a,['sources'])).some((s:any)=>s.id===expense),true);
 await assert.rejects(route(outsider,[project.id]));
 const searchParams=new URLSearchParams({entity:'cost_project',id:project.id});assert.equal((await search(a,searchParams)).total,1);assert.equal((await search(outsider,searchParams)).total,0);
 let other=await route(b,[project.id]);assert.equal(other.plan,undefined);assert.deepEqual(other.offsets,[]);assert.equal(other.personal[0].net,140000);assert.equal(other.household[0].offset,0);
 await route(b,[project.id,'respond'],'POST',{version:1,accept:true});detail=await route(a,[project.id]);assert.equal(detail.active,true);assert.equal(detail.pending,false);assert.equal(detail.personal[0].net,140000);
 assert.equal(JSON.stringify(await listAssets(a)),balance,'Allocation must never charge wallets');
 await assert.rejects(route(a,[],'POST',{plan}),/超过/,'Prevent double allocation');
 const changed=structuredClone(plan);changed.offsets[0].amount=200000;await route(a,[project.id],'PUT',{version:1,plan:changed});detail=await route(a,[project.id]);assert.equal(detail.personal[0].net,140000,'Pending proposal must not replace active version');
 await route(b,[project.id,'respond'],'POST',{version:2,accept:true});assert.equal((await route(a,[project.id])).personal[0].net,90000);
 assert.equal(JSON.stringify(await listAssets(a)),balance);
 const bBook=randomUUID(),bIncome=randomUUID(),bAccount=(await createAccount(b,{name:'Personal salary',opening:0,type:'cash'})).id;
 await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'B private','private',$2)",[bBook,b]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[bBook,b]);
 await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,title,created_by,event_id) VALUES($1,$2,$3,'income',500000,'2026-10-20','Private salary',$4,$1)",[bIncome,bBook,bAccount,b]);
 await route(b,[project.id,'personal-offsets'],'POST',{version:2,entries:[{id:randomUUID(),transactionId:bIncome,userId:b,month:'2026-10',amount:10000,shared:false}]});
 assert.equal((await route(b,[project.id])).personal[0].net,130000);assert.deepEqual((await route(a,[project.id])).personalOffsets,[]);
 const sharedReport=await route(a,['report'],'GET',{},new URLSearchParams({from:'2026-10-01',to:'2026-10-31',scope:'shared'}));assert.equal(sharedReport.totals.offset,0,'Private income must not enter shared aggregates');
 await assert.rejects(route(a,[project.id,'personal-offsets'],'POST',{version:3,entries:[{id:randomUUID(),transactionId:bIncome,userId:a,month:'2026-10',amount:1000,shared:false}]}));
 await db.query('UPDATE transactions SET amount=1300000 WHERE id=$1',[expense]);assert.equal((await route(a,[project.id])).valid,false);
 await route(a,[project.id],'PUT',{version:3,plan:changed});assert.equal((await route(a,[project.id])).valid,false,'Editing a changed source must not silently revive the old version');
 await route(b,[project.id,'respond'],'POST',{version:4,accept:true});assert.equal((await route(a,[project.id])).valid,true);
 const movement=randomUUID();await db.query("INSERT INTO family_movements(id,family_id,sender_id,recipient_id,source_id,target_id,kind,amount,date,status) VALUES($1,$2,$3,$4,$5,$6,'transfer',420000,'2026-10-15','confirmed')",[movement,family,b,a,bAccount,account]);
 assert.equal((await route(a,[project.id,'movements'])).some((m:any)=>m.id===movement),true);
 const beforeSettlement=JSON.stringify(await listAssets(a));await route(a,[project.id,'settlements'],'POST',{version:4,movementId:movement,amount:420000});assert.equal((await route(a,[project.id])).settlement.every((s:any)=>s.balance===0),true);assert.equal(JSON.stringify(await listAssets(a)),beforeSettlement,'Linking settlement must not repeat transfer');
 await assert.rejects(route(a,[project.id,'settlements'],'POST',{version:4,movementId:movement,amount:420001}));
 await db.query('DELETE FROM family_members WHERE family_id=$1 AND user_id=$2',[family,b]);await assert.rejects(route(b,[project.id]));
 console.log('Cost integration passed: private ledger, consent, salary portion, privacy, source changes, no balance changes.');
}finally{await db.end();}
