import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import pg from 'pg';
process.loadEnvFile('.env');
const original=process.env.DATABASE_URL!;const admin=new pg.Client({connectionString:original});await admin.connect();const dbName='tallybear_family_test_'+Date.now();await admin.query(`CREATE DATABASE ${dbName}`);const url=new URL(original);url.pathname='/'+dbName;process.env.DATABASE_URL=url.toString();
const {db}=await import('../src/server/db');
try{
 await db.query(readFileSync('scripts/schema.sql','utf8'));
 const {familyFinance:api}=await import('../src/server/family-finance');const {listAssets,accountReport}=await import('../src/server/accounts');
 const [a,b,outsider,f,wa,wb,wf,book,expense]=Array.from({length:9},()=>randomUUID());
 for(const u of [a,b,outsider])await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$2,$2,$2)',[u,u]);
 await db.query("INSERT INTO families(id,name,owner_id) VALUES($1,'test',$2)",[f,a]);for(const u of [a,b])await db.query('INSERT INTO family_members VALUES($1,$2)',[f,u]);
 for(const [id,owner] of [[wa,a],[wb,b]])await db.query("INSERT INTO accounts(id,name,owner_id,ownership,opening) VALUES($1,'private',$2,'personal',1000000)",[id,owner]);
 await db.query("INSERT INTO accounts(id,name,family_id,ownership) VALUES($1,'shared',$2,'shared')",[wf,f]);
 await db.query("INSERT INTO books(id,name,kind,owner_id,family_id) VALUES($1,'home','shared',$2,$3)",[book,b,f]);for(const u of [a,b])await db.query("INSERT INTO members VALUES($1,$2,'editor')",[book,u]);
 await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,created_by) VALUES($1,$2,$3,'expense',300000,'2026-09-16',$4)",[expense,book,wb,b]);
 await api(b,f,'POST',{operation:'shares',transactionId:expense,shares:[{userId:a,amount:150000},{userId:b,amount:150000}]});
 const id=randomUUID(),request={operation:'create',id,sourceId:wa,recipientId:b,kind:'aa',amount:150000,date:'2026-09-16',expenseId:expense};await api(a,f,'POST',request);await api(a,f,'POST',request);
 assert.equal((await listAssets(a)).find(x=>x.id===wa).balance,1000000);
 await assert.rejects(()=>api(a,f,'POST',{operation:'confirm',id,targetId:wa}),/收款人/);
 await assert.rejects(()=>api(outsider,f,'GET',{}),/无权/);
 await api(b,f,'POST',{operation:'confirm',id,targetId:wb});await api(b,f,'POST',{operation:'confirm',id,targetId:wb});
 assert.equal((await listAssets(a)).find(x=>x.id===wa).balance,850000);assert.equal((await listAssets(b)).find(x=>x.id===wb).balance,850000);
 await assert.rejects(()=>api(a,f,'POST',{...request,id:randomUUID()}),/超过|已有/);
 for(const [u,w] of [[a,wa],[b,wb]])await api(u,f,'POST',{operation:'create',id:randomUUID(),sourceId:w,targetId:wf,kind:'contribution',amount:10000,date:'2026-09-16'});
 assert.equal((await listAssets(a)).find(x=>x.id===wf).balance,20000);
 const view=await api(a,f,'GET',{}) as any;assert.ok(!view.wallets.some((x:any)=>x.id===wb));assert.equal(view.movements.filter((x:any)=>x.id===id).length,1);
 const report=await accountReport(b,new URLSearchParams({scope:'personal',from:'2026-09-01',to:'2026-09-30'}));assert.equal(report.summary.expense,300000);assert.equal(report.summary.income,0);
 const loan=randomUUID();await api(a,f,'POST',{operation:'create',id:loan,sourceId:wa,recipientId:b,kind:'loan',amount:5000,date:'2026-09-16'});await api(b,f,'POST',{operation:'confirm',id:loan,targetId:wb});
 const repay={operation:'create',id:randomUUID(),sourceId:wb,recipientId:a,kind:'repayment',loanId:loan,amount:2000,date:'2026-09-16'};await api(b,f,'POST',repay);await api(a,f,'POST',{operation:'confirm',id:repay.id,targetId:wa});
 await assert.rejects(()=>api(b,f,'POST',{...repay,id:randomUUID(),amount:4000}),/超过/);
 await assert.rejects(()=>api(a,f,'POST',{operation:'create',id:randomUUID(),sourceId:wb,recipientId:b,kind:'gift',amount:100,date:'2026-09-16'}),/自己的钱包/);
 const gift=randomUUID();await api(a,f,'POST',{operation:'create',id:gift,sourceId:wa,recipientId:b,kind:'gift',amount:100,date:'2026-09-16'});await api(b,f,'POST',{operation:'cancel',id:gift});
 assert.equal((await listAssets(a)).find(x=>x.id===wa).balance,837000);

 const {prepareChatAction,confirmChatAction,actionMissing}=await import('../src/server/chat-actions');
 const user=(id:string)=>({id,username:id,name:id,admin:false,avatar:'',theme:'bear' as const});
 async function saveCard(uid:string,card:any){const conversation=randomUUID(),turn=randomUUID();await db.query('INSERT INTO finance_conversations(id,book_id,user_id,title) VALUES($1,$2,$3,$4)',[conversation,book,uid,'test']);await db.query("INSERT INTO finance_turns(id,conversation_id,question,status,artifacts) VALUES($1,$2,'test','complete',$3)",[turn,conversation,JSON.stringify({actions:[card]})]);const body={id:conversation,turnId:turn,actionId:card.id,operation:'confirm_action'};await confirmChatAction(book,user(uid),body);await confirmChatAction(book,user(uid),body);}
 const cards:any[]=[];
 const card=await prepareChatAction({kind:'family',data:{operation:'create',familyId:f,sourceId:wa,recipientId:b,kind:'gift',amount:1234,date:'2026-09-17',externalId:'test-ref',platform:'微信'}},{book,user:user(a)},cards);
 assert.deepEqual(card.missing,[]);assert.deepEqual(actionMissing(card),[]);
 await saveCard(a,card);
 assert.equal(Number((await db.query('SELECT count(*) FROM family_movements WHERE id=$1',[card.id])).rows[0].count),1);
 const incoming=await prepareChatAction({kind:'family',data:{operation:'confirm',familyId:f,movementId:card.id,targetId:wb}},{book,user:user(b)},[]);assert.deepEqual(incoming.missing,[]);await saveCard(b,incoming);
 assert.equal((await db.query('SELECT status FROM family_movements WHERE id=$1',[card.id])).rows[0].status,'confirmed');
 const senderView:any=await api(a,f,'GET',{}),receiverView:any=await api(b,f,'GET',{});assert.equal(senderView.movements.find((x:any)=>x.id===card.id).target_id,null);assert.equal(senderView.movements.find((x:any)=>x.id===card.id).target_name,null);assert.equal(receiverView.movements.find((x:any)=>x.id===card.id).source_id,null);assert.equal(receiverView.movements.find((x:any)=>x.id===card.id).source_name,null);
 const wrong=await prepareChatAction({kind:'family',data:{operation:'confirm',familyId:f,movementId:card.id,targetId:wa}},{book,user:user(a)},[]);assert.ok(wrong.missing.length);
 await assert.rejects(()=>api(a,f,'POST',{operation:'create',id:randomUUID(),sourceId:wa,recipientId:b,kind:'gift',amount:1234,date:'2026-09-17'}),/已有/);
 await assert.rejects(()=>api(a,f,'POST',{operation:'create',id:randomUUID(),sourceId:wa,recipientId:b,kind:'gift',amount:1234,date:'2026-09-18',externalId:'test-ref',platform:'微信',allowSimilar:true}),/流水已记录/);
 const missing=await prepareChatAction({kind:'family',data:{operation:'create',familyId:f,kind:'contribution',amount:500}},{book,user:user(a),deviceTime:'2026-09-17T12:00:00+08:00'},[]);assert.ok(missing.missing.includes('转出钱包'));
 const editCards=[card];await prepareChatAction({actionId:card.id,kind:'family',data:{recipientId:null,targetId:wf,kind:'contribution'}},{book,user:user(a)},editCards);assert.equal(editCards[0].data.recipientId,undefined);
 const rollbackId=randomUUID();const {transaction}=await import('../src/server/db');await assert.rejects(()=>transaction(async c=>{await api(a,f,'POST',{operation:'create',id:rollbackId,sourceId:wa,targetId:wf,kind:'contribution',amount:987,date:'2026-09-18'},c);throw new Error('rollback-test');}),/rollback-test/);assert.equal((await db.query('SELECT 1 FROM family_movements WHERE id=$1',[rollbackId])).rowCount,0);

 const [pa,pb,pa2]=[randomUUID(),randomUUID(),randomUUID()];for(const [id,owner] of [[pa,a],[pa2,a],[pb,b]]){await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'private','private',$2)",[id,owner]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[id,owner]);}
 const {bookMovements}=await import('../src/server/family-books');const params=new URLSearchParams({from:'2026-09-01',to:'2026-09-30'});
 const balanceBefore=(await listAssets(a)).find(x=>x.id===wa).balance;
 await api(a,f,'POST',{operation:'display',id:card.id,displayBookId:pa});await api(b,f,'POST',{operation:'display',id:card.id,displayBookId:pb});
 assert.equal((await bookMovements(a,pa,params)).rows[0].direction,'out');assert.equal((await bookMovements(b,pb,params)).rows[0].direction,'in');
 await assert.rejects(()=>api(a,f,'POST',{operation:'display',id:card.id,displayBookId:pb}),/自己的个人账本/);await assert.rejects(()=>bookMovements(a,pb,params),/无权/);
 const privateView:any=await api(a,f,'GET',{});assert.equal(privateView.movements.find((x:any)=>x.id===card.id).displayBookId,pa);assert.ok(!privateView.books.some((x:any)=>x.id===pb));
 await api(a,f,'POST',{operation:'display',id:card.id,displayBookId:pa2});assert.equal((await bookMovements(a,pa,params)).total,0);assert.equal((await bookMovements(a,pa2,params)).total,1);assert.equal((await bookMovements(b,pb,params)).total,1);assert.equal((await listAssets(a)).find(x=>x.id===wa).balance,balanceBefore);
 const next=randomUUID();await api(a,f,'POST',{operation:'create',id:next,sourceId:wa,recipientId:b,kind:'transfer',amount:111,date:'2026-09-19'});assert.equal((await bookMovements(a,pa2,params)).total,2);await api(b,f,'POST',{operation:'confirm',id:next,targetId:wb});assert.equal((await bookMovements(b,pb,params)).total,2);
 await api(a,f,'POST',{operation:'display',id:card.id,displayBookId:null});assert.equal((await bookMovements(a,pa2,params)).total,1);assert.equal((await bookMovements(b,pb,params)).total,2);assert.equal(Number((await db.query('SELECT count(*) FROM transactions')).rows[0].count),1);
 const {report:ledgerReport,exportCSV}=await import('../src/server/reports');
 const {familyInbox}=await import('../src/server/family-inbox');
 const {overview}=await import('../src/server/reuse');
 await api(a,f,'POST',{operation:'display',id:loan,displayBookId:pa});
 await api(a,f,'POST',{operation:'display',id,displayBookId:pa});
 await api(a,f,'POST',{operation:'display',id:card.id,displayBookId:pa});
 assert.equal((await ledgerReport(pa,params)).totals.expense,1234);
 assert.equal((await ledgerReport(pb,params)).totals.income,1234);
 assert.equal((await ledgerReport([pa,pa2],params)).totals.expense,1234);
 assert.equal((await ledgerReport([pa,pb,book],params)).totals.expense,300000);
 assert.equal((await ledgerReport([pa,pb,book],params)).totals.income,0);
 assert.ok((await exportCSV(pa,params)).includes('12.34'));
 assert.equal((await overview(a,new URLSearchParams({month:'2026-09'}))).expense,300000);
 assert.equal((await ledgerReport(pa,new URLSearchParams({...Object.fromEntries(params),kind:'expense'}))).totals.count,1);
 assert.equal((await ledgerReport(pa,new URLSearchParams({...Object.fromEntries(params),category:'人情往来'}))).totals.expense,1234);
 assert.equal((await accountReport(a,new URLSearchParams({...Object.fromEntries(params),scope:'personal'}))).summary.expense,1234);
 assert.equal((await accountReport(b,new URLSearchParams({...Object.fromEntries(params),scope:'personal'}))).summary.income,1234);
 const inboxId=randomUUID();await api(a,f,'POST',{operation:'create',id:inboxId,sourceId:wa,recipientId:b,kind:'gift',amount:222,date:'2026-08-10',displayBookId:pa});
 const inbox=await familyInbox(b,new URLSearchParams());assert.ok(inbox.rows.some((v:any)=>v.id===inboxId));assert.ok(!('source_id' in inbox.rows[0]));assert.ok(!('target_id' in inbox.rows[0]));
 assert.equal((await familyInbox(outsider,new URLSearchParams())).total,0);
 const august=new URLSearchParams({from:'2026-08-01',to:'2026-08-31'});
 assert.equal((await ledgerReport(pa,august)).totals.expense,0);
 await api(b,f,'POST',{operation:'confirm',id:inboxId,targetId:wb,displayBookId:pb});
 assert.equal((await familyInbox(b,new URLSearchParams())).total,0);
 assert.equal((await ledgerReport(pb,august)).totals.income,222);
 assert.equal((await ledgerReport(pa,august)).totals.expense,222);
 assert.equal((await ledgerReport([pa,pb],august)).totals.expense,0);
 assert.equal((await ledgerReport([pa,pb],august)).totals.income,0);
 assert.equal(Number((await db.query('SELECT count(*) FROM transactions')).rows[0].count),1);
 console.log('PASS personal gift income/expenses, household elimination, unchanged principal flows, exports, private home inbox');
 console.log('PASS independent personal books, defaults, private permissions, display moves without balance changes');
 console.log('PASS chat proposals, editable cards, sender/recipient confirmation, repeat confirmation and cross-upload duplicates');
 console.log('PASS AA, shared contributions, idempotency, privacy, permission rejection, wallet balances and no duplicate expense');
}finally{await db.end();await admin.query(`DROP DATABASE ${dbName} WITH (FORCE)`);await admin.end();}
