import assert from 'node:assert/strict';import pg from 'pg';import sharp from 'sharp';import {randomUUID,randomBytes,scryptSync} from 'node:crypto';import {unlink} from 'node:fs/promises';
const db=new pg.Client({connectionString:process.env.DATABASE_URL});await db.connect();const base=process.env.TEST_ORIGIN||process.env.APP_ORIGIN,uid=randomUUID(),other=randomUUID(),name='improve_'+uid.slice(0,8),password=randomBytes(16).toString('hex'),salt=randomBytes(16).toString('hex');const books=[],files=[];
async function req(path,method='GET',body,cookie='',status=200){const r=await fetch(base+'/api/'+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});assert.equal(r.status,status,r.status!==status?await r.text():'');return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||''};}
try{for(const [id,n] of [[uid,name],[other,name+'x']])await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$2,$2,$3)',[id,n,salt+':'+scryptSync(password,salt,64).toString('hex')]);const a=(await req('login','POST',{username:name,password})).cookie,b=(await req('login','POST',{username:name+'x',password})).cookie;for(const kind of ['private','shared'])books.push((await req('books','POST',{name:'完善测试'+kind,kind},a)).data.id);const [privateBook,sharedBook]=books;const path='books/'+privateBook,shared='books/'+sharedBook;const ac=(await req(path+'/accounts','GET',undefined,a)).data[0],bc=(await req(shared+'/accounts','GET',undefined,a)).data[0];await req(shared+'/members','POST',{username:name+'x',role:'viewer'},a);
const upload=await fetch(base+'/api/receipts?book='+privateBook,{method:'POST',headers:{Origin:base,Cookie:a,'Content-Type':'image/png','x-file-name':encodeURIComponent('测试原图.png')},body:await sharp({create:{width:32,height:32,channels:3,background:'#ff0000'}}).png().toBuffer()});assert.equal(upload.status,200);const file=await upload.json();files.push(file.data.split('/').at(-1));assert.equal((await fetch(base+file.data,{headers:{Cookie:b}})).status,403);assert.equal((await fetch(base+file.data,{headers:{Cookie:a}})).status,200);
await req(path+'/drafts','PUT',{section:'images',version:0,value:[file]},a);const id=randomUUID(),entry={id,kind:'expense',amount:1000,date:'2026-09-13',accountId:ac.id,payee:'测试餐厅',category:'餐饮',note:'',lineItems:[{name:'午饭',quantity:1,unitPrice:900,amount:900}],attachmentIds:files,retainReceipts:true};await req(path+'/transactions','POST',{entries:[entry]},a,400);await req(path+'/transactions','POST',{entries:[{...entry,verificationReason:'小票缺少100分包装费，已核对实付'}]},a);assert.equal((await req(path+'/receipts?transaction='+id,'GET',undefined,a)).data.length,1);const pending=(await req(path+'/attention?mode=verification','GET',undefined,a)).data;assert.equal(pending.length,1);assert.ok(pending[0].verification_reason);
await req(path+'/transactions','DELETE',{id,version:1},a);assert.equal((await req(path+'/attention?mode=trash','GET',undefined,a)).data.length,1);await req(path+'/transactions','PATCH',{id,version:2,deleted:false},a);assert.equal((await req(path+'/attention?mode=trash','GET',undefined,a)).data.length,0);
const wallet=(await req('wallets','POST',{accountId:ac.id},a)).data.id;await req('wallets','POST',{accountId:bc.id,walletId:wallet},a);await req(path+'/reuse','POST',{id,version:3,targetBook:sharedBook,accountId:bc.id},a);let all=(await req('wallets','GET',undefined,a)).data;assert.equal(all.find(w=>w.id===wallet).balance,-1000);const restricted=(await req('wallets','GET',undefined,b)).data.find(w=>w.id===wallet);assert.equal(restricted.balance,null);assert.equal(restricted.visibleMovement,-1000);assert.equal(restricted.accounts.length,1);assert.equal((await fetch(base+file.data,{headers:{Cookie:b}})).status,403);
await req('wallets','PATCH',{walletId:wallet,balance:5000,expectedBalance:-1000,note:'核对真实钱包'},a);assert.equal((await req('wallets','GET',undefined,a)).data.find(w=>w.id===wallet).balance,5000);assert.equal((await req('wallets','GET',undefined,b)).data.find(w=>w.id===wallet).visibleMovement,-1000);await req('wallets','PATCH',{walletId:wallet,balance:6000,expectedBalance:-1000,note:'过期校准'},a,409);const linkedAccount=(await req(path+'/accounts','GET',undefined,a)).data.find(x=>x.id===ac.id);await req(path+'/accounts','PATCH',{operation:'reconcile',id:ac.id,version:linkedAccount.version,balance:5000,expectedBalance:linkedAccount.balance,note:'应转到真实钱包'},a,400);
const job=randomUUID();await db.query("INSERT INTO ai_jobs(id,user_id,book_id,kind,payload,status) VALUES($1,$2,$3,'assistant',$4,'error')",[job,uid,privateBook,{text:'模拟任务',images:['invalid-test-image']}]);await db.query('INSERT INTO ai_job_steps VALUES($1,$2,$3)',[job,'batch:0',{entries:[]}]);await req('jobs/'+job,'POST',{operation:'retry'},a);const state=(await db.query('SELECT status,payload FROM ai_jobs WHERE id=$1',[job])).rows[0];assert.equal(state.status,'queued');assert.ok(state.payload.images.length);assert.equal((await db.query('SELECT 1 FROM ai_job_steps WHERE job_id=$1',[job])).rowCount,1);await db.query('DELETE FROM ai_jobs WHERE id=$1',[job]);
console.log('PASS: receipt upload/private ACL/persistent links; mismatch confirmation; attention/trash/restore; canonical wallet event dedup/private balance protection; durable retry/checkpoint retention');
}finally{await db.query('DELETE FROM ai_jobs WHERE user_id=ANY($1::uuid[])',[[uid,other]]);await db.query('DELETE FROM transactions WHERE book_id=ANY($1::uuid[])', [books]);await db.query('DELETE FROM account_adjustments WHERE book_id=ANY($1::uuid[])',[books]);await db.query('DELETE FROM wallets WHERE owner_id=$1',[uid]);await db.query('DELETE FROM books WHERE id=ANY($1::uuid[])',[books]);await db.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[[uid,other]]);await db.query('DELETE FROM login_attempts WHERE username=ANY($1::text[])',[[name,name+'x']]);for(const f of files)await unlink((process.env.RECEIPT_DIR||'./data/receipts')+'/'+f).catch(()=>{});await db.end();}
