import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db,transaction} from '../src/server/db';
import {createAccount,listAssets,accountReport} from '../src/server/accounts';
import {changeInstallment,listInstallments} from '../src/server/installments';
import {allocations} from '../src/server/allocations';
import {entry} from '../src/server/model';
import {insertEntry} from '../src/server/ledger';
import {reuse,overview} from '../src/server/reuse';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_installment_test'));
const user=randomUUID(),stranger=randomUUID(),book=randomUUID(),other=randomUUID();
for(const id of [user,stranger])await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$4,$2,$3)',[id,'分期测试','unused',id]);
for(const id of [book,other]){await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'测试账本','private',$2)",[id,user]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[id,user]);}
const credit=(await createAccount(user,{name:'白条',type:'credit'})).id,bank=(await createAccount(user,{name:'银行卡',type:'bank',opening:1000000})).id;
await changeInstallment(user,{operation:'create',requestId:randomUUID(),book,name:'电脑分期',purchase:{accountId:credit,amount:600000,date:'2026-09-01',category:'购物'},terms:12,firstDate:'2026-09-30',fees:12000,allocate:true,allocationStart:'2026-09-01',allocationMonths:24});
let p=(await listInstallments(user)).plans[0];assert.equal(p.remaining,600000);assert.equal((await listInstallments(stranger)).plans.length,0);
const source=(await db.query('SELECT id,version FROM transactions WHERE event_id=$1',[p.event_id])).rows[0];
await reuse(book,user,{id:source.id,version:source.version,targetBook:other});
await assert.rejects(()=>db.query('UPDATE transactions SET amount=1 WHERE id=$1',[source.id]));
const copied=(await db.query('SELECT id FROM transactions WHERE event_id=$1 AND book_id=$2',[p.event_id,other])).rows[0];
await assert.rejects(()=>changeInstallment(user,{operation:'create',requestId:randomUUID(),book:other,name:'重复',transactionId:copied.id,terms:12,firstDate:'2026-09-30'}));
const requestId=randomUUID();const pay={operation:'pay',id:p.id,version:p.version,requestId,book,accountId:bank,date:'2026-09-15',principal:50000,fee:1000,feeCategory:'其他'};
await assert.rejects(()=>changeInstallment(user,{...pay,date:'2026-08-31'}));
await changeInstallment(user,pay);await changeInstallment(user,pay);
p=(await listInstallments(user)).plans[0];assert.equal(p.remaining,550000);assert.equal(p.payments.length,1);
let assets=await listAssets(user);assert.equal(assets.find(a=>a.id===credit).balance,-550000);assert.equal(assets.find(a=>a.id===bank).balance,949000);
assert.equal((await overview(user,new URLSearchParams({month:'2026-09'}))).expense,601000);
assert.equal((await allocations(book,'GET',{},new URLSearchParams({month:'2026-09'})) as {total:number}).total,26000);
const flow=await accountReport(user,new URLSearchParams({from:'2026-09-01',to:'2026-09-30'}));assert.equal(flow.summary.cashPaid,51000);assert.equal(flow.summary.debtPurchases,600000);
await assert.rejects(()=>changeInstallment(stranger,{operation:'pay',id:p.id,version:p.version,requestId:randomUUID(),book,accountId:bank,date:'2026-09-16',principal:1,fee:0}));
await assert.rejects(()=>changeInstallment(user,{...pay,requestId:randomUUID(),version:p.version,principal:550001}));
await changeInstallment(user,{operation:'schedule',id:p.id,version:p.version,name:'电脑分期',terms:5,firstDate:'2026-10-31',fees:0});p=(await listInstallments(user)).plans[0];assert.equal(p.schedule.reduce((n:number,r:any)=>n+r.principal,0),550000);
await transaction(c=>insertEntry(c,book,user,entry.parse({id:randomUUID(),accountId:credit,kind:'refund',amount:10000,date:'2026-09-16',refundOf:source.id,category:'购物'})));
p=(await listInstallments(user)).plans[0];assert.equal(p.remaining,540000);
await changeInstallment(user,{...pay,requestId:randomUUID(),version:p.version,date:'2026-09-17',principal:540000,fee:0,settle:true});p=(await listInstallments(user)).plans[0];assert.equal(p.remaining,0);assert.ok(p.dues.every((r:any)=>r.remaining===0));
assert.equal((await allocations(book,'GET',{},new URLSearchParams({month:'2026-09'})) as {total:number}).total,25584);
await changeInstallment(user,{operation:'void',id:p.id,version:p.version,paymentId:p.payments.find((r:any)=>r.principal===540000).id});p=(await listInstallments(user)).plans[0];assert.equal(p.remaining,540000);
await changeInstallment(user,{...pay,requestId:randomUUID(),version:p.version,principal:0,fee:100,date:'2026-09-18'});p=(await listInstallments(user)).plans[0];
await changeInstallment(user,{operation:'void',id:p.id,version:p.version,paymentId:p.payments.find((r:any)=>r.principal===0&&!r.voided).id});p=(await listInstallments(user)).plans[0];assert.equal(p.remaining,540000);
await assert.rejects(()=>changeInstallment(user,{operation:'schedule',id:p.id,version:p.version,name:p.name,terms:1,firstDate:'2026-10-01',schedule:[{date:'2026-10-01',principal:1,fee:0}]}));
await assert.rejects(()=>changeInstallment(user,{operation:'delete',id:p.id,version:p.version}));
await assert.rejects(()=>db.query('UPDATE transactions SET deleted=true WHERE event_id=(SELECT principal_event FROM installment_payments WHERE plan_id=$1 AND NOT voided LIMIT 1)',[p.id]));
const family=randomUUID();await db.query('INSERT INTO families(id,name,owner_id) VALUES($1,$2,$3)',[family,'测试家庭',user]);await db.query("INSERT INTO family_members(family_id,user_id) VALUES($1,$2),($1,$3)",[family,user,stranger]);
const familyCredit=(await createAccount(user,{name:'家庭信用卡',type:'credit',familyId:family})).id;
await changeInstallment(user,{operation:'create',requestId:randomUUID(),book,name:'家庭分期',purchase:{accountId:familyCredit,amount:120000,date:'2026-09-01',category:'购物'},terms:3,firstDate:'2026-09-30'});
assert.equal((await listInstallments(stranger)).plans.length,1);assert.equal((await listInstallments(stranger)).plans[0].name,'家庭分期');
console.log('PASS: acquisition, permissions, partial repayment, retry, refund, settlement, undo, wallet balances, independent cost allocation and cross-book deduplication');
await db.end();
