import assert from 'node:assert/strict';import{randomUUID,randomBytes,scryptSync}from'node:crypto';import pg from'pg';
const base=process.env.APP_ORIGIN;const db=new pg.Client({connectionString:process.env.DATABASE_URL});await db.connect();const users=[],books=[];let adminUsername;
async function req(path,method='GET',body,cookie='',expected=200){const r=await fetch(base+'/api/'+path,{method,headers:{Origin:base,'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
try{
 adminUsername='test_admin_'+randomBytes(6).toString('hex');const adminPassword=randomBytes(20).toString('hex'),salt=randomBytes(16).toString('hex');await db.query('INSERT INTO users(id,username,name,password,admin) VALUES($1,$2,$3,$4,true)',[randomUUID(),adminUsername,'临时集成测试管理员',salt+':'+scryptSync(adminPassword,salt,64).toString('hex')]);const admin=(await req('login','POST',{username:adminUsername,password:adminPassword})).cookie;
 const password=randomBytes(20).toString('hex');
 for(let i=0;i<2;i++){const username='test_'+randomBytes(6).toString('hex');await req('users','POST',{username,name:'权限测试'+i,password},admin);users.push(username);}
 const a=(await req('login','POST',{username:users[0],password})).cookie,b=(await req('login','POST',{username:users[1],password})).cookie;
 const privateBook=(await req('books','POST',{name:'私账隔离测试',kind:'private'},a)).data.id;books.push(privateBook);
 await req(`books/${privateBook}/transactions`,'GET',undefined,b,403);await req(`books/${privateBook}/transactions`,'GET',undefined,admin,403);
 await req(`books/${privateBook}/members`,'POST',{username:users[1],role:'editor'},a,400);
 const shared=(await req('books','POST',{name:'共享测试',kind:'shared'},a)).data.id;books.push(shared);
 await req(`books/${shared}/members`,'POST',{username:users[1],role:'viewer'},a);
 const accounts=(await req(`books/${shared}/accounts`,'GET',undefined,a)).data;
 const record={id:randomUUID(),accountId:accounts[0].id,kind:'income',amount:10000,date:'2026-09-13',payee:'测试收入',category:'工资',note:''};
 await req(`books/${shared}/transactions`,'POST',{entries:[record]},b,403);
 assert.equal((await req(`books/${shared}/transactions`,'POST',{entries:[record]},a)).data.added,1);
 assert.equal((await req(`books/${shared}/transactions`,'POST',{entries:[record]},a)).data.added,0);
 const transfer={...record,id:randomUUID(),kind:'transfer',amount:3000,targetId:accounts[1].id,payee:'账户转账'};
 await req(`books/${shared}/transactions`,'POST',{entries:[transfer]},a);
 const balances=(await req(`books/${shared}/accounts`,'GET',undefined,b)).data;
 assert.equal(balances.find(x=>x.id===accounts[0].id).balance,7000);assert.equal(balances.find(x=>x.id===accounts[1].id).balance,3000);
 const foreign=(await req(`books/${privateBook}/accounts`,'GET',undefined,a)).data[0];await req(`books/${shared}/transactions`,'POST',{entries:[{...record,id:randomUUID(),accountId:foreign.id}]},a,400);
 await req(`books/${shared}/transactions`,'PUT',{...record,version:1,amount:12000},a);await req(`books/${shared}/transactions`,'PUT',{...record,version:1,amount:11000},a,409);
 const del=await req(`books/${shared}/transactions`,'DELETE',{id:record.id,version:2},a);await req(`books/${shared}/transactions`,'PATCH',{id:record.id,version:del.data.version,deleted:false},a);
 await req('ai-settings','GET',undefined,b,403);

 const purchase={...record,id:randomUUID(),kind:'expense',amount:10000,date:'2026-08-31',payee:'京东测试店',category:'购物',platform:'京东',orderId:'test-order',product:''};
 const refund={...purchase,id:randomUUID(),kind:'refund',amount:3000,date:'2026-09-13',refundOf:purchase.id,externalId:'test-refund-1'};
 assert.equal((await req(`books/${shared}/transactions`,'POST',{entries:[refund,purchase]},a)).data.added,2);
 assert.equal((await req(`books/${shared}/transactions`,'POST',{entries:[{...refund,id:randomUUID()}]},a)).data.added,0);
 await req(`books/${shared}/transactions`,'POST',{entries:[{...refund,id:randomUUID(),externalId:'test-refund-over',amount:8000}]},a,400);
 await req(`books/${shared}/transactions`,'DELETE',{id:purchase.id,version:1},a,400);
 await req(`books/${shared}/transactions`,'PUT',{...purchase,version:1,amount:2000},a,400);
 await req(`books/${privateBook}/transactions`,'POST',{entries:[{...refund,id:randomUUID(),accountId:foreign.id,externalId:'cross-book'}]},a,400);
 const review=(await req(`books/${shared}/review`,'POST',{entries:[{...purchase,id:randomUUID(),product:'洗衣液 2kg × 2瓶'}]},a)).data.entries[0];assert.equal(review.action,'skip');assert.equal(review.matches[0].record.id,purchase.id);
 const merged=(await req(`books/${shared}/transactions`,'POST',{entries:[{...review,action:'merge',mergeId:purchase.id,mergeVersion:1}]},a)).data;assert.equal(merged.merged,1);assert.equal(merged.added,0);
 const stored=(await req(`books/${shared}/transactions`,'GET',undefined,a)).data;assert.equal(stored.find(t=>t.id===purchase.id).product,'洗衣液 2kg × 2瓶');assert.equal(stored.find(t=>t.id===purchase.id).amount,10000);
 const batch=(await req(`books/${shared}/review`,'POST',{entries:[{...purchase,id:randomUUID(),orderId:'another',amount:1600},{...purchase,id:randomUUID(),orderId:'another',amount:1600}]},a)).data.entries;assert.equal(batch[0].action,'create');assert.equal(batch[1].action,'skip');
 const accountAfter=(await req(`books/${shared}/accounts`,'GET',undefined,a)).data.find(x=>x.id===accounts[0].id);assert.equal(accountAfter.balance,2000);
 const monthly=(await req(`books/${shared}/transactions?month=2026-09`,'GET',undefined,a)).data;assert.equal(monthly.filter(t=>t.kind==='refund').reduce((n,t)=>n+t.amount,0),3000);

 const managed=(await req(`books/${shared}/accounts`,'GET',undefined,a)).data.find(x=>x.id===accounts[0].id);
 const countBefore=(await db.query('SELECT count(*)::int AS n FROM transactions WHERE book_id=$1',[shared])).rows[0].n;
 await req(`books/${shared}/accounts`,'PATCH',{operation:'reconcile',id:managed.id,version:managed.version,expectedBalance:managed.balance,balance:5000,note:'测试核对余额'},a);
 let revised=(await req(`books/${shared}/accounts`,'GET',undefined,a)).data.find(x=>x.id===managed.id);assert.equal(revised.balance,5000);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE book_id=$1',[shared])).rows[0].n,countBefore);
 await req(`books/${shared}/accounts`,'PATCH',{operation:'reconcile',id:managed.id,version:revised.version,expectedBalance:managed.balance,balance:8000,note:'过期余额不能覆盖'},a,409);
 const adjustments=(await req(`books/${shared}/account-history?account=${managed.id}`,'GET',undefined,a)).data;assert.equal(adjustments.length,1);assert.equal(adjustments[0].amount,5000-managed.balance);
 await req(`books/${shared}/accounts`,'PATCH',{operation:'archive',id:managed.id,version:revised.version,archived:true},a);
 await req(`books/${shared}/transactions`,'POST',{entries:[{...record,id:randomUUID(),accountId:managed.id}]},a,400);
 revised=(await req(`books/${shared}/accounts`,'GET',undefined,a)).data.find(x=>x.id===managed.id);assert.equal(revised.balance,5000);assert.equal(revised.archived,true);
 await req(`books/${shared}/accounts`,'PATCH',{operation:'archive',id:managed.id,version:revised.version,archived:false},a);
 await req(`books/${shared}/budgets`,'PUT',{month:'2026-09',category:'购物',amount:50000},a);await req(`books/${shared}/budgets`,'DELETE',{month:'2026-09',category:'购物'},a);assert.equal((await req(`books/${shared}/budgets?month=2026-09`,'GET',undefined,a)).data.length,0);
 const draftValue={text:'还没记完的私密文字',entries:[],history:false};
 assert.equal((await req(`books/${shared}/drafts?section=intake`,'GET',undefined,a)).data.version,0);
 await req(`books/${shared}/drafts`,'PUT',{section:'intake',version:0,value:draftValue},a);
 const restored=(await req(`books/${shared}/drafts?section=intake`,'GET',undefined,a)).data;assert.equal(restored.value.text,draftValue.text);
 assert.equal((await req(`books/${shared}/drafts?section=intake`,'GET',undefined,b)).data.value,null);
 await req(`books/${shared}/drafts`,'PUT',{section:'intake',version:0,value:{...draftValue,text:'过期设备'}},a,409);
 await req(`books/${shared}/drafts`,'PUT',{section:'manual',version:0,value:{}},b,403);
 await req(`books/${privateBook}/drafts?section=intake`,'GET',undefined,admin,403);
 await req(`books/${shared}/drafts`,'PUT',{section:'images',version:0,value:[{name:'测试.png',data:'data:image/png;base64,dGVzdA=='}]},a);
 assert.equal((await req(`books/${shared}/drafts?section=images`,'GET',undefined,a)).data.value.length,1);
 assert.equal((await req(`books/${shared}/drafts?section=intake`,'GET',undefined,a)).data.version,1);

 await req(`books/${shared}/categories`,'PUT',{name:'宠物测试',icon:'🐾'},a);
 const pet={...record,id:randomUUID(),kind:'expense',amount:900,category:'宠物测试',payee:'测试宠物店'};
 await req(`books/${shared}/transactions`,'POST',{entries:[pet]},a);
 await req(`books/${shared}/budgets`,'PUT',{month:'2026-09',category:'宠物测试',amount:10000},a);
 const draftVersion=(await req(`books/${shared}/drafts?section=intake`,'GET',undefined,a)).data.version;
 await req(`books/${shared}/drafts`,'PUT',{section:'intake',version:draftVersion,value:{text:'测试',entries:[pet]}},a);
 await req(`books/${shared}/templates`,'POST',{name:'宠物常用',value:pet},a);
 let shortcut=(await req(`books/${shared}/templates`,'GET',undefined,a)).data[0];assert.equal(shortcut.value.externalId,undefined);assert.equal(shortcut.value.date,undefined);
 assert.equal((await req(`books/${shared}/templates`,'GET',undefined,b)).data.length,0);
 await req(`books/${shared}/templates`,'POST',{name:'越权账户',value:{...pet,accountId:foreign.id}},a,400);
 await req(`books/${shared}/categories`,'PUT',{name:'宠物测试',newName:'萌宠测试',icon:'🐾'},a);
 assert.equal((await db.query('SELECT category FROM transactions WHERE id=$1',[pet.id])).rows[0].category,'萌宠测试');
 assert.equal((await req(`books/${shared}/budgets?month=2026-09`,'GET',undefined,a)).data[0].category,'萌宠测试');
 assert.equal((await req(`books/${shared}/drafts?section=intake`,'GET',undefined,a)).data.value.entries[0].category,'萌宠测试');
 shortcut=(await req(`books/${shared}/templates`,'GET',undefined,a)).data[0];assert.equal(shortcut.value.category,'萌宠测试');
 await req(`books/${shared}/transactions`,'POST',{entries:[{...pet,id:randomUUID()}]},a,400);
 await req(`books/${shared}/templates`,'PUT',{id:shortcut.id,version:shortcut.version,name:'改名常用',value:{...pet,category:'萌宠测试',amount:1000}},a);
 const next={...shortcut.value,id:randomUUID(),date:'2026-09-13'};
 assert.equal((await req(`books/${shared}/transactions`,'POST',{entries:[next,{...next,id:randomUUID()}]},a)).data.added,2);
 await req(`books/${shared}/templates`,'DELETE',{id:shortcut.id},a);assert.equal((await req(`books/${shared}/templates`,'GET',undefined,a)).data.length,0);
 await req(`books/${shared}/categories`,'PUT',{name:'萌宠测试',icon:'🐾',archived:true},b,403);

 await req(`books/${shared}/categories`,'PUT',{name:'图标删除测试',icon:'sticker:001'},a);
 assert.equal((await req(`books/${shared}/categories`,'GET',undefined,a)).data.find(c=>c.name==='图标删除测试').icon,'sticker:001');
 await req(`books/${shared}/categories`,'PUT',{name:'图标删除测试',operation:'delete'},a);
 assert.equal((await req(`books/${shared}/categories`,'GET',undefined,a)).data.some(c=>c.name==='图标删除测试'),false);
 await req(`books/${shared}/categories`,'PUT',{name:'萌宠测试',operation:'delete'},a);
 assert.equal((await db.query('SELECT category FROM transactions WHERE id=$1',[pet.id])).rows[0].category,'萌宠测试');
 await req(`books/${shared}/transactions`,'POST',{entries:[{...pet,id:randomUUID(),category:'萌宠测试'}]},a,400);
 await req(`books/${shared}/categories`,'PUT',{name:'图标删除测试',icon:'sticker:001'},a);
 assert.equal((await req(`books/${shared}/categories`,'GET',undefined,a)).data.some(c=>c.name==='图标删除测试'),true);
 await req(`books/${shared}/categories`,'PUT',{name:'萌宠测试',icon:'sticker:001'},a);
 const largeBook=(await req('books','POST',{name:'范围分页临时测试',kind:'private'},a)).data.id;books.push(largeBook);const largeAccount=(await req(`books/${largeBook}/accounts`,'GET',undefined,a)).data[0].id;
 const author=(await db.query('SELECT id FROM users WHERE username=$1',[users[0]])).rows[0].id;
 await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,payee,category,note,created_by) SELECT gen_random_uuid(),$1,$2,'expense',100,'2026-07-01','分页测试店','购物',n::text,$3 FROM generate_series(1,10001) n",[largeBook,largeAccount,author]);
 const credit={...record,id:randomUUID(),accountId:largeAccount,date:'2026-07-02',amount:200,kind:'income',payee:'=SUM(A1:A2)'};await req(`books/${largeBook}/transactions`,'POST',{entries:[credit,{...credit,id:randomUUID(),kind:'refund',amount:25},{...credit,id:randomUUID(),date:'2026-06-30',amount:500}]},a);
 const range='from=2026-07-01&to=2026-07-31';
 const page1=(await req(`books/${largeBook}/report?${range}&limit=50`,'GET',undefined,a)).data;
 assert.equal(page1.rows.length,50);assert.equal(page1.totals.count,10003);assert.equal(page1.totals.expense,1000100);assert.equal(page1.totals.refund,25);assert.equal(page1.totals.income,200);
 const page2=(await req(`books/${largeBook}/report?${range}&offset=50&limit=50`,'GET',undefined,a)).data;assert.equal(new Set([...page1.rows,...page2.rows].map(r=>r.id)).size,100);
 const last=(await req(`books/${largeBook}/report?${range}&offset=10000&limit=50`,'GET',undefined,a)).data;assert.equal(last.rows.length,3);
 const incomeOnly=(await req(`books/${largeBook}/report?${range}&kind=income`,'GET',undefined,a)).data;assert.equal(incomeOnly.totals.count,1);assert.equal(incomeOnly.totals.expense,0);
 await req(`books/${largeBook}/report?${range}`,'GET',undefined,b,403);await req(`books/${largeBook}/report?from=2026-08-01&to=2026-07-01`,'GET',undefined,a,400);
 const csvResponse=await fetch(base+`/api/books/${largeBook}/export?${range}&offset=10000`,{headers:{Cookie:a}});assert.equal(csvResponse.status,200);const csv=await csvResponse.text();assert.equal(csv.split('\r\n').length,10004);assert.ok(csv.includes("'"+'=SUM(A1:A2)'));

 const refundSearch=(await req(`books/${shared}/refund-options?q=${encodeURIComponent('京东测试店')}`,'GET',undefined,a)).data;assert.ok(refundSearch.some(r=>r.id===purchase.id));assert.equal(refundSearch.find(r=>r.id===purchase.id).remaining,7000);
 const excluding=(await req(`books/${shared}/refund-options?id=${purchase.id}&exclude=${refund.id}`,'GET',undefined,a)).data;assert.equal(excluding[0].remaining,10000);
 const limited=(await req(`books/${largeBook}/refund-options`,'GET',undefined,a)).data;assert.equal(limited.length,30);
 const exact=(await req(`books/${largeBook}/refund-options?id=${page1.rows.find(r=>r.kind==='expense').id}`,'GET',undefined,a)).data;assert.equal(exact.length,1);
 await req(`books/${largeBook}/refund-options?q=test`,'GET',undefined,b,403);

 const beforeSchedules=(await db.query('SELECT count(*)::int AS n FROM transactions WHERE book_id=$1',[shared])).rows[0].n;
 await req(`books/${shared}/schedules`,'POST',{name:'测试月末订阅',frequency:'monthly',nextDate:'2026-01-31',value:{...pet,category:'萌宠测试',amount:200}},a);
 let schedule=(await req(`books/${shared}/schedules`,'GET',undefined,a)).data[0];assert.equal((await req(`books/${shared}/schedules`,'GET',undefined,b)).data.length,0);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE book_id=$1',[shared])).rows[0].n,beforeSchedules);
 const confirm={operation:'confirm',id:schedule.id,version:schedule.version,dueDate:schedule.next_date,paidDate:'2026-01-31',amount:250};
 const first=(await req(`books/${shared}/schedules`,'POST',confirm,a)).data;assert.equal(first.nextDate,'2026-02-28');assert.equal((await req(`books/${shared}/schedules`,'POST',confirm,a)).data.alreadyProcessed,true);
 schedule=(await req(`books/${shared}/schedules`,'GET',undefined,a)).data[0];await req(`books/${shared}/schedules`,'POST',{operation:'skip',id:schedule.id,version:schedule.version,dueDate:schedule.next_date},a);
 schedule=(await req(`books/${shared}/schedules`,'GET',undefined,a)).data[0];assert.equal(schedule.next_date,'2026-03-31');
 await req(`books/${shared}/schedules`,'POST',{operation:'pause',id:schedule.id,version:schedule.version,paused:true},a);
 schedule=(await req(`books/${shared}/schedules`,'GET',undefined,a)).data[0];await req(`books/${shared}/schedules`,'POST',{operation:'confirm',id:schedule.id,version:schedule.version,dueDate:schedule.next_date,paidDate:schedule.next_date,amount:200},a,400);
 await req(`books/${shared}/schedules`,'POST',{operation:'pause',id:schedule.id,version:schedule.version,paused:false},a);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE book_id=$1',[shared])).rows[0].n,beforeSchedules+1);
 schedule=(await req(`books/${shared}/schedules`,'GET',undefined,a)).data[0];await req(`books/${shared}/schedules`,'POST',{operation:'delete',id:schedule.id,version:schedule.version},a);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM transactions WHERE id=$1',[first.transactionId])).rows[0].n,1);
 const subBook=(await req('books','POST',{name:'分摊临时测试',kind:'private'},a)).data.id;books.push(subBook);
 const subAccount=(await req(`books/${subBook}/accounts`,'GET',undefined,a)).data[0].id;
 await req(`books/${subBook}/schedules`,'POST',{name:'季度订阅',frequency:'monthly',intervalMonths:3,amortize:true,nextDate:'2026-01-31',value:{...record,id:randomUUID(),kind:'expense',accountId:subAccount,amount:10000}},a);
 let plan=(await req(`books/${subBook}/schedules`,'GET',undefined,a)).data[0];
 const pay={operation:'confirm',id:plan.id,version:plan.version,dueDate:plan.next_date,paidDate:'2026-01-31',startMonth:'2026-02',amount:10000};
 const payment=(await req(`books/${subBook}/schedules`,'POST',pay,a)).data;assert.equal(payment.nextDate,'2026-04-30');assert.equal((await req(`books/${subBook}/schedules`,'POST',pay,a)).data.alreadyProcessed,true);
 async function allocation(month){return (await req(`books/${subBook}/allocations?month=${month}`,'GET',undefined,a)).data;}
 assert.equal((await allocation('2026-01')).total,0);
 assert.deepEqual(await Promise.all(['2026-02','2026-03','2026-04'].map(async m=>(await allocation(m)).allocated)),[3334,3333,3333]);
 assert.equal((await allocation('2026-05')).allocated,0);
 assert.equal((await req(`books/${subBook}/accounts`,'GET',undefined,a)).data[0].balance,-10000);
 await req(`books/${subBook}/allocations`,'PUT',{id:payment.transactionId,version:1,months:12,start:'2026-02'},b,403);
 const refundEntry={...record,id:randomUUID(),accountId:subAccount,kind:'refund',refundOf:payment.transactionId,amount:1,date:'2026-03-01'};
 await req(`books/${subBook}/transactions`,'POST',{entries:[refundEntry]},a);
 assert.deepEqual(await Promise.all(['2026-02','2026-03','2026-04'].map(async m=>(await allocation(m)).total)),[3333,3333,3333]);
 plan=(await req(`books/${subBook}/schedules`,'GET',undefined,a)).data[0];await req(`books/${subBook}/schedules`,'POST',{operation:'delete',id:plan.id,version:plan.version},a);assert.equal((await allocation('2026-02')).allocated,3333);
 const subVersion=Number((await db.query('SELECT version FROM transactions WHERE id=$1',[payment.transactionId])).rows[0].version);
 await req(`books/${subBook}/allocations`,'PUT',{id:payment.transactionId,version:subVersion,start:'2026-02',months:36},a);
 assert.equal((await allocation('2029-02')).allocated,0);
 await req(`books/${subBook}/allocations`,'PUT',{id:payment.transactionId,version:subVersion,remove:true},a,409);
 await req(`books/${subBook}/allocations`,'PUT',{id:payment.transactionId,version:subVersion+1,remove:true},a);
 assert.equal((await allocation('2026-01')).total,10000);assert.equal((await allocation('2026-03')).total,-1);
 console.log('PASS: 季付续费、分摊合计精确、覆盖期首尾、延迟起始月、账户只扣款一次、退款重算、删计划保留分摊、已有交易调整/取消分摊、过期修改拒绝、私账权限');
 await req('me','PUT',{name:'资料测试',avatar:'sticker:001'},a);assert.equal((await req('me','GET',undefined,a)).data.name,'资料测试');
 const profileManaged=(await req('users','GET',undefined,admin)).data.find(u=>u.username===users[0]);assert.equal(profileManaged.avatar,'sticker:001');
 await req('users','PATCH',{id:profileManaged.id,name:'越权',avatar:'🧸',disabled:false},a,403);
 const sourceBook=(await req('books','POST',{name:'关联私账',kind:'private'},a)).data.id;books.push(sourceBook);
 const targetBook=(await req('books','POST',{name:'关联公账',kind:'shared'},a)).data.id;books.push(targetBook);
 await req(`books/${sourceBook}/metadata`,'PUT',{name:'我的订阅',kind:'private',description:'管理测试',icon:'sticker:001'},a);
 assert.equal((await req('books','GET',undefined,a)).data.find(x=>x.id===sourceBook).icon,'sticker:001');
 await req(`books/${targetBook}/members`,'POST',{username:users[1],role:'viewer'},a);
 await req(`books/${targetBook}/metadata`,'PUT',{name:'不应改名',kind:'private',description:'',icon:'📒'},b,403);
 const srcAcc=(await req(`books/${sourceBook}/accounts`,'GET',undefined,a)).data[0].id;
 const dstAcc=(await req(`books/${targetBook}/accounts`,'GET',undefined,a)).data[0].id;
 const uniqueExpense={...record,id:randomUUID(),date:'2021-02-03',kind:'expense',amount:10000,accountId:srcAcc};
 await req(`books/${sourceBook}/transactions`,'POST',{entries:[uniqueExpense]},a);
 const copy=(await req(`books/${sourceBook}/reuse`,'POST',{id:uniqueExpense.id,version:1,targetBook,accountId:dstAcc},a)).data;
 assert.equal((await req(`books/${sourceBook}/reuse`,'POST',{id:uniqueExpense.id,version:2,targetBook,accountId:dstAcc},a)).data.alreadyExists,true);
 let whole=(await req('overview?month=2021-02','GET',undefined,a)).data;assert.equal(whole.expense,10000);assert.equal(whole.appearances,2);assert.equal(whole.count,1);
 assert.equal((await req('overview?month=2021-02','GET',undefined,b)).data.expense,10000);
 await req(`books/${targetBook}/transactions`,'PUT',{...uniqueExpense,id:copy.id,accountId:dstAcc,amount:12000,version:1},b,403);
 await req(`books/${sourceBook}/transactions`,'PUT',{...uniqueExpense,amount:12000,version:2},a);
 assert.equal((await db.query('SELECT amount::int FROM transactions WHERE id=$1',[copy.id])).rows[0].amount,12000);
 await req(`books/${targetBook}/transactions`,'PUT',{...uniqueExpense,id:copy.id,accountId:dstAcc,amount:12000,version:2,note:'公账专用备注',category:'共享分类'},a);
 assert.notEqual((await db.query('SELECT note FROM transactions WHERE id=$1',[uniqueExpense.id])).rows[0].note,'公账专用备注');
 await req(`books/${targetBook}/members`,'POST',{username:users[1],role:'editor'},a);
 await req(`books/${targetBook}/transactions`,'PUT',{...uniqueExpense,id:copy.id,accountId:dstAcc,amount:12001,version:3},b,400);
 await req(`books/${targetBook}/transactions`,'DELETE',{id:copy.id,version:3},a);
 await req(`books/${sourceBook}/transactions`,'PUT',{...uniqueExpense,amount:12000,date:'2021-02-02',version:3},a);
 const deletedCopy=(await db.query("SELECT version,to_char(date,'YYYY-MM-DD') AS date FROM transactions WHERE id=$1",[copy.id])).rows[0];assert.equal(deletedCopy.date,'2021-02-02');
 await req(`books/${targetBook}/transactions`,'PATCH',{id:copy.id,version:deletedCopy.version,deleted:false},a);
 assert.equal((await req('overview?month=2021-02','GET',undefined,a)).data.expense,12000);
 const sharedRefund={...uniqueExpense,id:randomUUID(),kind:'refund',amount:7000,refundOf:uniqueExpense.id,date:'2021-02-04'};
 await req(`books/${sourceBook}/transactions`,'POST',{entries:[sharedRefund]},a);
 await req(`books/${sourceBook}/reuse`,'POST',{id:sharedRefund.id,version:1,targetBook,accountId:dstAcc},a);
 whole=(await req('overview?month=2021-02','GET',undefined,a)).data;assert.equal(whole.refund,7000);assert.equal(whole.expense,12000);assert.equal(whole.count,2);
 await req(`books/${targetBook}/transactions`,'POST',{entries:[{...sharedRefund,id:randomUUID(),accountId:dstAcc,refundOf:copy.id,amount:6000}]},a,400);
 await req(`books/${sourceBook}/transactions`,'POST',{entries:[{...uniqueExpense,id:randomUUID(),amount:12000}]},a);
 assert.equal((await req('overview?month=2021-02','GET',undefined,a)).data.expense,24000);
 assert.equal((await req('overview?month=2021-02','GET',undefined,b)).data.expense,12000);
 const blockedUsername='test_disabled_'+randomBytes(6).toString('hex');users.push(blockedUsername);await req('users','POST',{username:blockedUsername,name:'停用测试',password},admin);
 const blocked=(await req('users','GET',undefined,admin)).data.find(u=>u.username===blockedUsername);
 const prior=(await req('login','POST',{username:blockedUsername,password})).cookie;
 await req('users','PATCH',{id:blocked.id,name:'停用测试',avatar:'🧸',disabled:true},admin);
 await req('me','GET',undefined,prior,401);await req('login','POST',{username:blockedUsername,password},'',401);
 await req('users','PATCH',{id:blocked.id,name:'恢复测试',avatar:'🧸',disabled:false},admin);
 await req('login','POST',{username:blockedUsername,password});
 console.log('PASS: 头像/资料、管理员停用与恢复、会话撤销、账本资料与权限、跨账本复用去重、独立备注分类、关联金额同步、退款复用不重复、跨本退款上限、同金额独立消费不误合并');
 const conv=(await req(`books/${shared}/chat`,'POST',{operation:'create'},a)).data.id;
 await req(`books/${shared}/chat?id=${conv}`,'GET',undefined,b,404);
 await req(`books/${shared}/chat`,'POST',{operation:'rename',id:conv,title:'越权标题'},b,404);
 assert.equal((await req(`books/${shared}/chat`,'GET',undefined,b)).data.conversations.length,0);
 const savedTurn=randomUUID();await db.query("INSERT INTO finance_turns(id,conversation_id,question,answer,artifacts,status,model) VALUES($1,$2,'测试问题','测试报告',$3,'complete','test')",[savedTurn,conv,JSON.stringify({charts:[],tools:[],drafts:[]})]);
 await req(`books/${shared}/chat`,'POST',{operation:'save_report',turnId:savedTurn,title:'越权报告'},b,400);
 const savedReport=(await req(`books/${shared}/chat`,'POST',{operation:'save_report',turnId:savedTurn,title:'已保存分析'},a)).data.id;
 await req(`books/${shared}/chat`,'POST',{operation:'edit_report',id:savedReport,version:1,title:'越权修改'},b,409);
 await req(`books/${shared}/chat`,'POST',{operation:'edit_report',id:savedReport,version:1,title:'修改后的分析',content:'补充正文'},a);
 await req(`books/${shared}/chat`,'POST',{operation:'edit_report',id:savedReport,version:1,title:'过期修改'},a,409);
 await req(`books/${shared}/chat`,'POST',{operation:'delete',id:conv},a);
 assert.equal((await req(`books/${shared}/chat`,'GET',undefined,a)).data.reports.find(r=>r.id===savedReport).content,'补充正文');
 await req(`books/${shared}/chat`,'POST',{operation:'delete_report',id:savedReport,version:2},a);
 console.log('PASS: 对话与报告按用户隔离、报告编辑版本冲突、删除对话保留独立报告、报告删除');
 console.log('PASS: 周期计划不提前入账、实际金额核对、同一期幂等、跳过不记账、暂停恢复、月末锚定及删除保留已记账');
 console.log('PASS: 原消费关键字搜索、30笔限制、精确关联查询、剩余退款金额及编辑时排除自身、权限隔离');
 console.log('PASS: 10003笔完整汇总、50笔分页不重叠、末页正确、跨月排除、类型筛选、全量CSV及公式转义、查询权限');
 console.log('PASS: 自定义分类改名同步交易/预算/草稿/常用记录、停用禁新增、常用记录个人隔离、编辑删除、账户校验、重复使用生成独立交易');
 console.log('PASS: 余额校准独立留痕不计收支、过期余额保护、归档禁新增、恢复账户、预算删除、草稿恢复/分区/用户隔离及版本冲突');
 console.log('PASS: 批次去重、订单补充不重复扣款、部分及跨月退款、退款流水幂等、超额退款拒绝、关联消费保护、跨账本退款隔离');
 console.log('PASS: 私账隔离（含应用管理员）、共享只读权限、跨账本账户保护、重复提交、转账余额、编辑冲突、删除恢复、AI配置权限');
}finally{
 for(const book of books){await db.query('DELETE FROM bill_schedules WHERE book_id=$1',[book]);await db.query('DELETE FROM account_adjustments WHERE book_id=$1',[book]);await db.query('DELETE FROM transactions WHERE book_id=$1',[book]);await db.query('DELETE FROM budgets WHERE book_id=$1',[book]);await db.query('DELETE FROM accounts WHERE book_id=$1',[book]);await db.query('DELETE FROM members WHERE book_id=$1',[book]);await db.query('DELETE FROM books WHERE id=$1',[book]);}
 for(const username of users){await db.query('DELETE FROM users WHERE username=$1',[username]);await db.query('DELETE FROM login_attempts WHERE username=$1',[username]);}if(adminUsername){await db.query('DELETE FROM users WHERE username=$1',[adminUsername]);await db.query('DELETE FROM login_attempts WHERE username=$1',[adminUsername]);}await db.end();
}
