import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db,transaction} from '../src/server/db';
import {memoryRoute as route,searchMemories,suggestMemory} from '../src/server/memory';
import {runMemoryJob} from '../src/server/memory-worker';
import {createAccount} from '../src/server/accounts';
import {insertEntry} from '../src/server/ledger';
import {entry} from '../src/server/model';
import {sceneSchema} from '../src/lib/entry-scene';
import {search} from '../src/server/search';
import {prepareChatAction} from '../src/server/chat-actions';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_memory_test'),'Requires isolated memory_test database');
const owner=randomUUID(),outsider=randomUUID(),book=randomUUID(),family=randomUUID();
const user={id:owner,username:'memory-test',name:'测试',admin:false,avatar:'',theme:'bear'} as any;
const memoryRoute=(...args:Parameters<typeof route>):Promise<any>=>route(...args);
const write=(body:any)=>memoryRoute(user,'POST',new URLSearchParams(),body);
try{
 for(const id of [owner,outsider])await db.query('INSERT INTO users(id,username,name,password) VALUES($1::uuid,$1::text,$2,$3)',[id,'测试','not-a-login']);
 await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'记忆测试','private',$2)",[book,owner]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[book,owner]);
 const account=(await createAccount(owner,{name:'测试钱包',opening:0,type:'cash'})).id;
 const value=entry.parse({id:randomUUID(),kind:'expense',amount:1800,date:'2026-09-26',accountId:account,title:'牛肉面',product:'牛肉面',payee:'面馆',category:'餐饮'});
 await transaction(c=>insertEntry(c,book,owner,value));
 const before=(await db.query('SELECT amount,category,account_id FROM transactions WHERE id=$1',[value.id])).rows[0];
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:value.id},{});
 const found=await searchMemories(owner,'牛肉面','product',false);assert.equal(found.length,1);
 assert.equal((await searchMemories(outsider,'牛肉面','product',false)).length,0);
 const suggested=await suggestMemory(owner,{kind:'expense',product:'牛肉面',payee:'面馆',category:'购物',scene:sceneSchema.parse({})});assert.equal(suggested[0].status,'matched');
 assert.equal((await search(owner,new URLSearchParams({q:'牛肉面',entity:'memory'}))).total,1);
 await write({operation:'reject',targetId:found[0].id,name:'牛肉面'});assert.equal((await suggestMemory(owner,{kind:'expense',product:'牛肉面',payee:'面馆',category:'购物',scene:sceneSchema.parse({})})).length,0);
 await write({operation:'forget',id:found[0].id,version:found[0].version});await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:value.id},{});assert.equal((await searchMemories(owner,'牛肉面','product',false)).length,0);
 assert.deepEqual((await db.query('SELECT amount,category,account_id FROM transactions WHERE id=$1',[value.id])).rows[0],before);
 const created=await write({operation:'save',kind:'preference',title:'会员归会员订阅',content:'明确偏好'});
 const row=(await memoryRoute(user,'GET',new URLSearchParams({id:created.id}),{})).memory;
 await assert.rejects(memoryRoute({...user,id:outsider},'POST',new URLSearchParams(),{operation:'forget',id:row.id,version:row.version}),/不存在/);
 await write({operation:'save',id:row.id,version:row.version,kind:'preference',title:'会员归会员订阅',content:'新描述'});
 const events=(await memoryRoute(user,'GET',new URLSearchParams({events:'1'}),{})).items;await write({operation:'undo',eventId:events[0].id});assert.equal((await memoryRoute(user,'GET',new URLSearchParams({id:row.id}),{})).memory.content,'明确偏好');
 await db.query("INSERT INTO families(id,name,owner_id) VALUES($1,'测试家庭',$2)",[family,owner]);await db.query("INSERT INTO family_members(family_id,user_id) VALUES($1,$2),($1,$3)",[family,owner,outsider]);
 const current=(await memoryRoute(user,'GET',new URLSearchParams({id:row.id}),{})).memory;
 const prepared=await prepareChatAction({kind:'memory',data:{operation:'save',id:row.id,title:'新的明确偏好'}},{book,user},[]);
 assert.equal(prepared.data.id,row.id);assert.equal(prepared.data.version,current.version);assert.equal(prepared.data.title,'新的明确偏好');assert.equal(prepared.status,'pending');
 assert.equal((await memoryRoute(user,'GET',new URLSearchParams({id:row.id}),{})).memory.title,current.title,'preparation must not mutate memory');
 const product=await write({operation:'save',kind:'product',title:'面条同款'});
 await db.query('DELETE FROM memory_exclusions WHERE user_id=$1',[owner]);
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:value.id},{});
 const relearned=(await searchMemories(owner,'牛肉面','product',false))[0];
 await write({operation:'merge',id:relearned.id,version:relearned.version,targetId:product.id});
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:value.id},{});
 assert.equal((await db.query('SELECT memory_id FROM memory_sources WHERE source_id=$1',[value.id])).rows[0].memory_id,product.id);
 const merged=(await memoryRoute(user,'GET',new URLSearchParams({id:product.id}),{})).memory;
 const split=await write({operation:'split',id:merged.id,version:merged.version,sourceId:value.id,value:{title:'明确拆分的面条'}});
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:value.id},{});
 assert.equal((await db.query('SELECT memory_id FROM memory_sources WHERE source_id=$1',[value.id])).rows[0].memory_id,split.id);
 await db.query('UPDATE transactions SET deleted=true,version=version+1 WHERE id=$1',[value.id]);
 assert.equal((await memoryRoute(user,'GET',new URLSearchParams({id:split.id}),{})).stats.purchases,0);
 await write({operation:'share',id:row.id,version:current.version,familyId:family,shared:{kind:'preference',title:'共享偏好',content:'仅分享这段描述'}});
 assert.equal((await searchMemories(outsider,'共享偏好',undefined,false)).length,1);await db.query('DELETE FROM family_members WHERE family_id=$1 AND user_id=$2',[family,outsider]);assert.equal((await searchMemories(outsider,'共享偏好',undefined,false)).length,0);
 console.log('PASS: source learning, scope isolation, match rejection, forget exclusion, accounting invariance, undo, sharing and membership revocation');
 const legacy=entry.parse({...value,id:randomUUID(),title:'可复美次抛精华',product:'',category:'护肤'});
 await transaction(c=>insertEntry(c,book,owner,legacy));
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:legacy.id},{});
 assert.equal((await searchMemories(owner,legacy.title,'product',false)).length,1,'title-only legacy product is learned');
 const newer=entry.parse({...legacy,id:randomUUID(),category:'购物'});
 await transaction(c=>insertEntry(c,book,owner,newer));
 await db.query("UPDATE transactions SET updated_at=now()+interval '1 minute' WHERE id=$1",[newer.id]);
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:newer.id},{});
 assert.equal((await searchMemories(owner,legacy.title,'product',false))[0].attributes.category,'购物');
 await db.query('UPDATE transactions SET deleted=true,version=version+1 WHERE id=$1',[newer.id]);
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:newer.id},{});
 assert.equal((await searchMemories(owner,legacy.title,'product',false))[0].attributes.category,'护肤','deleted evidence cannot retain latest category');
 const first=randomUUID(),second=randomUUID(),multi=entry.parse({...value,id:randomUUID(),lineItems:[{id:first,name:'瓶装水',amount:800},{id:second,name:'面包',amount:1000}]});
 await transaction(c=>insertEntry(c,book,owner,multi));
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:multi.id},{});
 const beforeOrder=(await db.query('SELECT memory_id,item_id FROM memory_sources WHERE source_id=$1 ORDER BY item_id',[multi.id])).rows;
 await db.query('UPDATE transactions SET line_items=$2,version=version+1 WHERE id=$1',[multi.id,JSON.stringify([...multi.lineItems].reverse())]);
 await runMemoryJob(owner,{operation:'source',sourceType:'transaction',sourceId:multi.id},{});
 assert.deepEqual((await db.query('SELECT memory_id,item_id FROM memory_sources WHERE source_id=$1 ORDER BY item_id',[multi.id])).rows,beforeOrder);
 console.log('PASS: legacy title extraction, deleted-source preference recomputation, stable item identity after reordering');
}finally{await db.end();}
