import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db,withConnection} from '../src/server/db';
import {personalProfileRoute,profileEvidence,profileRules,sanitizeProfileContext} from '../src/server/personal-profile';
import {applyPersonalPreferences} from '../src/server/personal-preferences';
import {createAccount} from '../src/server/accounts';
import {insertEntry} from '../src/server/ledger';
import {entry} from '../src/server/model';
import {runOperation} from '../src/server/assistant-operations';
import {search} from '../src/server/search';
import {sceneSchema} from '../src/lib/entry-scene';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_test'),'Isolated test database required');
process.env.APP_ORIGIN='http://profile-test.local';
const c=await db.connect();await c.query('BEGIN');
try{await withConnection(c,async()=>{
 const owner=randomUUID(),other=randomUUID(),book=randomUUID();
 const user={id:owner,username:'profile-test',name:'Profile test',admin:false,avatar:'',theme:'bear'} as any;
 for(const id of [owner,other])await c.query('INSERT INTO users(id,username,name,password) VALUES($1::uuid,$1::text,$2,$3)',[id,'Profile test','not-a-login']);
 await c.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'Profile test','private',$2)",[book,owner]);await c.query("INSERT INTO members VALUES($1,$2,'owner')",[book,owner]);
 const wallet=(await createAccount(owner,{name:'Everyday wallet',type:'wechat',opening:100000})).id,alternative=(await createAccount(owner,{name:'Travel wallet',type:'alipay',opening:0})).id;
 const api=(body:any)=>personalProfileRoute(user,'POST',new URLSearchParams(),body);
 const get=(query='')=>personalProfileRoute(user,'GET',new URLSearchParams(query),{});
 const raw={recordedAt:new Date().toISOString(),timeZone:'Asia/Shanghai',location:{latitude:31.23456,longitude:121.47891,accuracy:20,capturedAt:new Date().toISOString()},useAsTransactionPlace:true};
 assert.equal((await sanitizeProfileContext(owner,raw))?.location,undefined,'Opt-in is required');
 await api({operation:'settings',enabled:true,locationEnabled:true,retainLocation:true});
 const place:any=await api({operation:'save_place',name:'Office area',latitude:31.23456,longitude:121.47891});
 const context=await sanitizeProfileContext(owner,raw);assert.equal(context?.placeId,place.id);assert.equal(context?.location,undefined,'No coordinates in jobs or model context');
 await personalProfileRoute({...user,id:other},'POST',new URLSearchParams(),{operation:'settings',enabled:true,locationEnabled:true,retainLocation:false});
 assert.equal((await sanitizeProfileContext(other,{...raw,placeId:place.id}))?.placeId,undefined,'Unavailable areas are dropped without blocking entry');
 for(let i=0;i<4;i++)await insertEntry(c,book,owner,entry.parse({id:randomUUID(),kind:'expense',amount:1200,date:new Date().toISOString().slice(0,10),occurredAt:'12:00:00',accountId:wallet,payee:'Lunch cafe',category:'餐饮',scene:{type:'dining',meal:'Lunch'},profileContext:context}));
 const rows=await profileEvidence(owner);assert.equal(rows.length,4);assert.equal(rows[0].placeId,place.id);
 const serialized=JSON.stringify((await c.query('SELECT context FROM profile_contexts WHERE user_id=$1',[owner])).rows);assert.ok(!serialized.includes('latitude')&&!serialized.includes('longitude'));
 const input={accountId:undefined as string|undefined,kind:'expense',category:'其他',payee:'Lunch cafe',scene:sceneSchema.parse({type:'dining'}),profileContext:context};
 assert.equal((await applyPersonalPreferences(owner,[input],{semantic:false}))[0].accountId,wallet);
 const rule={condition:{kind:'expense',fields:{'scene.type':'dining'}},field:'accountId',value:alternative,state:'confirmed'};
 const saved:any=await api({operation:'save_rule',rule});
 assert.equal((await api({operation:'save_rule',rule}) as any).id,saved.id,'Repeated confirmation does not duplicate rules');
 await assert.rejects(()=>api({operation:'save_rule',rule:{...rule,condition:{kind:'expense',fields:{}},field:'scene.type',value:'invalid-scene'}}),/Invalid preference/);
 assert.equal((await applyPersonalPreferences(owner,[input],{semantic:false}))[0].accountId,alternative);
 await assert.rejects(()=>api({operation:'save_rule',rule:{...rule,value:wallet}}),/explicit rule/);
 const replacement:any=await api({operation:'save_rule',rule:{...rule,value:wallet},replaceConflicts:true});
 assert.equal((await applyPersonalPreferences(owner,[input],{semantic:false}))[0].accountId,wallet);
 await assert.rejects(()=>personalProfileRoute({...user,id:other},'POST',new URLSearchParams(),{operation:'delete_rule',id:replacement.id,version:0}));
 const events:any=await get('section=events');const undoable=events.items.find((e:any)=>e.rule_id===replacement.id&&e.canUndo);assert.ok(undoable);
 await api({operation:'undo',id:undoable.id});assert.ok(!(await profileRules(owner)).some(r=>r.id===replacement.id));
 const read:any=await runOperation({operation:'personal_profile',params:{section:'settings'}},user);assert.ok(read.places.every((p:any)=>p.latitude===undefined&&p.longitude===undefined));
 await assert.rejects(()=>runOperation({operation:'profile_rule_save',params:{rule}},user),/确认/);
 await runOperation({operation:'profile_rule_save',params:{rule}},user,true);
 const found=await search(owner,new URLSearchParams({q:'Travel',entity:'profile'}));assert.ok(found.rows.some((r:any)=>r.entity==='profile'));
 assert.equal((await search(other,new URLSearchParams({entity:'profile'}))).total,0);
 const before=(await c.query('SELECT id,amount,category,account_id,date FROM transactions WHERE created_by=$1 ORDER BY id',[owner])).rows;
 await api({operation:'settings',enabled:false,locationEnabled:true,retainLocation:true});
 assert.equal((await applyPersonalPreferences(owner,[input],{semantic:false}))[0].accountId,undefined);
 await api({operation:'forget_locations'});assert.equal((await get('section=settings') as any).places.length,0);
 assert.equal((await c.query('SELECT 1 FROM profile_contexts WHERE user_id=$1',[owner])).rowCount,0);
 assert.deepEqual((await c.query('SELECT id,amount,category,account_id,date FROM transactions WHERE created_by=$1 ORDER BY id',[owner])).rows,before,'Profile operations never change ledger facts');
 await c.query('DELETE FROM members WHERE book_id=$1',[book]);assert.equal((await profileEvidence(owner)).length,0);
 assert.ok(saved.id);console.log('PASS: opt-in, coarse areas, private context persistence, field defaults, explicit conflicts/replacement/undo, owner isolation, assistant confirmation and coordinate redaction, global search, opt-out, purge and unchanged ledger');
});}finally{await c.query('ROLLBACK');c.release();await db.end();}
