import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {spawn,type ChildProcess} from 'node:child_process';
import {randomUUID} from 'node:crypto';
const url=new URL(process.env.DATABASE_URL!);url.pathname='/bubu_queue_test';process.env.DATABASE_URL=url.toString();process.env.APP_ORIGIN='http://127.0.0.1:3018';
const {db}=await import('../src/server/db');const {passwordHash}=await import('../src/server/auth');const {encrypt}=await import('../src/server/ai');
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));let server:ChildProcess|undefined,worker:ChildProcess|undefined;
const ids=[randomUUID(),randomUUID()],book=randomUUID(),password='Queue-test-only-1234';
async function req(path:string,method='GET',body?:any,cookie='',status=200){const r=await fetch(process.env.APP_ORIGIN+'/api/'+path,{method,headers:{Origin:process.env.APP_ORIGIN!,'Content-Type':'application/json',Cookie:cookie},body:body?JSON.stringify(body):undefined});assert.equal(r.status,status,await (r.status!==status?r.text():Promise.resolve('')));return {data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||''};}
const start=()=>spawn(process.execPath,['--import','tsx','tests/queue-worker-fixture.ts'],{env:process.env,stdio:['ignore','pipe','pipe']});
async function finished(id:string,cookie:string){for(let i=0;i<100;i++){const j=(await req('jobs/'+id,'GET',undefined,cookie)).data;if(!['running','queued'].includes(j.status))return j;await sleep(150);}throw new Error('task timeout');}
try{
 await db.query(readFileSync('scripts/schema.sql','utf8'));for(let i=0;i<2;i++)await db.query('INSERT INTO users(id,username,name,password,admin) VALUES($1,$2,$2,$3,$4)',[ids[i],'queue'+i,passwordHash(password),i===0]);await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'测试账本','private',$2)",[book,ids[0]]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[book,ids[0]]);await db.query('INSERT INTO ai_settings VALUES(1,$1,$2,$2,$3)',['https://queue-test.invalid','test-model',encrypt('not-a-real-key')]);
 server=spawn(process.execPath,[process.env.TEST_RELEASE+'/server.js'],{env:{...process.env,PORT:'3018',HOSTNAME:'127.0.0.1'},stdio:'ignore'});for(let i=0;i<60;i++){try{if((await fetch(process.env.APP_ORIGIN+'/api/health')).ok)break;}catch{}await sleep(200);}
 const a=(await req('login','POST',{username:'queue0',password})).cookie,b=(await req('login','POST',{username:'queue1',password})).cookie;
 await req('queue-settings','PUT',{concurrency:0},a,400);await req('queue-settings','PUT',{concurrency:3},b,403);await req('queue-settings','PUT',{concurrency:2},a);
 const submit=()=>req(`books/${book}/assistant`,'POST',{text:'测试订单',background:true},a,202);
 const batch=await Promise.all([submit(),submit(),submit()]);const jobIds=batch.map(j=>j.data.jobId);assert.equal((await req('jobs','GET',undefined,b)).data.length,0);await req('jobs/'+jobIds[0],'GET',undefined,b,404);
 worker=start();let counts:any[]=[];for(let attempt=0;attempt<100;attempt++){counts=(await db.query("SELECT status,count(*)::int AS n FROM ai_jobs GROUP BY status")).rows;if(counts.find(c=>c.status==='running')?.n===2)break;await sleep(100);}assert.equal(counts.find(c=>c.status==='running')?.n,2);assert.equal(counts.find(c=>c.status==='queued')?.n,1);
 await req('queue-settings','PUT',{concurrency:1},a);for(const id of jobIds)assert.equal((await finished(id,a)).status,'complete');
 // A real response stream is cancelled: the job must still finish.
 const controller=new AbortController();const response=await fetch(process.env.APP_ORIGIN+`/api/books/${book}/assistant`,{method:'POST',headers:{Origin:process.env.APP_ORIGIN!,'Content-Type':'application/json',Cookie:a},body:JSON.stringify({text:'离开网页'}),signal:controller.signal});const detached=response.headers.get('x-task-id')!;assert.ok(detached);await response.body!.getReader().read();controller.abort();assert.equal((await finished(detached,a)).status,'complete');
 const conversation=(await req(`books/${book}/chat`,'POST',{operation:'create'},a)).data.id,turn=randomUUID();await req(`books/${book}/chat`,'POST',{operation:'send',id:conversation,requestId:turn,text:'分析测试',month:'2026-09',background:true},a);let live:any;for(let n=0;n<30;n++){live=(await req(`books/${book}/chat?id=${conversation}`,'GET',undefined,a)).data.turns[0];if(live.artifacts.thinking?.length)break;await sleep(100);}assert.equal(live.status,'running');assert.equal(live.answer,'');assert.equal(live.artifacts.thinking[0].text,'供应商返回的测试思考片段');assert.equal((await finished(turn,a)).status,'complete');const saved=(await req(`books/${book}/chat?id=${conversation}`,'GET',undefined,a)).data.turns[0];assert.equal(saved.answer,'测试财务分析已完成');assert.equal(saved.artifacts.thinking[0].text,'供应商返回的测试思考片段');assert.equal(saved.artifacts.thinking[0].status,'complete');
 const j1=(await submit()).data.jobId,j2=(await submit()).data.jobId;await sleep(700);await req('jobs/'+j2,'POST',{operation:'cancel'},a);await req('jobs/'+j1,'POST',{operation:'cancel'},a);assert.equal((await finished(j2,a)).status,'cancelled');assert.equal((await finished(j1,a)).status,'cancelled');
 worker.kill('SIGTERM');await new Promise(r=>worker!.once('exit',r));const persisted=(await submit()).data.jobId;assert.equal((await req('jobs/'+persisted,'GET',undefined,a)).data.status,'queued');await db.query("UPDATE ai_jobs SET status='running' WHERE id=$1",[persisted]);const cancelledRestart=(await submit()).data.jobId;await db.query("UPDATE ai_jobs SET status='running',cancel_requested=true WHERE id=$1",[cancelledRestart]);worker=start();assert.equal((await finished(persisted,a)).status,'complete');assert.equal((await finished(cancelledRestart,a)).status,'cancelled');assert.equal((await db.query('SELECT 1 FROM ai_job_events WHERE job_id=$1',[cancelledRestart])).rowCount,0);
 console.log('PASS: durable queue, disconnected browser, concurrency 2→1, per-user isolation, cancellation, saved chat, running work resumes after worker restart');
}finally{worker?.kill('SIGTERM');server?.kill('SIGTERM');await db.end();}
