import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {db,transaction} from '../src/server/db';
import {createAccount} from '../src/server/accounts';
import {entry} from '../src/server/model';
import {insertEntry} from '../src/server/ledger';
import {reuse} from '../src/server/reuse';
import {templates} from '../src/server/templates';
import {applyPreferences} from '../src/server/receipt-preferences';
import {sceneSchema} from '../src/lib/entry-scene';
assert.ok(new URL(process.env.DATABASE_URL!).pathname.endsWith('_scene_test'));
const user=randomUUID(),book=randomUUID(),second=randomUUID();
await db.query('INSERT INTO users(id,username,name,password) VALUES($1,$4,$2,$3)',[user,'场景测试','unused',user]);
for(const id of [book,second]){await db.query("INSERT INTO books(id,name,kind,owner_id) VALUES($1,'场景账本','private',$2)",[id,user]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[id,user]);}
const account=(await createAccount(user,{name:'微信',opening:10000,type:'wechat'})).id;
const scene=sceneSchema.parse({type:'transport',transport:'地铁',origin:'西直门',destination:'国贸'});
const e=entry.parse({id:randomUUID(),accountId:account,kind:'expense',amount:400,date:'2026-09-14',category:'交通',payee:'地铁公司',scene,occurredAt:'08:30'});
await transaction(c=>insertEntry(c,book,user,e));
assert.deepEqual((await db.query('SELECT scene FROM transactions WHERE id=$1',[e.id])).rows[0].scene,scene);
await reuse(book,user,{id:e.id,version:1,targetBook:second});
assert.deepEqual((await db.query('SELECT scene FROM transactions WHERE book_id=$1',[second])).rows[0].scene,scene);
await templates(book,user,'POST',{name:'通勤',value:e});
assert.deepEqual((await templates(book,user,'GET',{}) as any[])[0].value.scene,scene);
const current={...e,scene:sceneSchema.parse({type:'transport',transport:'地铁'}),amount:600,occurredAt:'',category:'其他',title:''};
const [normalized]=await applyPreferences(book,[current],true,false,{},user);
assert.equal(normalized.category,'交通');assert.equal(normalized.scene.origin,'');assert.equal(normalized.amount,600);assert.equal(normalized.occurredAt,'');
const [disabled]=await applyPreferences(book,[current],false,false);assert.equal(disabled.category,'其他');
console.log('PASS: scene persistence, linked copy, templates, relevant category matching, consent off, missing facts preserved');
await db.end();
