import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';import {report} from '../src/server/reports';import {db} from '../src/server/db';import {search,searchOptions} from '../src/server/search';
const users=[randomUUID(),randomUUID()],books=[randomUUID(),randomUUID()],accounts=[randomUUID(),randomUUID()],ids=[randomUUID(),randomUUID(),randomUUID()];
const tokens=new Map<string,string>(users.map(u=>[u,randomUUID()]));const base=process.env.TEST_ORIGIN;const find=async(u:string,params:Record<string,string>)=>{if(!base)return search(u,new URLSearchParams(params));const r=await fetch(base+'/api/search?'+new URLSearchParams(params),{headers:{Cookie:'bubu_session='+tokens.get(u)}});assert.equal(r.status,200,await(r.ok?Promise.resolve(''):r.text()));return r.json();};
try{for(let n=0;n<2;n++){await db.query('INSERT INTO users(id,username,name,password,admin) VALUES($1::uuid,$1::text,$1::text,$2,true)',[users[n],'fixture']);await db.query("INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[tokens.get(users[n]),users[n]]);await db.query('INSERT INTO books(id,name,kind,owner_id) VALUES($1,$2,$3,$4)',[books[n],n?'家庭账':'私人账',n?'shared':'private',users[0]]);await db.query("INSERT INTO members VALUES($1,$2,'owner')",[books[n],users[0]]);await db.query('INSERT INTO accounts(id,book_id,name) VALUES($1,$2,$3)',[accounts[n],books[n],n?'家庭微信':'秘密银行卡']);}await db.query("INSERT INTO members VALUES($1,$2,'viewer')",[books[1],users[1]]);
for(let n=0;n<3;n++)await db.query(`INSERT INTO transactions(id,book_id,account_id,kind,amount,date,payee,category,note,created_by,line_items,deleted,order_id) VALUES($1,$2,$3,'expense',$4,'2026-09-13',$5,'餐饮','100%_原味',$6,$7,$8,$9)`,[ids[n],books[n===0?0:1],accounts[n===0?0:1],n===2?2500:5000,n===0?'私密餐馆':n===1?'家庭餐馆':'家庭餐馆分店',users[0],JSON.stringify([{name:n===0?'私密牛肉':'牛肉面',amount:1500,quantity:1,unitPrice:1500},{name:'绿茶',amount:3600,quantity:1,unitPrice:3600},{name:'满减优惠',amount:-100,quantity:null,unitPrice:null}]),n===2,'order-'+n]);
const opts={book:books[1],entity:'transaction'};const options=await searchOptions(users[1],new URLSearchParams());assert.equal(options.accounts.length,1);assert.ok(options.categories.includes('餐饮'));if(base){assert.equal((await fetch(base+'/api/search?q=牛肉')).status,401);const optsResponse=await fetch(base+'/api/search-options',{headers:{Cookie:'bubu_session='+tokens.get(users[1])}});assert.equal(optsResponse.status,200);assert.equal((await optsResponse.json()).accounts.length,1);}assert.equal((await find(users[1],{...opts,min:'-100',max:'-100',amountScope:'item'})).total,1);assert.equal((await find(users[1],{...opts,q:'ORDER-1',mode:'exact',field:'order'})).total,1);assert.equal((await find(users[1],{q:"' OR 1=1 --"})).total,0);assert.equal((await find(users[1],{q:'私密'})).total,0);assert.equal((await find(users[1],{book:books[0]})).total,0);
assert.equal((await find(users[1],{...opts,q:'牛肉面',mode:'exact',field:'item'})).total,1);assert.equal((await find(users[1],{...opts,q:'牛肉',mode:'exact',field:'item'})).total,0);assert.equal((await find(users[1],{...opts,q:'牛肉 家庭'})).total,1);assert.equal((await find(users[1],{...opts,q:'%_'})).total,1);
assert.equal((await find(users[1],{...opts,min:'1500',max:'1500',amountScope:'item',category:'餐饮'})).total,1);assert.equal((await find(users[1],{...opts,min:'1500',max:'1500',amountScope:'order'})).total,0);assert.equal((await find(users[1],{...opts,from:'2026-09-14'})).total,0);assert.equal((await find(users[1],{...opts,state:'trash'})).total,1);
assert.equal((await find(users[1],{entity:'category',q:'餐饮',mode:'exact'})).total,1);
const reportQuery=new URLSearchParams({from:'2026-09-01',to:'2026-09-30',q:'牛肉面',mode:'exact'});assert.equal((await report(books[1],reportQuery)).totals.count,1);reportQuery.set('q','quantity');assert.equal((await report(books[1],reportQuery)).totals.count,0);
const c=randomUUID();await db.query('INSERT INTO finance_conversations(id,book_id,user_id,title) VALUES($1,$2,$3,$4)',[c,books[1],users[0],'秘密分析']);await db.query('INSERT INTO finance_turns(id,conversation_id,question,answer) VALUES($1,$2,$3,$4)',[randomUUID(),c,'我要分析','隐藏回答']);assert.equal((await find(users[1],{q:'隐藏回答'})).total,0);assert.equal((await find(users[0],{q:'隐藏回答',mode:'exact'})).total,1);
for(let n=0;n<35;n++)await db.query("INSERT INTO transactions(id,book_id,account_id,kind,amount,date,payee,category,created_by) VALUES($1,$2,$3,'expense',100,'2026-09-13','分页测试','其他',$4)",[randomUUID(),books[1],accounts[1],users[0]]);const first=await find(users[1],{...opts,q:'分页测试'}),next=await find(users[1],{...opts,q:'分页测试',offset:'30'});assert.equal(first.total,35);assert.equal(first.rows.length,30);assert.equal(next.rows.length,5);assert.ok(!next.rows.some((r:any)=>first.rows.some((a:any)=>a.id===r.id)));
console.log('PASS search: exact/Chinese multi-term/subitems/literal symbols/category/date/item amount/trash, private-book & own-conversation isolation, complete counts and stable pagination');
}finally{await db.query('DELETE FROM transactions WHERE book_id=ANY($1::uuid[])',[books]);await db.query('DELETE FROM accounts WHERE book_id=ANY($1::uuid[])',[books]);await db.query('DELETE FROM members WHERE book_id=ANY($1::uuid[])',[books]);await db.query('DELETE FROM books WHERE id=ANY($1::uuid[])',[books]);await db.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[users]);await db.end();}
